"""Quiz bank: ALGORITHMS."""
from quiz_banks._common import Book, Q

ALGORITHMS = Book(
    title="Algorithms",
    parent_topic="Computer Science",
    subtopic="Algorithms",
    slug="algorithms-jeff-erickson",
    source_url="https://jeffe.cs.illinois.edu/teaching/algorithms/",
    easy=[
        Q("Asymptotic Analysis",
          "What does O(n log n) describe?",
          "An upper bound on a function's growth rate, ignoring constants and lower-order terms.",
          ["The exact number of operations an algorithm performs.",
           "A lower bound on a function's growth rate.",
           "The average number of operations across random inputs."],
          "Big-O is a worst-case upper bound up to constant factors; it tells you the function grows no faster than n log n for large n.",
          {"The exact number of operations an algorithm performs.": "Big-O hides constants and lower-order terms; it isn't an exact count.",
           "A lower bound on a function's growth rate.": "That's Big-Ω. Big-O is an upper bound.",
           "The average number of operations across random inputs.": "That's average-case analysis; Big-O on its own is worst-case asymptotic."}),
        Q("Sorting",
          "Which sort runs in O(n log n) worst case and uses O(1) extra space (excluding recursion stack)?",
          "Heapsort",
          ["Quicksort", "Mergesort", "Insertion sort"],
          "Heapsort builds a heap in place and repeatedly extracts the max, giving deterministic O(n log n) with O(1) extra space.",
          {"Quicksort": "Quicksort is O(n log n) on average but O(n²) worst case.",
           "Mergesort": "Mergesort is O(n log n) but needs O(n) auxiliary space for the merge buffer.",
           "Insertion sort": "Insertion sort is O(n²) in the worst case."}),
        Q("Sorting",
          "Which property is true of a stable sort?",
          "Equal-keyed elements keep their original relative order.",
          ["It always runs in linear time.",
           "It sorts without using comparisons.",
           "It never uses extra memory."],
          "Stability means two records with the same key appear in the output in the same order they appeared in the input.",
          {"It always runs in linear time.": "Stability is unrelated to running time.",
           "It sorts without using comparisons.": "Many stable sorts (e.g., merge sort) use comparisons.",
           "It never uses extra memory.": "Stability says nothing about memory."}),
        Q("Data Structures",
          "What is the worst-case time to find an element in a balanced binary search tree of n nodes?",
          "O(log n)",
          ["O(1)", "O(n)", "O(n log n)"],
          "A balanced BST has height Θ(log n), and search descends one level at a time.",
          {"O(1)": "Constant-time lookup is a hash-table property, not a BST.",
           "O(n)": "That's the worst case for an unbalanced (degenerate) BST.",
           "O(n log n)": "That's a typical sort cost, not search."}),
        Q("Data Structures",
          "Which operation is O(1) amortized on a dynamic array (e.g., Python list, C++ vector)?",
          "Append to the end.",
          ["Insert at the front.",
           "Delete from the middle.",
           "Find the k-th smallest element."],
          "Doubling the backing array makes the amortized cost per append constant, even though some appends trigger an O(n) resize.",
          {"Insert at the front.": "Front insertion shifts every element — Θ(n).",
           "Delete from the middle.": "Mid-deletion also shifts elements — Θ(n).",
           "Find the k-th smallest element.": "That requires selection (Θ(n)) or a sorted structure."}),
        Q("Graphs",
          "BFS from a source in an unweighted graph computes which property of every reachable vertex?",
          "The minimum number of edges from the source.",
          ["The minimum total edge weight from the source.",
           "A topological ordering of vertices.",
           "A minimum spanning tree of the graph."],
          "BFS explores vertices in order of edge-count distance, so it yields shortest paths in unweighted graphs.",
          {"The minimum total edge weight from the source.": "Weighted shortest paths need Dijkstra or Bellman–Ford.",
           "A topological ordering of vertices.": "Topological order comes from DFS on a DAG.",
           "A minimum spanning tree of the graph.": "MSTs are computed with Kruskal or Prim."}),
        Q("Graphs",
          "Which algorithm computes single-source shortest paths in a graph with non-negative edge weights?",
          "Dijkstra's algorithm",
          ["Kruskal's algorithm",
           "Floyd–Warshall",
           "Topological sort"],
          "Dijkstra greedily settles the nearest unvisited vertex; correctness relies on non-negative weights.",
          {"Kruskal's algorithm": "Kruskal builds a minimum spanning tree, not shortest paths.",
           "Floyd–Warshall": "Floyd–Warshall solves all-pairs shortest paths, not single-source.",
           "Topological sort": "Topological sort orders a DAG; it isn't a shortest-path algorithm."}),
        Q("Recursion",
          "The recurrence T(n) = 2 T(n/2) + O(n) solves to which closed form?",
          "Θ(n log n)",
          ["Θ(n)", "Θ(n²)", "Θ(log n)"],
          "By the Master Theorem, a = 2, b = 2, f(n) = n falls in case 2, so T(n) = Θ(n log n) — exactly the mergesort recurrence.",
          {"Θ(n)": "Linear time would require the merge step to be sublinear.",
           "Θ(n²)": "That's the quicksort worst case; this recurrence is balanced.",
           "Θ(log n)": "Logarithmic time would imply constant work per level, but each level here does Θ(n) work."}),
        Q("Hashing",
          "What is the expected time to look up a key in a hash table with a good hash function and load factor under 1?",
          "O(1)",
          ["O(log n)", "O(n)", "O(n log n)"],
          "With uniform hashing and bounded load factor, the expected probe count is constant.",
          {"O(log n)": "That's tree-based search, not hashing.",
           "O(n)": "Linear is the worst case if every key collides, not the expectation.",
           "O(n log n)": "That's a sort cost."}),
        Q("Greedy Algorithms",
          "When does a greedy algorithm provably yield an optimal solution?",
          "When the problem has the greedy-choice property and optimal substructure.",
          ["Whenever the input is sorted.",
           "Whenever the answer is a number.",
           "Only on graphs."],
          "Greedy correctness requires that a locally optimal choice extends to a global optimum (greedy choice) and that subproblems can be solved independently (optimal substructure).",
          {"Whenever the input is sorted.": "Sorted input helps efficiency but doesn't justify greedy correctness.",
           "Whenever the answer is a number.": "Numerical output is unrelated to whether greedy is correct.",
           "Only on graphs.": "Greedy applies far beyond graphs (e.g., Huffman coding, scheduling)."}),
        Q("Dynamic Programming",
          "What is the central idea of dynamic programming?",
          "Solve and memoize overlapping subproblems so each is computed only once.",
          ["Repeatedly halve the input until it fits in cache.",
           "Pick the locally best option at each step.",
           "Restart from scratch whenever the answer changes."],
          "DP exploits overlapping subproblems and optimal substructure by caching results in a table.",
          {"Repeatedly halve the input until it fits in cache.": "That's divide-and-conquer (without memoization).",
           "Pick the locally best option at each step.": "That's greedy.",
           "Restart from scratch whenever the answer changes.": "DP avoids recomputation — the opposite of restarting."}),
        Q("Complexity",
          "What does it mean for a problem to be NP-hard?",
          "Every problem in NP reduces to it in polynomial time.",
          ["It can be solved in polynomial time.",
           "It requires exponential space.",
           "It has no known algorithm at all."],
          "NP-hardness is defined by polynomial-time reductions from every NP problem; the hard problem need not itself be in NP.",
          {"It can be solved in polynomial time.": "If an NP-hard problem were in P, then P = NP.",
           "It requires exponential space.": "Hardness is about time reductions, not space.",
           "It has no known algorithm at all.": "Many NP-hard problems have algorithms — just none known to run in polynomial time."}),
        Q("Graphs",
          "Which traversal naturally produces a topological order on a DAG?",
          "DFS, emitting each vertex when its recursion returns (post-order, reversed).",
          ["BFS from any source.",
           "Dijkstra's algorithm.",
           "Union-find."],
          "DFS post-order finishes a vertex only after all its descendants, so reversing the finishing order yields a topological sort.",
          {"BFS from any source.": "BFS gives shortest-edge-count layers, not a topological order.",
           "Dijkstra's algorithm.": "Dijkstra computes shortest paths; it doesn't order DAG vertices.",
           "Union-find.": "Union-find tracks connectivity; it doesn't order vertices."}),
        Q("Recursion",
          "What invariant does binary search maintain on each iteration?",
          "If the target exists in the array, it lies within the current [lo, hi] window.",
          ["The array is partitioned around a pivot.",
           "The window length doubles each step.",
           "Every element in the window is equal to the target."],
          "Binary search shrinks the candidate window by half each step while preserving the invariant that the target, if present, is inside the window.",
          {"The array is partitioned around a pivot.": "That's quicksort's partition step.",
           "The window length doubles each step.": "It halves, not doubles.",
           "Every element in the window is equal to the target.": "That's not maintained; the window contains both larger and smaller values."}),
        Q("Sorting",
          "Counting sort can sort n integers in the range [0, k] in time…",
          "O(n + k)",
          ["O(n log n)", "O(n log k)", "O(nk)"],
          "Counting sort builds a frequency array of size k+1 in O(n+k) and writes the output in one pass.",
          {"O(n log n)": "That's the comparison-sort lower bound; counting sort beats it because it isn't comparison-based.",
           "O(n log k)": "There's no log factor in counting sort.",
           "O(nk)": "Counting sort is linear, not the product of n and k."}),
        Q("Data Structures",
          "What is the expected height of a randomly built BST on n distinct keys?",
          "Θ(log n)",
          ["Θ(1)", "Θ(√n)", "Θ(n)"],
          "Inserting keys in random order produces a tree of expected height O(log n), even without explicit balancing.",
          {"Θ(1)": "That would require a constant number of keys.",
           "Θ(√n)": "Square-root depth doesn't arise in BST analysis.",
           "Θ(n)": "That's the worst-case height for adversarial insertion orders."}),
        Q("Hashing",
          "Open addressing resolves a collision by…",
          "Probing other slots in the table according to a fixed sequence.",
          ["Storing colliding keys in a linked list at each slot.",
           "Re-hashing every key in the table.",
           "Discarding the colliding key."],
          "Open addressing keeps every key in the table itself; on collision it probes alternate slots (linear, quadratic, double hashing).",
          {"Storing colliding keys in a linked list at each slot.": "That's separate chaining, not open addressing.",
           "Re-hashing every key in the table.": "Rehashing happens on resize, not on each collision.",
           "Discarding the colliding key.": "Discarding would lose data; collisions must be resolved."}),
        Q("Greedy Algorithms",
          "Huffman coding builds an optimal prefix code by repeatedly…",
          "Merging the two least-frequent nodes into a new parent.",
          ["Splitting the alphabet in half by frequency.",
           "Assigning shorter codes to the most-frequent symbols arbitrarily.",
           "Sorting symbols alphabetically."],
          "Huffman's greedy step always combines the two minimum-weight subtrees, producing an optimal prefix-free code.",
          {"Splitting the alphabet in half by frequency.": "That's a Shannon–Fano style top-down split, not Huffman.",
           "Assigning shorter codes to the most-frequent symbols arbitrarily.": "Frequency rank alone doesn't yield an optimal code.",
           "Sorting symbols alphabetically.": "Alphabetical order is irrelevant to code length."}),
        Q("Complexity",
          "What is the relationship between P and NP that's known (not conjectured)?",
          "P is a subset of NP.",
          ["P equals NP.",
           "NP is a subset of P.",
           "P and NP are disjoint."],
          "Every problem solvable in polynomial time is also verifiable in polynomial time, so P ⊆ NP. Whether the containment is strict is open.",
          {"P equals NP.": "That's the famous open question; it isn't known to be true.",
           "NP is a subset of P.": "That would mean P = NP, also unknown.",
           "P and NP are disjoint.": "Many problems (e.g., shortest path) are in both."}),
        Q("Graphs",
          "Kruskal's algorithm uses which data structure to detect cycles efficiently?",
          "A union-find (disjoint-set) structure.",
          ["A min-heap of vertices.",
           "A hash table of edges.",
           "A topological sort."],
          "Kruskal sorts edges by weight and adds each one only if its endpoints are in different components, tracked by union-find.",
          {"A min-heap of vertices.": "Prim's algorithm uses a priority queue; Kruskal doesn't.",
           "A hash table of edges.": "Edges aren't hashed in Kruskal.",
           "A topological sort.": "Topological sort applies to DAGs, not undirected MSTs."}),
    ],
    medium=[
        Q("Asymptotic Analysis",
          "If f(n) = 3n² + 10n + 50, which of the following is the tightest correct bound?",
          "f(n) = Θ(n²)",
          ["f(n) = Θ(n)",
           "f(n) = O(n log n)",
           "f(n) = Ω(n³)"],
          "The dominant term is 3n², so f(n) is both O(n²) and Ω(n²) — hence Θ(n²).",
          {"f(n) = Θ(n)": "Linear is too small; the n² term dominates.",
           "f(n) = O(n log n)": "n² grows faster than n log n.",
           "f(n) = Ω(n³)": "f grows slower than n³, so the lower bound is wrong."}),
        Q("Recursion",
          "Apply the Master Theorem: T(n) = 3 T(n/2) + n. What is T(n)?",
          "Θ(n^{log₂ 3}) ≈ Θ(n^{1.585})",
          ["Θ(n log n)", "Θ(n²)", "Θ(n)"],
          "a = 3, b = 2, so n^{log_b a} = n^{log₂ 3} ≈ n^{1.585}, which dominates f(n) = n. Case 1 applies.",
          {"Θ(n log n)": "That's case 2, requiring f(n) = Θ(n^{log_b a}). Here log₂ 3 > 1.",
           "Θ(n²)": "n² grows faster than n^{1.585}; the recurrence doesn't reach it.",
           "Θ(n)": "Linear would require f(n) to dominate, which it doesn't here."}),
        Q("Sorting",
          "Why does the comparison-sort lower bound Ω(n log n) hold?",
          "A decision tree distinguishing n! permutations has height at least log₂(n!) = Θ(n log n).",
          ["Because mergesort runs in n log n time.",
           "Because every sort needs to copy the array at least log n times.",
           "Because the input has n log n bits of entropy."],
          "Any deterministic comparison sort corresponds to a decision tree whose leaves are the n! permutations; height is at least the log of the leaf count.",
          {"Because mergesort runs in n log n time.": "That's an upper-bound example, not a proof of the lower bound.",
           "Because every sort needs to copy the array at least log n times.": "There's no such requirement; in-place sorts exist.",
           "Because the input has n log n bits of entropy.": "Closer to right in spirit, but the formal argument is the decision-tree height."}),
        Q("Graphs",
          "In Dijkstra's algorithm with a binary-heap priority queue, the running time on a graph with V vertices and E edges is…",
          "O((V + E) log V)",
          ["O(V log V)", "O(VE)", "O(V²)"],
          "Each vertex is extracted once (O(log V)) and each edge triggers at most one decrease-key (O(log V)), giving (V+E) log V.",
          {"O(V log V)": "That omits the per-edge relaxation cost.",
           "O(VE)": "That's Bellman–Ford's cost, not Dijkstra's with a heap.",
           "O(V²)": "That's Dijkstra with an array-based priority queue, which can be faster for dense graphs."}),
        Q("Dynamic Programming",
          "What is the time and space complexity of the standard DP for the 0/1 knapsack with n items and capacity W?",
          "O(nW) time and O(nW) space (reducible to O(W) space).",
          ["O(n log W) time.",
           "O(2^n) time, since the problem is NP-hard.",
           "O(n + W) time."],
          "The pseudo-polynomial DP fills an n × W table; you can keep only the previous row to use O(W) space.",
          {"O(n log W) time.": "Too fast; each cell costs Θ(1) and there are nW of them.",
           "O(2^n) time, since the problem is NP-hard.": "Knapsack is NP-hard in the input length, but DP runs in pseudo-polynomial time O(nW).",
           "O(n + W) time.": "Far too fast; you must consider each item against each capacity."}),
        Q("Greedy Algorithms",
          "Activity selection (max non-overlapping intervals) is optimally solved by greedily choosing…",
          "The interval with the earliest finish time among compatible ones.",
          ["The shortest interval.",
           "The interval with the earliest start time.",
           "The interval overlapping the fewest others."],
          "Sorting by finish time and picking the earliest-finishing compatible interval leaves maximum room for the rest — exchange argument gives optimality.",
          {"The shortest interval.": "Counterexample exists: a short interval can block two longer compatible ones.",
           "The interval with the earliest start time.": "Earliest start can lock in a long interval that blocks many.",
           "The interval overlapping the fewest others.": "Sounds reasonable but doesn't optimize; finish-time greedy is the proven rule."}),
        Q("Hashing",
          "Universal hashing guarantees what about collisions between two distinct keys x ≠ y?",
          "Pr[h(x) = h(y)] ≤ 1/m, taken over the random choice of h from the family.",
          ["No two distinct keys ever collide.",
           "Collisions only happen when keys are similar.",
           "Every slot is hit exactly the same number of times."],
          "A family H is universal if, picking h uniformly at random from H, any pair of distinct keys collides with probability at most 1/m.",
          {"No two distinct keys ever collide.": "That's perfect hashing for a fixed set, not universal hashing in general.",
           "Collisions only happen when keys are similar.": "Universality is independent of key similarity.",
           "Every slot is hit exactly the same number of times.": "That would require a specific input, not a family property."}),
        Q("Graphs",
          "Bellman–Ford handles negative edge weights but rejects graphs with…",
          "A negative-weight cycle reachable from the source.",
          ["Self-loops of positive weight.",
           "Disconnected components.",
           "Vertices with no outgoing edges."],
          "If a negative cycle is reachable, no shortest path is well-defined; Bellman–Ford detects this on the (V−1)+1-th relaxation pass.",
          {"Self-loops of positive weight.": "Positive self-loops never affect shortest paths.",
           "Disconnected components.": "Unreachable vertices simply keep distance ∞.",
           "Vertices with no outgoing edges.": "Sinks are fine; the algorithm just doesn't relax through them."}),
        Q("Data Structures",
          "A min-heap supports which two operations in O(log n)?",
          "insert and extract-min",
          ["find-min and insert",
           "extract-min and find-max",
           "find-min and decrease-key only"],
          "find-min is O(1); insert and extract-min restore the heap property in O(log n) by sifting.",
          {"find-min and insert": "find-min is O(1), not O(log n).",
           "extract-min and find-max": "find-max requires scanning leaves — Θ(n) in a min-heap.",
           "find-min and decrease-key only": "find-min is O(1); decrease-key is O(log n), but extract-min is the canonical second op."}),
        Q("Dynamic Programming",
          "What is the running time of the standard DP for the longest common subsequence of two strings of lengths m and n?",
          "Θ(mn)",
          ["Θ(m + n)", "Θ(min(m, n))", "Θ((mn)²)"],
          "The DP fills an (m+1)×(n+1) table; each cell is O(1) work, giving Θ(mn) total.",
          {"Θ(m + n)": "That would require constant work per character of one string, but each cell depends on its row and column.",
           "Θ(min(m, n))": "Far too fast.",
           "Θ((mn)²)": "Each cell is O(1), not O(mn)."}),
        Q("Graphs",
          "Strongly connected components of a directed graph can be found in linear time using…",
          "Two DFS passes (Kosaraju's or Tarjan's algorithm).",
          ["A single BFS pass.",
           "Floyd–Warshall.",
           "Topological sort followed by Dijkstra."],
          "Kosaraju runs DFS on G, then DFS on the transpose in reverse finishing order; both passes are O(V+E).",
          {"A single BFS pass.": "BFS alone doesn't recover SCCs in directed graphs.",
           "Floyd–Warshall.": "That's O(V³) and unnecessary for SCCs.",
           "Topological sort followed by Dijkstra.": "Topological sort requires a DAG, which the graph may not be."}),
        Q("Recursion",
          "Quicksort's worst-case Θ(n²) running time occurs when…",
          "Every partition is maximally unbalanced (e.g., already-sorted input with a deterministic pivot).",
          ["The input is uniformly random.",
           "The recursion depth is log n.",
           "The pivot is chosen at random."],
          "Picking the first or last element as pivot on sorted data forces partitions of size 1 and n−1, giving Θ(n²) work.",
          {"The input is uniformly random.": "Random input gives expected Θ(n log n).",
           "The recursion depth is log n.": "Log-depth recursion implies balanced partitions and Θ(n log n).",
           "The pivot is chosen at random.": "Random pivots give expected Θ(n log n) regardless of input."}),
        Q("Complexity",
          "The decision version of 3-SAT is NP-complete. What does that imply?",
          "It's in NP and every NP problem reduces to it in polynomial time.",
          ["It can be solved in polynomial time.",
           "It is undecidable.",
           "It is harder than every problem in NP."],
          "NP-completeness means a problem is both in NP and NP-hard.",
          {"It can be solved in polynomial time.": "Only if P = NP, which is open.",
           "It is undecidable.": "3-SAT is decidable — brute force works in 2^n time.",
           "It is harder than every problem in NP.": "It's at most as hard as the hardest NP problems, not strictly harder."}),
        Q("Greedy Algorithms",
          "For interval scheduling with weighted intervals, the earliest-finish-time greedy…",
          "Fails to give an optimal solution.",
          ["Is still optimal.",
           "Gives a 2-approximation only.",
           "Runs in exponential time."],
          "Once weights vary, greedy ignores the value tradeoff. The optimal algorithm is DP after sorting by finish time.",
          {"Is still optimal.": "Weights break the exchange argument that justified greedy in the unweighted case.",
           "Gives a 2-approximation only.": "No such bound; greedy can be arbitrarily bad here.",
           "Runs in exponential time.": "Greedy is fast — the issue is correctness, not speed."}),
        Q("Data Structures",
          "What is the amortized cost per operation on a Fibonacci heap for extract-min, and for decrease-key?",
          "O(log n) amortized for extract-min, O(1) amortized for decrease-key.",
          ["O(1) for both.",
           "O(log n) for both.",
           "O(n) for both."],
          "Fibonacci heaps' main benefit is O(1) amortized decrease-key, enabling Dijkstra in O(E + V log V).",
          {"O(1) for both.": "extract-min still costs Θ(log n) amortized.",
           "O(log n) for both.": "decrease-key is O(1) amortized — that's the whole point of Fibonacci heaps.",
           "O(n) for both.": "Far too high for any heap of interest."}),
        Q("Sorting",
          "Radix sort using counting sort as a stable subroutine sorts n d-digit numbers in…",
          "O(d (n + b)) where b is the radix.",
          ["O(n log n)", "O(d · n log n)", "O(n²)"],
          "Each of d passes runs counting sort in O(n + b); total is O(d(n+b)).",
          {"O(n log n)": "Radix avoids the comparison-sort lower bound.",
           "O(d · n log n)": "Each pass is linear, not n log n.",
           "O(n²)": "Each pass is linear; total is linear in d."}),
        Q("Graphs",
          "Floyd–Warshall computes all-pairs shortest paths in time…",
          "Θ(V³)",
          ["Θ(V²)", "Θ(VE)", "Θ(E log V)"],
          "Three nested loops over V vertices give Θ(V³).",
          {"Θ(V²)": "Only enough for one source.",
           "Θ(VE)": "That's V runs of Bellman–Ford.",
           "Θ(E log V)": "That's one Dijkstra run with a heap; you'd need V of them for all-pairs."}),
        Q("Dynamic Programming",
          "Top-down DP with memoization differs from bottom-up DP in that…",
          "It only computes subproblems actually reached by the recursion.",
          ["It uses no extra memory.",
           "It runs in less asymptotic time.",
           "It only works for problems with optimal substructure."],
          "Memoized recursion can skip unreachable cells of the DP table; bottom-up fills the whole table.",
          {"It uses no extra memory.": "Both styles store subproblem solutions.",
           "It runs in less asymptotic time.": "Asymptotically they match; constants differ.",
           "It only works for problems with optimal substructure.": "Optimal substructure is required for both styles."}),
        Q("Hashing",
          "Linear probing degrades sharply when…",
          "The load factor approaches 1 (primary clustering).",
          ["The hash function is universal.",
           "The keys are integers.",
           "The table size is prime."],
          "Long runs of occupied slots form clusters; expected probe length grows like 1/(1−α)² as α → 1.",
          {"The hash function is universal.": "Universality helps, not hurts.",
           "The keys are integers.": "Key type is irrelevant.",
           "The table size is prime.": "Primes help linear probing, if anything."}),
        Q("Complexity",
          "A polynomial-time reduction from problem A to problem B shows…",
          "B is at least as hard as A (up to polynomial factors).",
          ["A is at least as hard as B.",
           "A and B are equally hard.",
           "B is in P."],
          "If A reduces to B in poly time and B has a poly-time algorithm, so does A — so B is at least as hard.",
          {"A is at least as hard as B.": "The arrow goes the other way: reductions transfer hardness *to* the target.",
           "A and B are equally hard.": "Only if reductions exist in both directions.",
           "B is in P.": "Reduction doesn't say where B sits; only how A relates to it."}),
    ],
    hard=[
        Q("Complexity",
          "Suppose 3-SAT can be solved in time O(n^k) for some constant k. What follows?",
          "P = NP.",
          ["NP = coNP.",
           "Every problem is in P.",
           "Nothing — 3-SAT is already in P."],
          "3-SAT is NP-complete, so a polynomial-time algorithm for it implies polynomial-time algorithms for every NP problem via reduction.",
          {"NP = coNP.": "P = NP implies NP = coNP, but the immediate consequence is P = NP.",
           "Every problem is in P.": "Only problems in NP would collapse; problems outside NP (e.g., undecidable ones) wouldn't.",
           "Nothing — 3-SAT is already in P.": "3-SAT is not known to be in P; that's the open question."}),
        Q("Dynamic Programming",
          "Bellman–Ford runs in O(VE) time. Why doesn't repeating the relaxation pass beyond V−1 iterations help?",
          "After V−1 passes, all shortest paths (which have at most V−1 edges) are computed; further changes signal a negative cycle.",
          ["Because the edge list is sorted by weight.",
           "Because each pass halves the remaining work.",
           "Because the algorithm uses memoization."],
          "Any simple path has at most V−1 edges; V−1 relaxation rounds suffice unless a negative cycle keeps lowering some distance.",
          {"Because the edge list is sorted by weight.": "Bellman–Ford doesn't require sorted edges.",
           "Because each pass halves the remaining work.": "Each pass is O(E); work doesn't shrink.",
           "Because the algorithm uses memoization.": "It doesn't; it's an iterative relaxation."}),
        Q("Graphs",
          "A graph is 2-colorable if and only if it…",
          "Contains no odd-length cycle.",
          ["Is connected.",
           "Has at least two vertices.",
           "Contains a Hamiltonian path."],
          "A graph is bipartite (i.e., 2-colorable) iff every cycle has even length; BFS layering proves it constructively.",
          {"Is connected.": "Many disconnected graphs are 2-colorable; many connected ones aren't.",
           "Has at least two vertices.": "Necessary but far from sufficient.",
           "Contains a Hamiltonian path.": "Hamiltonicity is unrelated to chromatic number."}),
        Q("Sorting",
          "Quickselect (Hoare's) finds the k-th smallest in expected linear time. Why isn't the worst case linear?",
          "Adversarial inputs force unbalanced partitions giving Θ(n²); deterministic worst-case linear requires median-of-medians.",
          ["Worst-case linear-time selection is impossible.",
           "Quickselect uses recursion, which is always slower than iteration.",
           "Random pivots make the worst case exponential."],
          "Plain Quickselect can degenerate to Θ(n²); median-of-medians chooses a guaranteed-balanced pivot for deterministic O(n).",
          {"Worst-case linear-time selection is impossible.": "Median-of-medians achieves it.",
           "Quickselect uses recursion, which is always slower than iteration.": "Recursion isn't the issue.",
           "Random pivots make the worst case exponential.": "Random pivots give expected linear, not exponential worst case."}),
        Q("Dynamic Programming",
          "The edit-distance DP can be optimized from O(mn) space to O(min(m, n)) by…",
          "Keeping only the previous row (or column) of the table.",
          ["Switching to a greedy algorithm.",
           "Using a hash table instead of an array.",
           "Recomputing on the fly without memoization."],
          "Each cell depends only on the cell above, left, and upper-left, so a single previous row suffices.",
          {"Switching to a greedy algorithm.": "Greedy doesn't solve edit distance optimally.",
           "Using a hash table instead of an array.": "The same number of cells must still be computed.",
           "Recomputing on the fly without memoization.": "That blows running time up exponentially."}),
        Q("Hashing",
          "Cuckoo hashing guarantees O(1) worst-case lookup. What is the cost paid for this?",
          "Insertions may trigger a rehash and are O(1) only amortized in expectation.",
          ["Lookups occasionally take O(n) time.",
           "It only works on integer keys.",
           "Deletions are not supported."],
          "Cuckoo hashing's lookup probes a constant number of slots, but insertions can chain evictions and may need a full rehash.",
          {"Lookups occasionally take O(n) time.": "Lookups always touch O(1) slots — that's the whole point.",
           "It only works on integer keys.": "Any hashable key works.",
           "Deletions are not supported.": "Deletion is O(1) — just clear the slot you find the key in."}),
        Q("Graphs",
          "Max-flow equals min-cut in any flow network with a single source and sink — the…",
          "Max-flow min-cut theorem.",
          ["König's theorem.",
           "Hall's marriage theorem.",
           "Menger's theorem."],
          "The max-flow min-cut theorem (Ford–Fulkerson, 1956) equates the value of a maximum flow with the capacity of a minimum s–t cut.",
          {"König's theorem.": "König relates max matching and min vertex cover in bipartite graphs.",
           "Hall's marriage theorem.": "Hall characterizes when a perfect matching exists in a bipartite graph.",
           "Menger's theorem.": "Menger relates max disjoint paths and min vertex/edge separators — a related but distinct result."}),
        Q("Greedy Algorithms",
          "Matroid theory characterizes problems where greedy is provably optimal: greedy works on (E, I) when…",
          "(E, I) is a matroid — closed under subsets and satisfying the exchange property.",
          ["E is finite.",
           "I is closed under intersection.",
           "Weights are non-negative."],
          "Edmonds showed that greedy maximization over (E, I) is correct iff (E, I) is a matroid.",
          {"E is finite.": "Necessary for the problem to make sense, not sufficient.",
           "I is closed under intersection.": "Matroids are closed under taking subsets of independent sets, not intersections.",
           "Weights are non-negative.": "Greedy on matroids works for any weights; negatives just get rejected."}),
        Q("Complexity",
          "The class coNP consists of problems whose…",
          "No-instances have polynomial-time-verifiable witnesses.",
          ["Yes-instances have polynomial-time-verifiable witnesses.",
           "Solutions can be enumerated in polynomial space.",
           "Algorithms run in randomized polynomial time."],
          "NP verifies yes-instances; coNP verifies no-instances. Example: tautology is in coNP because a falsifying assignment certifies non-tautology.",
          {"Yes-instances have polynomial-time-verifiable witnesses.": "That's NP, not coNP.",
           "Solutions can be enumerated in polynomial space.": "That's PSPACE.",
           "Algorithms run in randomized polynomial time.": "That's BPP or RP."}),
        Q("Data Structures",
          "Union-find with union-by-rank and path compression supports m operations on n elements in time…",
          "O(m α(n)) where α is the inverse Ackermann function.",
          ["O(m log n)", "O(m)", "O(n²)"],
          "Tarjan proved the amortized cost is Θ(α(n)) per operation, which is effectively constant for any conceivable n.",
          {"O(m log n)": "That's union-by-rank alone, without path compression.",
           "O(m)": "Strict O(1) per operation isn't achievable.",
           "O(n²)": "Way too pessimistic for these heuristics."}),
        Q("Recursion",
          "An adversary lower-bound argument shows that finding the maximum of n elements needs at least…",
          "n − 1 comparisons.",
          ["log n comparisons.",
           "n log n comparisons.",
           "n/2 comparisons."],
          "Every non-maximum element must lose at least one comparison; with n−1 non-maxima, you need n−1 comparisons.",
          {"log n comparisons.": "Far too few; each comparison eliminates only one candidate from being the max.",
           "n log n comparisons.": "That's a sort lower bound, not a max-finding bound.",
           "n/2 comparisons.": "Not enough to eliminate n−1 non-maxima."}),
        Q("Sorting",
          "Why does selecting the median in linear time (median-of-medians) recurse on at most 7n/10 elements?",
          "Roughly 3n/10 elements are guaranteed smaller and 3n/10 guaranteed larger than the chosen pivot.",
          ["Because the input is split exactly in half.",
           "Because randomization removes 30% of elements.",
           "Because cache effects limit the recursion."],
          "Grouping into fives and recursing on the median of medians leaves at most 7n/10 in either side of the partition.",
          {"Because the input is split exactly in half.": "It isn't exactly half; the bound is 7n/10.",
           "Because randomization removes 30% of elements.": "Median-of-medians is deterministic.",
           "Because cache effects limit the recursion.": "Cache isn't part of the analysis."}),
        Q("Dynamic Programming",
          "Matrix-chain multiplication's DP runs in Θ(n³). Knuth's optimization brings it down to…",
          "Θ(n²) using the monotonicity of split points.",
          ["Θ(n log n)", "Θ(n)", "Θ(2^n)"],
          "Knuth–Yao speedup exploits the fact that the optimal split point is monotone, eliminating an n factor.",
          {"Θ(n log n)": "No such bound is known here.",
           "Θ(n)": "Far too fast; you must consider O(n²) subproblems.",
           "Θ(2^n)": "That's exhaustive parenthesization."}),
        Q("Graphs",
          "Why is BFS not directly usable for shortest paths in graphs with non-negative weighted edges?",
          "BFS treats every edge as unit cost, so it minimizes hops rather than total weight.",
          ["BFS only works on directed graphs.",
           "BFS requires a heap.",
           "BFS doesn't terminate on cyclic graphs."],
          "BFS layers reflect edge counts; weighted shortest paths need a priority queue (Dijkstra) or relaxation (Bellman–Ford).",
          {"BFS only works on directed graphs.": "BFS works on both directed and undirected graphs.",
           "BFS requires a heap.": "Plain BFS uses a FIFO queue.",
           "BFS doesn't terminate on cyclic graphs.": "BFS with a visited set always terminates."}),
        Q("Hashing",
          "A Bloom filter trades exact membership for space efficiency. What kind of error can it make?",
          "False positives, but never false negatives.",
          ["False negatives, but never false positives.",
           "Both, with equal probability.",
           "Neither — it's exact."],
          "An item known to be inserted always tests positive; items never inserted may collide on all hashed bits and falsely test positive.",
          {"False negatives, but never false positives.": "Reversed: if a bit was set on insert, it stays set.",
           "Both, with equal probability.": "Inserts don't clear bits, so negatives are reliable.",
           "Neither — it's exact.": "A Bloom filter isn't exact; that's the point."}),
        Q("Complexity",
          "The PSPACE class contains problems solvable in polynomial space. The known containment chain is:",
          "P ⊆ NP ⊆ PSPACE ⊆ EXPTIME.",
          ["PSPACE ⊆ NP ⊆ P.",
           "EXPTIME ⊆ NP ⊆ PSPACE.",
           "P = NP = PSPACE."],
          "Polynomial time is in polynomial space; NP and coNP are also in PSPACE (Savitch); PSPACE is in EXPTIME.",
          {"PSPACE ⊆ NP ⊆ P.": "Reversed inclusions.",
           "EXPTIME ⊆ NP ⊆ PSPACE.": "EXPTIME is the largest of these; it isn't contained in NP.",
           "P = NP = PSPACE.": "All equalities are open; the first two are believed false."}),
        Q("Recursion",
          "Strassen's algorithm multiplies two n×n matrices in time…",
          "Θ(n^{log₂ 7}) ≈ Θ(n^{2.807})",
          ["Θ(n²)", "Θ(n³)", "Θ(n log n)"],
          "Seven recursive multiplications of n/2-sized blocks give T(n) = 7 T(n/2) + Θ(n²), solving to n^{log₂ 7}.",
          {"Θ(n²)": "The Ω(n²) lower bound is open; no algorithm is known at n².",
           "Θ(n³)": "That's the naive algorithm; Strassen beats it.",
           "Θ(n log n)": "Far below known lower bounds for matrix multiplication."}),
        Q("Greedy Algorithms",
          "Set Cover's greedy algorithm (pick the set covering most uncovered elements) achieves what approximation ratio?",
          "Hₙ ≈ ln n (best possible unless P = NP).",
          ["A constant factor, like 2.",
           "An additive factor, independent of n.",
           "Optimal, with no error."],
          "Greedy set cover is an (ln n)-approximation, and Feige showed no polynomial-time algorithm does asymptotically better unless P = NP.",
          {"A constant factor, like 2.": "Vertex cover is 2-approximable, not set cover in general.",
           "An additive factor, independent of n.": "There's no additive bound known.",
           "Optimal, with no error.": "Set cover is NP-hard; no efficient exact algorithm is known."}),
        Q("Data Structures",
          "Skip lists achieve expected O(log n) search using…",
          "Randomized layering — each node is promoted to higher levels with probability p.",
          ["A balanced rotation invariant.",
           "Hashing of keys to integers.",
           "Doubling the underlying array."],
          "Coin flips decide each node's tower height; the expected longest tower is Θ(log n), and search descends levels then walks forward.",
          {"A balanced rotation invariant.": "That's red-black or AVL trees.",
           "Hashing of keys to integers.": "Skip lists don't hash.",
           "Doubling the underlying array.": "That's dynamic arrays, not skip lists."}),
        Q("Graphs",
          "Edmonds–Karp implements Ford–Fulkerson with BFS to choose augmenting paths, giving running time…",
          "O(V · E²)",
          ["O(V + E)", "O(E log V)", "O(2^V)"],
          "BFS finds shortest augmenting paths; at most O(VE) augmentations occur, each costing O(E).",
          {"O(V + E)": "That's a single BFS; max-flow needs many.",
           "O(E log V)": "That's MST or Dijkstra territory, not max-flow.",
           "O(2^V)": "Ford–Fulkerson with poor pivots can be slow, but Edmonds–Karp is polynomial."}),
    ],
)




BOOK = ALGORITHMS
