"""Quiz bank: Calculus Volume 1 (OpenStax)."""
from quiz_banks._make_book import make_book

BOOK = make_book(
    title="Calculus Volume 1",
    parent_topic="Mathematics",
    subtopic="Calculus",
    slug="calculus-openstax-v1",
    source_url="https://openstax.org/details/books/calculus-volume-1",
    easy=[
        (
            "Limits",
            "What is lim_{x→0} (sin x)/x?",
            "1",
            ["0", "∞", "Does not exist"],
            "The standard limit lim_{x→0} sin(x)/x = 1 (squeeze theorem or L'Hôpital).",
            {
                "0": "sin x/x → 1, not 0 — the numerator and denominator both vanish but their ratio tends to 1.",
                "∞": "The ratio stays bounded near 0; it does not blow up.",
                "Does not exist": "The limit exists and is one of the most used limits in calculus.",
            },
        ),
        (
            "Limits",
            "What is lim_{x→2} (x² − 4)/(x − 2)?",
            "4",
            ["0", "2", "Does not exist"],
            "Factor: (x−2)(x+2)/(x−2) = x+2 for x≠2, so the limit is 2+2 = 4.",
            {
                "0": "Plugging the simplified form x+2 at x=2 gives 4, not 0.",
                "2": "That's the point approached, not the value of the limit.",
                "Does not exist": "The removable discontinuity cancels; the limit exists.",
            },
        ),
        (
            "Limits",
            "A function f is continuous at x = a if and only if…",
            "lim_{x→a} f(x) = f(a)",
            [
                "f(a) = 0",
                "f is differentiable at a",
                "lim_{x→a} f(x) = 0",
            ],
            "Continuity at a requires the limit to exist and equal the function value at a.",
            {
                "f(a) = 0": "Continuity does not require the value to be zero.",
                "f is differentiable at a": "Differentiability implies continuity, not the other way around.",
                "lim_{x→a} f(x) = 0": "The limit must match f(a), which need not be 0.",
            },
        ),
        (
            "Limits",
            "What is lim_{x→∞} 1/x?",
            "0",
            ["1", "∞", "−1"],
            "As x grows without bound, 1/x becomes arbitrarily small and approaches 0.",
            {
                "1": "1/x → 0, not 1, as x → ∞.",
                "∞": "The expression shrinks, it does not grow.",
                "−1": "1/x is positive for large positive x.",
            },
        ),
        (
            "Derivatives",
            "Using the power rule, what is d/dx [x³]?",
            "3x²",
            ["x²", "3x³", "x³/3"],
            "Power rule: d/dx x^n = n x^{n−1} with n = 3.",
            {
                "x²": "Missing the factor 3 from the power rule.",
                "3x³": "Differentiation lowers the power; it does not keep x³.",
                "x³/3": "That's the antiderivative of x², not the derivative of x³.",
            },
        ),
        (
            "Derivatives",
            "What is d/dx [sin x]?",
            "cos x",
            ["−cos x", "sin x", "−sin x"],
            "The derivative of sine is cosine.",
            {
                "−cos x": "Sign error — it's +cos x.",
                "sin x": "Differentiating sin x changes it to cos x.",
                "−sin x": "That's the derivative of cos x.",
            },
        ),
        (
            "Derivatives",
            "What is the derivative of the natural exponential, d/dx [e^x]?",
            "e^x",
            ["x e^{x−1}", "ln x", "1"],
            "The exponential e^x is its own derivative.",
            {
                "x e^{x−1}": "That's the power rule applied incorrectly to e^x.",
                "ln x": "ln x is the antiderivative of 1/x, not the derivative of e^x.",
                "1": "e^x changes with x; its derivative is not constant.",
            },
        ),
        (
            "Derivatives",
            "Geometrically, f′(a) represents…",
            "The slope of the tangent line to y = f(x) at x = a",
            [
                "The area under f from 0 to a",
                "The average value of f on [0, a]",
                "The y-intercept of f",
            ],
            "The derivative at a point gives the instantaneous rate of change, i.e., tangent slope.",
            {
                "The area under f from 0 to a": "Area is an integral, not a derivative.",
                "The average value of f on [0, a]": "Average value involves an integral over an interval.",
                "The y-intercept of f": "f′(a) is a slope, not an intercept.",
            },
        ),
        (
            "Derivatives",
            "Using the power rule, d/dx [x⁵] equals…",
            "5x⁴",
            ["5x⁵", "x⁴", "x⁵/5"],
            "Bring down the exponent 5 and reduce power by 1: 5x⁴.",
            {
                "5x⁵": "The exponent should decrease after differentiation.",
                "x⁴": "Missing the coefficient 5.",
                "x⁵/5": "Antiderivative of x⁴, not derivative of x⁵.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [sin(2x)]?",
            "2 cos(2x)",
            ["cos(2x)", "2 sin(2x)", "−2 sin(2x)"],
            "Chain rule: derivative of sin(u) is cos(u)·u′ with u = 2x, u′ = 2.",
            {
                "cos(2x)": "Missing the factor 2 from the inner derivative.",
                "2 sin(2x)": "Differentiating sine gives cosine, not sine again.",
                "−2 sin(2x)": "Wrong trig function and sign for d/dx sin(2x).",
            },
        ),
        (
            "Chain Rule",
            "For f(x) = (3x + 1)², the inner function u(x) in the chain rule is…",
            "3x + 1",
            ["(3x + 1)²", "3x", "x"],
            "Write f = u² where u = 3x + 1; differentiate outer then multiply by u′.",
            {
                "(3x + 1)²": "That's the whole f, not the inner function.",
                "3x": "Missing the +1 constant shift inside the square.",
                "x": "The inner function is the full linear expression 3x + 1.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [(x² + 1)³]?",
            "6x(x² + 1)²",
            ["3(x² + 1)²", "6x²(x² + 1)", "(x² + 1)³"],
            "Outer: 3u²; inner u′ = 2x; product 3(x²+1)²·2x = 6x(x²+1)².",
            {
                "3(x² + 1)²": "Missing the inner derivative factor 2x.",
                "6x²(x² + 1)": "Power on (x²+1) should stay squared, not first power only.",
                "(x² + 1)³": "That's f itself, not its derivative.",
            },
        ),
        (
            "Integrals",
            "What is ∫ x dx (indefinite integral)?",
            "x²/2 + C",
            ["x² + C", "2x + C", "x + C"],
            "Reverse power rule: ∫ x dx = x^{2}/2 + C.",
            {
                "x² + C": "Missing the division by 2.",
                "2x + C": "That's the derivative of x², not ∫ x dx.",
                "x + C": "That's ∫ 1 dx, not ∫ x dx.",
            },
        ),
        (
            "Integrals",
            "What is the indefinite integral ∫ 1 dx (antiderivative of the constant 1)?",
            "x + C",
            ["1 + C", "0", "ln x + C"],
            "The antiderivative of 1 is x, plus an arbitrary constant C.",
            {
                "1 + C": "Antiderivative must be a function of x, not constant 1.",
                "0": "Derivative of 0 is 0, but ∫ 1 dx is not 0.",
                "ln x + C": "ln x differentiates to 1/x, not 1.",
            },
        ),
        (
            "Integrals",
            "A definite integral ∫_a^b f(x) dx represents (when f ≥ 0)…",
            "The signed area between y = f(x) and the x-axis from x = a to x = b",
            [
                "The slope of f at b",
                "The maximum value of f on [a, b]",
                "The derivative of f at a",
            ],
            "Definite integrals accumulate net area; with f ≥ 0 that area is positive.",
            {
                "The slope of f at b": "Slope is f′(b), not an integral.",
                "The maximum value of f on [a, b]": "Integrals sum area, not pick a maximum.",
                "The derivative of f at a": "That's f′(a), not ∫_a^b f.",
            },
        ),
        (
            "Integrals",
            "What is the indefinite integral ∫ cos x dx?",
            "sin x + C",
            ["−sin x + C", "cos x + C", "−cos x + C"],
            "d/dx (sin x) = cos x, so ∫ cos x dx = sin x + C.",
            {
                "−sin x + C": "Sign error — derivative of −sin x is −cos x.",
                "cos x + C": "cos x differentiates to −sin x.",
                "−cos x + C": "−cos x differentiates to sin x.",
            },
        ),
        (
            "Applications",
            "If s(t) is position, velocity v(t) equals…",
            "s′(t)",
            ["s(t)/t", "∫ s(t) dt", "s″(t)"],
            "Velocity is the instantaneous rate of change of position: the derivative.",
            {
                "s(t)/t": "Average speed might use Δs/Δt, not the derivative definition.",
                "∫ s(t) dt": "Integration accumulates; differentiation gives velocity.",
                "s″(t)": "Second derivative of position is acceleration.",
            },
        ),
        (
            "Applications",
            "If s(t) is position, acceleration a(t) equals…",
            "s″(t)",
            ["s′(t)", "∫ s′(t) dt", "s(t) − s(0)"],
            "Acceleration is the rate of change of velocity, hence the second derivative of position.",
            {
                "s′(t)": "s′ is velocity, not acceleration.",
                "∫ s′(t) dt": "Integrating velocity recovers position (up to constant).",
                "s(t) − s(0)": "Displacement, not acceleration.",
            },
        ),
        (
            "Applications",
            "A local maximum of differentiable f at an interior point x = c requires…",
            "f′(c) = 0 (necessary but not sufficient alone)",
            ["f(c) = 0", "f″(c) = 0 always", "f is constant near c"],
            "Fermat's theorem: if f has a local extremum at c and f′(c) exists, then f′(c) = 0.",
            {
                "f(c) = 0": "The function value need not be zero at a maximum.",
                "f″(c) = 0 always": "f″(c) = 0 is inconclusive (inflection possible).",
                "f is constant near c": "At a max, f decreases on one side and increases on the other (typically).",
            },
        ),
        (
            "Applications",
            "The marginal cost when cost is C(x) units for x items is best modeled by…",
            "C′(x)",
            ["C(x)/x", "∫ C(x) dx", "C(x) − C(0)"],
            "Marginal cost is the approximate cost of one more unit: derivative of total cost.",
            {
                "C(x)/x": "Average cost is C(x)/x, not marginal.",
                "∫ C(x) dx": "Integration does not give marginal rate.",
                "C(x) − C(0)": "Total variable cost, not marginal.",
            },
        ),
    ],
    medium=[
        (
            "Limits",
            "What is lim_{x→0} (1 − cos x)/x²?",
            "1/2",
            ["0", "1", "Does not exist"],
            "Use 1−cos x ~ x²/2 near 0, or L'Hôpital twice, to get limit 1/2.",
            {
                "0": "The numerator is quadratic small; ratio tends to 1/2, not 0.",
                "1": "Off by a factor of 2 — standard limit gives 1/2.",
                "Does not exist": "The limit exists by Taylor expansion or L'Hôpital.",
            },
        ),
        (
            "Limits",
            "For f(x) = |x|/x when x ≠ 0, what is true about lim_{x→0} f(x)?",
            "The limit does not exist (left and right limits differ)",
            ["The limit is 0", "The limit is 1", "The limit is −1"],
            "Left limit: −1; right limit: +1; two-sided limit fails.",
            {
                "The limit is 0": "f(x) is ±1 near 0, not approaching 0.",
                "The limit is 1": "Only the right-hand limit is 1.",
                "The limit is −1": "Only the left-hand limit is −1.",
            },
        ),
        (
            "Limits",
            "What is lim_{x→∞} (3x² + 2x)/(x² − 1)?",
            "3",
            ["0", "∞", "2"],
            "Divide numerator and denominator by x²: leading terms 3/1 = 3.",
            {
                "0": "Degrees match; ratio of leading coefficients is 3.",
                "∞": "Top and bottom grow at the same rate — finite limit.",
                "2": "That's the coefficient on the linear term, not the limit.",
            },
        ),
        (
            "Derivatives",
            "What is d/dx [x² sin x]?",
            "2x sin x + x² cos x",
            ["2x cos x", "x² cos x", "2 sin x"],
            "Product rule: (x²)′ sin x + x² (sin x)′ = 2x sin x + x² cos x.",
            {
                "2x cos x": "Differentiated only one factor incorrectly.",
                "x² cos x": "Missing the derivative of x² term.",
                "2 sin x": "Ignored the product structure entirely.",
            },
        ),
        (
            "Derivatives",
            "What is d/dx [ln(3x)] for x > 0?",
            "1/x",
            ["1/(3x)", "3/x", "ln 3"],
            "ln(3x) = ln 3 + ln x, so derivative is 1/x.",
            {
                "1/(3x)": "Chain rule on ln(3x) gives (1/(3x))·3 = 1/x.",
                "3/x": "Inner derivative 3 cancels with 1/(3x).",
                "ln 3": "ln 3 is constant; derivative involves 1/x.",
            },
        ),
        (
            "Derivatives",
            "What is d/dx [tan x]?",
            "sec² x",
            ["sec x", "−sec² x", "cot x"],
            "d/dx tan x = sec² x (or 1/cos² x).",
            {
                "sec x": "sec x is not the derivative of tan x.",
                "−sec² x": "Sign is positive for tan x.",
                "cot x": "cot is related to tan but is not its derivative.",
            },
        ),
        (
            "Derivatives",
            "If f(x) = x e^x, then f′(x) equals…",
            "e^x(x + 1)",
            ["x e^x", "e^x", "x e^{x−1}"],
            "Product rule: e^x + x e^x = e^x(x+1).",
            {
                "x e^x": "That's f, not f′.",
                "e^x": "Missing derivative of x factor.",
                "x e^{x−1}": "Misapplied power rule to e^x.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [√(x² + 1)]?",
            "x/√(x² + 1)",
            ["1/√(x² + 1)", "2x/√(x² + 1)", "x/(x² + 1)"],
            "Outer: (1/2)u^{−1/2}; inner 2x; simplifies to x/√(x²+1).",
            {
                "1/√(x² + 1)": "Missing inner derivative factor x.",
                "2x/√(x² + 1)": "Extra factor of 2 — chain rule halves it.",
                "x/(x² + 1)": "Wrong power on the denominator.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [e^{−x²}]?",
            "−2x e^{−x²}",
            ["e^{−x²}", "2x e^{−x²}", "−e^{−x²}"],
            "Chain: e^u with u = −x², u′ = −2x.",
            {
                "e^{−x²}": "Missing inner derivative −2x.",
                "2x e^{−x²}": "Sign error on inner derivative.",
                "−e^{−x²}": "Factor −2x is required, not just −1.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [cos(x³)]?",
            "−3x² sin(x³)",
            ["−sin(x³)", "3x² sin(x³)", "−x² sin(x³)"],
            "Derivative −sin(u)·3x² with u = x³.",
            {
                "−sin(x³)": "Missing factor 3x² from chain rule.",
                "3x² sin(x³)": "Sign error — derivative of cos is −sin.",
                "−x² sin(x³)": "Missing one factor of 3 from u′.",
            },
        ),
        (
            "Integrals",
            "What is ∫ (2x + 3) dx?",
            "x² + 3x + C",
            ["2x² + 3x + C", "x² + 3 + C", "2 + C"],
            "Integrate termwise: x² + 3x + C.",
            {
                "2x² + 3x + C": "∫ 2x dx = x², not 2x².",
                "x² + 3 + C": "∫ 3 dx = 3x, not 3.",
                "2 + C": "Antiderivative must include x dependence.",
            },
        ),
        (
            "Integrals",
            "Evaluate ∫_0^1 x² dx.",
            "1/3",
            ["1/2", "1", "2/3"],
            "[x³/3]_0^1 = 1/3 − 0 = 1/3.",
            {
                "1/2": "That's ∫_0^1 x dx.",
                "1": "Integral of x² on [0,1] is less than 1.",
                "2/3": "Arithmetic error on x³/3 at 1.",
            },
        ),
        (
            "Integrals",
            "What is ∫ e^{2x} dx?",
            "e^{2x}/2 + C",
            ["e^{2x} + C", "2e^{2x} + C", "e^x + C"],
            "Substitution u = 2x gives (1/2)∫ e^u du = e^{2x}/2 + C.",
            {
                "e^{2x} + C": "Missing factor 1/2 from inner derivative.",
                "2e^{2x} + C": "Would differentiate to 4e^{2x}.",
                "e^x + C": "Wrong exponent — integrand is e^{2x}.",
            },
        ),
        (
            "Integrals",
            "Using substitution u = x² + 1, ∫ x/(x² + 1) dx equals…",
            "(1/2) ln(x² + 1) + C",
            ["ln(x² + 1) + C", "1/(x² + 1) + C", "arctan x + C"],
            "With u = x² + 1 and du = 2x dx, ∫ x/(x²+1) dx = (1/2)∫ du/u = (1/2) ln|u| + C.",
            {
                "ln(x² + 1) + C": "Missing the factor 1/2 from du = 2x dx.",
                "1/(x² + 1) + C": "Derivative of arctan, not this antiderivative.",
                "arctan x + C": "∫ 1/(1+x²) dx = arctan x — different integrand.",
            },
        ),
        (
            "Integrals",
            "The Fundamental Theorem of Calculus (Part 1) states that if F′ = f, then ∫_a^b f(x) dx equals…",
            "F(b) − F(a)",
            ["f(b) − f(a)", "F(b) + F(a)", "f′(b) − f′(a)"],
            "FTC Part 1: definite integral equals antiderivative evaluated at endpoints.",
            {
                "f(b) − f(a)": "Uses integrand values, not antiderivative F.",
                "F(b) + F(a)": "Should be difference, not sum.",
                "f′(b) − f′(a)": "Confuses f with its antiderivative.",
            },
        ),
        (
            "Applications",
            "Find the critical points of f(x) = x³ − 3x.",
            "x = −1 and x = 1",
            ["x = 0 only", "x = ±√3", "No critical points"],
            "f′(x) = 3x² − 3 = 3(x²−1); zeros at x = ±1.",
            {
                "x = 0 only": "f′(0) = −3 ≠ 0.",
                "x = ±√3": "Those solve x³ − 3x = 0, not f′ = 0.",
                "No critical points": "f′ vanishes at two points.",
            },
        ),
        (
            "Applications",
            "On [0, π], where does f(x) = sin x attain its maximum?",
            "x = π/2",
            ["x = 0", "x = π", "x = π/4"],
            "sin x peaks at 1 when x = π/2 on [0, π].",
            {
                "x = 0": "sin 0 = 0, not maximum.",
                "x = π": "sin π = 0.",
                "x = π/4": "sin(π/4) = √2/2 < 1.",
            },
        ),
        (
            "Applications",
            "A circle's radius increases at 2 cm/s. How fast is the area increasing when r = 5 cm?",
            "20π cm²/s",
            ["10π cm²/s", "25π cm²/s", "4π cm²/s"],
            "A = πr², dA/dt = 2πr dr/dt = 2π(5)(2) = 20π.",
            {
                "10π cm²/s": "Missing a factor of 2 from dr/dt or 2πr.",
                "25π cm²/s": "Confused with πr² at r=5.",
                "4π cm²/s": "Used dr/dt without the 2πr factor.",
            },
        ),
        (
            "Applications",
            "To minimize a closed rectangular box with square base and volume V, the optimal height h relates to base side s by…",
            "h = s/2 (height half the base side for minimal surface area)",
            ["h = s", "h = 2s", "h = V/s²"],
            "Surface A = 2s² + 4sh with s²h = V gives h = s/2 at optimum.",
            {
                "h = s": "Makes a cube only for special V; general optimum has h = s/2.",
                "h = 2s": "Too tall for minimal surface area.",
                "h = V/s²": "That's volume constraint, not the optimum relation alone.",
            },
        ),
        (
            "Applications",
            "The linearization L(x) of f at a approximates f near a by…",
            "L(x) = f(a) + f′(a)(x − a)",
            ["L(x) = f(a) + f″(a)(x − a)²", "L(x) = f′(a)x", "L(x) = f(x) + f′(x)(x − a)"],
            "Tangent line approximation: value plus derivative times increment.",
            {
                "L(x) = f(a) + f″(a)(x − a)²": "Quadratic term is second-order, not linearization.",
                "L(x) = f′(a)x": "Missing intercept f(a) − f′(a)a.",
                "L(x) = f(x) + f′(x)(x − a)": "Uses f(x) instead of anchor f(a).",
            },
        ),
    ],
    hard=[
        (
            "Limits",
            "Evaluate lim_{x→0} (e^x − 1 − x)/x² using standard techniques.",
            "1/2",
            ["0", "1", "e"],
            "Taylor: e^x = 1 + x + x²/2 + … so numerator ~ x²/2, ratio → 1/2.",
            {
                "0": "Numerator is second-order small; limit is nonzero.",
                "1": "Would require numerator ~ x², but coefficient is 1/2.",
                "e": "e is the base, not this limit value.",
            },
        ),
        (
            "Limits",
            "What is lim_{x→0⁺} x^x?",
            "1",
            ["0", "e", "Does not exist"],
            "Write x^x = e^{x ln x}; as x→0⁺, x ln x → 0, so exponent → 0 and limit is e⁰ = 1.",
            {
                "0": "0⁰ is indeterminate but the limit is 1, not 0.",
                "e": "The limit of the exponent is 0, not 1.",
                "Does not exist": "The one-sided limit exists and equals 1.",
            },
        ),
        (
            "Limits",
            "If lim_{x→a} f(x) = L and f(a) ≠ L, then at x = a the function has…",
            "A removable discontinuity (if f can be redefined to be continuous)",
            [
                "A jump discontinuity necessarily",
                "An infinite discontinuity",
                "No discontinuity",
            ],
            "Limit exists but differs from value (or is undefined) — hole, fixable by redefining f(a) = L.",
            {
                "A jump discontinuity necessarily": "Jump requires left ≠ right limit; here two-sided limit is L.",
                "An infinite discontinuity": "Infinite limits blow up; here limit is finite L.",
                "No discontinuity": "f(a) ≠ L means not continuous at a.",
            },
        ),
        (
            "Derivatives",
            "What is d/dx [x^x] for x > 0?",
            "x^x (ln x + 1)",
            ["x x^{x−1}", "x^x ln x", "x^{x−1}"],
            "ln y = x ln x, y′/y = ln x + 1, so y′ = x^x(ln x + 1).",
            {
                "x x^{x−1}": "Treats exponent x as constant — wrong for variable exponent.",
                "x^x ln x": "Missing the +1 from differentiating x ln x.",
                "x^{x−1}": "Power rule does not apply when both base and exponent vary.",
            },
        ),
        (
            "Derivatives",
            "Using implicit differentiation on x² + y² = 25, dy/dx equals…",
            "−x/y",
            ["x/y", "−y/x", "2x"],
            "2x + 2y y′ = 0 ⇒ y′ = −x/y.",
            {
                "x/y": "Sign error.",
                "−y/x": "Inverted roles of x and y.",
                "2x": "That's ∂/∂x of left side set to zero incorrectly solved.",
            },
        ),
        (
            "Derivatives",
            "What is the second derivative f″(x) if f(x) = x ln x for x > 0?",
            "1/x",
            ["ln x + 1", "ln x", "1"],
            "f′ = ln x + 1; f″ = 1/x.",
            {
                "ln x + 1": "That's f′, not f″.",
                "ln x": "One differentiation short.",
                "1": "Missing the 1/x from d/dx (ln x + 1).",
            },
        ),
        (
            "Derivatives",
            "For f(x) = |x³ − 3x|, at x = 0 the derivative f′(0) is…",
            "Does not exist (corner from absolute value)",
            ["0", "−3", "3"],
            "Inside |·|, g(x)=x³−3x has g′(0)=−3; absolute value creates a corner unless g′(0)=0.",
            {
                "0": "Left and right derivatives of |g| disagree at 0.",
                "−3": "That's g′(0), but |g| is not differentiable at 0.",
                "3": "Sign/magnitude confusion; derivative does not exist.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [arcsin(2x)] for |x| ≤ 1/2?",
            "2/√(1 − 4x²)",
            ["1/√(1 − 4x²)", "2/√(1 − x²)", "1/(1 + 4x²)"],
            "d/dx arcsin(u) = u′/√(1−u²) with u=2x, u′=2.",
            {
                "1/√(1 − 4x²)": "Missing inner factor 2.",
                "2/√(1 − x²)": "Wrong expression under square root — use 1−(2x)².",
                "1/(1 + 4x²)": "Confused with arctan derivative form.",
            },
        ),
        (
            "Chain Rule",
            "If y = f(g(h(x))), then dy/dx equals…",
            "f′(g(h(x))) · g′(h(x)) · h′(x)",
            [
                "f′(x) · g′(x) · h′(x)",
                "f(g′(h′(x)))",
                "f′(g) + g′(h) + h′(x)",
            ],
            "Chain rule multiplies derivatives along the composition: outer′ × inner′ × …",
            {
                "f′(x) · g′(x) · h′(x)": "Must evaluate each derivative at the correct inner point.",
                "f(g′(h′(x)))": "Composition is multiplicative, not nested substitution like this.",
                "f′(g) + g′(h) + h′(x)": "Derivatives compose by product, not sum.",
            },
        ),
        (
            "Chain Rule",
            "What is d/dx [ln(cos x)] for cos x > 0?",
            "−tan x",
            ["tan x", "sec x", "−sin x"],
            "(1/cos x)·(−sin x) = −sin x/cos x = −tan x.",
            {
                "tan x": "Sign error.",
                "sec x": "That's d/dx ln|sec x + tan x|, not ln(cos x).",
                "−sin x": "Missing division by cos x from chain rule.",
            },
        ),
        (
            "Integrals",
            "Evaluate ∫_0^{π/2} sin² x dx.",
            "π/4",
            ["π/2", "1", "0"],
            "Use sin²x = (1−cos 2x)/2; integral = [x/2 − sin(2x)/4]_0^{π/2} = π/4.",
            {
                "π/2": "That's ∫_0^{π/2} sin x dx.",
                "1": "Average value of sin² on [0,π/2] is 1/2, integral over length π/2 gives π/4.",
                "0": "sin² is positive on (0,π/2); integral is positive.",
            },
        ),
        (
            "Integrals",
            "Evaluate ∫ x e^{x²} dx.",
            "e^{x²}/2 + C",
            ["e^{x²} + C", "2x e^{x²} + C", "e^x + C"],
            "Let u = x², du = 2x dx: (1/2)∫ e^u du = e^{x²}/2 + C.",
            {
                "e^{x²} + C": "Missing 1/2 from du = 2x dx.",
                "2x e^{x²} + C": "That's the integrand, not antiderivative.",
                "e^x + C": "Wrong exponent inside exponential.",
            },
        ),
        (
            "Integrals",
            "The area between y = x and y = x² on [0, 1] is…",
            "1/6",
            ["1/2", "1/3", "1/12"],
            "∫_0^1 (x − x²) dx = [x²/2 − x³/3]_0^1 = 1/2 − 1/3 = 1/6.",
            {
                "1/2": "That's only ∫ x dx on [0,1], ignoring subtraction of x².",
                "1/3": "That's ∫ x² dx alone.",
                "1/12": "Arithmetic error on 1/2 − 1/3.",
            },
        ),
        (
            "Integrals",
            "Using integration by parts with u = ln x, dv = dx, ∫ ln x dx equals…",
            "x ln x − x + C",
            ["1/x + C", "ln x + C", "x ln x + C"],
            "∫ ln x dx = x ln x − ∫ 1 dx = x ln x − x + C.",
            {
                "1/x + C": "Derivative of ln x, not antiderivative.",
                "ln x + C": "Differentiate to 1/x, not ln x.",
                "x ln x + C": "Sign error on the ∫ v du term.",
            },
        ),
        (
            "Integrals",
            "If F(x) = ∫_1^x (1/t) dt for x > 0, then F′(x) equals…",
            "1/x",
            ["ln x", "1", "x"],
            "FTC Part 2: derivative of ∫_1^x f(t) dt is f(x) = 1/x.",
            {
                "ln x": "F(x) = ln x, but F′(x) = 1/x.",
                "1": "Constant derivative would integrate to x, not ln.",
                "x": "Confused with ∫ t dt.",
            },
        ),
        (
            "Applications",
            "Among rectangles with perimeter 40, which dimensions maximize area?",
            "A square with side length 10 (area 100)",
            [
                "Width 8 and height 12 (area 96)",
                "Width 5 and height 15 (area 75)",
                "Width 20 and height 0",
            ],
            "With perimeter 2w + 2h = 40, area wh is maximized when w = h = 10.",
            {
                "Width 8 and height 12 (area 96)": "A non-square rectangle gives less area than 10×10.",
                "Width 5 and height 15 (area 75)": "More extreme aspect ratio lowers area further.",
                "Width 20 and height 0": "Degenerate rectangle has zero area.",
            },
        ),
        (
            "Applications",
            "A 13-ft ladder slides down a wall; when the base is 5 ft from the wall and moves at 2 ft/s, how fast is the top sliding down (ft/s)?",
            "10/6 (about 1.67)",
            ["2", "5", "13"],
            "x² + y² = 169; at x=5, y=12; differentiate: 2x x′ + 2y y′ = 0 ⇒ y′ = −(x/y)x′ = −(5/12)(2) = −10/6.",
            {
                "2": "That's dx/dt, not dy/dt.",
                "5": "Confused horizontal position with vertical rate.",
                "13": "Ladder length is constant; its derivative is zero.",
            },
        ),
        (
            "Applications",
            "For f(x) = x³ − 6x² + 9x + 1, which x gives a local maximum?",
            "x = 1",
            ["x = 3", "x = 0", "x = 2"],
            "f′ = 3x² − 12x + 9 = 3(x−1)(x−3); f″ = 6x − 12 gives f″(1) < 0 (max), f″(3) > 0 (min).",
            {
                "x = 3": "x = 3 is a local minimum.",
                "x = 0": "f′(0) = 9 ≠ 0.",
                "x = 2": "Not a critical point.",
            },
        ),
        (
            "Applications",
            "The volume of a sphere V = (4/3)πr³. If r increases at 3 cm/s, dV/dt when r = 2 cm is…",
            "48π cm³/s",
            ["12π cm³/s", "32π cm³/s", "36π cm³/s"],
            "dV/dt = 4πr² dr/dt = 4π(4)(3) = 48π.",
            {
                "12π cm³/s": "Used πr² without factor 4 or wrong r.",
                "32π cm³/s": "Missing a factor in 4πr² dr/dt.",
                "36π cm³/s": "Arithmetic slip on 4π·4·3.",
            },
        ),
        (
            "Limits",
            "Using L'Hôpital's rule, lim_{x→0} (e^x − 1)/x equals…",
            "1",
            ["0", "e", "∞"],
            "Indeterminate 0/0; derivative of numerator and denominator gives e^x → 1.",
            {
                "0": "e^x − 1 behaves like x near 0, so ratio → 1.",
                "e": "That's the base of the exponential, not the limit.",
                "∞": "The limit is finite.",
            },
        ),
    ],
)
