"""Quiz bank: Database Design."""
from quiz_banks._make_book import make_book

_EASY = [
    (
        "Relational Model",
        "In the relational model, what is a relation?",
        "A table — a set of tuples (rows) sharing the same attributes (columns).",
        [
            "A foreign-key link between two tables.",
            "A single row identified by a primary key.",
            "A query that joins multiple tables.",
        ],
        "A relation is the mathematical name for a table: a set of rows with a fixed schema.",
        {
            "A foreign-key link between two tables.": "That describes a referential constraint, not a relation.",
            "A single row identified by a primary key.": "A row is a tuple; the whole table is the relation.",
            "A query that joins multiple tables.": "A join is an operation over relations, not the relation itself.",
        },
    ),
    (
        "Relational Model",
        "What is the purpose of a primary key?",
        "To uniquely identify each row in a table.",
        [
            "To speed up every SELECT query automatically.",
            "To link a child row to a parent row in another table.",
            "To store the largest value in each column.",
        ],
        "A primary key guarantees entity integrity: no two rows share the same key value.",
        {
            "To speed up every SELECT query automatically.": "Indexes may help lookups, but that is not the definition of a primary key.",
            "To link a child row to a parent row in another table.": "That is the role of a foreign key.",
            "To store the largest value in each column.": "Keys identify rows; they are not aggregate summaries.",
        },
    ),
    (
        "Relational Model",
        "A foreign key enforces what kind of integrity?",
        "Referential integrity between child and parent rows.",
        [
            "Domain integrity on numeric columns only.",
            "Entity integrity within a single table.",
            "Transactional durability after COMMIT.",
        ],
        "Foreign keys require that referenced parent values exist (or use defined ON DELETE/UPDATE actions).",
        {
            "Domain integrity on numeric columns only.": "Domain constraints apply to data types and allowed values, not cross-table links.",
            "Entity integrity within a single table.": "Entity integrity is enforced by the primary key.",
            "Transactional durability after COMMIT.": "Durability is an ACID property, not referential integrity.",
        },
    ),
    (
        "Schema Design",
        "In an ER diagram, a one-to-many relationship between Department and Employee means…",
        "Each employee belongs to at most one department; a department can have many employees.",
        [
            "Each department has exactly one employee.",
            "Each employee can belong to many departments simultaneously in this relationship.",
            "Departments and employees must share the same primary key.",
        ],
        "One-to-many is the usual works-for pattern: many employees, one department per assignment.",
        {
            "Each department has exactly one employee.": "That would be one-to-one, not one-to-many.",
            "Each employee can belong to many departments simultaneously in this relationship.": "That describes many-to-many.",
            "Departments and employees must share the same primary key.": "Related tables use separate keys linked by foreign keys.",
        },
    ),
    (
        "SQL",
        "Which SQL clause filters rows before they are grouped?",
        "WHERE",
        ["HAVING", "GROUP BY", "ORDER BY"],
        "WHERE filters individual rows; HAVING filters groups after aggregation.",
        {
            "HAVING": "HAVING applies predicates to grouped results, not to raw rows.",
            "GROUP BY": "GROUP BY forms groups; it does not filter row-level predicates.",
            "ORDER BY": "ORDER BY sorts the final result set.",
        },
    ),
    (
        "SQL",
        "What does SELECT DISTINCT do?",
        "Removes duplicate rows from the query result.",
        [
            "Sorts rows in ascending order.",
            "Returns only the first row of the table.",
            "Locks the table for exclusive write access.",
        ],
        "DISTINCT applies to the full projected row: identical combinations appear once.",
        {
            "Sorts rows in ascending order.": "Use ORDER BY to sort.",
            "Returns only the first row of the table.": "Use LIMIT 1 for a single row; DISTINCT removes duplicates, not all but one.",
            "Locks the table for exclusive write access.": "Locking is a transaction concern, not DISTINCT.",
        },
    ),
    (
        "SQL",
        "Which statement adds a new row to an existing table?",
        "INSERT",
        ["UPDATE", "ALTER TABLE", "CREATE TABLE"],
        "INSERT supplies values for a new tuple; UPDATE modifies existing rows.",
        {
            "UPDATE": "UPDATE changes existing rows.",
            "ALTER TABLE": "ALTER changes schema (columns, constraints), not row data.",
            "CREATE TABLE": "CREATE TABLE defines a new relation.",
        },
    ),
    (
        "SQL",
        "DELETE removes rows; what does DROP TABLE do?",
        "Removes the table definition and all its data from the schema.",
        [
            "Removes only rows that fail a WHERE clause but keeps the table.",
            "Renames the table while preserving all rows.",
            "Rolls back the last transaction.",
        ],
        "DROP is DDL that destroys the relation; DELETE is DML that removes selected rows.",
        {
            "Removes only rows that fail a WHERE clause but keeps the table.": "That describes DELETE with a predicate.",
            "Renames the table while preserving all rows.": "Use RENAME/ALTER RENAME for renaming.",
            "Rolls back the last transaction.": "Use ROLLBACK to undo a transaction.",
        },
    ),
    (
        "Normalization",
        "First normal form (1NF) requires that…",
        "Each cell holds a single atomic (indivisible) value and repeating groups are eliminated.",
        [
            "Every determinant is a candidate key.",
            "No non-key attribute depends on another non-key attribute.",
            "All joins are lossless without projection.",
        ],
        "1NF bans nested lists and multi-valued cells in a single column.",
        {
            "Every determinant is a candidate key.": "That characterizes BCNF, not 1NF.",
            "No non-key attribute depends on another non-key attribute.": "That is 3NF-style dependency rules.",
            "All joins are lossless without projection.": "Lossless join is a decomposition property, not 1NF.",
        },
    ),
    (
        "Normalization",
        "A relation is in 2NF if it is in 1NF and…",
        "No non-key attribute depends on a proper subset of a composite primary key.",
        [
            "Every table has exactly one column.",
            "All foreign keys reference surrogate keys only.",
            "Every index is clustered on the primary key.",
        ],
        "2NF removes partial dependencies: attributes must depend on the whole key, not part of it.",
        {
            "Every table has exactly one column.": "2NF allows composite keys; it concerns partial dependencies.",
            "All foreign keys reference surrogate keys only.": "Surrogate keys are a design choice, not part of 2NF.",
            "Every index is clustered on the primary key.": "Indexing is physical design, not normal form.",
        },
    ),
    (
        "Indexes",
        "Why are indexes created on database columns?",
        "To speed up data retrieval at the cost of extra storage and write overhead.",
        [
            "To guarantee that every query returns sorted results.",
            "To replace the need for a primary key.",
            "To enforce that no two transactions run concurrently.",
        ],
        "Indexes are auxiliary access paths (often B-trees) that reduce scan cost for selective lookups.",
        {
            "To guarantee that every query returns sorted results.": "ORDER BY controls sort order; indexes only help if the planner uses them.",
            "To replace the need for a primary key.": "Primary keys enforce uniqueness; indexes are optional helpers.",
            "To enforce that no two transactions run concurrently.": "Concurrency is controlled by locking and isolation, not indexes.",
        },
    ),
    (
        "Indexes",
        "A typical B-tree index supports which operation efficiently?",
        "Point lookups and range scans on the indexed key order.",
        [
            "Full table scans faster than reading heap pages.",
            "Arbitrary Cartesian products without sorting.",
            "Guaranteed O(1) lookup regardless of table size.",
        ],
        "B-trees keep keys sorted in balanced pages, enabling log-time seeks and ordered range reads.",
        {
            "Full table scans faster than reading heap pages.": "Sequential heap scans often beat random index probes for low selectivity.",
            "Arbitrary Cartesian products without sorting.": "Join algorithms still matter; indexes do not eliminate join cost.",
            "Guaranteed O(1) lookup regardless of table size.": "B-tree height grows with table size (logarithmic, not constant).",
        },
    ),
    (
        "Transactions",
        "What is a database transaction?",
        "A sequence of operations executed as a single logical unit of work.",
        [
            "Any SELECT statement that returns more than one row.",
            "A permanent schema change applied with ALTER TABLE.",
            "A network connection between client and server.",
        ],
        "Transactions group reads and writes so they commit or roll back together.",
        {
            "Any SELECT statement that returns more than one row.": "A multi-row SELECT is not necessarily transactional.",
            "A permanent schema change applied with ALTER TABLE.": "DDL may be transactional in some systems but is not the definition.",
            "A network connection between client and server.": "A session/connection can host many transactions.",
        },
    ),
    (
        "ACID",
        "Atomicity in ACID means…",
        "Either all operations in a transaction take effect, or none do.",
        [
            "Concurrent transactions never block each other.",
            "The database schema never changes.",
            "Every query runs in constant time.",
        ],
        "Atomicity is all-or-nothing: partial updates are rolled back on failure.",
        {
            "Concurrent transactions never block each other.": "That would ignore locking; isolation handles concurrency.",
            "The database schema never changes.": "Schema can change; atomicity applies to a transaction's effects.",
            "Every query runs in constant time.": "Complexity is unrelated to atomicity.",
        },
    ),
    (
        "ACID",
        "Consistency in ACID means…",
        "A committed transaction moves the database from one valid state to another, honoring constraints.",
        [
            "All replicas return identical answers at every instant.",
            "No transaction may ever abort.",
            "Indexes are always kept in memory.",
        ],
        "Consistency is about invariant rules (keys, checks, triggers) holding after commit.",
        {
            "All replicas return identical answers at every instant.": "That is a distributed replication concern, not the ACID definition.",
            "No transaction may ever abort.": "Transactions may abort to preserve consistency.",
            "Indexes are always kept in memory.": "Storage layout is implementation detail.",
        },
    ),
    (
        "ACID",
        "Isolation in ACID means…",
        "Concurrent transactions behave as if they did not interleave in problematic ways.",
        [
            "Data is encrypted on disk.",
            "Backups run only on weekends.",
            "Every table has at most one row.",
        ],
        "Isolation levels define which interleavings are visible (dirty reads, phantoms, etc.).",
        {
            "Data is encrypted on disk.": "Encryption is security, not isolation.",
            "Backups run only on weekends.": "Backup scheduling is operational, not ACID isolation.",
            "Every table has at most one row.": "Tables can have many rows.",
        },
    ),
    (
        "ACID",
        "Durability in ACID means…",
        "Committed changes survive crashes and restarts.",
        [
            "Uncommitted changes are visible to all users.",
            "Queries never use the write-ahead log.",
            "Indexes are rebuilt on every SELECT.",
        ],
        "Once COMMIT succeeds, the system must recover committed data after failure (often via WAL).",
        {
            "Uncommitted changes are visible to all users.": "That would violate isolation, not define durability.",
            "Queries never use the write-ahead log.": "WAL is a common durability mechanism.",
            "Indexes are rebuilt on every SELECT.": "SELECT should not rebuild indexes.",
        },
    ),
    (
        "Transactions",
        "What does COMMIT do?",
        "Makes a transaction's changes permanent and visible to other sessions (per isolation rules).",
        [
            "Undoes all changes made since the transaction began.",
            "Deletes the database file.",
            "Creates a new index on every column.",
        ],
        "COMMIT ends the transaction successfully; ROLLBACK discards changes.",
        {
            "Undoes all changes made since the transaction began.": "That is ROLLBACK.",
            "Deletes the database file.": "COMMIT persists work; it does not drop the database.",
            "Creates a new index on every column.": "Indexes are created explicitly with DDL.",
        },
    ),
    (
        "Transactions",
        "What does ROLLBACK do?",
        "Discards uncommitted changes made in the current transaction.",
        [
            "Permanently saves changes to disk.",
            "Increases the isolation level to SERIALIZABLE automatically.",
            "Exports the entire schema to CSV.",
        ],
        "ROLLBACK aborts the transaction and restores the pre-transaction view for that session.",
        {
            "Permanently saves changes to disk.": "That is COMMIT.",
            "Increases the isolation level to SERIALIZABLE automatically.": "Isolation is set explicitly, not by ROLLBACK.",
            "Exports the entire schema to CSV.": "Export tools are separate from transaction control.",
        },
    ),
    (
        "Schema Design",
        "A surrogate key is…",
        "An artificial identifier (e.g., auto-increment ID) with no business meaning.",
        [
            "A natural key derived from government-issued numbers only.",
            "A foreign key pointing to two parent tables at once.",
            "A checksum of all non-key columns.",
        ],
        "Surrogate keys stabilize joins when natural keys are composite or change over time.",
        {
            "A natural key derived from government-issued numbers only.": "Natural keys come from the domain (email, ISBN), not surrogates.",
            "A foreign key pointing to two parent tables at once.": "A foreign key references one parent relation (possibly composite).",
            "A checksum of all non-key columns.": "Checksums detect corruption; they are not primary keys.",
        },
    ),
]

_MEDIUM = [
    (
        "SQL",
        "An INNER JOIN between Orders and Customers returns…",
        "Only rows with matching keys in both tables.",
        [
            "All orders plus customers with NULLs where no match exists.",
            "All customers even if they placed no orders.",
            "The Cartesian product of every order with every customer.",
        ],
        "INNER JOIN keeps matches on the join predicate; non-matching rows are dropped.",
        {
            "All orders plus customers with NULLs where no match exists.": "That describes a LEFT OUTER JOIN from orders.",
            "All customers even if they placed no orders.": "That is RIGHT/LEFT OUTER from the customer side.",
            "The Cartesian product of every order with every customer.": "CROSS JOIN omits an equality predicate; INNER JOIN requires one.",
        },
    ),
    (
        "SQL",
        "Which clause filters groups after aggregation?",
        "HAVING",
        ["WHERE", "SELECT DISTINCT", "LIMIT"],
        "HAVING predicates apply to grouped aggregates (e.g., COUNT(*) > 10).",
        {
            "WHERE": "WHERE filters rows before grouping.",
            "SELECT DISTINCT": "DISTINCT removes duplicate result rows.",
            "LIMIT": "LIMIT caps row count after the query is evaluated.",
        },
    ),
    (
        "SQL",
        "A LEFT OUTER JOIN from A to B keeps…",
        "All rows from A, with NULLs in B's columns when no B row matches.",
        [
            "Only rows that match in both A and B.",
            "Only rows from B when A has no match.",
            "Rows from A only if B has at least two matching rows.",
        ],
        "LEFT OUTER preserves the left side entirely and pads missing right-side values with NULL.",
        {
            "Only rows that match in both A and B.": "That is an INNER JOIN.",
            "Only rows from B when A has no match.": "That would be RIGHT OUTER from B's perspective.",
            "Rows from A only if B has at least two matching rows.": "Joins do not require multiple matches on the right.",
        },
    ),
    (
        "Normalization",
        "Third normal form (3NF) eliminates…",
        "Transitive dependencies: non-key attributes depending on other non-key attributes.",
        [
            "Repeating groups within a single cell.",
            "Partial dependencies on part of a composite key only.",
            "Multivalued dependencies between independent facts.",
        ],
        "3NF requires non-key attributes depend only on keys, not on other non-key attributes.",
        {
            "Repeating groups within a single cell.": "That is addressed by 1NF.",
            "Partial dependencies on part of a composite key only.": "That is 2NF.",
            "Multivalued dependencies between independent facts.": "That is 4NF.",
        },
    ),
    (
        "Normalization",
        "Boyce-Codd Normal Form (BCNF) requires that…",
        "Every determinant of a functional dependency is a candidate key.",
        [
            "Every table has no more than three columns.",
            "All attributes are multi-valued.",
            "Foreign keys may not exist.",
        ],
        "BCNF strengthens 3NF: if X → Y, then X must be a superkey.",
        {
            "Every table has no more than three columns.": "BCNF is about dependencies, not column count.",
            "All attributes are multi-valued.": "BCNF assumes relational values (1NF).",
            "Foreign keys may not exist.": "BCNF allows foreign keys.",
        },
    ),
    (
        "Schema Design",
        "Denormalization is often used to…",
        "Reduce join cost and speed read-heavy workloads at the expense of update anomalies.",
        [
            "Guarantee BCNF in every table automatically.",
            "Eliminate the need for indexes entirely.",
            "Prevent any redundant data from ever existing.",
        ],
        "Denormalization trades redundancy for performance in OLAP or hot read paths.",
        {
            "Guarantee BCNF in every table automatically.": "Denormalization intentionally introduces redundancy.",
            "Eliminate the need for indexes entirely.": "Indexes remain useful on denormalized tables.",
            "Prevent any redundant data from ever existing.": "Denormalization adds redundant copies.",
        },
    ),
    (
        "Indexes",
        "A composite index on (last_name, first_name) helps most when a query…",
        "Filters or sorts on last_name, or on both columns in that order.",
        [
            "Filters only on first_name with no predicate on last_name.",
            "Selects all rows with SELECT * without a WHERE clause.",
            "Updates unrelated columns in random order.",
        ],
        "Composite B-tree indexes support left-prefix matching: leading column must be constrained for efficiency.",
        {
            "Filters only on first_name with no predicate on last_name.": "Skipping the leading column often prevents index use.",
            "Selects all rows with SELECT * without a WHERE clause.": "Full scans ignore selective index benefit.",
            "Updates unrelated columns in random order.": "Write patterns affect maintenance cost but not this lookup rule.",
        },
    ),
    (
        "Indexes",
        "A covering index for a query is one that…",
        "Includes all columns needed by the query so the engine can satisfy it from the index alone.",
        [
            "Spans every table in the database schema.",
            "Replaces the primary key constraint.",
            "Stores only NULL values for faster scans.",
        ],
        "Index-only scans avoid heap lookups when projected columns are in the index payload.",
        {
            "Spans every table in the database schema.": "Indexes are per-table (or per-partition) structures.",
            "Replaces the primary key constraint.": "Covering indexes complement, not replace, keys.",
            "Stores only NULL values for faster scans.": "NULL handling exists but covering means included columns, not NULL-only.",
        },
    ),
    (
        "Transactions",
        "A deadlock occurs when…",
        "Two or more transactions wait on each other's locks in a cycle.",
        [
            "A single transaction runs longer than one second.",
            "The database runs out of disk space during SELECT.",
            "An index is missing on a foreign key.",
        ],
        "Circular wait-for graphs cause deadlock; engines abort one victim transaction.",
        {
            "A single transaction runs longer than one second.": "Long transactions are problematic but not deadlock by definition.",
            "The database runs out of disk space during SELECT.": "That is resource exhaustion, not lock cycling.",
            "An index is missing on a foreign key.": "Missing indexes hurt performance but do not define deadlock.",
        },
    ),
    (
        "Isolation Levels",
        "A lost update anomaly happens when…",
        "Two transactions read the same value, compute new values independently, and the later write overwrites the earlier without merging.",
        [
            "A transaction reads uncommitted data from another session.",
            "A transaction sees new rows inserted by another transaction on re-read.",
            "The database loses power before COMMIT.",
        ],
        "Lost update is a write-write conflict without proper locking or versioning.",
        {
            "A transaction reads uncommitted data from another session.": "That is a dirty read.",
            "A transaction sees new rows inserted by another transaction on re-read.": "That is a phantom read.",
            "The database loses power before COMMIT.": "That concerns durability, not lost updates.",
        },
    ),
    (
        "Isolation Levels",
        "A dirty read is…",
        "Reading data written by another transaction that has not yet committed.",
        [
            "Reading only committed data at snapshot time.",
            "Reading the same row twice with identical results under repeatable read.",
            "Reading an empty table after TRUNCATE in another session that rolled back.",
        ],
        "Dirty reads see uncommitted changes that may be rolled back.",
        {
            "Reading only committed data at snapshot time.": "That is consistent snapshot behavior.",
            "Reading the same row twice with identical results under repeatable read.": "Repeatable read prevents non-repeatable reads, not dirty reads by definition.",
            "Reading an empty table after TRUNCATE in another session that rolled back.": "If the other transaction rolled back, you should not see TRUNCATE effects—dirty read is about uncommitted writes.",
        },
    ),
    (
        "Isolation Levels",
        "READ COMMITTED isolation typically prevents…",
        "Dirty reads.",
        [
            "All phantom reads in every database engine.",
            "All write skew anomalies without extra locking.",
            "Deadlocks entirely.",
        ],
        "READ COMMITTED hides uncommitted data; phantoms and write skew may still occur.",
        {
            "All phantom reads in every database engine.": "Phantom prevention usually needs higher isolation or locking.",
            "All write skew anomalies without extra locking.": "Write skew needs careful constraints or SERIALIZABLE.",
            "Deadlocks entirely.": "Deadlocks can occur at any isolation level.",
        },
    ),
    (
        "Isolation Levels",
        "REPEATABLE READ usually guarantees that…",
        "Rows read earlier in the transaction appear unchanged on subsequent reads in the same transaction.",
        [
            "No new rows can ever be inserted into the database.",
            "All sessions see identical global snapshots forever.",
            "Every SELECT uses a full table lock on all tables.",
        ],
        "Repeatable read stabilizes existing rows; phantoms may still appear depending on engine.",
        {
            "No new rows can ever be inserted into the database.": "Inserts by others may still occur (phantoms).",
            "All sessions see identical global snapshots forever.": "Snapshots are per-transaction, not permanent.",
            "Every SELECT uses a full table lock on all tables.": "Engines use row/version mechanisms, not global SELECT locks.",
        },
    ),
    (
        "Isolation Levels",
        "SERIALIZABLE isolation aims to ensure…",
        "Transaction schedules are equivalent to some serial (one-at-a-time) order.",
        [
            "All queries execute in parallel without any locks.",
            "Only one table may be referenced per transaction.",
            "Indexes are disabled to avoid deadlocks.",
        ],
        "Serializable is the strongest ANSI level: no anomalies from interleaving.",
        {
            "All queries execute in parallel without any locks.": "Serializable still uses locking or validation.",
            "Only one table may be referenced per transaction.": "Multi-table transactions are allowed.",
            "Indexes are disabled to avoid deadlocks.": "Indexes remain active.",
        },
    ),
    (
        "SQL",
        "A SQL view is…",
        "A stored query definition that behaves like a virtual table.",
        [
            "A physical copy of data refreshed only on database restart.",
            "A transaction isolation level.",
            "An index organized by column cardinality.",
        ],
        "Views encapsulate queries; some are updatable under strict rules.",
        {
            "A physical copy of data refreshed only on database restart.": "That describes a materialized view.",
            "A transaction isolation level.": "Isolation levels are transaction properties.",
            "An index organized by column cardinality.": "Indexes are storage structures, not view definitions.",
        },
    ),
    (
        "Schema Design",
        "ON DELETE CASCADE on a foreign key means…",
        "Deleting a parent row automatically deletes referencing child rows.",
        [
            "Child rows become orphaned with NULL primary keys.",
            "Deletes are forbidden on the parent table.",
            "The child table is dropped from the schema.",
        ],
        "CASCADE propagates deletes (and UPDATE CASCADE propagates key changes) along the FK.",
        {
            "Child rows become orphaned with NULL primary keys.": "SET NULL or RESTRICT behave differently; CASCADE removes children.",
            "Deletes are forbidden on the parent table.": "That is RESTRICT/NO ACTION, not CASCADE.",
            "The child table is dropped from the schema.": "CASCADE removes rows, not tables.",
        },
    ),
    (
        "Query Planning",
        "Selectivity of a predicate measures…",
        "The fraction of rows the predicate is expected to match.",
        [
            "The number of columns in the SELECT list.",
            "The maximum transaction isolation level.",
            "The width of VARCHAR columns in bytes.",
        ],
        "Low selectivity (high match fraction) favors sequential scans; high selectivity favors indexes.",
        {
            "The number of columns in the SELECT list.": "Projection width is unrelated to predicate selectivity.",
            "The maximum transaction isolation level.": "Isolation is transactional, not selectivity.",
            "The width of VARCHAR columns in bytes.": "Column width affects I/O size, not match fraction.",
        },
    ),
    (
        "Query Planning",
        "EXPLAIN (or EXPLAIN ANALYZE) shows…",
        "The optimizer's chosen plan operators and estimated costs (and actual timings with ANALYZE).",
        [
            "The complete history of every committed transaction.",
            "A list of all user passwords in hashed form.",
            "The ER diagram rendered as SVG.",
        ],
        "Plan output reveals joins, scans, index usage, and cost estimates for tuning.",
        {
            "The complete history of every committed transaction.": "Transaction logs are separate audit/recovery artifacts.",
            "A list of all user passwords in hashed form.": "Security catalogs are not EXPLAIN output.",
            "The ER diagram rendered as SVG.": "EXPLAIN is execution-plan text, not modeling diagrams.",
        },
    ),
    (
        "Schema Design",
        "Referential integrity ensures that…",
        "Foreign-key values reference existing primary-key values (or defined exceptions).",
        [
            "Every column has a UNIQUE constraint.",
            "All queries use indexes.",
            "Transactions always run at SERIALIZABLE.",
        ],
        "FK constraints tie child tuples to valid parents unless ON DELETE/UPDATE rules apply.",
        {
            "Every column has a UNIQUE constraint.": "Uniqueness is optional per column.",
            "All queries use indexes.": "The optimizer chooses access paths; integrity is constraint-based.",
            "Transactions always run at SERIALIZABLE.": "Default isolation varies by system.",
        },
    ),
    (
        "SQL",
        "A materialized view differs from an ordinary view because it…",
        "Stores the result set physically and must be refreshed to stay current.",
        [
            "Cannot be queried with SQL.",
            "Automatically enforces 5NF on base tables.",
            "Replaces the write-ahead log for durability.",
        ],
        "Materialized views trade freshness for read performance via stored answers.",
        {
            "Cannot be queried with SQL.": "Materialized views are queried like tables.",
            "Automatically enforces 5NF on base tables.": "Normal forms are design properties, not view features.",
            "Replaces the write-ahead log for durability.": "Durability still uses logging mechanisms.",
        },
    ),
]

_HARD = [
    (
        "Normalization",
        "Fourth normal form (4NF) addresses…",
        "Multivalued dependencies: independent multi-valued facts about the same key should be split.",
        [
            "Partial dependencies on part of a composite key.",
            "Transitive dependencies among non-key attributes only.",
            "Lossless join without dependency preservation.",
        ],
        "4NF separates unrelated multi-valued sets (e.g., skills and languages for an employee).",
        {
            "Partial dependencies on part of a composite key.": "Partial dependencies are 2NF concerns.",
            "Transitive dependencies among non-key attributes only.": "Transitive dependencies are 3NF concerns.",
            "Lossless join without dependency preservation.": "That is decomposition theory, not the 4NF definition.",
        },
    ),
    (
        "Normalization",
        "Fifth normal form (5NF), or PJ/NF, deals with…",
        "Join dependencies that cannot be reconstructed from smaller projections without spurious tuples.",
        [
            "Only tables with exactly five columns.",
            "Encrypting attributes at rest.",
            "Mandatory clustered indexes on foreign keys.",
        ],
        "5NF splits relations when join recombination invents extra rows not present in the original.",
        {
            "Only tables with exactly five columns.": "The 'fifth' refers to normal form level, not column count.",
            "Encrypting attributes at rest.": "Security is orthogonal to PJ/NF.",
            "Mandatory clustered indexes on foreign keys.": "Physical design is separate from 5NF.",
        },
    ),
    (
        "Query Planning",
        "A nested-loop join is often chosen when…",
        "One input is small and indexed lookups on the inner table are cheap per outer row.",
        [
            "Both inputs are huge unsorted heaps with no indexes.",
            "The optimizer must guarantee SERIALIZABLE isolation.",
            "All predicates are non-equality cross products.",
        ],
        "Nested-loop probes the inner for each outer row; it excels with selective indexes on the inner key.",
        {
            "Both inputs are huge unsorted heaps with no indexes.": "Large unsorted inputs favor hash or merge joins.",
            "The optimizer must guarantee SERIALIZABLE isolation.": "Isolation is independent of join algorithm choice.",
            "All predicates are non-equality cross products.": "Cross products are expensive; nested-loop still needs join predicates for equi-joins.",
        },
    ),
    (
        "Query Planning",
        "A hash join typically builds a hash table on…",
        "The smaller (build) input, probing with the larger (probe) input.",
        [
            "Always the alphabetically first table name.",
            "Only columns with UNIQUE constraints disabled.",
            "The transaction log to ensure durability.",
        ],
        "Hash joins partition by join key on the build side, then probe hashes for matches.",
        {
            "Always the alphabetically first table name.": "Optimizers pick build side by size/cardinality, not name.",
            "Only columns with UNIQUE constraints disabled.": "Uniqueness affects plan cost but not the build/probe roles directly.",
            "The transaction log to ensure durability.": "Logs are recovery structures, not join hash tables.",
        },
    ),
    (
        "Indexes",
        "An index-only scan is possible when…",
        "All required columns appear in the index (including INCLUDE/ covering columns) so heap access is unnecessary.",
        [
            "The query performs arbitrary user-defined functions on heap-only columns.",
            "The table has no primary key defined.",
            "The isolation level is READ UNCOMMITTED only.",
        ],
        "Visibility map and index tuple versions must allow answering from the index leaf pages alone.",
        {
            "The query performs arbitrary user-defined functions on heap-only columns.": "Heap columns force heap fetches unless expressions are indexed.",
            "The table has no primary key defined.": "Primary keys are unrelated to index-only feasibility.",
            "The isolation level is READ UNCOMMITTED only.": "Isolation affects visibility, but covering columns are the main requirement.",
        },
    ),
    (
        "Isolation Levels",
        "A phantom read occurs when…",
        "A transaction re-issues a range query and sees new rows committed by another transaction.",
        [
            "A transaction reads the same row twice with different uncommitted values.",
            "Two transactions deadlock on the same row.",
            "The database returns an error on the first SELECT.",
        ],
        "Phantoms are new tuples appearing in a range; repeatable read may block some but not all engines block phantoms.",
        {
            "A transaction reads the same row twice with different uncommitted values.": "Uncommitted changes imply dirty/non-repeatable reads, not phantoms.",
            "Two transactions deadlock on the same row.": "Deadlock is lock cycling, not phantom inserts.",
            "The database returns an error on the first SELECT.": "Errors are unrelated to phantom anomaly definition.",
        },
    ),
    (
        "Isolation Levels",
        "Snapshot isolation (common in MVCC engines) provides…",
        "Consistent reads of committed data as of a transaction start snapshot, but may allow write skew without extra rules.",
        [
            "Strict serial equivalence identical to two-phase locking in all cases.",
            "Dirty reads of uncommitted transactions.",
            "Automatic normalization to BCNF on commit.",
        ],
        "Readers see a stable snapshot; writers may conflict; write skew needs careful handling beyond SI alone.",
        {
            "Strict serial equivalence identical to two-phase locking in all cases.": "Snapshot isolation is not always equivalent to full serializability.",
            "Dirty reads of uncommitted transactions.": "MVCC snapshots hide uncommitted writes.",
            "Automatic normalization to BCNF on commit.": "Schema normal forms are design-time, not commit-time.",
        },
    ),
    (
        "Transactions",
        "Two-phase locking (2PL) ensures conflict-serializability by…",
        "Growing locks until the transaction reaches its peak, then shrinking locks only after commit/abort begins.",
        [
            "Never acquiring shared locks on reads.",
            "Committing immediately after the first read.",
            "Disabling all indexes during updates.",
        ],
        "Strict 2PL holds all locks until end of transaction, preventing cascading rollbacks of schedules.",
        {
            "Never acquiring shared locks on reads.": "Shared locks are part of 2PL for reads.",
            "Committing immediately after the first read.": "Early commit would release locks too soon.",
            "Disabling all indexes during updates.": "Indexes remain; locking governs interleaving.",
        },
    ),
    (
        "Isolation Levels",
        "Write skew happens when…",
        "Two transactions read overlapping data, make disjoint writes based on stale reads, and together violate an invariant.",
        [
            "A single UPDATE touches every row in the table.",
            "The database rejects all SERIALIZABLE transactions.",
            "An index is rebuilt during SELECT.",
        ],
        "Classic example: two doctors on-call checks each read count≥1, both go off-call, leaving zero—needs serializable or constraints.",
        {
            "A single UPDATE touches every row in the table.": "Bulk update is not write skew.",
            "The database rejects all SERIALIZABLE transactions.": "Serializable prevents write skew; it does not define it.",
            "An index is rebuilt during SELECT.": "Maintenance operations are unrelated.",
        },
    ),
    (
        "Transactions",
        "Optimistic concurrency control (OCC) typically…",
        "Validates at commit that no conflicting writes occurred since the transaction's snapshot/read set.",
        [
            "Locks every row on first SELECT FOR UPDATE automatically.",
            "Disallows any read operations.",
            "Requires denormalized schemas only.",
        ],
        "OCC assumes low conflict: read freely, check versions/validation on commit, abort if conflict detected.",
        {
            "Locks every row on first SELECT FOR UPDATE automatically.": "That is pessimistic locking, not OCC.",
            "Disallows any read operations.": "OCC relies on reads with validation.",
            "Requires denormalized schemas only.": "Schema style is independent of OCC.",
        },
    ),
    (
        "Indexes",
        "A partial index (filtered index) indexes…",
        "Only rows satisfying a predicate (e.g., WHERE active = true), reducing size and maintenance cost.",
        [
            "Every column in the table including LOB blobs always.",
            "Only rows that violate foreign keys.",
            "Only temporary tables in the information schema.",
        ],
        "Partial indexes target hot subsets (active users, open orders) for selective queries.",
        {
            "Every column in the table including LOB blobs always.": "Partial means row filter, not all columns by default.",
            "Only rows that violate foreign keys.": "Invalid rows should not exist if constraints enforce integrity.",
            "Only temporary tables in the information schema.": "Partial indexes apply to user tables with predicates.",
        },
    ),
    (
        "Normalization",
        "A decomposition is lossless when…",
        "Joining the projected relations recovers exactly the original tuples without spurious rows.",
        [
            "Every attribute appears in only one relation regardless of dependencies.",
            "All functional dependencies are eliminated entirely.",
            "The database removes all foreign keys.",
        ],
        "Lossless join tests (e.g., chase) ensure natural join of fragments equals the source relation.",
        {
            "Every attribute appears in only one relation regardless of dependencies.": "Dependency preservation is a separate goal.",
            "All functional dependencies are eliminated entirely.": "Dependencies should be preserved when possible.",
            "The database removes all foreign keys.": "Foreign keys express relationships; lossless join is relational algebra property.",
        },
    ),
    (
        "Normalization",
        "BCNF can be stricter than 3NF when…",
        "A relation has overlapping candidate keys so a non-superkey determinant remains.",
        [
            "Every determinant is a single-attribute primary key.",
            "The table has no functional dependencies at all.",
            "All attributes are prime (part of some candidate key).",
        ],
        "Classic example: R(Student, Course, Instructor) with Instructor → Course is in 3NF but not BCNF if (Student, Course) is key.",
        {
            "Every determinant is a single-attribute primary key.": "Then BCNF and 3NF often coincide.",
            "The table has no functional dependencies at all.": "Without FDs, normal forms trivially hold.",
            "All attributes are prime (part of some candidate key).": "That is 3NF-by-definition case where BCNF may still differ with overlapping keys.",
        },
    ),
    (
        "Query Planning",
        "Histogram statistics in the catalog help the optimizer…",
        "Estimate predicate selectivity and data distribution per column.",
        [
            "Encrypt data at rest with AES-256 automatically.",
            "Guarantee zero deadlocks globally.",
            "Store undo logs for every SELECT query.",
        ],
        "Histograms capture non-uniform distributions better than single average row width alone.",
        {
            "Encrypt data at rest with AES-256 automatically.": "Encryption is security configuration.",
            "Guarantee zero deadlocks globally.": "Deadlocks can still occur with accurate stats.",
            "Store undo logs for every SELECT query.": "SELECT does not generate undo; DML does.",
        },
    ),
    (
        "Query Planning",
        "A cost-based optimizer chooses plans by…",
        "Estimating resource costs (I/O, CPU, memory) for alternative physical operators and picking a low-cost plan.",
        [
            "Always picking nested-loop joins regardless of size.",
            "Executing every possible plan fully before choosing.",
            "Ignoring table statistics entirely.",
        ],
        "CBO uses stats (row counts, NDV, histograms) and cost models to compare join orders and access paths.",
        {
            "Always picking nested-loop joins regardless of size.": "CBO weighs hash/merge/nested-loop based on estimates.",
            "Executing every possible plan fully before choosing.": "That would be prohibitively expensive; estimates suffice.",
            "Ignoring table statistics entirely.": "Stats are central to cost estimation.",
        },
    ),
    (
        "Schema Design",
        "Slowly Changing Dimension (SCD) Type 2 tracking typically…",
        "Stores a new row with new surrogate key and effective dates when an attribute changes, preserving history.",
        [
            "Overwrites the old row in place without history.",
            "Deletes the dimension table on each change.",
            "Stores only the current value in a flat file outside the database.",
        ],
        "Type 2 adds version rows (valid_from/valid_to, is_current) for warehouse history.",
        {
            "Overwrites the old row in place without history.": "That is Type 1 overwrite.",
            "Deletes the dimension table on each change.": "Dimensions persist; versions accumulate.",
            "Stores only the current value in a flat file outside the database.": "SCD Type 2 is a relational warehousing pattern.",
        },
    ),
    (
        "Schema Design",
        "OLTP schemas differ from OLAP star schemas mainly because OLTP…",
        "Normalizes data to support many small concurrent writes with integrity constraints.",
        [
            "Stores only denormalized fact tables without dimensions.",
            "Disallows transactions and indexes.",
            "Requires every query to scan all partitions fully.",
        ],
        "OLTP favors normalized operational tables; OLAP favors denormalized stars for analytic scans.",
        {
            "Stores only denormalized fact tables without dimensions.": "Star schemas with facts and dimensions are OLAP.",
            "Disallows transactions and indexes.": "OLTP relies heavily on transactions and indexes.",
            "Requires every query to scan all partitions fully.": "Analytic scans are OLAP; OLTP targets point lookups/short updates.",
        },
    ),
    (
        "Schema Design",
        "Choosing a natural key over a surrogate key is preferable when…",
        "The business identifier is stable, unique, and small enough for efficient joins.",
        [
            "The identifier frequently changes format or merges across legacy systems.",
            "Composite keys always slow every join and must be avoided even if stable.",
            "Surrogate keys are prohibited by SQL standards.",
        ],
        "Natural keys (ISBN, country code) expose meaning; surrogates help when natural keys change or are wide.",
        {
            "The identifier frequently changes format or merges across legacy systems.": "Instability favors surrogates.",
            "Composite keys always slow every join and must be avoided even if stable.": "Stable composite natural keys are valid when modeled carefully.",
            "Surrogate keys are prohibited by SQL standards.": "SQL allows both; choice is engineering tradeoff.",
        },
    ),
    (
        "Indexes",
        "For composite index (a, b, c), a query filtering on b and c alone without a predicate on a…",
        "Often cannot use the index for a pure index range scan on b,c due to left-prefix rules (unless index skip scan exists).",
        [
            "Always performs an index-only scan on all three leading columns.",
            "Forces the database to drop the primary key.",
            "Requires SERIALIZABLE isolation to read any rows.",
        ],
        "B-tree composite indexes are ordered by leading columns; skipping 'a' breaks contiguous range access.",
        {
            "Always performs an index-only scan on all three leading columns.": "Missing leading column usually blocks efficient range use.",
            "Forces the database to drop the primary key.": "Primary keys are independent of secondary index prefix rules.",
            "Requires SERIALIZABLE isolation to read any rows.": "Isolation does not govern index prefix usability.",
        },
    ),
    (
        "Query Planning",
        "Index merge (intersection/union) plans combine…",
        "Multiple single-column (or narrow) indexes to satisfy AND/OR predicates when one composite index is unavailable.",
        [
            "Two unrelated databases on different hosts without federation.",
            "Only full-table scans because indexes cannot be combined.",
            "User passwords with hash join build sides.",
        ],
        "Optimizers may bitmap-or/and rowid sets from several indexes to filter rows before heap access.",
        {
            "Two unrelated databases on different hosts without federation.": "Index merge is intra-database plan choice.",
            "Only full-table scans because indexes cannot be combined.": "Index merge exists precisely to combine indexes.",
            "User passwords with hash join build sides.": "Security data is unrelated to index intersection plans.",
        },
    ),
]

BOOK = make_book(
    title="Database Design",
    parent_topic="Computer Science",
    subtopic="Databases",
    slug="databases-design",
    source_url="https://open.umn.edu/opentextbooks/textbooks/database-design-2nd-edition",
    easy=_EASY,
    medium=_MEDIUM,
    hard=_HARD,
)
