"""Quiz bank: Dive into Deep Learning (D2L) — deep learning focus."""
from quiz_banks._make_book import make_book

BOOK = make_book(
    title="Dive into Deep Learning",
    parent_topic="AI & Machine Learning",
    subtopic="Deep Learning",
    slug="deep-learning-d2l",
    source_url="https://d2l.ai/",
    easy=[
        (
            "Neural Networks",
            "A single artificial neuron (perceptron) computes its output by…",
            "Forming a weighted sum of inputs plus bias, then applying an activation function.",
            [
                "Sorting inputs and returning the median value.",
                "Counting how many inputs are nonzero, with no weights.",
                "Multiplying all inputs together without any bias term.",
            ],
            "y = σ(wᵀx + b) is the basic unit; depth stacks many such units with nonlinear σ.",
            {
                "Sorting inputs and returning the median value.": "Neurons use learned weights, not order statistics.",
                "Counting how many inputs are nonzero, with no weights.": "That ignores continuous features and learned parameters.",
                "Multiplying all inputs together without any bias term.": "Affine transforms use sums and bias, not products alone.",
            },
        ),
        (
            "Neural Networks",
            "Stacking multiple hidden layers in a feedforward network primarily enables…",
            "Hierarchical feature composition through repeated nonlinear transforms.",
            [
                "Guaranteed convex optimization of the loss.",
                "Eliminating the need for any labeled data.",
                "Fixed-size outputs regardless of input dimension.",
            ],
            "Each layer builds increasingly abstract representations; depth adds expressive power beyond a single layer.",
            {
                "Guaranteed convex optimization of the loss.": "Deep nets are generally non-convex in their parameters.",
                "Eliminating the need for any labeled data.": "Supervised deep learning still needs labels for training.",
                "Fixed-size outputs regardless of input dimension.": "Architecture must match input/output shapes.",
            },
        ),
        (
            "Forward Pass",
            "During forward propagation in a feedforward network, each layer…",
            "Transforms the previous layer's activations into new activations until the output layer.",
            [
                "Updates weights using gradients from the next batch.",
                "Randomly permutes training labels.",
                "Computes validation accuracy without using inputs.",
            ],
            "Forward pass is inference through the computation graph: inputs flow toward predictions.",
            {
                "Updates weights using gradients from the next batch.": "Weight updates happen after backward pass, not during forward.",
                "Randomly permutes training labels.": "Labels are fixed targets; forward pass uses features.",
                "Computes validation accuracy without using inputs.": "Predictions require passing inputs through the network.",
            },
        ),
        (
            "Backpropagation",
            "Backpropagation through a deep network applies the chain rule to…",
            "Propagate loss gradients backward through each layer's local Jacobians.",
            [
                "Cluster unlabeled examples into k groups.",
                "Normalize pixel values to unit variance only at test time.",
                "Select hyperparameters without computing any derivatives.",
            ],
            "Reverse-mode autodiff multiplies ∂L/∂(layer output) by ∂(layer output)/∂(parameters) at each step.",
            {
                "Cluster unlabeled examples into k groups.": "Clustering is unsupervised; backprop computes supervised gradients.",
                "Normalize pixel values to unit variance only at test time.": "Normalization is preprocessing, not gradient propagation.",
                "Select hyperparameters without computing any derivatives.": "Backprop explicitly computes derivatives for learning.",
            },
        ),
        (
            "Convolutions",
            "Compared with a fully connected layer on images, convolution uses…",
            "Local receptive fields and shared filters slid across spatial positions.",
            [
                "A separate unique weight for every input–output pair globally.",
                "Only 1×1 kernels that never mix neighboring pixels.",
                "Fixed random filters that are never learned from data.",
            ],
            "Local connectivity and weight sharing exploit spatial structure and reduce parameters.",
            {
                "A separate unique weight for every input–output pair globally.": "That describes a dense layer on flattened pixels.",
                "Only 1×1 kernels that never mix neighboring pixels.": "Typical conv kernels (3×3, 5×5) mix local neighborhoods.",
                "Fixed random filters that are never learned from data.": "Conv filters are learned parameters.",
            },
        ),
        (
            "Convolutions",
            "Stride greater than 1 in a convolutional layer…",
            "Downsamples the spatial resolution of the feature map.",
            [
                "Increases channel depth without changing height or width.",
                "Applies the same filter only once at the image center.",
                "Removes the need for any activation function.",
            ],
            "Stride s moves the kernel s pixels per step, producing smaller H×W outputs.",
            {
                "Increases channel depth without changing height or width.": "Channel depth is set by number of filters, not stride alone.",
                "Applies the same filter only once at the image center.": "Conv slides across the input grid (subject to padding).",
                "Removes the need for any activation function.": "Activations remain important for nonlinearity.",
            },
        ),
        (
            "Convolutions",
            "Zero-padding around an image before convolution is commonly used to…",
            "Control output spatial size (e.g., preserve dimensions with 'same' padding).",
            [
                "Convert RGB images to grayscale automatically.",
                "Guarantee that training loss is exactly zero.",
                "Replace backpropagation with a closed-form solution.",
            ],
            "Padding adds border pixels so kernels can be applied at edges without shrinking excessively.",
            {
                "Convert RGB images to grayscale automatically.": "Channel reduction is a separate preprocessing choice.",
                "Guarantee that training loss is exactly zero.": "Padding affects geometry, not optimality of loss.",
                "Replace backpropagation with a closed-form solution.": "Training still uses gradient-based learning.",
            },
        ),
        (
            "Convolutions",
            "Max pooling over a 2×2 window with stride 2 typically…",
            "Halves height and width while keeping the strongest local response per region.",
            [
                "Doubles the number of input channels.",
                "Computes a weighted sum of all pixels in the image.",
                "Applies a learnable 3×3 kernel at every position.",
            ],
            "Max pool selects the maximum activation in each window, downsampling spatially.",
            {
                "Doubles the number of input channels.": "Pooling reduces spatial size; channel count is unchanged unless followed by conv.",
                "Computes a weighted sum of all pixels in the image.": "That is closer to global average pooling over the whole map.",
                "Applies a learnable 3×3 kernel at every position.": "Pooling has no learnable weights (unlike conv).",
            },
        ),
        (
            "RNNs",
            "At each time step t, a vanilla RNN combines…",
            "The current input x_t with the previous hidden state h_{t−1} to produce h_t.",
            [
                "Only x_t, with no memory of earlier steps.",
                "The entire future sequence x_{t+1}, … before seeing x_t.",
                "Independent parallel predictions with no shared parameters across time.",
            ],
            "h_t = f(W_h h_{t−1} + W_x x_t + b) recurs over time, carrying summarized history.",
            {
                "Only x_t, with no memory of earlier steps.": "That would be a feedforward model per step, not an RNN.",
                "The entire future sequence x_{t+1}, … before seeing x_t.": "Causal RNNs do not use future inputs at step t.",
                "Independent parallel predictions with no shared parameters across time.": "RNNs share weights across time steps.",
            },
        ),
        (
            "RNNs",
            "Backpropagation through time (BPTT) on an RNN…",
            "Unrolls the recurrent computation over T steps and applies backprop on that graph.",
            [
                "Trains each time step with a separate unrelated network.",
                "Propagates gradients only through the final time step.",
                "Eliminates gradients by detaching all hidden states.",
            ],
            "BPTT treats the unfolded chain as a deep feedforward net through time.",
            {
                "Trains each time step with a separate unrelated network.": "Shared weights tie steps together in one model.",
                "Propagates gradients only through the final time step.": "Earlier steps receive gradients via recurrent connections.",
                "Eliminates gradients by detaching all hidden states.": "Detaching stops BPTT; standard training keeps the graph connected.",
            },
        ),
        (
            "Optimization",
            "If the learning rate is far too large during SGD training, you often observe…",
            "Oscillating or diverging loss instead of stable descent.",
            [
                "Instant convergence to zero loss in one iteration.",
                "Gradients that are always exactly zero.",
                "Automatic doubling of dataset size each epoch.",
            ],
            "Oversized steps overshoot minima and can explode activations and weights.",
            {
                "Instant convergence to zero loss in one iteration.": "Oversized steps rarely find a good minimum immediately.",
                "Gradients that are always exactly zero.": "That suggests vanishing gradients or a bug, not high LR alone.",
                "Automatic doubling of dataset size each epoch.": "Learning rate does not change the dataset.",
            },
        ),
        (
            "Optimization",
            "A mini-batch gradient update uses…",
            "The average gradient over a subset of examples (batch size B).",
            [
                "The exact full-dataset gradient every single step.",
                "One randomly chosen weight dimension per step only.",
                "No stochasticity — only deterministic closed-form solves.",
            ],
            "Mini-batches balance noise and throughput: ∇ ≈ (1/B) Σᵢ ∇ℓᵢ.",
            {
                "The exact full-dataset gradient every single step.": "That is full-batch gradient descent.",
                "One randomly chosen weight dimension per step only.": "SGD updates use gradients for all parameters.",
                "No stochasticity — only deterministic closed-form solves.": "Mini-batch SGD is inherently stochastic.",
            },
        ),
        (
            "Regularization",
            "At inference time, dropout is typically handled by…",
            "Disabling dropout (or equivalently using the expected scaling used during training).",
            [
                "Randomly zeroing half the neurons on every test example.",
                "Doubling the learning rate for each layer.",
                "Removing all nonlinear activation functions.",
            ],
            "Dropout is a training-time stochastic regularizer; the full network is used at test time.",
            {
                "Randomly zeroing half the neurons on every test example.": "That would inject noise into predictions at deployment.",
                "Doubling the learning rate for each layer.": "Learning rate is not applied during inference.",
                "Removing all nonlinear activation functions.": "Activations remain; only dropout masks stop.",
            },
        ),
        (
            "Regularization",
            "Data augmentation for images (random crops, flips) helps generalization by…",
            "Exposing the model to plausible label-preserving variations during training.",
            [
                "Reducing the number of unique parameters to zero.",
                "Guaranteeing that test images are identical to training images.",
                "Replacing the loss function with unsupervised clustering.",
            ],
            "Augmentation simulates more diverse inputs without collecting new labels.",
            {
                "Reducing the number of unique parameters to zero.": "Augmentation does not remove parameters.",
                "Guaranteeing that test images are identical to training images.": "Test data should remain unseen; augmentation diversifies train only.",
                "Replacing the loss function with unsupervised clustering.": "Augmentation keeps supervised labels on transformed inputs.",
            },
        ),
        (
            "Training",
            "Transfer learning in vision often starts by…",
            "Using weights pretrained on a large dataset, then fine-tuning on the target task.",
            [
                "Training from random initialization only on three images.",
                "Removing all convolutional layers and using only pooling.",
                "Freezing the loss function so it never changes.",
            ],
            "Pretrained features (e.g., on ImageNet) provide strong low-level filters for new tasks.",
            {
                "Training from random initialization only on three images.": "Too little data; pretraining supplies useful representations.",
                "Removing all convolutional layers and using only pooling.": "Conv layers carry most transferable features.",
                "Freezing the loss function so it never changes.": "The loss is fixed by task; weights are what adapt.",
            },
        ),
        (
            "Neural Networks",
            "A flatten (reshape) layer before a classifier head…",
            "Converts a convolutional feature map tensor into a 1D vector for dense layers.",
            [
                "Applies a 3×3 convolution with stride 2.",
                "Performs max pooling across the entire dataset.",
                "Encodes positional information with sinusoids.",
            ],
            "After conv blocks, H×W×C features are vectorized for fully connected classification.",
            {
                "Applies a 3×3 convolution with stride 2.": "Flatten does not convolve; it reshapes.",
                "Performs max pooling across the entire dataset.": "Pooling operates on spatial maps, not batch-level flatten.",
                "Encodes positional information with sinusoids.": "That describes transformer positional encodings.",
            },
        ),
        (
            "Neural Networks",
            "Residual (skip) connections in ResNet add…",
            "The layer's input to its transformed output: y = F(x) + x.",
            [
                "The loss value directly to every weight matrix.",
                "A second softmax over all hidden units.",
                "Random noise sampled from the training labels.",
            ],
            "Identity shortcuts let gradients flow across blocks and ease optimization of very deep nets.",
            {
                "The loss value directly to every weight matrix.": "Loss affects updates via gradients, not additive skip paths.",
                "A second softmax over all hidden units.": "Softmax is typically an output activation, not a skip connection.",
                "Random noise sampled from the training labels.": "Skip connections add activations, not label noise.",
            },
        ),
        (
            "Training",
            "One training iteration (step) usually means…",
            "One parameter update from one mini-batch (forward + backward + optimizer step).",
            [
                "One complete pass through the entire training set.",
                "One evaluation pass over the test set only.",
                "One random shuffle of the filesystem directory tree.",
            ],
            "Iteration counts optimizer steps; epoch counts full passes over the training data.",
            {
                "One complete pass through the entire training set.": "That is one epoch, not one iteration.",
                "One evaluation pass over the test set only.": "Evaluation does not perform training updates.",
                "One random shuffle of the filesystem directory tree.": "Shuffling data may happen, but an iteration is an update step.",
            },
        ),
        (
            "Optimization",
            "Weight decay in modern deep learning optimizers typically…",
            "Shrinks weights each step (often decoupled from the loss penalty in AdamW).",
            [
                "Increases weight magnitudes to fight underfitting always.",
                "Replaces gradients with zero vectors.",
                "Randomly deletes entire layers each epoch.",
            ],
            "Decay adds a proportional shrinkage toward zero, improving generalization.",
            {
                "Increases weight magnitudes to fight underfitting always.": "Decay penalizes large weights; capacity is controlled elsewhere.",
                "Replaces gradients with zero vectors.": "Gradients still drive learning; decay is an extra term.",
                "Randomly deletes entire layers each epoch.": "That would be structural pruning, not weight decay.",
            },
        ),
        (
            "Convolutions",
            "An RGB image fed into the first conv layer is usually represented as a tensor with shape…",
            "Height × Width × 3 channels (batch dimension added for mini-batches).",
            [
                "A single scalar brightness value only.",
                "3 × 3 weight matrix shared across all datasets globally.",
                "Sequence length × vocabulary size like text tokens.",
            ],
            "Color images have three channel maps (R, G, B) aligned spatially.",
            {
                "A single scalar brightness value only.": "Images are spatial grids, not one number.",
                "3 × 3 weight matrix shared across all datasets globally.": "3×3 may be kernel size; channels are separate feature maps.",
                "Sequence length × vocabulary size like text tokens.": "That is typical NLP input layout, not raw images.",
            },
        ),
    ],
    medium=[
        (
            "Convolutions",
            "Stacking two 3×3 convolution layers (stride 1, same padding) yields an effective receptive field of…",
            "5×5 on the input (each 3×3 stack expands reach by 2 pixels per side).",
            ["3×3 only — depth does not increase receptive field.",
             "7×7 after one layer.",
             "1×1 because kernels are small."],
            "Receptive field grows with depth: two 3×3 layers see a 5×5 patch of the original grid.",
            {"3×3 only — depth does not increase receptive field.": "Each conv layer expands the region of input influencing an output.",
             "7×7 after one layer.": "Two 3×3 layers reach 5×5, not 7×7.",
             "1×1 because kernels are small.": "Small kernels still aggregate context when stacked."},
        ),
        (
            "Convolutions",
            "A 1×1 convolution primarily…",
            "Mixes channels at each spatial location without enlarging the receptive field.",
            ["Convolves a large 7×7 neighborhood at every pixel.",
             "Pools spatial dimensions by taking the maximum.",
             "Embeds word tokens into continuous vectors."],
            "1×1 conv is channel-wise linear combination — useful for bottlenecks (e.g., Inception, ResNet).",
            {"Convolves a large 7×7 neighborhood at every pixel.": "1×1 kernels do not look at spatial neighbors.",
             "Pools spatial dimensions by taking the maximum.": "Pooling downsamples; 1×1 conv does not.",
             "Embeds word tokens into continuous vectors.": "That is an embedding layer in NLP."},
        ),
        (
            "Convolutions",
            "Dilated (atrous) convolution increases receptive field by…",
            "Spacing kernel taps with gaps (dilation rate) without adding more parameters.",
            ["Duplicating every filter across all datasets.",
             "Using only 1×1 kernels exclusively.",
             "Removing nonlinear activations between layers."],
            "Dilation r inserts r−1 zeros between kernel elements, expanding context per layer.",
            {"Duplicating every filter across all datasets.": "Dilation is an architectural spacing trick, not data copying.",
             "Using only 1×1 kernels exclusively.": "Dilation applies to larger kernels (e.g., 3×3 dilated).",
             "Removing nonlinear activations between layers.": "Activations are independent of dilation."},
        ),
        (
            "Normalization",
            "Batch normalization during training normalizes activations using…",
            "Mean and variance computed over the current mini-batch (per channel).",
            ["Statistics from the entire test set only.",
             "Fixed constants set once before any training.",
             "Gradients of the loss with respect to labels."],
            "BN uses batch statistics μ_B, σ_B then learns affine scale/shift γ, β.",
            {"Statistics from the entire test set only.": "Test stats are not used for train-time normalization.",
             "Fixed constants set once before any training.": "Batch stats change each step.",
             "Gradients of the loss with respect to labels.": "BN normalizes activations, not label gradients."},
        ),
        (
            "Optimization",
            "Gradient clipping (by global norm) is used mainly to…",
            "Cap the magnitude of the update when recurrent or deep nets risk exploding gradients.",
            ["Force all gradients to be exactly zero.",
             "Replace Adam with full-batch Newton steps.",
             "Increase learning rate automatically every iteration."],
            "If ‖g‖ > τ, scale g ← τ·g/‖g‖ to prevent destabilizing parameter jumps.",
            {"Force all gradients to be exactly zero.": "Clipping limits large gradients, it does not zero all learning.",
             "Replace Adam with full-batch Newton steps.": "Clipping is orthogonal to optimizer choice.",
             "Increase learning rate automatically every iteration.": "Clipping bounds steps; LR schedules are separate."},
        ),
        (
            "Optimization",
            "Cosine annealing of the learning rate…",
            "Smoothly decreases η following a cosine curve over training epochs.",
            ["Keeps η constant forever after the first step.",
             "Doubles η whenever validation loss increases.",
             "Sets every weight to zero at epoch 10."],
            "Cosine schedules decay LR toward a minimum, often helping late-stage fine convergence.",
            {"Keeps η constant forever after the first step.": "Annealing means η changes over time.",
             "Doubles η whenever validation loss increases.": "That is not the cosine schedule pattern.",
             "Sets every weight to zero at epoch 10.": "LR schedules adjust step size, not zero all weights."},
        ),
        (
            "RNNs",
            "In an LSTM, the forget gate controls…",
            "How much of the previous cell state c_{t−1} is retained versus erased.",
            ["Which optimizer (Adam vs SGD) is selected.",
             "The RGB channel order of input images.",
             "The number of layers in a ResNet backbone."],
            "f_t = σ(W_f·[h_{t−1}, x_t]) scales c_{t−1} before adding new content.",
            {"Which optimizer (Adam vs SGD) is selected.": "Gates are part of the RNN dynamics, not optimizer choice.",
             "The RGB channel order of input images.": "LSTMs operate on sequences, not image channel layout.",
             "The number of layers in a ResNet backbone.": "That is CNN architecture design."},
        ),
        (
            "RNNs",
            "A GRU compared with an LSTM…",
            "Merges forget and input gating into update and reset gates with fewer parameters.",
            ["Requires a separate cell state c_t distinct from h_t always.",
             "Cannot model sequences longer than three steps.",
             "Uses only convolutional kernels over time."],
            "GRUs are a streamlined gated RNN often competitive with LSTMs on many tasks.",
            {"Requires a separate cell state c_t distinct from h_t always.": "GRU combines state into hidden update without separate cell.",
             "Cannot model sequences longer than three steps.": "GRUs handle long sequences (subject to training stability).",
             "Uses only convolutional kernels over time.": "GRUs are recurrent, not purely convolutional over time."},
        ),
        (
            "RNNs",
            "Teacher forcing during RNN training means…",
            "Feeding ground-truth previous tokens as inputs instead of the model's own predictions.",
            ["Forcing the learning rate to zero after each epoch.",
             "Using only unlabeled data for the loss.",
             "Disabling backpropagation through time entirely."],
            "Teacher forcing speeds convergence but can cause exposure bias at inference.",
            {"Forcing the learning rate to zero after each epoch.": "Teacher forcing concerns input feeding, not LR.",
             "Using only unlabeled data for the loss.": "Seq2seq with teacher forcing is supervised on targets.",
             "Disabling backpropagation through time entirely.": "BPTT still runs; inputs are gold prefixes."},
        ),
        (
            "Embeddings",
            "A word embedding layer maps each token index to…",
            "A learned dense vector in ℝ^d used as input to downstream layers.",
            ["A one-hot vector of length equal to vocabulary with no learning.",
             "The probability of the next TCP packet.",
             "A fixed 7×7 convolutional filter bank."],
            "Embeddings are lookup tables W[idx] trained end-to-end with the task loss.",
            {"A one-hot vector of length equal to vocabulary with no learning.": "One-hot is sparse baseline; embeddings are dense and learned.",
             "The probability of the next TCP packet.": "That is networking, not NLP representations.",
             "A fixed 7×7 convolutional filter bank.": "Embeddings are for discrete tokens, not image filters."},
        ),
        (
            "Regularization",
            "Label smoothing for classification replaces hard 0/1 targets with…",
            "Soft targets (e.g., (1−ε) on the true class and ε spread over others).",
            ["All-zero targets for every class.",
             "Random permutation of input pixels only.",
             "Exact duplicate copies of the test set labels."],
            "Smoothing discourages overconfident logits and can improve calibration.",
            {"All-zero targets for every class.": "Targets must remain a valid distribution.",
             "Random permutation of input pixels only.": "That is image augmentation, not label smoothing.",
             "Exact duplicate copies of the test set labels.": "Test labels must never leak into training targets."},
        ),
        (
            "Initialization",
            "He (Kaiming) initialization is tailored for ReLU networks because it scales variance by…",
            "fan-in (or fan-out for forward/backward balance) assuming half the activations are zeroed.",
            ["Always setting every weight to exactly 1.0.",
             "Using the global dataset mean as each weight.",
             "Initializing all biases to large positive values only."],
            "Var(w) ≈ 2/fan_in compensates for ReLU killing half the activations on average.",
            {"Always setting every weight to exactly 1.0.": "He init samples from a distribution, not a constant.",
             "Using the global dataset mean as each weight.": "Init uses architectural fan-in, not data means.",
             "Initializing all biases to large positive values only.": "Bias init is usually small/zero; variance scaling targets weights."},
        ),
        (
            "Convolutions",
            "Depthwise separable convolution factorizes a standard conv into…",
            "Depthwise spatial conv per channel, then 1×1 pointwise mixing across channels.",
            ["Only average pooling with no learnable parameters.",
             "A fully connected layer on flattened pixels only.",
             "Random Fourier features of the loss landscape."],
            "Separable conv cuts compute (MobileNet) by decoupling spatial and channel mixing.",
            {"Only average pooling with no learnable parameters.": "Separable conv still has learnable depthwise and pointwise ops.",
             "A fully connected layer on flattened pixels only.": "Separable conv keeps spatial structure.",
             "Random Fourier features of the loss landscape.": "That is unrelated to separable conv factorization."},
        ),
        (
            "Convolutions",
            "Transposed convolution (often called 'deconv') is used to…",
            "Upsample feature maps (learned upsampling), e.g., in decoders and segmentation heads.",
            ["Compute exact matrix inverse of the weight matrix.",
             "Apply max pooling with stride 2.",
             "Remove all parameters from the network."],
            "Transposed conv inserts stride gaps then convolves, increasing spatial resolution.",
            {"Compute exact matrix inverse of the weight matrix.": "It is not a literal matrix inverse operation.",
             "Apply max pooling with stride 2.": "Pooling downsamples; transposed conv upsamples.",
             "Remove all parameters from the network.": "Transposed conv layers have learnable kernels."},
        ),
        (
            "Architectures",
            "An Inception module's parallel branches primarily allow…",
            "Multiple filter sizes and pooling paths to be computed and concatenated in one block.",
            ["Only a single 11×11 kernel with no alternatives.",
             "Training without any nonlinear activation.",
             "Eliminating all parameters via weight sharing with labels."],
            "Inception captures multi-scale patterns by fusing 1×1, 3×3, 5×5, and pool outputs.",
            {"Only a single 11×11 kernel with no alternatives.": "Inception is defined by parallel multi-branch paths.",
             "Training without any nonlinear activation.": "Activations remain inside branches.",
             "Eliminating all parameters via weight sharing with labels.": "Inception still has learnable filters per branch."},
        ),
        (
            "Architectures",
            "VGG-style networks deepen using…",
            "Repeated stacks of small 3×3 convolutions instead of very large kernels.",
            ["Only 1×1 kernels with no spatial mixing.",
             "Hand-crafted Sobel edge filters frozen forever.",
             "No pooling or striding anywhere."],
            "Many 3×3 layers build large receptive fields with fewer parameters per layer than one huge kernel.",
            {"Only 1×1 kernels with no spatial mixing.": "VGG famously stacks 3×3 convs.",
             "Hand-crafted Sobel edge filters frozen forever.": "VGG learns filters end-to-end.",
             "No pooling or striding anywhere.": "VGG uses pooling between blocks."},
        ),
        (
            "Attention",
            "Scaled dot-product attention computes weights as…",
            "softmax(QKᵀ / √d_k) applied to V.",
            ["sigmoid(Wx + b) on raw pixels only.",
             "k-means cluster assignments of batch norms.",
             "The determinant of the Hessian matrix."],
            "Attention distributes a convex combination of values based on query–key similarity.",
            {"sigmoid(Wx + b) on raw pixels only.": "That describes a perceptron, not attention.",
             "k-means cluster assignments of batch norms.": "Clustering is unrelated to QKV attention.",
             "The determinant of the Hessian matrix.": "Second-order determinants are not attention scores."},
        ),
        (
            "RNNs",
            "A bidirectional RNN for sequence labeling…",
            "Runs a forward and backward RNN and concatenates (or merges) their hidden states per step.",
            ["Uses future labels at train time by leaking test answers.",
             "Cannot be applied to variable-length sequences.",
             "Requires replacing all gates with 1×1 convolutions only."],
            "Bidirection gives each position context from both past and future inputs.",
            {"Uses future labels at train time by leaking test answers.": "It uses future inputs, not future labels, at position t.",
             "Cannot be applied to variable-length sequences.": "BiRNNs handle variable length with padding/masking.",
             "Requires replacing all gates with 1×1 convolutions only.": "BiRNNs are recurrent, not purely 1×1 conv."},
        ),
        (
            "Optimization",
            "Adam's bias correction for the first moments exists because…",
            "m_t and v_t are initialized at zero, so early estimates are biased toward zero.",
            ["Gradients are always zero in deep nets.",
             "The learning rate must be infinite at step 1.",
             "Batch normalization removes all stochasticity."],
            "Corrected m̂_t = m_t/(1−β₁^t) (and similarly for v) fixes cold-start underestimation.",
            {"Gradients are always zero in deep nets.": "Adam assumes nonzero gradients on real tasks.",
             "The learning rate must be infinite at step 1.": "Bias correction stabilizes early steps, not infinite η.",
             "Batch normalization removes all stochasticity.": "BN and Adam address different issues."},
        ),
        (
            "Regularization",
            "Mixup training regularizes by…",
            "Linearly interpolating pairs of inputs and labels: x̃ = λx_i + (1−λ)x_j, ỹ = λy_i + (1−λ)y_j.",
            ["Duplicating the test set into the training folder.",
             "Setting all weights to the same constant each step.",
             "Removing nonlinearities from every layer."],
            "Mixup encourages linear behavior between examples and smoother decision boundaries.",
            {"Duplicating the test set into the training folder.": "That would leak evaluation data.",
             "Setting all weights to the same constant each step.": "Mixup blends examples, it does not collapse weights.",
             "Removing nonlinearities from every layer.": "Mixup keeps standard architectures."},
        ),
    ],
    hard=[
        (
            "Backpropagation",
            "Reverse-mode autodiff (backprop) is especially efficient for neural nets when…",
            "Many inputs (parameters) influence few scalar outputs (loss), because one backward pass yields all ∂L/∂w.",
            ["There is only one scalar parameter and millions of outputs.",
             "The loss is constant for all parameters.",
             "No chain rule applies because activations are linear only."],
            "Reverse mode costs O(1) backward pass relative to forward for scalar loss — ideal for weight gradients.",
            {"There is only one scalar parameter and millions of outputs.": "That favors forward mode, not reverse mode.",
             "The loss is constant for all parameters.": "Constant loss gives zero gradients — nothing to propagate.",
             "No chain rule applies because activations are linear only.": "Linear stacks still use chain rule; depth without nonlinearity collapses layers."},
        ),
        (
            "RNNs",
            "Truncated BPTT (TBPTT) trades off…",
            "Faithful long-range gradient flow for lower memory by backpropagating only through K unrolled steps.",
            ["Exact full-history gradients with zero memory.",
             "Elimination of all recurrent connections.",
             "Guaranteed convexity of the RNN loss in all parameters."],
            "TBPTT cuts the unfolded graph every K steps, approximating long-term credit assignment.",
            {"Exact full-history gradients with zero memory.": "Full BPTT over T steps costs O(T) memory; TBPTT approximates.",
             "Elimination of all recurrent connections.": "Recurrence remains; only backward horizon is shortened.",
             "Guaranteed convexity of the RNN loss in all parameters.": "RNN training remains non-convex."},
        ),
        (
            "Normalization",
            "At inference, batch normalization uses running mean/variance because…",
            "Mini-batch statistics would be noisy or undefined for batch size 1 and must match training scale.",
            ["Gradients are not defined during inference.",
             "Dropout masks must be recomputed from test labels.",
             "Convolutions cannot run without batch size 32."],
            "Exponential moving averages of μ, σ collected during training stabilize normalization at test time.",
            {"Gradients are not defined during inference.": "Inference disables grad; BN still needs stable μ, σ.",
             "Dropout masks must be recomputed from test labels.": "Dropout is off at inference; unrelated to BN stats.",
             "Convolutions cannot run without batch size 32.": "Conv works with any batch size; BN needs consistent stats."},
        ),
        (
            "Normalization",
            "Layer normalization differs from batch normalization in that layer norm…",
            "Normalizes across features within each example (and time step), not across the batch dimension.",
            ["Requires batch size greater than 1000 always.",
             "Can only be applied to the output softmax.",
             "Uses test-set labels to compute variance."],
            "Layer norm is batch-independent — preferred in transformers and variable batch RNNs.",
            {"Requires batch size greater than 1000 always.": "Layer norm works with batch size 1.",
             "Can only be applied to the output softmax.": "Layer norm is used inside blocks, not only at softmax.",
             "Uses test-set labels to compute variance.": "Norm uses activations, never labels."},
        ),
        (
            "Optimization",
            "Sharpness-aware minimization (SAM) seeks parameters that…",
            "Lie in flat regions of the loss landscape (robust to small perturbations), not just low loss points.",
            ["Maximize training loss on purpose.",
             "Have zero gradient norm everywhere exactly.",
             "Eliminate the need for any validation data."],
            "SAM approximates worst-case loss in a neighborhood, favoring wider minima linked to generalization.",
            {"Maximize training loss on purpose.": "SAM still minimizes loss, but penalizes sharp minima.",
             "Have zero gradient norm everywhere exactly.": "SAM perturbs weights; gradients are generally nonzero.",
             "Eliminate the need for any validation data.": "SAM is a training objective tweak; validation remains useful."},
        ),
        (
            "Generative Models",
            "Mode collapse in GAN training refers to…",
            "The generator producing a small variety of outputs that fool the discriminator but lack diversity.",
            ["The discriminator always outputting exactly 0.5.",
             "Both networks sharing identical weights permanently.",
             "Using only L2 loss on RGB pixels with no adversary."],
            "Collapsed generators map many z to few modes, failing to cover the data distribution.",
            {"The discriminator always outputting exactly 0.5.": "Collapse is about limited support in generated samples.",
             "Both networks sharing identical weights permanently.": "GANs have separate G and D parameters.",
             "Using only L2 loss on RGB pixels with no adversary.": "That describes pixel regression, not GAN collapse."},
        ),
        (
            "Representation Learning",
            "InfoNCE / contrastive learning objectives encourage…",
            "Representations where augmented views of the same instance align and other instances repel.",
            ["All embeddings to become identical vectors.",
             "Labels to be removed from self-supervised pipelines entirely without pairs.",
             "Only k-means cluster centroids with no neural network."],
            "Contrastive losses maximize agreement between positives and separate negatives in embedding space.",
            {"All embeddings to become identical vectors.": "Collapse to a point is failure; contrastive losses prevent trivial solutions.",
             "Labels to be removed from self-supervised pipelines entirely without pairs.": "Self-supervised still defines positive pairs (augmentations).",
             "Only k-means cluster centroids with no neural network.": "Contrastive SSL trains encoders with neural nets."},
        ),
        (
            "Backpropagation",
            "For ReLU activations, the subgradient used in backprop is…",
            "1 where the pre-activation was positive and 0 where it was non-positive (convention at 0).",
            ["Always the second derivative of sigmoid.",
             "Undefined everywhere so gradients cannot flow.",
             "Equal to the input x squared for all regions."],
            "ReLU's gate multiplies upstream gradients by an indicator of active units.",
            {"Always the second derivative of sigmoid.": "ReLU backprop uses piecewise constant subgradient, not sigmoid derivatives.",
             "Undefined everywhere so gradients cannot flow.": "Subgradients at 0 are conventionally chosen; learning proceeds.",
             "Equal to the input x squared for all regions.": "That is not the ReLU derivative."},
        ),
        (
            "Architectures",
            "When input and output dimensions differ in a ResNet block, the skip connection often uses…",
            "A learned 1×1 convolution (projection) to match channel/spatial size before the addition.",
            ["No skip at all — the block cannot be residual.",
             "Max pooling on the residual path only.",
             "Softmax over all pixels in the skip branch."],
            "Projection shortcuts align F(x) and x so y = F(x) + W_s x is well-defined.",
            {"No skip at all — the block cannot be residual.": "ResNet uses projections instead of dropping skips.",
             "Max pooling on the residual path only.": "Pooling changes resolution; 1×1 conv is the standard channel matcher.",
             "Softmax over all pixels in the skip branch.": "Softmax is not used to align residual tensor shapes."},
        ),
        (
            "RNNs",
            "The LSTM cell state's additive update c_t = f⊙c_{t−1} + i⊙g helps gradients because…",
            "Gradients can flow across many time steps via near-identity paths without repeated Jacobian products shrinking to zero.",
            ["It removes all nonlinear gates from the network.",
             "It forces every gate to be exactly zero always.",
             "It replaces recurrence with a single feedforward layer."],
            "Additive memory provides a 'highway' mitigating vanishing gradients in long sequences.",
            {"It removes all nonlinear gates from the network.": "Gates remain; the cell update is additive.",
             "It forces every gate to be exactly zero always.": "Zero gates would erase memory; trained gates are selective.",
             "It replaces recurrence with a single feedforward layer.": "LSTMs are still recurrent over time."},
        ),
        (
            "Attention",
            "Multi-head self-attention splits Q, K, V into h heads primarily to…",
            "Let the model attend to information from different representation subspaces in parallel.",
            ["Reduce sequence length to 1 token always.",
             "Eliminate the need for any feedforward sublayers.",
             "Compute exact eigenvalues of the dataset covariance offline only."],
            "Each head learns different attention patterns; outputs are concatenated and projected.",
            {"Reduce sequence length to 1 token always.": "Attention maps over tokens; length is unchanged.",
             "Eliminate the need for any feedforward sublayers.": "Transformers still use position-wise FFN blocks.",
             "Compute exact eigenvalues of the dataset covariance offline only.": "That is unrelated to multi-head attention."},
        ),
        (
            "Transformers",
            "Sinusoidal positional encodings in the original Transformer…",
            "Inject order information by adding fixed sin/cos functions of position to input embeddings.",
            ["Replace token embeddings with one-hot bag-of-words.",
             "Train a CNN on 224×224 images only.",
             "Compute the adversarial discriminator loss."],
            "Attention is permutation-invariant without positions; encodings break symmetry across sequence index.",
            {"Replace token embeddings with one-hot bag-of-words.": "Embeddings remain; positions are added.",
             "Train a CNN on 224×224 images only.": "Sinusoidal PE is for sequences in transformers.",
             "Compute the adversarial discriminator loss.": "PE is not part of GAN discriminators."},
        ),
        (
            "Optimization",
            "AdamW decouples weight decay from the adaptive gradient step by…",
            "Applying weight decay directly on weights each step, not as an L2 term mixed into the Adam gradient.",
            ["Removing momentum estimates entirely.",
             "Using full-batch Hessian inverses every iteration.",
             "Setting all adaptive learning rates to zero."],
            "Decoupled decay fixes the interaction between Adam's preconditioning and L2-style shrinkage.",
            {"Removing momentum estimates entirely.": "AdamW retains Adam's moment estimates.",
             "Using full-batch Hessian inverses every iteration.": "AdamW is still first-order adaptive.",
             "Setting all adaptive learning rates to zero.": "Adaptive per-parameter scaling remains."},
        ),
        (
            "Generalization",
            "The lottery ticket hypothesis suggests that…",
            "Dense networks contain sparse subnetworks that, if trained in isolation from matching init, can reach similar accuracy.",
            ["Random initialization never matters for any architecture.",
             "Wider networks always generalize worse than linear models.",
             "Gradients are unnecessary if batch size is 1."],
            "Winning tickets are sparse masks + initial weights that train effectively — implying redundant parameters.",
            {"Random initialization never matters for any architecture.": "The hypothesis stresses matching initial signs/magnitudes.",
             "Wider networks always generalize worse than linear models.": "Overparameterization can still generalize well.",
             "Gradients are unnecessary if batch size is 1.": "Training still requires gradient-based learning."},
        ),
        (
            "Convolutions",
            "Effective receptive field analysis often shows that…",
            "Not all pixels in the theoretical RF contribute equally — central pixels dominate the gradient magnitude.",
            ["Every pixel in the RF has identical influence by definition.",
             "Receptive field shrinks as you add more conv layers.",
             "Pooling never affects which input pixels matter."],
            "Gradients concentrate near the center; theoretical RF overestimates uniform contribution.",
            {"Every pixel in the RF has identical influence by definition.": "Empirical ERF is non-uniform.",
             "Receptive field shrinks as you add more conv layers.": "Depth generally increases RF size.",
             "Pooling never affects which input pixels matter.": "Pooling expands the region influencing downstream units."},
        ),
        (
            "Training",
            "Knowledge distillation trains a student network using…",
            "Soft targets from a larger teacher (high-temperature softmax) plus often the hard labels.",
            ["Only unlabeled random noise with no teacher.",
             "Exact copy-paste of teacher weights into every layer shape blindly.",
             "Removing the loss function and stopping after one forward pass."],
            "Student learns dark knowledge from teacher probabilities, not just argmax labels.",
            {"Only unlabeled random noise with no teacher.": "Distillation requires teacher outputs on data.",
             "Exact copy-paste of teacher weights into every layer shape blindly.": "Student may differ in architecture; soft targets guide training.",
             "Removing the loss function and stopping after one forward pass.": "Distillation optimizes a KL/cross-entropy style objective."},
        ),
        (
            "Regularization",
            "Spectral normalization in GAN discriminators constrains…",
            "The spectral norm (largest singular value) of weight matrices to stabilize Lipschitz behavior.",
            ["The learning rate to be exactly zero.",
             "All activations to be strictly positive via ReLU only.",
             "Batch size to match vocabulary size."],
            "Bounding Lipschitz constants of D helps control gradient magnitudes in adversarial training.",
            {"The learning rate to be exactly zero.": "Spectral norm bounds weights, not η.",
             "All activations to be strictly positive via ReLU only.": "SN is a weight reparameterization, not an activation choice.",
             "Batch size to match vocabulary size.": "Unrelated hyperparameter link."},
        ),
        (
            "Optimization",
            "Second-order methods (e.g., exact Newton) are rarely used at full deep-net scale because…",
            "Forming and inverting the Hessian is O(n²) or worse in parameter count n.",
            ["Gradients do not exist for ReLU networks.",
             "SGD cannot minimize non-convex losses.",
             "Mini-batches are impossible on GPUs."],
            "Quasi-Newton and diagonal approximations exist, but full Hessians are prohibitive for millions of weights.",
            {"Gradients do not exist for ReLU networks.": "Subgradients enable first-order training at scale.",
             "SGD cannot minimize non-convex losses.": "SGD works well empirically despite non-convexity.",
             "Mini-batches are impossible on GPUs.": "GPUs excel at mini-batch parallel training."},
        ),
        (
            "Sequence Models",
            "Attention as used in seq2seq decoders replaces fixed context vectors by…",
            "Weighted sums over all encoder hidden states, with weights from compatibility scores.",
            ["Always selecting only the final encoder hidden state.",
             "Sorting the vocabulary alphabetically at decode time.",
             "Applying 2×2 max pooling on the source sentence tokens."],
            "Bahdanau/Luong attention lets each decode step focus on different source positions.",
            {"Always selecting only the final encoder hidden state.": "That is the bottleneck of basic enc–dec without attention.",
             "Sorting the vocabulary alphabetically at decode time.": "Decoding uses learned attention, not alphabetical sorts.",
             "Applying 2×2 max pooling on the source sentence tokens.": "Pooling is a vision downsampling op, not seq2seq attention."},
        ),
        (
            "Hardware",
            "Data parallelism during distributed training synchronizes…",
            "Gradients (or gradient shards) across workers after each backward pass before the optimizer step.",
            ["Individual pixel values inside each image only.",
             "Random seeds for dropout at inference on clients.",
             "DNS records for model checkpoint hostnames only."],
            "Each GPU has a model replica; all-reduces average gradients so updates stay consistent.",
            {"Individual pixel values inside each image only.": "Data parallel syncs parameters/gradients, not raw pixels across GPUs.",
             "Random seeds for dropout at inference on clients.": "Inference dropout is off; training sync is about gradients.",
             "DNS records for model checkpoint hostnames only.": "Networking metadata is unrelated to gradient all-reduce."},
        ),
    ],
)
