"""Quiz bank: Discrete Mathematics (Open Math Books)."""
from quiz_banks._make_book import make_book

BOOK = make_book(
    title="Discrete Mathematics: An Open Introduction",
    parent_topic="Mathematics",
    subtopic="Discrete Math",
    slug="discrete-math-oscar",
    source_url="https://discrete.openmathbooks.org/",
    easy=[
        (
            "Logic and Proofs",
            "To prove a statement of the form “for all integers n, P(n)” by induction, you must show…",
            "A base case and that P(k) implies P(k+1) for all relevant k.",
            [
                "Only that P(1) holds.",
                "That P(n) is true for finitely many sample values of n.",
                "That the contrapositive of P(n) is false.",
            ],
            "Mathematical induction needs an anchor (base) and an inductive step linking k to k+1.",
            {
                "Only that P(1) holds.": "The base case alone does not propagate truth to all n.",
                "That P(n) is true for finitely many sample values of n.": "Checking examples is not a proof for all integers.",
                "That the contrapositive of P(n) is false.": "Induction is not framed via contrapositives of P(n).",
            },
        ),
        (
            "Logic and Proofs",
            "Which method proves “if n² is even then n is even” most directly?",
            "Prove the contrapositive: if n is odd then n² is odd.",
            [
                "Assume n is even and conclude n² is even.",
                "Find one even n with n² even.",
                "Prove by enumerating n = 0, 1, 2.",
            ],
            "The desired implication is awkward to assume directly; its contrapositive is a clean odd-times-odd argument.",
            {
                "Assume n is even and conclude n² is even.": "That proves the converse direction, not the stated implication.",
                "Find one even n with n² even.": "One example does not establish a universal implication.",
                "Prove by enumerating n = 0, 1, 2.": "Finitely many cases do not prove the statement for all integers.",
            },
        ),
        (
            "Logic and Proofs",
            "A proof that √2 is irrational typically starts by…",
            "Assuming √2 = p/q in lowest terms and deriving a contradiction.",
            [
                "Showing √2 ≈ 1.414 on a calculator.",
                "Proving every real number is a ratio of integers.",
                "Applying the pigeonhole principle to {1, √2}.",
            ],
            "Classic proof by contradiction: coprime p, q would force both to be even.",
            {
                "Showing √2 ≈ 1.414 on a calculator.": "A decimal approximation is not a proof of irrationality.",
                "Proving every real number is a ratio of integers.": "That would deny irrational numbers entirely.",
                "Applying the pigeonhole principle to {1, √2}.": "Pigeonhole is unrelated to this classical argument.",
            },
        ),
        (
            "Logic and Proofs",
            "Which expression is always true for propositions P and Q (tautology)?",
            "P → (Q → P)",
            [
                "P ∧ ¬P",
                "(P → Q) → (Q → P)",
                "¬(P ∨ Q) ↔ (¬P ∧ ¬Q)",
            ],
            "When P is true, Q → P is true; when P is false, P → (Q → P) is vacuously true.",
            {
                "P ∧ ¬P": "A contradiction, never true.",
                "(P → Q) → (Q → P)": "This is not valid in general (converse fallacy).",
                "¬(P ∨ Q) ↔ (¬P ∧ ¬Q)": "This is De Morgan's equivalence, not the listed tautology.",
            },
        ),
        (
            "Sets",
            "If A = {1, 2} and B = {a, b}, how many elements are in A × B?",
            "4",
            ["2", "3", "8"],
            "|A × B| = |A| · |B| = 2 · 2 = 4 ordered pairs.",
            {
                "2": "That counts one set's size, not the Cartesian product.",
                "3": "Not the product of the two set sizes.",
                "8": "That would be 2³, not |A| · |B|.",
            },
        ),
        (
            "Sets",
            "The power set of a finite set with n elements has how many subsets?",
            "2^n",
            ["n", "n!", "2n"],
            "Each element may be included or excluded independently.",
            {
                "n": "That's the set size, not the number of subsets.",
                "n!": "Permutation count, not subset count.",
                "2n": "Linear in n, not exponential.",
            },
        ),
        (
            "Sets",
            "For sets A and B, A ∩ B is the set of elements that…",
            "Belong to both A and B.",
            [
                "Belong to A or B (or both).",
                "Belong to A but not B.",
                "Belong to exactly one of A and B.",
            ],
            "Intersection is the overlap; union, difference, and symmetric difference use other rules.",
            {
                "Belong to A or B (or both).": "That defines the union A ∪ B.",
                "Belong to A but not B.": "That is the set difference A \\ B.",
                "Belong to exactly one of A and B.": "That is symmetric difference.",
            },
        ),
        (
            "Sets",
            "The empty set ∅ satisfies which statement?",
            "∅ ⊆ A for every set A.",
            [
                "∅ ∈ A for every set A.",
                "∅ = {0}.",
                "|∅| = 1.",
            ],
            "The empty set is a subset of every set; it is not generally an element of every set.",
            {
                "∅ ∈ A for every set A.": "Membership in A is not universal.",
                "∅ = {0}.": "{0} contains one element; ∅ has none.",
                "|∅| = 1.": "The empty set has cardinality 0.",
            },
        ),
        (
            "Combinatorics",
            "How many 3-element subsets can be chosen from a set of 7 elements?",
            "35",
            ["21", "210", "7"],
            "C(7,3) = 7!/(3!4!) = 35.",
            {
                "21": "That is C(7,2), not C(7,3).",
                "210": "That is C(7,4) or P(7,4) depending on context — not C(7,3).",
                "7": "That counts single elements, not triples.",
            },
        ),
        (
            "Combinatorics",
            "How many ways can 5 distinct books be arranged on a shelf?",
            "120",
            ["25", "5", "3125"],
            "5! = 120 permutations of 5 distinct objects.",
            {
                "25": "5² counts pairs with repetition, not permutations.",
                "5": "That's the number of books, not orderings.",
                "3125": "That is 5⁵, not 5!.",
            },
        ),
        (
            "Combinatorics",
            "The binomial coefficient C(n, k) counts…",
            "k-element subsets of an n-element set.",
            [
                "k-permutations of n elements.",
                "Sequences of length k from n elements with repetition.",
                "Partitions of n into k positive parts only.",
            ],
            "C(n,k) is unordered selection; permutations and sequences use different formulas.",
            {
                "k-permutations of n elements.": "Those are counted by P(n,k) = n!/(n−k)!.",
                "Sequences of length k from n elements with repetition.": "That is n^k with repetition allowed.",
                "Partitions of n into k positive parts only.": "Integer partitions use a different counting function.",
            },
        ),
        (
            "Combinatorics",
            "If 10 pigeons nest in 9 holes, the pigeonhole principle guarantees…",
            "At least one hole contains at least two pigeons.",
            [
                "Every hole has exactly one pigeon.",
                "At least one hole is empty.",
                "No two pigeons share a hole.",
            ],
            "With more pigeons than holes, some hole must hold ≥ 2.",
            {
                "Every hole has exactly one pigeon.": "Impossible with 10 pigeons and 9 holes.",
                "At least one hole is empty.": "Emptiness is not forced; overcrowding is.",
                "No two pigeons share a hole.": "That contradicts the forced overlap.",
            },
        ),
        (
            "Graph Theory",
            "In a simple undirected graph, the sum of all vertex degrees equals…",
            "Twice the number of edges.",
            ["The number of edges.",
             "The number of vertices.",
             "The chromatic number."],
            "Each edge contributes 2 to the total degree (handshaking lemma).",
            {
                "The number of edges.": "Each edge adds 2 to the degree sum, not 1.",
                "The number of vertices.": "Degree sum depends on edges, not |V| alone.",
                "The chromatic number.": "Coloring is unrelated to the degree sum identity.",
            },
        ),
        (
            "Graph Theory",
            "A tree with n vertices has how many edges?",
            "n − 1",
            ["n", "n + 1", "n(n − 1)/2"],
            "Trees are connected and acyclic, so |E| = |V| − 1.",
            {
                "n": "n edges would create a cycle in a connected n-vertex graph.",
                "n + 1": "Too many edges for a tree.",
                "n(n − 1)/2": "That's the edge count of K_n, not a tree.",
            },
        ),
        (
            "Graph Theory",
            "The complete graph K₄ has how many edges?",
            "6",
            ["4", "8", "12"],
            "K_n has n(n−1)/2 edges; for n=4, 6.",
            {
                "4": "That's the number of vertices, not edges.",
                "8": "Too many — K₄ is not K₅.",
                "12": "That would correspond to a denser graph on 4 vertices.",
            },
        ),
        (
            "Graph Theory",
            "An Euler trail in a connected graph uses each edge…",
            "Exactly once.",
            ["Exactly twice.",
             "At least once but vertices may repeat.",
             "Only on vertices of odd degree."],
            "Euler trails/circuits traverse every edge once; vertices may repeat.",
            {
                "Exactly twice.": "Using each edge twice is not the standard Euler definition.",
                "At least once but vertices may repeat.": "Edges, not vertices, are the focus; 'at least once' is too weak.",
                "Only on vertices of odd degree.": "Odd degree counts vertices, not edge usage.",
            },
        ),
        (
            "Recurrence Relations",
            "If T(n) = T(n − 1) + 1 with T(1) = 1, then T(n) equals…",
            "n",
            ["1", "n²", "2^n"],
            "Unrolling gives T(n) = n.",
            {
                "1": "Constant only if the recurrence did not add 1 each step.",
                "n²": "Quadratic growth needs a different recurrence.",
                "2^n": "Exponential growth needs multiplying branches.",
            },
        ),
        (
            "Recurrence Relations",
            "The Fibonacci numbers satisfy F_n = F_{n−1} + F_{n−2} with F_0 = 0 and F_1 = 1. What is F_5?",
            "5",
            ["3", "8", "13"],
            "Sequence: 0, 1, 1, 2, 3, 5.",
            {
                "3": "That is F_4.",
                "8": "That is F_6.",
                "13": "That is F_7.",
            },
        ),
        (
            "Recurrence Relations",
            "A linear homogeneous recurrence a_n = 5a_{n−1} − 6a_{n−2} has characteristic roots…",
            "2 and 3",
            ["1 and 6", "−2 and −3", "5 and −6"],
            "r² − 5r + 6 = 0 factors as (r−2)(r−3) = 0.",
            {
                "1 and 6": "Those do not satisfy r² − 5r + 6 = 0.",
                "−2 and −3": "Signs are wrong for this polynomial.",
                "5 and −6": "Confuses coefficients with roots.",
            },
        ),
        (
            "Recurrence Relations",
            "The recurrence T(n) = 2T(n/2) + n describes the cost of…",
            "Merge sort (and similar divide-and-conquer algorithms).",
            [
                "Linear search on a sorted array.",
                "A single loop from 1 to n.",
                "Constant-time array access.",
            ],
            "Halving the problem twice per level with O(n) combine work is the merge-sort template.",
            {
                "Linear search on a sorted array.": "Linear scan is Θ(n) without this recurrence.",
                "A single loop from 1 to n.": "One loop is typically Θ(n), not T(n)=2T(n/2)+n.",
                "Constant-time array access.": "Indexing is O(1), not divide-and-conquer.",
            },
        ),
    ],
    medium=[
        (
            "Logic and Proofs",
            "Strong induction differs from ordinary induction because the inductive step assumes…",
            "P(j) for all j ≤ k when proving P(k+1).",
            [
                "Only P(k) when proving P(k+1).",
                "P(k) for all k ≥ 1000 only.",
                "The conclusion is false before proving it.",
            ],
            "Strong induction lets you use all prior cases, not just the immediate predecessor.",
            {
                "Only P(k) when proving P(k+1).": "That is ordinary (weak) induction.",
                "P(k) for all k ≥ 1000 only.": "Induction does not arbitrarily start at 1000 without a base.",
                "The conclusion is false before proving it.": "Proof by contradiction assumes negation, not strong induction.",
            },
        ),
        (
            "Logic and Proofs",
            "To disprove ∀x ∈ S, P(x), it suffices to…",
            "Exhibit one x ∈ S with ¬P(x).",
            [
                "Show P(x) for many sample x.",
                "Prove ∀x ∈ S, ¬P(x).",
                "Assume P(x) and derive a tautology.",
            ],
            "A single counterexample refutes a universal claim.",
            {
                "Show P(x) for many sample x.": "Examples do not prove or disprove ∀x P(x).",
                "Prove ∀x ∈ S, ¬P(x).": "That proves the negation universally — stronger than one counterexample.",
                "Assume P(x) and derive a tautology.": "That does not construct a counterexample.",
            },
        ),
        (
            "Logic and Proofs",
            "Which is equivalent to ¬(P → Q) in propositional logic?",
            "P ∧ ¬Q",
            [
                "¬P ∧ Q",
                "P → ¬Q",
                "¬P → ¬Q",
            ],
            "P → Q is false exactly when P is true and Q is false.",
            {
                "¬P ∧ Q": "That does not match the false case of implication.",
                "P → ¬Q": "Not equivalent to negated implication in general.",
                "¬P → ¬Q": "That is the contrapositive form, not ¬(P → Q).",
            },
        ),
        (
            "Logic and Proofs",
            "In a proof by contradiction of statement S, you…",
            "Assume ¬S and derive an impossibility.",
            [
                "Assume S and list true consequences.",
                "Prove S for n = 1, 2, 3 by induction only.",
                "Replace S with its contrapositive without assuming anything.",
            ],
            "Contradiction proofs assume the negation and reach ⊥ or an absurdity.",
            {
                "Assume S and list true consequences.": "That is a direct proof strategy, not contradiction.",
                "Prove S for n = 1, 2, 3 by induction only.": "Induction is a separate proof family.",
                "Replace S with its contrapositive without assuming anything.": "Contrapositive is a direct rewrite, not contradiction.",
            },
        ),
        (
            "Sets",
            "For finite sets A and B, |A ∪ B| equals…",
            "|A| + |B| − |A ∩ B|",
            [
                "|A| + |B|",
                "|A| · |B|",
                "|A| − |B|",
            ],
            "Inclusion–exclusion for two sets subtracts the overlap counted twice.",
            {
                "|A| + |B|": "Double-counts elements in A ∩ B.",
                "|A| · |B|": "Product rule applies to Cartesian products, not unions.",
                "|A| − |B|": "Difference of sizes is not |A ∪ B|.",
            },
        ),
        (
            "Sets",
            "How many elements are in ℘({a, b, c})?",
            "8",
            ["6", "7", "9"],
            "|℘(S)| = 2^|S| = 2³ = 8.",
            {
                "6": "Undercounts subsets.",
                "7": "One less than 2³.",
                "9": "Overcounts — not 3².",
            },
        ),
        (
            "Sets",
            "If A ⊆ B, then A ∩ B equals…",
            "A",
            [
                "B",
                "A ∪ B",
                "∅",
            ],
            "Every element of A is already in B, so the overlap is A itself.",
            {
                "B": "Intersection is the smaller set when A ⊆ B.",
                "A ∪ B": "That is B, not A ∩ B.",
                "∅": "Nonempty A would make A ∩ B nonempty.",
            },
        ),
        (
            "Sets",
            "The set {x ∈ ℤ : x² < 10} has how many elements?",
            "7",
            ["6", "8", "9"],
            "Integers with x² < 10 are −3, −2, −1, 0, 1, 2, 3 — seven values.",
            {
                "6": "Misses one valid integer.",
                "8": "Includes one too many.",
                "9": "Counts non-integers or wrong bounds.",
            },
        ),
        (
            "Combinatorics",
            "How many bit strings of length 8 have exactly three 1s?",
            "56",
            ["28", "168", "256"],
            "Choose positions for the three 1s: C(8,3) = 56.",
            {
                "28": "That is C(8,2), not C(8,3).",
                "168": "Too large for this selection count.",
                "256": "That is all 8-bit strings without a fixed number of 1s.",
            },
        ),
        (
            "Combinatorics",
            "How many anagrams (distinct rearrangements) of the letters in MISSISSIPPI are there?",
            "34,650",
            ["11!", "39,916,800", "4,950"],
            "11!/(4!4!2!) accounts for repeated I, S, and P.",
            {
                "11!": "Ignores repeated letters.",
                "39,916,800": "Uses wrong multiplicity divisors.",
                "4,950": "Undercounts valid permutations.",
            },
        ),
        (
            "Combinatorics",
            "How many 5-card poker hands are there from a standard 52-card deck?",
            "2,598,960",
            ["52", "259,896", "10,240"],
            "C(52,5) = 2,598,960.",
            {
                "52": "Single-card choices, not 5-card hands.",
                "259,896": "Off by a factor of 10.",
                "10,240": "Far too small.",
            },
        ),
        (
            "Combinatorics",
            "The number of ways to distribute 10 identical balls into 4 distinct bins (bins may be empty) is…",
            "C(13, 3) = 286",
            ["4^10", "10^4", "C(10, 4)"],
            "Stars and bars: C(n+k−1, k−1) with n=10, k=4 gives C(13,3).",
            {
                "4^10": "Counts distinct balls, not identical ones.",
                "10^4": "Swaps roles incorrectly.",
                "C(10, 4)": "Chooses bins, not distributions with repetition.",
            },
        ),
        (
            "Graph Theory",
            "A connected graph has an Euler circuit if and only if…",
            "Every vertex has even degree.",
            [
                "It has exactly two vertices of odd degree.",
                "It is bipartite.",
                "It is a tree.",
            ],
            "Euler circuits exist iff the graph is connected and all degrees are even.",
            {
                "It has exactly two vertices of odd degree.": "That condition characterizes an Euler trail between two odd vertices, not a circuit.",
                "It is bipartite.": "Bipartiteness does not determine Euler circuits.",
                "It is a tree.": "Trees with n>1 have two leaves (odd degree) and no Euler circuit.",
            },
        ),
        (
            "Graph Theory",
            "How many edges does the complete bipartite graph K_{3,4} have?",
            "12",
            ["7", "10", "18"],
            "K_{m,n} has mn edges; 3·4 = 12.",
            {
                "7": "That's m+n, not mn.",
                "10": "Incorrect product.",
                "18": "Overcounts.",
            },
        ),
        (
            "Graph Theory",
            "A graph is bipartite if and only if it contains no…",
            "Odd-length cycle.",
            [
                "Cycle of any length.",
                "Vertex of degree greater than 3.",
                "Hamiltonian path.",
            ],
            "Bipartite graphs are exactly those with no odd cycles.",
            {
                "Cycle of any length.": "Even cycles occur in bipartite graphs.",
                "Vertex of degree greater than 3.": "Degree does not characterize bipartiteness.",
                "Hamiltonian path.": "Hamilton paths can exist in non-bipartite graphs.",
            },
        ),
        (
            "Graph Theory",
            "For a planar connected graph with v vertices, e edges, and f faces, Euler's formula states…",
            "v − e + f = 2",
            ["v + e + f = 2", "v − e − f = 0", "e = v + f"],
            "For planar embeddings of connected graphs, v − e + f = 2.",
            {
                "v + e + f = 2": "Signs are wrong.",
                "v − e − f = 0": "Not the standard Euler relation.",
                "e = v + f": "Misstates the balance among v, e, f.",
            },
        ),
        (
            "Recurrence Relations",
            "Solving a_n = 3a_{n−1} with a_0 = 2 gives the closed form…",
            "a_n = 2 · 3^n",
            ["a_n = 2 + 3n", "a_n = 3^n", "a_n = 2^n"],
            "Homogeneous first-order: multiply by 3 each step from a_0 = 2.",
            {
                "a_n = 2 + 3n": "Linear, not exponential.",
                "a_n = 3^n": "Misses the initial factor 2.",
                "a_n = 2^n": "Wrong base.",
            },
        ),
        (
            "Recurrence Relations",
            "For T(n) = 2T(n/2) + n, the Master Theorem gives T(n) = …",
            "Θ(n log n)",
            ["Θ(n)", "Θ(n²)", "Θ(log n)"],
            "a=2, b=2, f(n)=n: case 2 with log_b a = 1 and f(n) = Θ(n).",
            {
                "Θ(n)": "Ignores the log factor from two recursive calls.",
                "Θ(n²)": "Too fast for this divide-and-conquer.",
                "Θ(log n)": "Far too slow.",
            },
        ),
        (
            "Recurrence Relations",
            "If a_n = 4a_{n−1} − 4a_{n−2} with characteristic equation r² − 4r + 4 = 0, the general solution has…",
            "A repeated root r = 2, so (c₁ + c₂ n)2^n.",
            [
                "Distinct roots 2 and −2 only.",
                "Complex roots only.",
                "No n·2^n term because the root is repeated.",
            ],
            "Repeated root r=2 yields (c₁ + c₂ n)2^n.",
            {
                "Distinct roots 2 and −2 only.": "The polynomial has a double root at 2.",
                "Complex roots only.": "r² − 4r + 4 = (r−2)² is real.",
                "No n·2^n term because the root is repeated.": "Repeated roots require the extra n factor.",
            },
        ),
        (
            "Recurrence Relations",
            "The recurrence T(n) = T(n−1) + n with T(1) = 1 satisfies T(n) = …",
            "n(n+1)/2",
            ["n²", "n log n", "2^n"],
            "Summing 1+2+…+n gives the triangular number formula.",
            {
                "n²": "Quadratic but wrong constant — sum is n(n+1)/2.",
                "n log n": "Not the closed form of this arithmetic accumulation.",
                "2^n": "Exponential does not match adding n each step.",
            },
        ),
    ],
    hard=[
        (
            "Logic and Proofs",
            "Which statement can be proved for all n ≥ 4 by strong induction more naturally than by weak induction alone?",
            "Every integer n ≥ 8 can be written as 3a + 5b for nonnegative integers a, b.",
            [
                "1 + 1 = 2.",
                "n² ≥ n for all n ≥ 1.",
                "If n is even, n² is even.",
            ],
            "Coin problem style: use prior cases n−3 and n−5, not only n−1.",
            {
                "1 + 1 = 2.": "No induction needed.",
                "n² ≥ n for all n ≥ 1.": "Ordinary induction on n−1 suffices.",
                "If n is even, n² is even.": "Direct or weak induction on parity is enough.",
            },
        ),
        (
            "Logic and Proofs",
            "Let P(n) be “n² + n + 41 is prime.” Which is true?",
            "P(n) fails at n = 41 because 41² + 41 + 41 is divisible by 41.",
            [
                "P(n) is true for all integers n.",
                "P(n) fails only for negative n.",
                "P(n) is a theorem provable by induction on n.",
            ],
            "Euler's polynomial generates many primes early but not for all n.",
            {
                "P(n) is true for all integers n.": "n = 41 gives a composite value.",
                "P(n) fails only for negative n.": "The counterexample is positive.",
                "P(n) is a theorem provable by induction on n.": "No finite induction pattern proves primality for all n.",
            },
        ),
        (
            "Logic and Proofs",
            "In ℤ, the statement “if 3 | (n² − 1) then 3 ∤ n” is best proved by…",
            "Contrapositive: if 3 | n then 3 ∤ (n² − 1), since n² ≡ 0 (mod 3).",
            [
                "Checking n = 1, 2, 4 only.",
                "Assuming 3 | (n² − 1) and squaring both sides.",
                "Proof by vacuous truth for all n.",
            ],
            "Modular arithmetic on n mod 3 makes the contrapositive immediate.",
            {
                "Checking n = 1, 2, 4 only.": "Samples do not prove divisibility for all integers.",
                "Assuming 3 | (n² − 1) and squaring both sides.": "Invalid manipulation in modular proofs.",
                "Proof by vacuous truth for all n.": "The implication is not vacuous.",
            },
        ),
        (
            "Logic and Proofs",
            "How many rows does a full truth table for a formula with 4 distinct atomic propositions have?",
            "16",
            ["8", "32", "4"],
            "Each proposition doubles the rows: 2⁴ = 16.",
            {
                "8": "That is 2³.",
                "32": "That is 2⁵.",
                "4": "That's the number of propositions, not rows.",
            },
        ),
        (
            "Sets",
            "If |A| = 5, |B| = 7, and |A ∩ B| = 2, then |A \\ B| equals…",
            "3",
            ["5", "7", "10"],
            "|A \\ B| = |A| − |A ∩ B| = 5 − 2 = 3.",
            {
                "5": "Ignores elements shared with B.",
                "7": "That's |B|, not A \\ B.",
                "10": "That's |A ∪ B|, not the difference.",
            },
        ),
        (
            "Sets",
            "How many subsets of {1, 2, …, 10} contain at least one even number?",
            "2^10 − 2^5 = 992",
            ["2^5", "2^10", "10"],
            "Complement: subsets with no evens are subsets of the five odd numbers only.",
            {
                "2^5": "Counts subsets using only odds, not 'at least one even'.",
                "2^10": "Includes subsets with no evens.",
                "10": "Confuses subset count with element count.",
            },
        ),
        (
            "Sets",
            "The cardinality of ℚ (rationals) is…",
            "Countably infinite (same as ℕ).",
            [
                "Strictly larger than ℕ but smaller than ℝ.",
                "Equal to ℝ.",
                "Finite.",
            ],
            "ℚ can be listed in a sequence; |ℚ| = ℵ₀.",
            {
                "Strictly larger than ℕ but smaller than ℝ.": "ℚ is countable, not strictly larger than ℕ.",
                "Equal to ℝ.": "|ℝ| is strictly greater than |ℚ|.",
                "Finite.": "There are infinitely many rationals.",
            },
        ),
        (
            "Sets",
            "For sets A, B, C, (A ∪ B) ∩ C equals…",
            "(A ∩ C) ∪ (B ∩ C)",
            [
                "(A ∩ C) ∩ (B ∩ C)",
                "A ∪ (B ∩ C)",
                "(A ∪ B) ∪ C",
            ],
            "Distributivity of ∩ over ∪.",
            {
                "(A ∩ C) ∩ (B ∩ C)": "That is intersection, not the distributed union form.",
                "A ∪ (B ∩ C)": "Mixed union/intersection without full distribution.",
                "(A ∪ B) ∪ C": "That is A ∪ B ∪ C, not distributing ∩.",
            },
        ),
        (
            "Combinatorics",
            "How many solutions in nonnegative integers are there to x₁ + x₂ + x₃ + x₄ = 12?",
            "C(15, 3) = 455",
            ["12^4", "C(12, 4)", "4^12"],
            "Stars and bars: C(12+4−1, 4−1) = C(15,3).",
            {
                "12^4": "Treats variables as independent 12-ary choices incorrectly.",
                "C(12, 4)": "Chooses four positions without the sum constraint encoding.",
                "4^12": "Assigns 12 labeled objects to 4 bins distinctly.",
            },
        ),
        (
            "Combinatorics",
            "The inclusion–exclusion formula for |A ∪ B ∪ C| subtracts pairwise intersections and adds back…",
            "|A ∩ B ∩ C|",
            [
                "|A| + |B| + |C| only",
                "|A ∩ B| only",
                "Zero triple intersections always",
            ],
            "Three-set inclusion–exclusion: + singles − pairs + triple.",
            {
                "|A| + |B| + |C| only": "Omits subtraction of pairwise overlaps.",
                "|A ∩ B| only": "Does not complete the three-set formula.",
                "Zero triple intersections always": "Triple overlap may be nonempty.",
            },
        ),
        (
            "Combinatorics",
            "How many surjections are there from a 5-element set onto a 3-element set?",
            "150",
            ["243", "60", "125"],
            "Inclusion–exclusion on functions: 3⁵ − 3·2⁵ + 3·1⁵ = 243 − 96 + 3 = 150.",
            {
                "243": "Counts all functions, not necessarily surjective.",
                "60": "Undercounts — misses valid surjections.",
                "125": "Incorrect application of inclusion–exclusion.",
            },
        ),
        (
            "Combinatorics",
            "The coefficient of x³y⁴ in (x + y)^7 is…",
            "35",
            ["21", "35y", "7"],
            "Binomial term: C(7,3) = C(7,4) = 35.",
            {
                "21": "That is C(7,2), wrong powers.",
                "35y": "Includes an extra factor of y incorrectly.",
                "7": "That's the exponent sum, not the coefficient.",
            },
        ),
        (
            "Graph Theory",
            "K₅ is not planar because…",
            "It contains K₅ as a subgraph (it is K₅) and violates Kuratowski's criterion.",
            [
                "It has a vertex of degree 4 only.",
                "It is bipartite.",
                "It has fewer than 9 edges.",
            ],
            "K₅ and K_{3,3} are forbidden minors for planarity.",
            {
                "It has a vertex of degree 4 only.": "Degree 4 in K₅ is not the obstruction.",
                "It is bipartite.": "K₅ contains odd cycles and is not bipartite.",
                "It has fewer than 9 edges.": "K₅ has 10 edges.",
            },
        ),
        (
            "Graph Theory",
            "The chromatic number of the cycle graph C₅ is…",
            "3",
            ["2", "4", "5"],
            "Odd cycles need three colors; even cycles need two.",
            {
                "2": "Bipartite coloring fails on odd cycles.",
                "4": "Three colors suffice.",
                "5": "Vertices can share colors with non-adjacent vertices.",
            },
        ),
        (
            "Graph Theory",
            "How many labeled trees are there on 4 vertices?",
            "16",
            ["4", "6", "24"],
            "Cayley's formula: n^{n−2} = 4² = 16.",
            {
                "4": "Unlabeled tree count is 2, not labeled.",
                "6": "That's K₄'s edge count, not tree count.",
                "24": "That's 4!, not the number of labeled trees.",
            },
        ),
        (
            "Graph Theory",
            "Mantel's theorem: a simple graph on n vertices with more than n²/4 edges must contain…",
            "A triangle (K₃).",
            [
                "A Hamiltonian cycle always.",
                "No 3-cycle and no 4-cycle.",
                "A complete bipartite subgraph K_{n/2, n/2} only.",
            ],
            "Extremal bound: beyond n²/4 edges, some three vertices are pairwise adjacent.",
            {
                "A Hamiltonian cycle always.": "Many dense graphs lack a Hamiltonian cycle.",
                "No 3-cycle and no 4-cycle.": "The theorem guarantees a triangle.",
                "A complete bipartite subgraph K_{n/2, n/2} only.": "That describes the Turán extremal graph at the bound, not what exceeding it forces.",
            },
        ),
        (
            "Recurrence Relations",
            "For T(n) = 3T(n/4) + n², the Master Theorem yields…",
            "Θ(n²)",
            ["Θ(n)", "Θ(n log n)", "Θ(n^{log_4 3})"],
            "f(n)=n² dominates n^{log_4 3} ≈ n^{0.79}; case 3 applies.",
            {
                "Θ(n)": "Polynomial f(n) wins over the subproblem growth.",
                "Θ(n log n)": "No logarithmic factor arises here.",
                "Θ(n^{log_4 3})": "That's the recursive part alone, smaller than n².",
            },
        ),
        (
            "Recurrence Relations",
            "A solution to a_n = a_{n−1} + a_{n−2} with roots r₁ ≠ r₂ is…",
            "a_n = c₁ r₁^n + c₂ r₂^n",
            [
                "a_n = (c₁ + c₂ n) r₁^n only",
                "a_n = c₁ + c₂ n always",
                "a_n = n! regardless of initials",
            ],
            "Distinct characteristic roots give independent exponential solutions.",
            {
                "a_n = (c₁ + c₂ n) r₁^n only": "The n factor appears only for repeated roots.",
                "a_n = c₁ + c₂ n always": "Linear, not Fibonacci-type unless roots are 1.",
                "a_n = n! regardless of initials": "Factorial does not solve this recurrence in general.",
            },
        ),
        (
            "Recurrence Relations",
            "The generating-function approach to a_n = 2a_{n−1} with a_0 = 1 gives a_n = …",
            "2^n",
            ["n · 2^{n−1}", "2n", "n²"],
            "A(x) = 1/(1−2x) expands to Σ 2^n x^n.",
            {
                "n · 2^{n−1}": "Extra factor of n is wrong here.",
                "2n": "Linear, not exponential.",
                "n²": "Wrong growth rate.",
            },
        ),
        (
            "Recurrence Relations",
            "If T(n) = T(n/2) + 1, then T(n) = …",
            "Θ(log n)",
            ["Θ(1)", "Θ(n)", "Θ(n log n)"],
            "Halving the problem once per level for n levels gives logarithmic depth.",
            {
                "Θ(1)": "The +1 work per level accumulates over log n levels.",
                "Θ(n)": "Too large — only one subproblem of half size.",
                "Θ(n log n)": "That needs two branches per level like merge sort.",
            },
        ),
    ],
)
