"""Quiz bank: Distributed Systems (Tanenbaum & Van Steen DS4)."""
from quiz_banks._make_book import make_book

BOOK = make_book(
    title="Distributed Systems",
    parent_topic="Computer Science",
    subtopic="Distributed Systems",
    slug="distributed-systems-ds4",
    source_url="https://www.distributed-systems.net/index.php/books/ds4/",
    easy=[
        (
            "Replication",
            "What is the main purpose of data replication in a distributed system?",
            "To improve availability and reduce latency by keeping copies on multiple nodes.",
            [
                "To encrypt data at rest on every disk.",
                "To guarantee that all nodes run identical application code.",
                "To eliminate the need for network communication.",
            ],
            "Replicas let clients read or fail over locally when a node is down or distant.",
            {
                "To encrypt data at rest on every disk.": "Encryption protects confidentiality; replication addresses availability and performance.",
                "To guarantee that all nodes run identical application code.": "That's deployment uniformity, not data replication.",
                "To eliminate the need for network communication.": "Replicas still synchronize over the network.",
            },
        ),
        (
            "Replication",
            "In primary-backup replication, who typically accepts writes?",
            "The primary (leader) replica.",
            [
                "Any replica chosen at random by the client.",
                "Only the backup with the lowest load.",
                "All replicas simultaneously without coordination.",
            ],
            "Clients send updates to the primary; backups receive propagated changes.",
            {
                "Any replica chosen at random by the client.": "Uncontrolled writes would conflict without a single writer.",
                "Only the backup with the lowest load.": "Backups are followers; they do not own write authority in this model.",
                "All replicas simultaneously without coordination.": "That would be multi-primary and needs conflict handling.",
            },
        ),
        (
            "Consistency",
            "What does linearizability (strong consistency) guarantee for concurrent operations?",
            "Operations appear to execute atomically in some total order consistent with real-time precedence.",
            [
                "Reads always return data from five seconds ago.",
                "Writes are visible only after a manual administrator approval.",
                "Clients never need to retry failed requests.",
            ],
            "Linearizability ties observable behavior to a single sequential history respecting timing.",
            {
                "Reads always return data from five seconds ago.": "That would be a fixed staleness bound, not linearizability.",
                "Writes are visible only after a manual administrator approval.": "Strong consistency is automatic, not operator-gated.",
                "Clients never need to retry failed requests.": "Retries are still needed for timeouts and failures.",
            },
        ),
        (
            "Consistency",
            "Eventual consistency means that if updates stop, what happens eventually?",
            "All replicas converge to the same value.",
            [
                "The system immediately rolls back every write.",
                "Reads return random values forever.",
                "The primary is permanently frozen.",
            ],
            "Without new writes, replication and repair eventually align replicas.",
            {
                "The system immediately rolls back every write.": "Eventual consistency does not imply rollback.",
                "Reads return random values forever.": "Convergence is the defining guarantee once writes halt.",
                "The primary is permanently frozen.": "Leaders can change; convergence is about data, not leadership freeze.",
            },
        ),
        (
            "CAP",
            "In the CAP theorem, what do C, A, and P stand for?",
            "Consistency, Availability, and Partition tolerance.",
            [
                "Concurrency, Authentication, and Privacy.",
                "Caching, Allocation, and Persistence.",
                "Compression, Archiving, and Parallelism.",
            ],
            "CAP names the three properties often traded off under network partitions.",
            {
                "Concurrency, Authentication, and Privacy.": "Those are security and programming concerns, not CAP.",
                "Caching, Allocation, and Persistence.": "CAP is about consistency, availability, and partitions.",
                "Compression, Archiving, and Parallelism.": "CAP does not refer to storage compression or archiving.",
            },
        ),
        (
            "CAP",
            "During a network partition, why can a distributed system not always offer both strong consistency and full availability?",
            "Answering every request while partitions isolate nodes can force inconsistent views unless some requests are refused.",
            [
                "CPUs become too slow to process packets.",
                "TLS handshakes fail on every link.",
                "Disk quotas are exceeded on all replicas.",
            ],
            "If replicas cannot talk, serving all nodes without coordination risks divergent state.",
            {
                "CPUs become too slow to process packets.": "CAP is a logical tradeoff, not a CPU speed limit.",
                "TLS handshakes fail on every link.": "Security handshakes are unrelated to the CAP tradeoff.",
                "Disk quotas are exceeded on all replicas.": "Storage limits do not define CAP.",
            },
        ),
        (
            "Consensus",
            "What problem does a distributed consensus algorithm solve?",
            "Getting all non-faulty nodes to agree on a single value or log entry.",
            [
                "Compressing log files on one machine.",
                "Scheduling threads on a single CPU core.",
                "Translating SQL queries into HTML.",
            ],
            "Consensus ensures a uniform decision despite failures and asynchronous networks.",
            {
                "Compressing log files on one machine.": "That is local storage maintenance, not distributed agreement.",
                "Scheduling threads on a single CPU core.": "That is single-machine OS scheduling.",
                "Translating SQL queries into HTML.": "That is unrelated application-layer formatting.",
            },
        ),
        (
            "Consensus",
            "In Paxos, what role proposes a value to be chosen?",
            "The proposer.",
            [
                "The load balancer.",
                "The metrics collector.",
                "The backup DNS server.",
            ],
            "Proposers initiate prepare and accept phases toward a chosen value.",
            {
                "The load balancer.": "Load balancers route traffic; they are not Paxos roles.",
                "The metrics collector.": "Monitoring components do not propose values in Paxos.",
                "The backup DNS server.": "DNS is naming infrastructure, not Paxos.",
            },
        ),
        (
            "Fault Tolerance",
            "A crash-stop failure model assumes faulty processes do what?",
            "Stop executing and responding, without sending incorrect messages.",
            [
                "Send arbitrary malicious messages forever.",
                "Always corrupt disk silently while continuing to run.",
                "Never fail under any circumstance.",
            ],
            "Crash-stop faults halt progress but do not equivocate.",
            {
                "Send arbitrary malicious messages forever.": "That describes Byzantine behavior, not crash-stop.",
                "Always corrupt disk silently while continuing to run.": "Crash-stop halts; it does not imply ongoing silent corruption.",
                "Never fail under any circumstance.": "The model explicitly allows failures.",
            },
        ),
        (
            "Fault Tolerance",
            "What is the purpose of a heartbeat between cluster members?",
            "To detect suspected node failures when messages are not received in time.",
            [
                "To encrypt all RPC payloads automatically.",
                "To assign primary keys in a SQL schema.",
                "To compile source code on each node.",
            ],
            "Missed heartbeats trigger suspicion and failover procedures.",
            {
                "To encrypt all RPC payloads automatically.": "Heartbeats are liveness signals, not encryption.",
                "To assign primary keys in a SQL schema.": "Primary keys are a data-model concern.",
                "To compile source code on each node.": "Build systems are unrelated to failure detection.",
            },
        ),
        (
            "Clocks",
            "Why do distributed systems often use logical clocks instead of only wall-clock time?",
            "Wall clocks skew and drift, so causal order needs a clock independent of absolute time.",
            [
                "Logical clocks run faster than light.",
                "Wall clocks are illegal on public clouds.",
                "Logical clocks store passwords securely.",
            ],
            "Lamport and vector clocks capture happened-before without tight clock sync.",
            {
                "Logical clocks run faster than light.": "They order events; they do not violate physics.",
                "Wall clocks are illegal on public clouds.": "NTP and hardware clocks are widely used.",
                "Logical clocks store passwords securely.": "Clocks order events; they are not secret stores.",
            },
        ),
        (
            "Clocks",
            "What does a Lamport timestamp provide?",
            "A partial ordering of events consistent with happened-before.",
            [
                "A globally synchronized UTC time with microsecond accuracy everywhere.",
                "A guarantee that all nodes share one physical clock chip.",
                "Proof that no messages were lost on the network.",
            ],
            "Lamport clocks increment on send/receive to preserve causal order when possible.",
            {
                "A globally synchronized UTC time with microsecond accuracy everywhere.": "That requires physical clock sync, not Lamport clocks alone.",
                "A guarantee that all nodes share one physical clock chip.": "Distributed nodes have separate hardware clocks.",
                "Proof that no messages were lost on the network.": "Timestamps do not detect packet loss.",
            },
        ),
        (
            "Partitioning",
            "What is hash partitioning of a key space?",
            "Assigning each key to a shard via a hash function modulo the number of partitions.",
            [
                "Storing every key on every node for every query.",
                "Sorting keys alphabetically on a single machine only.",
                "Encrypting keys with a public certificate.",
            ],
            "Hashing spreads keys evenly across shards for scalable storage.",
            {
                "Storing every key on every node for every query.": "That is full replication, not partitioning.",
                "Sorting keys alphabetically on a single machine only.": "That does not distribute across nodes.",
                "Encrypting keys with a public certificate.": "Partitioning is about placement, not PKIX encryption.",
            },
        ),
        (
            "Partitioning",
            "A hot partition (hot spot) occurs when what happens?",
            "One shard receives disproportionately many accesses for its key range.",
            [
                "All shards are idle because traffic is zero.",
                "Every key hashes to a unique physical datacenter.",
                "The network has zero latency between all nodes.",
            ],
            "Skewed access patterns overload a single partition despite hashing.",
            {
                "All shards are idle because traffic is zero.": "Hot spots imply high load, not idleness.",
                "Every key hashes to a unique physical datacenter.": "That would be extreme over-sharding, not a hot spot definition.",
                "The network has zero latency between all nodes.": "Latency does not define partition skew.",
            },
        ),
        (
            "RPC",
            "What is a remote procedure call (RPC)?",
            "Invoking a procedure on a remote machine as if it were local, via stubs and messaging.",
            [
                "Running a procedure only inside the kernel on one host.",
                "Copying a database file with FTP.",
                "Sending email between two users.",
            ],
            "RPC marshals arguments, sends a request, and unmarshals results across the network.",
            {
                "Running a procedure only inside the kernel on one host.": "That is local kernel code, not remote invocation.",
                "Copying a database file with FTP.": "File transfer is not procedure call semantics.",
                "Sending email between two users.": "Email is messaging for people, not structured RPC.",
            },
        ),
        (
            "RPC",
            "In RPC, what does the client stub typically do?",
            "Marshal arguments and send the request to the server stub.",
            [
                "Format the server's hard disk without permission.",
                "Replace the server's operating system kernel.",
                "Store only cached DNS records for the client.",
            ],
            "Stubs hide wire format and network details from application code.",
            {
                "Format the server's hard disk without permission.": "Stubs serialize calls; they do not disk-format remotes.",
                "Replace the server's operating system kernel.": "RPC does not swap remote kernels.",
                "Store only cached DNS records for the client.": "DNS caching is unrelated to RPC marshaling.",
            },
        ),
        (
            "Distributed Transactions",
            "What does the 'A' in ACID stand for?",
            "Atomicity — all operations in a transaction succeed or none are applied.",
            [
                "Availability — every read returns the newest value instantly.",
                "Anonymity — user identities are hidden from the database.",
                "Archiving — old rows are moved to cold storage automatically.",
            ],
            "Atomicity treats the transaction as an indivisible unit of work.",
            {
                "Availability — every read returns the newest value instantly.": "Availability is a separate systems property, not the A in ACID.",
                "Anonymity — user identities are hidden from the database.": "ACID does not mean anonymity.",
                "Archiving — old rows are moved to cold storage automatically.": "Archiving is lifecycle management, not atomicity.",
            },
        ),
        (
            "Distributed Transactions",
            "Two-phase commit (2PC) has which two phases?",
            "Prepare (vote) and commit (decision).",
            [
                "Compile and link.",
                "Encrypt and decrypt.",
                "Boot and shutdown.",
            ],
            "Participants vote in phase one; the coordinator decides commit or abort in phase two.",
            {
                "Compile and link.": "Those are build steps, not transaction phases.",
                "Encrypt and decrypt.": "2PC is about agreement, not cryptography phases.",
                "Boot and shutdown.": "Machine power states are unrelated to 2PC.",
            },
        ),
        (
            "Replication",
            "Synchronous replication waits for what before acknowledging a write to the client?",
            "Confirmation that backups have applied (or persisted) the update.",
            [
                "A full cluster reboot of all nodes.",
                "Deletion of all older snapshots worldwide.",
                "Completion of a unrelated batch job queue.",
            ],
            "The client learns the write is safe on replicas only after replicas acknowledge.",
            {
                "A full cluster reboot of all nodes.": "Replication acks do not require rebooting everyone.",
                "Deletion of all older snapshots worldwide.": "Snapshot policy is separate from sync replication acks.",
                "Completion of a unrelated batch job queue.": "Unrelated jobs are not part of the replication contract.",
            },
        ),
        (
            "Consistency",
            "Read-your-writes consistency ensures that a client sees what?",
            "Its own prior writes on subsequent reads.",
            [
                "Every other client's writes before they happen.",
                "Only data from nodes in a different continent.",
                "Nothing — reads always fail.",
            ],
            "A session observes its updates without waiting for global convergence of all clients.",
            {
                "Every other client's writes before they happen.": "That would be stronger than read-your-writes.",
                "Only data from nodes in a different continent.": "Geography is not the defining constraint.",
                "Nothing — reads always fail.": "The guarantee is about visibility of own writes, not total failure.",
            },
        ),
    ],
    medium=[
        (
            "Replication",
            "Quorum reads and writes with N replicas, write quorum W, and read quorum R ensure strong consistency when what holds?",
            "R + W > N (and typically W > N/2).",
            [
                "R + W = 0",
                "N = 1 always",
                "R = W = 1 regardless of N",
            ],
            "Overlapping quorums force reads and writes to intersect on at least one up-to-date replica.",
            {
                "R + W = 0": "Zero quorums would contact no replicas.",
                "N = 1 always": "A single replica removes quorum overlap benefits for fault tolerance.",
                "R = W = 1 regardless of N": "Singleton quorums do not guarantee overlap when N > 1.",
            },
        ),
        (
            "Replication",
            "Multi-primary (active-active) replication most directly increases risk of what?",
            "Write-write conflicts requiring detection or resolution.",
            [
                "Impossible read operations on any replica.",
                "Automatic elimination of network partitions.",
                "Guaranteed zero storage use.",
            ],
            "Concurrent writes to the same data from different primaries can diverge without coordination.",
            {
                "Impossible read operations on any replica.": "Reads still work; conflicts arise on concurrent writes.",
                "Automatic elimination of network partitions.": "Partitions still occur; multi-primary does not remove them.",
                "Guaranteed zero storage use.": "More primaries usually mean more copies, not zero storage.",
            },
        ),
        (
            "Consistency",
            "Monotonic reads consistency prevents which client-visible anomaly?",
            "Seeing newer data then older data on later reads in the same session.",
            [
                "Writing the same key twice in one transaction.",
                "Observing strictly increasing wall-clock on every packet.",
                "Receiving duplicate TCP segments only.",
            ],
            "Once a client reads a value, later reads in that view should not go backward in time.",
            {
                "Writing the same key twice in one transaction.": "That is allowed; monotonic reads concern read ordering.",
                "Observing strictly increasing wall-clock on every packet.": "Packet timestamps differ from monotonic read guarantees.",
                "Receiving duplicate TCP segments only.": "Transport duplicates are not the consistency model target.",
            },
        ),
        (
            "Consistency",
            "Causal consistency requires that if operation A happened-before B, then what?",
            "Every node observes A before B.",
            [
                "A and B may be seen in either order by every node.",
                "Only wall-clock time determines visibility, ignoring message chains.",
                "B must always execute on the same CPU core as A.",
            ],
            "Causal chains from communication and dependencies must be preserved in visible order.",
            {
                "A and B may be seen in either order by every node.": "That would violate causal ordering.",
                "Only wall-clock time determines visibility, ignoring message chains.": "Causality follows dependencies, not clocks alone.",
                "B must always execute on the same CPU core as A.": "Physical core affinity is not required.",
            },
        ),
        (
            "CAP",
            "Dynamo-style systems under partition often favor availability and partition tolerance by offering what consistency style?",
            "Eventual consistency with conflict resolution (e.g., version vectors, last-writer-wins).",
            [
                "Strict serializability on every read without exception.",
                "No writes allowed ever during normal operation.",
                "Single-node strict two-phase locking only.",
            ],
            "AP designs accept temporary divergence and reconcile later.",
            {
                "Strict serializability on every read without exception.": "That is a CP-style choice under partition stress.",
                "No writes allowed ever during normal operation.": "These systems allow writes with reconciliation.",
                "Single-node strict two-phase locking only.": "That ignores partition-first distributed design.",
            },
        ),
        (
            "CAP",
            "A CP system under network partition typically does what to preserve consistency?",
            "Rejects or blocks some operations on minority or unreachable sides until the partition heals.",
            [
                "Always serves every request on all partitions with latest data.",
                "Deletes all data on the majority partition.",
                "Disables authentication on all nodes.",
            ],
            "Sacrificing availability on isolated nodes avoids inconsistent reads and writes.",
            {
                "Always serves every request on all partitions with latest data.": "That risks split-brain inconsistent state.",
                "Deletes all data on the majority partition.": "CP systems block or redirect; they do not wipe majority data by default.",
                "Disables authentication on all nodes.": "Security policy is unrelated to CP behavior.",
            },
        ),
        (
            "Consensus",
            "In Raft, when does a follower become a candidate?",
            "After election timeout without hearing from the current leader.",
            [
                "Immediately when any client read arrives.",
                "Only when the cluster has zero nodes.",
                "Whenever the leader sends a heartbeat.",
            ],
            "Expired heartbeats suggest a dead leader, triggering a new election.",
            {
                "Immediately when any client read arrives.": "Client reads do not start elections.",
                "Only when the cluster has zero nodes.": "Elections need live nodes to vote.",
                "Whenever the leader sends a heartbeat.": "Heartbeats suppress elections, they do not trigger candidacy.",
            },
        ),
        (
            "Consensus",
            "What safety property does Paxos guarantee about chosen values?",
            "Only a value that was proposed by some proposer can be chosen, and at most one value is chosen per instance.",
            [
                "Every proposer always wins on the first message.",
                "Acceptors never persist any state to disk.",
                "Clients never need unique request identifiers.",
            ],
            "Agreement and validity prevent conflicting decisions for the same consensus instance.",
            {
                "Every proposer always wins on the first message.": "Contention and failures can require multiple rounds.",
                "Acceptors never persist any state to disk.": "Persistence is often required to survive restarts.",
                "Clients never need unique request identifiers.": "Idempotency at clients is a separate concern.",
            },
        ),
        (
            "Fault Tolerance",
            "To tolerate f crash-stop failures in a synchronous replication setting with in-sync replicas, you need at least how many replicas?",
            "f + 1 working copies (often discussed as 2f + 1 nodes for voting quorums).",
            [
                "Exactly one replica total.",
                "Zero replicas if heartbeats are enabled.",
                "f − 1 replicas when f > 0",
            ],
            "You must have enough non-faulty nodes to form a quorum or elect a leader.",
            {
                "Exactly one replica total.": "One replica cannot survive any failure.",
                "Zero replicas if heartbeats are enabled.": "Heartbeats do not replace redundant copies.",
                "f − 1 replicas when f > 0": "Fewer than f+1 cannot survive f failures.",
            },
        ),
        (
            "Fault Tolerance",
            "Byzantine fault tolerance differs from crash-stop tolerance because Byzantine nodes may do what?",
            "Send conflicting or malicious messages while appearing partially correct.",
            [
                "Only halt and never respond.",
                "Only lose power once and never restart.",
                "Only fail during scheduled maintenance windows.",
            ],
            "Byzantine faults include equivocation and arbitrary behavior, not just silence.",
            {
                "Only halt and never respond.": "That is crash-stop behavior.",
                "Only lose power once and never restart.": "Power loss is a physical failure mode, not the Byzantine definition.",
                "Only fail during scheduled maintenance windows.": "Byzantine faults are not limited to maintenance.",
            },
        ),
        (
            "Clocks",
            "A vector clock entry for process P contains what information?",
            "A count of events known to P, per process, used to compare causality.",
            [
                "The GPS latitude of process P only.",
                "The SHA-256 hash of P's disk serial number only.",
                "The TCP port number clients should use forever.",
            ],
            "Vector clocks track per-process logical times to detect concurrency and causality.",
            {
                "The GPS latitude of process P only.": "Location is unrelated to vector clock semantics.",
                "The SHA-256 hash of P's disk serial number only.": "Hardware IDs do not implement happened-before.",
                "The TCP port number clients should use forever.": "Ports are networking details, not causal clocks.",
            },
        ),
        (
            "Clocks",
            "TrueTime-style bounded clock uncertainty (small ε) helps distributed databases do what?",
            "Order commits with wait intervals so external consistency bounds hold.",
            [
                "Eliminate all network partitions automatically.",
                "Remove the need for replication entirely.",
                "Guarantee zero CPU usage on all nodes.",
            ],
            "Tight uncertainty windows let transactions commit with global time-based ordering guarantees.",
            {
                "Eliminate all network partitions automatically.": "Clock bounds do not prevent partitions.",
                "Remove the need for replication entirely.": "Spanner still replicates; clocks aid ordering.",
                "Guarantee zero CPU usage on all nodes.": "Waiting for clock intervals consumes time, not zero CPU.",
            },
        ),
        (
            "Partitioning",
            "Range partitioning can cause hot spots when keys are what?",
            "Sequential or highly correlated (e.g., time-ordered IDs hitting one range).",
            [
                "Uniformly random and spread across the key space.",
                "Hashed with a good hash function into many shards.",
                "Never written by any client.",
            ],
            "Adjacent keys land on the same shard, concentrating load.",
            {
                "Uniformly random and spread across the key space.": "That reduces hot spots, not causes them.",
                "Hashed with a good hash function into many shards.": "Hashing mitigates sequential clustering.",
                "Never written by any client.": "No writes imply no access hot spot.",
            },
        ),
        (
            "Partitioning",
            "Consistent hashing reduces data movement when what changes?",
            "The number of shards (nodes) in the cluster.",
            [
                "The client switches from HTTP to gRPC.",
                "A user changes their password.",
                "The TLS cipher suite is upgraded.",
            ],
            "Only keys near changed ring segments remap, not the entire key space.",
            {
                "The client switches from HTTP to gRPC.": "Protocol choice does not define remapping on shard add/remove.",
                "A user changes their password.": "Credential rotation is unrelated to shard membership.",
                "The TLS cipher suite is upgraded.": "Cipher upgrades do not re-home partition keys by themselves.",
            },
        ),
        (
            "RPC",
            "Why is idempotency important for at-least-once RPC retry?",
            "A retried call must not apply side effects twice (e.g., duplicate charges).",
            [
                "Retries are forbidden in all distributed systems.",
                "UDP cannot carry bytes larger than one bit.",
                "Servers must never log RPC requests.",
            ],
            "At-least-once delivery implies duplicates possible without idempotent handlers.",
            {
                "Retries are forbidden in all distributed systems.": "Retries are common; idempotency makes them safe.",
                "UDP cannot carry bytes larger than one bit.": "UDP payload limits are unrelated to idempotency.",
                "Servers must never log RPC requests.": "Logging is operational; idempotency is correctness.",
            },
        ),
        (
            "RPC",
            "gRPC over HTTP/2 primarily benefits RPC by providing what?",
            "Multiplexed streams, header compression, and efficient binary framing (Protobuf).",
            [
                "Guaranteed absence of network partitions.",
                "Automatic Byzantine agreement on every call.",
                "Replacement of all databases with local files.",
            ],
            "HTTP/2 features reduce connection overhead; Protobuf shrinks payloads.",
            {
                "Guaranteed absence of network partitions.": "Transport choice does not remove partitions.",
                "Automatic Byzantine agreement on every call.": "Consensus is not built into ordinary RPC.",
                "Replacement of all databases with local files.": "RPC does not replace databases.",
            },
        ),
        (
            "Distributed Transactions",
            "In two-phase commit, if the coordinator crashes after all participants voted YES but before sending COMMIT, what problem arises?",
            "Participants may block holding locks until the coordinator recovers (blocking problem).",
            [
                "Participants automatically commit without any recovery.",
                "All data is instantly deleted on every node.",
                "Network partitions are permanently impossible afterward.",
            ],
            "Uncertain transaction outcome requires coordinator recovery or heuristic decisions.",
            {
                "Participants automatically commit without any recovery.": "In-doubt participants wait for coordinator decision.",
                "All data is instantly deleted on every node.": "2PC blocking does not imply mass deletion.",
                "Network partitions are permanently impossible afterward.": "Partitions remain possible; 2PC is fragile under failures.",
            },
        ),
        (
            "Distributed Transactions",
            "Saga pattern compensates for lack of global locks by doing what?",
            "Chaining local transactions with defined compensating actions on failure.",
            [
                "Using one giant two-phase commit across 500 microservices always.",
                "Forbidding any rollback or undo in the system.",
                "Storing all state only in client browser cookies.",
            ],
            "Each step commits locally; compensations undo prior effects semantically.",
            {
                "Using one giant two-phase commit across 500 microservices always.": "Sagas avoid long-lived global 2PC.",
                "Forbidding any rollback or undo in the system.": "Compensating transactions are explicit rollbacks.",
                "Storing all state only in client browser cookies.": "Durable saga state lives in services/databases.",
            },
        ),
        (
            "Replication",
            "Read repair in quorum systems fixes what after a sloppy quorum read?",
            "Stale values on contacted replicas by writing back the latest version read.",
            [
                "TLS certificates on load balancers.",
                "OS kernel versions on clients.",
                "DNS TTL for unrelated domains.",
            ],
            "Anti-entropy on read path updates lagging replicas when divergence is detected.",
            {
                "TLS certificates on load balancers.": "Certificate rotation is unrelated to replica repair.",
                "OS kernel versions on clients.": "Client kernels do not define read repair.",
                "DNS TTL for unrelated domains.": "DNS caching is not read repair.",
            },
        ),
        (
            "Consistency",
            "Sequential consistency differs from linearizability in that sequential consistency requires what?",
            "A total order of all operations consistent with each process's program order, but not necessarily real-time order across processes.",
            [
                "No total order exists across operations.",
                "Real-time ordering of non-overlapping operations across processes is mandatory.",
                "Only UDP datagrams may carry writes.",
            ],
            "Sequential consistency is weaker: concurrent operations from different processes may be reordered in the global order.",
            {
                "No total order exists across operations.": "Sequential consistency still provides a global sequence.",
                "Real-time ordering of non-overlapping operations across processes is mandatory.": "That extra real-time constraint is linearizability.",
                "Only UDP datagrams may carry writes.": "Transport protocol is unrelated.",
            },
        ),
    ],
    hard=[
        (
            "Consensus",
            "In Raft, which invariant prevents two different leaders from being elected for the same term?",
            "A candidate must receive votes from a majority, and at most one majority can exist in a given term.",
            [
                "Leaders are chosen by uniform random without votes.",
                "Followers never reject AppendEntries RPCs.",
                "Terms decrease after every successful election.",
            ],
            "Majority intersection ensures at most one leader per term.",
            {
                "Leaders are chosen by uniform random without votes.": "Raft requires quorum votes, not random selection.",
                "Followers never reject AppendEntries RPCs.": "Followers reject stale leaders via term checks.",
                "Terms decrease after every successful election.": "Terms are monotonically non-decreasing.",
            },
        ),
        (
            "Consensus",
            "The Paxos accept phase requires acceptors to promise what after receiving a prepare with number n?",
            "Not to accept any proposal numbered less than n, and to report the highest-numbered proposal already accepted (if any).",
            [
                "To delete all log entries immediately.",
                "To accept only proposals numbered zero forever.",
                "To ignore all messages from proposers entirely.",
            ],
            "Promises and reporting prior accepts let proposers reuse learned values and avoid dueling proposers breaking safety.",
            {
                "To delete all log entries immediately.": "Acceptors retain state needed for safety.",
                "To accept only proposals numbered zero forever.": "Higher ballot/proposal numbers supersede lower ones.",
                "To ignore all messages from proposers entirely.": "Acceptors must respond to prepares and accepts.",
            },
        ),
        (
            "Replication",
            "Chain replication (head → … → tail) achieves strong consistency with what tradeoff?",
            "Lower write latency variance on the tail for reads, but failure of a chain node requires careful reconfiguration.",
            [
                "No need for any ordered log on any node.",
                "Clients may write to any random node without rules.",
                "Automatic multi-datacenter Byzantine agreement for free.",
            ],
            "Ordered chain append gives a clear commit point at the tail while keeping replication bandwidth bounded per hop.",
            {
                "No need for any ordered log on any node.": "Chain replication still orders updates along the chain.",
                "Clients may write to any random node without rules.": "Writes go to the head; ordering follows the chain.",
                "Automatic multi-datacenter Byzantine agreement for free.": "Chain replication targets crash faults, not free BFT.",
            },
        ),
        (
            "Replication",
            "Leaderless quorum systems (e.g., Dynamo-style) during a partition with W + R ≤ N may return what?",
            "Stale reads that do not include the latest write if quorums do not overlap.",
            [
                "Guaranteed linearizable reads always.",
                "Impossible writes because disks are read-only.",
                "Automatic Paxos leader election on every read.",
            ],
            "Without quorum overlap, read and write sets may miss the newest replica.",
            {
                "Guaranteed linearizable reads always.": "Insufficient overlap breaks strong read guarantees.",
                "Impossible writes because disks are read-only.": "Writes can succeed on a side; reads may be stale.",
                "Automatic Paxos leader election on every read.": "Quorum stores do not run Paxos per read by default.",
            },
        ),
        (
            "Consistency",
            "Serializable isolation in a distributed database is closest to which guarantee?",
            "Transactions appear to execute in some serial order equivalent to their committed effects.",
            [
                "Every transaction sees only uncommitted data from others.",
                "Reads never block writes and writes never block reads in any implementation.",
                "All transactions must execute on a single thread globally with no network.",
            ],
            "Serializability is about equivalence to a serial schedule, not necessarily linearizability timing.",
            {
                "Every transaction sees only uncommitted data from others.": "That would be reading dirty data, violating isolation.",
                "Reads never block writes and writes never block reads in any implementation.": "SSI and locking implementations may block.",
                "All transactions must execute on a single thread globally with no network.": "Distributed serializable systems still use networks.",
            },
        ),
        (
            "Consistency",
            "Session consistency bundles which practical guarantees for a single client session?",
            "Monotonic reads, monotonic writes, read-your-writes, and writes-follow-reads (related variants).",
            [
                "Only eventual consistency with no per-session rules.",
                "Strict serializability across all clients globally with real-time order.",
                "No ordering guarantees of any kind.",
            ],
            "Session guarantees align a client's view without requiring global strong consistency for everyone.",
            {
                "Only eventual consistency with no per-session rules.": "Session consistency adds per-client ordering constraints.",
                "Strict serializability across all clients globally with real-time order.": "That is much stronger than session guarantees.",
                "No ordering guarantees of any kind.": "Session models explicitly define several ordering properties.",
            },
        ),
        (
            "CAP",
            "PACELC extends CAP by stating that else (E), even without partition, one often trades between what?",
            "Latency (L) and consistency (C).",
            [
                "Password length and certificate color.",
                "CPU brand and keyboard layout.",
                "File extension and MIME type only.",
            ],
            "When the network is normal, replication and coordination choices still affect latency vs consistency.",
            {
                "Password length and certificate color.": "PACELC concerns latency and consistency, not credentials aesthetics.",
                "CPU brand and keyboard layout.": "Hardware peripherals are unrelated.",
                "File extension and MIME type only.": "Web typing is unrelated to database tradeoffs.",
            },
        ),
        (
            "CAP",
            "During a split-brain with two writable primaries, the most dangerous outcome for data is what?",
            "Divergent writes that cannot be merged automatically without application rules.",
            [
                "Slightly higher RPC latency only.",
                "Uniform read-only mode on both sides forever.",
                "Automatic agreement on every conflicting value via magic.",
            ],
            "Concurrent incompatible updates on both sides require conflict resolution or operator merge.",
            {
                "Slightly higher RPC latency only.": "Split-brain risks correctness, not just latency.",
                "Uniform read-only mode on both sides forever.": "Split-brain often means both sides still accept writes.",
                "Automatic agreement on every conflicting value via magic.": "Conflicts need protocols; they do not self-resolve.",
            },
        ),
        (
            "Fault Tolerance",
            "The FLP impossibility result implies that in an asynchronous system with crash failures, deterministic consensus is impossible if what may happen?",
            "Messages can be delayed arbitrarily and processes may appear slow or crashed (no bounded timeouts).",
            [
                "The network delivers all messages in one millisecond always.",
                "Processes share a perfectly synchronized atomic clock for free.",
                "No process may ever fail.",
            ],
            "Without synchrony assumptions, a bivalent configuration cannot be forced to decide within finite steps.",
            {
                "The network delivers all messages in one millisecond always.": "Bounded delivery is a synchrony assumption FLP avoids.",
                "Processes share a perfectly synchronized atomic clock for free.": "Strong synchrony would change the model.",
                "No process may ever fail.": "FLP allows crash failures; the core issue is asynchrony.",
            },
        ),
        (
            "Fault Tolerance",
            "PBFT (Practical Byzantine Fault Tolerance) can tolerate how many Byzantine replicas out of 3f + 1 total?",
            "Up to f Byzantine replicas.",
            [
                "Up to 2f + 1 Byzantine replicas.",
                "Zero — PBFT only handles crash-stop faults.",
                "All replicas except one, regardless of f.",
            ],
            "3f + 1 replicas allow quorum sizes that intersect despite f equivocating nodes.",
            {
                "Up to 2f + 1 Byzantine replicas.": "That would exceed the designed fault threshold.",
                "Zero — PBFT only handles crash-stop faults.": "PBFT explicitly targets Byzantine faults.",
                "All replicas except one, regardless of f.": "Tolerance is bounded by f, not arbitrary majorities faulty.",
            },
        ),
        (
            "Clocks",
            "Hybrid logical clocks (HLC) combine physical and logical time primarily to achieve what?",
            "Causality tracking with timestamps close to physical time for TTL and debugging.",
            [
                "Elimination of all NTP traffic worldwide.",
                "Proof that wall clocks never drift.",
                "Replacement of vector clocks with one bit only.",
            ],
            "HLC preserves happened-before while staying near UTC when clocks are reasonably synchronized.",
            {
                "Elimination of all NTP traffic worldwide.": "HLC still benefits from coarse physical sync.",
                "Proof that wall clocks never drift.": "Drift still exists; HLC bounds misuse when sync is loose.",
                "Replacement of vector clocks with one bit only.": "HLC is a hybrid timestamp, not a single bit.",
            },
        ),
        (
            "Clocks",
            "If two events are concurrent under vector clock comparison (neither less than the other), what can you conclude?",
            "Neither event causally depends on the other; they may need merge or conflict handling.",
            [
                "One event definitely happened-before the other in real time.",
                "Both events occurred on the same physical CPU core.",
                "The network guaranteed exactly-once delivery for both.",
            ],
            "Incomparable vectors indicate concurrency, not a causal path between them.",
            {
                "One event definitely happened-before the other in real time.": "Incomparability means not causally ordered by the clock.",
                "Both events occurred on the same physical CPU core.": "Concurrency is logical, not core affinity.",
                "The network guaranteed exactly-once delivery for both.": "Delivery semantics are separate from clock comparison.",
            },
        ),
        (
            "Partitioning",
            "Rebalancing shards with consistent hashing while serving traffic risks what if not coordinated?",
            "Clients or backends routing to wrong shards, causing temporary unavailability or consistency anomalies.",
            [
                "Automatic doubling of network bandwidth with no work.",
                "Permanent impossibility of adding nodes to the cluster.",
                "Elimination of the need for replication.",
            ],
            "Membership changes require staged handoff or dual-read rules to avoid lost or double-served keys.",
            {
                "Automatic doubling of network bandwidth with no work.": "Rebalancing adds work and migration traffic.",
                "Permanent impossibility of adding nodes to the cluster.": "Clusters add nodes with migration protocols.",
                "Elimination of the need for replication.": "Partitioning complements replication, not replaces it.",
            },
        ),
        (
            "Partitioning",
            "Secondary indexes in a partitioned database are hard because an index lookup may require what?",
            "Scatter-gather queries across many shards or maintaining separate index partitions.",
            [
                "Only local disk access on one machine with no network.",
                "Disabling all writes globally forever.",
                "Storing the entire database in L1 CPU cache.",
            ],
            "Index entries for a key may live on different shards than the primary record.",
            {
                "Only local disk access on one machine with no network.": "Distributed indexes cross shard boundaries.",
                "Disabling all writes globally forever.": "Indexes are maintained during normal writes with extra cost.",
                "Storing the entire database in L1 CPU cache.": "Scale-out systems do not fit in L1 cache.",
            },
        ),
        (
            "RPC",
            "Exactly-once RPC semantics in practice usually combines at-least-once delivery with what on the server?",
            "Idempotent operations or deduplication using client request IDs stored until completion.",
            [
                "Ignoring all duplicate packets without tracking anything.",
                "Disabling retries and assuming TCP never retransmits.",
                "Returning random errors for every second call.",
            ],
            "Duplicates are inevitable; dedup tables or idempotent design make effects appear exactly once.",
            {
                "Ignoring all duplicate packets without tracking anything.": "Blind ignore can drop legitimate first attempts too.",
                "Disabling retries and assuming TCP never retransmits.": "TCP retransmits; application retries add more duplicates.",
                "Returning random errors for every second call.": "That does not provide exactly-once semantics.",
            },
        ),
        (
            "RPC",
            "The thundering herd problem after cache expiry is mitigated in distributed RPC layers by techniques such as what?",
            "Request coalescing (singleflight), lease-based early refresh, or jittered backoff on regenerating values.",
            [
                "Increasing herd size by notifying all clients to hit origin simultaneously.",
                "Disabling caching entirely on every node without replacement.",
                "Using only UDP broadcast storms for refresh.",
            ],
            "Coalescing ensures one backend rebuild while others wait for the same result.",
            {
                "Increasing herd size by notifying all clients to hit origin simultaneously.": "That worsens the herd, not mitigates it.",
                "Disabling caching entirely on every node without replacement.": "Removes cache benefits; does not specifically fix stampedes.",
                "Using only UDP broadcast storms for refresh.": "Broadcast storms amplify load.",
            },
        ),
        (
            "Distributed Transactions",
            "Three-phase commit (3PC) attempts to reduce 2PC blocking by adding a pre-commit phase so that participants know what before commit?",
            "That all participants are ready and will commit if the coordinator proceeds, enabling timeout-based recovery rules.",
            [
                "That no participant ever persisted any vote.",
                "That the transaction must abort if any network byte is lost ever.",
                "That only one phase is needed total.",
            ],
            "Pre-commit narrows uncertain states but still assumes weaker failure models than async reality.",
            {
                "That no participant ever persisted any vote.": "Votes and states are still recorded.",
                "That the transaction must abort if any network byte is lost ever.": "3PC does not require abort on any loss.",
                "That only one phase is needed total.": "3PC still has multiple phases (can-ready-precommit-commit).",
            },
        ),
        (
            "Distributed Transactions",
            "Percolator-style transactions on Bigtable use which mechanism to detect write-write conflicts across rows?",
            "Primary locks with a write column and commit timestamp after a prewrite phase.",
            [
                "Global two-phase commit with a single in-memory lock on one laptop.",
                "Deleting all row keys before every read.",
                "Ignoring timestamps and using only last-writer-wins silently.",
            ],
            "Prewrite locks + commit timestamps provide optimistic concurrency control at scale.",
            {
                "Global two-phase commit with a single in-memory lock on one laptop.": "Percolator avoids single global 2PC coordinator.",
                "Deleting all row keys before every read.": "Destructive deletes are not the conflict detection method.",
                "Ignoring timestamps and using only last-writer-wins silently.": "Timestamps and locks are central to Percolator.",
            },
        ),
        (
            "Consensus",
            "Raft's log matching property requires that if two logs contain an entry with the same index and term, then what?",
            "The logs are identical in all preceding entries.",
            [
                "The logs may differ arbitrarily before that index.",
                "Only the last entry must match; earlier entries are irrelevant.",
                "Terms must decrease after the matching entry.",
            ],
            "Induction from the leader's AppendEntries consistency check ensures replicated prefixes match.",
            {
                "The logs may differ arbitrarily before that index.": "Matching index/term implies identical prefixes.",
                "Only the last entry must match; earlier entries are irrelevant.": "Safety depends on entire prefix agreement.",
                "Terms must decrease after the matching entry.": "Terms are non-decreasing along a log.",
            },
        ),
        (
            "Replication",
            "State machine replication requires replicas to process commands how for correctness?",
            "In the same deterministic order, usually via a replicated log agreed by consensus.",
            [
                "In arbitrary different orders on each replica as long as throughput is high.",
                "Only on weekends when traffic is low.",
                "Without any agreement protocol if the language is Java.",
            ],
            "Deterministic state machines + agreed log order yield identical final states.",
            {
                "In arbitrary different orders on each replica as long as throughput is high.": "Different orders produce divergent state.",
                "Only on weekends when traffic is low.": "Ordering is required whenever commands mutate state.",
                "Without any agreement protocol if the language is Java.": "Language choice does not replace consensus ordering.",
            },
        ),
    ],
)
