"""Quiz bank: Linear Algebra (Hefferon)."""
from quiz_banks._make_book import make_book

EASY = [
    (
        "Vectors",
        "What is the length (Euclidean norm) of the vector (3, 4) in ℝ²?",
        "5",
        ["7", "25", "√7"],
        "‖(3,4)‖ = √(3² + 4²) = √(9 + 16) = 5.",
        {
            "7": "That's 3 + 4, not the Pythagorean combination of components.",
            "25": "That's the squared norm 3² + 4²; take the square root for the length.",
            "√7": "Not √(9 + 16).",
        },
    ),
    (
        "Vectors",
        "Compute the dot product (1, 2) · (3, 4).",
        "11",
        ["7", "10", "14"],
        "(1)(3) + (2)(4) = 3 + 8 = 11.",
        {
            "7": "That's 1 + 2 + 3 + 4, not componentwise multiplication summed.",
            "10": "Off by one in the arithmetic.",
            "14": "That's 2·7 or another product — use (1)(3) + (2)(4).",
        },
    ),
    (
        "Vectors",
        "In ℝ³, the standard basis vector e₂ is…",
        "(0, 1, 0)",
        ["(1, 0, 0)", "(0, 0, 1)", "(1, 1, 1)"],
        "e₂ has a 1 in the second coordinate and 0 elsewhere.",
        {
            "(1, 0, 0)": "That's e₁, not e₂.",
            "(0, 0, 1)": "That's e₃.",
            "(1, 1, 1)": "Not a standard basis vector.",
        },
    ),
    (
        "Matrices",
        "What is the 2 × 2 identity matrix I₂?",
        "[[1, 0], [0, 1]]",
        ["[[0, 1], [1, 0]]", "[[1, 1], [1, 1]]", "[[1, 0], [1, 0]]"],
        "I₂ has ones on the diagonal and zeros elsewhere; it leaves vectors unchanged under multiplication.",
        {
            "[[0, 1], [1, 0]]": "That swaps coordinates — it's a permutation matrix, not the identity.",
            "[[1, 1], [1, 1]]": "That matrix is singular and does not preserve all vectors.",
            "[[1, 0], [1, 0]]": "Rows are dependent; not the identity.",
        },
    ),
    (
        "Matrices",
        "A matrix with 2 rows and 3 columns is described as…",
        "2 × 3",
        ["3 × 2", "2 × 2", "3 × 3"],
        "By convention, m × n means m rows and n columns.",
        {
            "3 × 2": "That would be 3 rows and 2 columns — dimensions are reversed.",
            "2 × 2": "A 2 × 2 matrix has only two columns.",
            "3 × 3": "That requires three rows and three columns.",
        },
    ),
    (
        "Row Reduction",
        "In row echelon form, the leading entry of each nonzero row (the pivot) lies…",
        "Strictly to the right of the pivot in the row above.",
        [
            "In the same column as every other pivot",
            "Below the pivot in the same column",
            "Only in the last column",
        ],
        "Echelon form forces pivots to move right as you go down the rows.",
        {
            "In the same column as every other pivot": "Pivots generally shift right; they need not share a column.",
            "Below the pivot in the same column": "That would be a zero below each pivot in REF, not the definition of pivot position.",
            "Only in the last column": "Pivots appear across columns depending on the matrix.",
        },
    ),
    (
        "Determinants",
        "What is det [[1, 2], [3, 4]]?",
        "−2",
        ["2", "10", "−10"],
        "det = (1)(4) − (2)(3) = 4 − 6 = −2.",
        {
            "2": "That's ad + bc or a sign error — use ad − bc.",
            "10": "That's 1 + 2 + 3 + 4, not a determinant.",
            "−10": "Wrong combination of products.",
        },
    ),
    (
        "Eigenvalues",
        "A scalar λ is an eigenvalue of A if there exists a nonzero vector v with…",
        "Av = λv",
        ["Av = 0 for every v", "det A = λ", "A = λI"],
        "Eigenvalues are defined through nontrivial solutions to (A − λI)v = 0.",
        {
            "Av = 0 for every v": "That would mean A is the zero matrix on all inputs, not an eigenpair.",
            "det A = λ": "det A is a single number for the matrix, not the eigenvalue condition.",
            "A = λI": "That would mean every vector is an eigenvector with the same λ — far stronger than one eigenpair.",
        },
    ),
    (
        "Linear Independence",
        "The vectors (1, 2) and (2, 4) in ℝ² are…",
        "Linearly dependent (one is a scalar multiple of the other).",
        [
            "Linearly independent",
            "Orthogonal",
            "A basis for ℝ³",
        ],
        "(2, 4) = 2(1, 2), so one lies in the span of the other.",
        {
            "Linearly independent": "A nontrivial combination 2·(1,2) − 1·(2,4) = 0 shows dependence.",
            "Orthogonal": "Their dot product is 1·2 + 2·4 = 10 ≠ 0.",
            "A basis for ℝ³": "They live in ℝ² and there are only two vectors anyway.",
        },
    ),
    (
        "Span",
        "The span of a single nonzero vector v in ℝⁿ is…",
        "All scalar multiples of v (a line through the origin).",
        [
            "All of ℝⁿ",
            "Only the zero vector",
            "The set of unit vectors",
        ],
        "Span{v} = {cv : c ∈ ℝ}, a one-dimensional subspace when v ≠ 0.",
        {
            "All of ℝⁿ": "One nonzero vector cannot reach every direction in ℝⁿ unless n = 1.",
            "Only the zero vector": "cv includes v itself when c = 1.",
            "The set of unit vectors": "Scalar multiples need not have length 1.",
        },
    ),
    (
        "Orthogonality",
        "Two vectors u and v are orthogonal when…",
        "u · v = 0",
        ["‖u‖ = ‖v‖", "u × v = 0 in ℝ²", "u = v"],
        "Orthogonality in Euclidean space is defined by zero inner product.",
        {
            "‖u‖ = ‖v‖": "Equal length does not imply perpendicularity.",
            "u × v = 0 in ℝ²": "The cross product is a 3D tool; in ℝ² use the dot product.",
            "u = v": "Identical nonzero vectors are parallel, not orthogonal.",
        },
    ),
    (
        "Least Squares",
        "When Ax = b has no exact solution (overdetermined inconsistent system), least squares seeks x that…",
        "Minimizes ‖Ax − b‖",
        [
            "Makes Ax = b exactly",
            "Maximizes ‖Ax − b‖",
            "Sets x = 0 always",
        ],
        "Least squares minimizes the residual norm, giving the best fit in the column space of A.",
        {
            "Makes Ax = b exactly": "If no exact solution exists, that goal is impossible.",
            "Maximizes ‖Ax − b‖": "That would be the worst fit, not the best.",
            "Sets x = 0 always": "x = 0 is optimal only in special cases.",
        },
    ),
    (
        "Vectors",
        "If u = (1, −1) and v = (2, 3), then u + v equals…",
        "(3, 2)",
        ["(1, −3)", "(2, −3)", "(−1, 4)"],
        "Add componentwise: (1+2, −1+3) = (3, 2).",
        {
            "(1, −3)": "That's u − v or a sign error on the second component.",
            "(2, −3)": "Mixed components from multiplication, not addition.",
            "(−1, 4)": "That's v − u.",
        },
    ),
    (
        "Matrices",
        "If A is 2 × 3 and B is 3 × 4, the product AB has size…",
        "2 × 4",
        ["3 × 3", "2 × 3", "3 × 4"],
        "Inner dimensions must match (3); the result has the outer dimensions 2 × 4.",
        {
            "3 × 3": "That's only when both factors are 3 × 3.",
            "2 × 3": "That's the size of A, not the product.",
            "3 × 4": "That's the size of B, not the product.",
        },
    ),
    (
        "Row Reduction",
        "An augmented matrix [A | b] represents the linear system…",
        "Ax = b",
        ["Ab = x", "xA = b", "A = bx"],
        "Columns of A combine with entries of x to produce b.",
        {
            "Ab = x": "Matrix sizes would not align for ordinary matrix-vector multiplication.",
            "xA = b": "Variables are usually written as a column on the right of A.",
            "A = bx": "Not the standard form of a linear system.",
        },
    ),
    (
        "Determinants",
        "For any n, det(Iₙ) equals…",
        "1",
        ["0", "n", "−1"],
        "The identity matrix is invertible with determinant product of diagonal ones.",
        {
            "0": "A singular matrix has determinant zero; Iₙ is nonsingular.",
            "n": "That's the trace for Iₙ, not the determinant.",
            "−1": "Determinant −1 arises from an odd number of row swaps of Iₙ, not Iₙ itself.",
        },
    ),
    (
        "Eigenvalues",
        "If Av = 3v for nonzero v, then 3 is…",
        "An eigenvalue of A with eigenvector v",
        ["Not related to A", "Always the only eigenvalue", "The determinant of A"],
        "The equation matches Av = λv with λ = 3.",
        {
            "Not related to A": "It is the eigenvalue in the defining equation.",
            "Always the only eigenvalue": "A may have other eigenvalues and eigenvectors.",
            "The determinant of A": "det A equals the product of eigenvalues (with multiplicity) only in specific cases, not from one eigenpair alone.",
        },
    ),
    (
        "Linear Independence",
        "Any three vectors in ℝ² are…",
        "Linearly dependent",
        [
            "Always linearly independent",
            "Always a basis",
            "Always orthogonal",
        ],
        "dim ℝ² = 2, so more than two vectors must satisfy a nontrivial dependence relation.",
        {
            "Always linearly independent": "Impossible when count exceeds dimension.",
            "Always a basis": "A basis of ℝ² has exactly two independent vectors.",
            "Always orthogonal": "Dependence does not force orthogonality.",
        },
    ),
    (
        "Span",
        "The standard basis {e₁, …, eₙ} spans…",
        "All of ℝⁿ",
        ["Only the first coordinate axis", "Only vectors with positive entries", "The empty set"],
        "Every vector is a linear combination of basis vectors with coefficients its entries.",
        {
            "Only the first coordinate axis": "e₂, …, eₙ are needed for other coordinates.",
            "Only vectors with positive entries": "Negative coefficients allow negative entries in combinations.",
            "The empty set": "Each eᵢ is in the span, so the span is nonempty.",
        },
    ),
    (
        "Orthogonality",
        "The projection of (4, 0) onto the x-axis in ℝ² is…",
        "(4, 0)",
        ["(0, 4)", "(2, 2)", "(0, 0)"],
        "The vector already lies on the x-axis, so projection leaves it unchanged.",
        {
            "(0, 4)": "That's alignment with the y-axis, not the x-axis.",
            "(2, 2)": "Not collinear with the x-axis.",
            "(0, 0)": "Only the zero vector projects to zero here; (4,0) is nonzero on the axis.",
        },
    ),
]

MEDIUM = [
    (
        "Vectors",
        "Find a unit vector in the direction of v = (3, −4).",
        "(3/5, −4/5)",
        ["(3, −4)", "(4/5, 3/5)", "(−3/5, 4/5)"],
        "‖v‖ = 5, so v/‖v‖ = (3/5, −4/5).",
        {
            "(3, −4)": "That has length 5, not 1.",
            "(4/5, 3/5)": "Swaps and signs — not parallel to (3, −4).",
            "(−3/5, 4/5)": "Opposite direction — still parallel but wrong sign if matching v's direction.",
        },
    ),
    (
        "Matrices",
        "Compute [[1, 2], [0, 3]] [[1], [2]].",
        "[[5], [6]]",
        ["[[3], [6]]", "[[1], [6]]", "[[5], [3]]"],
        "Row 1: 1·1 + 2·2 = 5; row 2: 0·1 + 3·2 = 6.",
        {
            "[[3], [6]]": "First-row arithmetic used 1+2 instead of 1·1 + 2·2.",
            "[[1], [6]]": "Missed the contribution of the second column to the first row.",
            "[[5], [3]]": "Second row should be 6, not 3.",
        },
    ),
    (
        "Row Reduction",
        "How many free variables can a 3 × 5 coefficient matrix have at most?",
        "5",
        ["3", "2", "0"],
        "With 5 unknowns, free variables = 5 − rank; rank can be as low as 0, giving up to 5 free variables.",
        {
            "3": "That's the maximum rank (row count), not the maximum free variables.",
            "2": "That's the minimum free count when rank is 3, not the maximum.",
            "0": "Zero free variables require rank 5, impossible with only 3 rows unless the matrix is degenerate in a different sense.",
        },
    ),
    (
        "Determinants",
        "If A is 3 × 3 with det A = 2, then det(2A) equals…",
        "16",
        ["4", "6", "12"],
        "Scaling a 3 × 3 matrix by 2 multiplies the determinant by 2³ = 8; 8 · 2 = 16.",
        {
            "4": "Used factor 2 once instead of 2³.",
            "6": "Added 2 to det A instead of multiplying by 2³.",
            "12": "Used 2² instead of 2³.",
        },
    ),
    (
        "Eigenvalues",
        "The eigenvalues of [[2, 0], [0, 3]] are…",
        "2 and 3",
        ["0 and 5", "2 and 0", "1 and 6"],
        "Diagonal matrices have eigenvalues on the diagonal.",
        {
            "0 and 5": "Confused trace/determinant with individual eigenvalues.",
            "2 and 0": "The second eigenvalue is 3, not 0.",
            "1 and 6": "Not the diagonal entries.",
        },
    ),
    (
        "Linear Independence",
        "Which set is linearly independent in ℝ³?",
        "{(1,0,0), (0,1,0), (0,0,1)}",
        [
            "{(1,0,0), (2,0,0)}",
            "{(1,1,0), (2,2,0), (0,0,1)}",
            "{(1,0,0), (0,1,0), (1,1,0)}",
        ],
        "The standard basis has no nontrivial combination giving zero.",
        {
            "{(1,0,0), (2,0,0)}": "Second vector is 2 times the first — dependent.",
            "{(1,1,0), (2,2,0), (0,0,1)}": "(1,1,0) and (2,2,0) are multiples — dependent triple.",
            "{(1,0,0), (0,1,0), (1,1,0)}": "Third vector is the sum of the first two — dependent.",
        },
    ),
    (
        "Span",
        "The span of {(1,0), (0,1)} in ℝ² is…",
        "All of ℝ²",
        ["Only the x-axis", "A line y = x", "The empty set"],
        "The two vectors are the standard basis for ℝ².",
        {
            "Only the x-axis": "(0,1) is not on the x-axis but is in the span.",
            "A line y = x": "That line is span{(1,1)}, not the coordinate axes.",
            "The empty set": "Contains (1,0) and (0,1).",
        },
    ),
    (
        "Orthogonality",
        "Apply Gram–Schmidt to v₁ = (1, 0) and v₂ = (1, 1). The orthogonal second vector is…",
        "(0, 1)",
        ["(1, 1)", "(1, 0)", "(0, 0)"],
        "proj_{v₁} v₂ = (1,0); v₂ − proj = (1,1) − (1,0) = (0,1).",
        {
            "(1, 1)": "Not orthogonal to v₁ — dot product is 1.",
            "(1, 0)": "That's v₁, not the component perpendicular to v₁.",
            "(0, 0)": "v₂ is not parallel to v₁, so the perpendicular part is nonzero.",
        },
    ),
    (
        "Least Squares",
        "The normal equations for least squares with full column rank A are…",
        "AᵀAx = Aᵀb",
        ["Ax = b", "AAx = b", "x = A⁻¹b"],
        "Minimizing ‖Ax − b‖² leads to AᵀAx = Aᵀb when AᵀA is invertible.",
        {
            "Ax = b": "Used when an exact solution exists, not the least-squares substitute.",
            "AAx = b": "Missing transpose on the first factor — wrong derivation.",
            "x = A⁻¹b": "A may not be square or invertible.",
        },
    ),
    (
        "Vectors",
        "The angle between u = (1, 0) and v = (1, 1) satisfies cos θ = …",
        "1/√2",
        ["1/2", "0", "√2"],
        "u·v = 1, ‖u‖ = 1, ‖v‖ = √2, so cos θ = 1/√2.",
        {
            "1/2": "Would correspond to θ = 60° in a different configuration.",
            "0": "Would mean orthogonal vectors.",
            "√2": "Cosine cannot exceed 1.",
        },
    ),
    (
        "Matrices",
        "Which matrix is invertible?",
        "[[1, 2], [3, 7]]",
        [
            "[[1, 2], [2, 4]]",
            "[[0, 0], [1, 1]]",
            "[[1, 1], [1, 1]]",
        ],
        "det [[1,2],[3,7]] = 7 − 6 = 1 ≠ 0; the others have dependent rows.",
        {
            "[[1, 2], [2, 4]]": "Row 2 is 2× row 1 — determinant zero.",
            "[[0, 0], [1, 1]]": "Zero row — singular.",
            "[[1, 1], [1, 1]]": "Identical rows — singular.",
        },
    ),
    (
        "Row Reduction",
        "A homogeneous system Ax = 0 with more unknowns than equations (n > m) always has…",
        "A nontrivial solution",
        [
            "No solution",
            "Exactly one solution",
            "Determinant 1",
        ],
        "Rank ≤ m < n, so there are free variables and infinitely many solutions including x ≠ 0.",
        {
            "No solution": "x = 0 is always a solution for homogeneous systems.",
            "Exactly one solution": "Free variables prevent uniqueness when n > rank.",
            "Determinant 1": "A need not be square.",
        },
    ),
    (
        "Determinants",
        "If A and B are 2 × 2, then det(AB) equals…",
        "det A · det B",
        ["det A + det B", "det(A + B)", "det A / det B"],
        "Determinant is multiplicative: det(AB) = det A det B.",
        {
            "det A + det B": "Determinant is not additive in general.",
            "det(A + B)": "det(A + B) rarely equals det A det B.",
            "det A / det B": "Not the product rule.",
        },
    ),
    (
        "Eigenvalues",
        "The characteristic polynomial of A = [[0, 1], [1, 0]] is…",
        "λ² − 1",
        ["λ² + 1", "λ − 1", "λ²"],
        "det([[−λ, 1], [1, −λ]]) = λ² − 1; eigenvalues ±1.",
        {
            "λ² + 1": "Sign error on the diagonal product.",
            "λ − 1": "Degree 1 — characteristic polynomial is degree 2 for 2 × 2.",
            "λ²": "Missed the 1 from off-diagonal.",
        },
    ),
    (
        "Linear Independence",
        "A set containing the zero vector is always…",
        "Linearly dependent",
        [
            "Linearly independent",
            "A basis",
            "Orthonormal",
        ],
        "1·0 + 0·(other vectors) = 0 is a nontrivial dependence on the zero vector alone.",
        {
            "Linearly independent": "The zero vector alone gives a nontrivial combination.",
            "A basis": "Bases consist of independent vectors; zero cannot be in a basis.",
            "Orthonormal": "Independence fails before discussing normalization.",
        },
    ),
    (
        "Span",
        "If S = {(1,0,0), (0,1,0)}, then dim(span S) equals…",
        "2",
        ["1", "3", "0"],
        "The two vectors are independent and lie in a plane in ℝ³.",
        {
            "1": "They are not parallel.",
            "3": "Two non-coplanar-independent vectors in ℝ³ span a plane, not all of ℝ³.",
            "0": "Span contains nonzero vectors.",
        },
    ),
    (
        "Orthogonality",
        "If Q is an orthogonal matrix, then QᵀQ equals…",
        "I",
        ["0", "Q", "Q²"],
        "Orthogonal means Qᵀ = Q⁻¹, so QᵀQ = I.",
        {
            "0": "Orthogonal matrices are invertible.",
            "Q": "Would imply Qᵀ = I, not generally true.",
            "Q²": "Not the defining identity.",
        },
    ),
    (
        "Least Squares",
        "Fitting a line y = a + bx to data points minimizes…",
        "Sum of squared vertical residuals",
        [
            "Sum of absolute x-coordinates",
            "Maximum single residual only",
            "Sum of squared x-values",
        ],
        "Ordinary least squares penalizes (yᵢ − a − bxᵢ)².",
        {
            "Sum of absolute x-coordinates": "Independent variable error is not the standard least-squares objective.",
            "Maximum single residual only": "That describes minimax (Chebyshev) fit, not least squares.",
            "Sum of squared x-values": "xᵢ are fixed inputs, not residuals.",
        },
    ),
    (
        "Vectors",
        "The cross product (0, 0, 1) × (0, 1, 0) in ℝ³ equals…",
        "(−1, 0, 0)",
        ["(1, 0, 0)", "(0, 0, −1)", "(0, 1, 1)"],
        "Standard right-hand rule: i × j = k, so k × j = −i.",
        {
            "(1, 0, 0)": "Sign reversed from k × j.",
            "(0, 0, −1)": "Result must be perpendicular to both factors — not along z.",
            "(0, 1, 1)": "Not orthogonal to (0,1,0).",
        },
    ),
    (
        "Matrices",
        "The transpose of [[1, 2, 3], [4, 5, 6]] is…",
        "[[1, 4], [2, 5], [3, 6]]",
        [
            "[[1, 2, 3], [4, 5, 6]]",
            "[[6, 5, 4], [3, 2, 1]]",
            "[[1, 2], [3, 4], [5, 6]]",
        ],
        "Transpose swaps rows and columns: 2 × 3 becomes 3 × 2.",
        {
            "[[1, 2, 3], [4, 5, 6]]": "Only symmetric matrices equal their transpose.",
            "[[6, 5, 4], [3, 2, 1]]": "That's a 180° reversal, not transpose.",
            "[[1, 2], [3, 4], [5, 6]]": "Wrong dimensions and entries.",
        },
    ),
]

HARD = [
    (
        "Row Reduction",
        "What is the rank of [[1, 2, 3], [2, 4, 6], [1, 1, 1]]?",
        "2",
        ["1", "3", "0"],
        "Row 2 equals 2× row 1; eliminating leaves two pivot rows — rank 2.",
        {
            "1": "Rows 1 and 3 are not multiples of each other.",
            "3": "Row 2 is dependent, so there cannot be three independent rows.",
            "0": "Matrix is nonzero.",
        },
    ),
    (
        "Determinants",
        "If A is 4 × 4 with det A = 5, then det(A⁻¹) equals…",
        "1/5",
        ["−5", "5", "1/625"],
        "det(A⁻¹) = 1/det A = 1/5.",
        {
            "−5": "Determinant of inverse is reciprocal, not negated.",
            "5": "That's det A, not det(A⁻¹).",
            "1/625": "Would be (det A)⁻⁴, not the correct exponent.",
        },
    ),
    (
        "Eigenvalues",
        "A 2 × 2 matrix with trace 5 and determinant 6 has eigenvalues…",
        "2 and 3",
        ["1 and 4", "5 and 6", "−2 and −3"],
        "Eigenvalues solve λ² − (tr)λ + det = λ² − 5λ + 6 = (λ−2)(λ−3).",
        {
            "1 and 4": "Sum 5 but product 4, not 6.",
            "5 and 6": "Confused trace and determinant with eigenvalues.",
            "−2 and −3": "Product would be 6 but sum would be −5, not 5.",
        },
    ),
    (
        "Linear Independence",
        "The dimension of the space of 2 × 2 symmetric matrices is…",
        "3",
        ["4", "2", "1"],
        "Symmetric 2 × 2 matrices depend on three parameters: two diagonal entries and one off-diagonal (equal top-right and bottom-left).",
        {
            "4": "That's all 2 × 2 matrices without symmetry.",
            "2": "Too few — diagonal and off-diagonal constraints need three degrees of freedom.",
            "1": "More than one independent symmetric matrix exists.",
        },
    ),
    (
        "Span",
        "The column space of a 3 × 2 matrix A with rank 2 in ℝ³ is…",
        "A plane through the origin (2-dimensional subspace)",
        [
            "All of ℝ³",
            "A line through the origin only",
            "The empty set",
        ],
        "Rank 2 with two columns means the two columns are independent and span a 2D subspace.",
        {
            "All of ℝ³": "Would require rank 3.",
            "A line through the origin only": "Would require rank 1.",
            "The empty set": "Column space always contains 0 and column vectors.",
        },
    ),
    (
        "Orthogonality",
        "If W is a subspace of ℝⁿ, then (W⊥)⊥ equals…",
        "W",
        ["ℝⁿ", "{0}", "W⊥"],
        "In finite-dimensional inner product spaces, double orthogonal complement returns W.",
        {
            "ℝⁿ": "Only true when W = {0} or W = ℝⁿ in special cases.",
            "{0}": "Only when W = ℝⁿ.",
            "W⊥": "One complement is not the double complement.",
        },
    ),
    (
        "Least Squares",
        "If the columns of A are orthonormal, the least-squares solution to Ax ≈ b is…",
        "x = Aᵀb",
        ["x = A⁻¹b", "x = b", "x = (AᵀA)⁻¹Aᵀb only when A is not orthonormal"],
        "With orthonormal columns, AᵀA = I and the normal equations reduce to x = Aᵀb.",
        {
            "x = A⁻¹b": "A is typically rectangular — no ordinary inverse.",
            "x = b": "b need not lie in the column space.",
            "x = (AᵀA)⁻¹Aᵀb only when A is not orthonormal": "That formula always holds; it simplifies to Aᵀb when columns are orthonormal.",
        },
    ),
    (
        "Vectors",
        "Let u, v be nonzero. ‖u + v‖ = ‖u‖ + ‖v‖ holds if and only if…",
        "u and v are nonnegative scalar multiples in the same direction",
        [
            "u and v are orthogonal",
            "u = −v",
            "Always for any u, v",
        ],
        "Triangle inequality is equality exactly when vectors are parallel and point the same way.",
        {
            "u and v are orthogonal": "Orthogonal nonzero vectors give strict inequality.",
            "u = −v": "Then u + v = 0, not full norm additivity of positive lengths in the same direction sense.",
            "Always for any u, v": "Triangle inequality is usually strict.",
        },
    ),
    (
        "Matrices",
        "If A is m × n with rank r, how many pivot columns appear in any echelon form of A?",
        "r",
        ["m", "n", "m + n"],
        "Pivot count equals rank — dimension of column space.",
        {
            "m": "Row count upper-bounds rank but pivots equal rank, not always m.",
            "n": "Column count can exceed rank when columns are dependent.",
            "m + n": "Not a standard invariant.",
        },
    ),
    (
        "Row Reduction",
        "The solution set of Ax = b with a particular solution xₚ and homogeneous solutions xₕ is…",
        "xₚ + null(A)",
        ["only xₚ", "null(A) only", "empty unless b = 0"],
        "Affine line/plane/hyperplane: translate the null space by any particular solution.",
        {
            "only xₚ": "Homogeneous solutions can be added when the null space is nontrivial.",
            "null(A) only": "Misses the particular solution shift unless b = 0.",
            "empty unless b = 0": "Consistent inhomogeneous systems have solutions.",
        },
    ),
    (
        "Determinants",
        "Swapping two rows of A multiplies det A by…",
        "−1",
        ["0", "1", "2"],
        "A single row interchange flips the sign of the determinant.",
        {
            "0": "Swapping rows does not zero the determinant unless it was already zero for other reasons.",
            "1": "Would mean determinant unchanged — false for one swap.",
            "2": "Scaling rows by 2 affects det differently from swapping.",
        },
    ),
    (
        "Eigenvalues",
        "A matrix A with Aᵀ = −A (real skew-symmetric, n odd) must have eigenvalue 0 because…",
        "det A = (−1)ⁿ det A forces det A = 0 when n is odd",
        [
            "All eigenvalues are positive",
            "A is always diagonal",
            "Trace equals sum of squares of entries",
        ],
        "For odd n, det A = −det A implies det A = 0, so 0 is an eigenvalue.",
        {
            "All eigenvalues are positive": "Skew-symmetric eigenvalues are purely imaginary (zero real part).",
            "A is always diagonal": "Skew-symmetric matrices are usually not diagonal.",
            "Trace equals sum of squares of entries": "Trace is zero for skew-symmetric A.",
        },
    ),
    (
        "Linear Independence",
        "If {v₁, v₂, v₃} is a basis of ℝ³ and T: ℝ³ → ℝ³ is linear with T(vᵢ) = eᵢ (standard basis), then T is…",
        "Invertible (an isomorphism)",
        [
            "The zero map",
            "Not linear",
            "Singular with rank 1",
        ],
        "Mapping a basis to a basis extends to an invertible linear transformation.",
        {
            "The zero map": "Sends basis vectors to eᵢ, not to 0.",
            "Not linear": "Given by linear extension from basis images.",
            "Singular with rank 1": "Rank 3 — spans all of ℝ³.",
        },
    ),
    (
        "Span",
        "The null space of [[1, 1, 0], [2, 2, 0]] is all vectors of the form…",
        "t(−1, 1, 0) + s(0, 0, 1)",
        [
            "only (0, 0, 0)",
            "t(1, 1, 0)",
            "all of ℝ³ with no restriction",
        ],
        "x₁ + x₂ = 0 gives x₂ = −x₁; x₃ is free — two-parameter family.",
        {
            "only (0, 0, 0)": "Free variables yield infinitely many solutions.",
            "t(1, 1, 0)": "Violates x₁ + x₂ = 0 unless t = 0.",
            "all of ℝ³ with no restriction": "Equation x₁ + x₂ = 0 restricts the first two coordinates.",
        },
    ),
    (
        "Orthogonality",
        "The matrix of the orthogonal projection onto the line spanned by unit vector u is…",
        "uuᵀ",
        ["uᵀu", "I − uuᵀ", "uu"],
        "P = u(uᵀ) for unit u; (uᵀx)u = (uuᵀ)x.",
        {
            "uᵀu": "That's the scalar 1 for unit u, not the projection matrix.",
            "I − uuᵀ": "That's projection onto the orthogonal complement.",
            "uu": "Missing transpose — wrong dimensions for ℝⁿ.",
        },
    ),
    (
        "Least Squares",
        "Multicollinearity (nearly dependent columns of A) in least squares mainly harms…",
        "Numerical stability of (AᵀA)⁻¹Aᵀb",
        [
            "Existence of a minimizer",
            "Linearity of the model",
            "The fact that residuals are perpendicular to Col(A)",
        ],
        "AᵀA becomes ill-conditioned; small data changes swing coefficients even though a minimizer exists.",
        {
            "Existence of a minimizer": "A least-squares minimizer still exists.",
            "Linearity of the model": "The model remains linear in parameters.",
            "The fact that residuals are perpendicular to Col(A)": "Geometry of the residual stays; coefficient estimates become unstable.",
        },
    ),
    (
        "Vectors",
        "The reflection of vector x across the line spanned by unit u is…",
        "2(uᵀx)u − x",
        ["x − 2(uᵀx)u", "2x − u", "(uᵀx)u"],
        "Reflect = 2·proj_u x − x = 2uuᵀx − x.",
        {
            "x − 2(uᵀx)u": "That's reflection across the orthogonal complement hyperplane.",
            "2x − u": "Not the standard reflection formula.",
            "(uᵀx)u": "That's projection onto u, not reflection.",
        },
    ),
    (
        "Matrices",
        "If A has singular value decomposition A = UΣVᵀ with Σ diagonal nonnegative, then ‖A‖₂ (operator 2-norm) equals…",
        "The largest singular value σ₁",
        ["The smallest singular value", "det A", "trace A"],
        "The spectral norm equals the top singular value.",
        {
            "The smallest singular value": "That's related to the smallest stretch, not the maximum.",
            "det A": "Only defined for square A and not the operator norm.",
            "trace A": "Not the maximum stretch factor.",
        },
    ),
    (
        "Row Reduction",
        "For inconsistent system [A|b], a least-squares solution minimizes ‖Ax − b‖. Geometrically, Ax is the orthogonal projection of b onto…",
        "Col(A)",
        ["Null(A)", "Row(A)", "ℝⁿ"],
        "The closest point in the column space is the orthogonal projection of b.",
        {
            "Null(A)": "Null space contains only vectors mapped to 0, not approximations to b.",
            "Row(A)": "Row space lives in domain space ℝⁿ, not target space where b lies.",
            "ℝⁿ": "Too large unless A is square and invertible — generally b's closest point is in Col(A) ⊂ ℝᵐ.",
        },
    ),
    (
        "Determinants",
        "An n × n matrix A is singular if and only if…",
        "det A = 0",
        ["trace A = 0", "A has a zero row", "A is not symmetric"],
        "Invertibility and nonzero determinant are equivalent for square matrices.",
        {
            "trace A = 0": "Trace zero does not imply singularity.",
            "A has a zero row": "Sufficient for singularity but not equivalent — singular matrices may have no zero row.",
            "A is not symmetric": "Many nonsymmetric matrices are invertible.",
        },
    ),
]

BOOK = make_book(
    title="Linear Algebra",
    parent_topic="Mathematics",
    subtopic="Linear Algebra",
    slug="linear-algebra-hefferon",
    source_url="https://hefferon.net/linearalgebra/",
    easy=EASY,
    medium=MEDIUM,
    hard=HARD,
)
