"""Quiz bank: LOGIC."""
from quiz_banks._common import Book, Q

LOGIC = Book(
    title="forall x: Calgary",
    parent_topic="Philosophy & Psychology",
    subtopic="Logic",
    slug="logic-forallx-calgary",
    source_url="https://openlogicproject.org/",
    easy=[
        Q("Propositional Logic",
          "Which of these is a tautology?",
          "P ∨ ¬P",
          ["P ∧ ¬P", "P → ¬P", "P ↔ ¬P"],
          "The law of excluded middle: any proposition is either true or false, so P ∨ ¬P is always true.",
          {"P ∧ ¬P": "That's a contradiction — always false.",
           "P → ¬P": "True only when P is false.",
           "P ↔ ¬P": "Always false (a proposition can't be equivalent to its own negation)."}),
        Q("Propositional Logic",
          "What does the connective ∧ stand for?",
          "Conjunction (and).",
          ["Disjunction (or).",
           "Implication (if-then).",
           "Negation (not)."],
          "P ∧ Q is true exactly when both P and Q are true.",
          {"Disjunction (or).": "That's ∨.",
           "Implication (if-then).": "That's →.",
           "Negation (not).": "That's ¬."}),
        Q("Truth Tables",
          "The truth table for P → Q is false in exactly which case?",
          "P is true and Q is false.",
          ["P is true and Q is true.",
           "P is false and Q is true.",
           "P is false and Q is false."],
          "Material implication is true except when a true antecedent leads to a false consequent.",
          {"P is true and Q is true.": "True — antecedent and consequent both hold.",
           "P is false and Q is true.": "Vacuously true.",
           "P is false and Q is false.": "Vacuously true."}),
        Q("Truth Tables",
          "P ↔ Q is true exactly when…",
          "P and Q have the same truth value.",
          ["At least one of P or Q is true.",
           "Both P and Q are true.",
           "Both P and Q are false."],
          "Biconditional is equivalence: both true or both false.",
          {"At least one of P or Q is true.": "That's disjunction.",
           "Both P and Q are true.": "That's only half of the biconditional's true cases.",
           "Both P and Q are false.": "Also only half."}),
        Q("Logical Equivalence",
          "Which is logically equivalent to ¬(P ∧ Q)?",
          "¬P ∨ ¬Q",
          ["¬P ∧ ¬Q", "P ∨ Q", "P → Q"],
          "De Morgan's law: the negation of a conjunction is the disjunction of negations.",
          {"¬P ∧ ¬Q": "That's the negation of (P ∨ Q), not (P ∧ Q).",
           "P ∨ Q": "Unrelated.",
           "P → Q": "Not equivalent to ¬(P ∧ Q)."}),
        Q("Logical Equivalence",
          "P → Q is logically equivalent to which of the following?",
          "¬P ∨ Q",
          ["P ∧ Q", "¬(P ∧ Q)", "Q → P"],
          "Material implication is true unless P is true and Q is false — same truth table as ¬P ∨ Q.",
          {"P ∧ Q": "Far stricter than implication.",
           "¬(P ∧ Q)": "False only when both are true — wrong table.",
           "Q → P": "That's the converse; not equivalent in general."}),
        Q("Validity",
          "An argument is valid if and only if…",
          "It is impossible for the premises to be true and the conclusion false.",
          ["The premises are true.",
           "The conclusion is true.",
           "It uses only true premises."],
          "Validity is about preservation of truth from premises to conclusion, not about whether premises are actually true.",
          {"The premises are true.": "That's soundness combined with validity.",
           "The conclusion is true.": "Valid arguments can have false conclusions when premises are false.",
           "It uses only true premises.": "That's about soundness too."}),
        Q("Validity",
          "A sound argument is one that is…",
          "Valid and has all true premises.",
          ["Valid only.",
           "Has a true conclusion.",
           "Uses no quantifiers."],
          "Soundness requires both validity and actually true premises; this guarantees a true conclusion.",
          {"Valid only.": "Validity alone allows false premises.",
           "Has a true conclusion.": "A true conclusion can come from invalid reasoning.",
           "Uses no quantifiers.": "Quantifiers don't bear on soundness."}),
        Q("Predicate Logic",
          "In first-order logic, ∀x F(x) means…",
          "Every element of the domain has property F.",
          ["Some element has property F.",
           "Exactly one element has property F.",
           "No element has property F."],
          "Universal quantification: F(x) holds for all x in the domain.",
          {"Some element has property F.": "That's ∃x F(x).",
           "Exactly one element has property F.": "That's ∃!x F(x).",
           "No element has property F.": "That's ¬∃x F(x)."}),
        Q("Predicate Logic",
          "∃x F(x) is logically equivalent to…",
          "¬∀x ¬F(x).",
          ["∀x F(x).",
           "¬∀x F(x).",
           "∀x ¬F(x)."],
          "Quantifier interchange: 'some F' iff 'not all are non-F'.",
          {"∀x F(x).": "Far too strong.",
           "¬∀x F(x).": "That means 'some non-F', not 'some F'.",
           "∀x ¬F(x).": "That means 'no F'."}),
        Q("Inference Rules",
          "From P → Q and P, we may conclude Q. This rule is called…",
          "Modus ponens.",
          ["Modus tollens.",
           "Disjunctive syllogism.",
           "Conjunction introduction."],
          "MP is the basic rule for eliminating implications.",
          {"Modus tollens.": "MT goes from P → Q and ¬Q to ¬P.",
           "Disjunctive syllogism.": "DS uses disjunctions: P ∨ Q and ¬P give Q.",
           "Conjunction introduction.": "That introduces ∧, not eliminating →."}),
        Q("Inference Rules",
          "From P → Q and ¬Q, we may conclude ¬P. This rule is called…",
          "Modus tollens.",
          ["Modus ponens.",
           "Hypothetical syllogism.",
           "Reductio ad absurdum."],
          "MT contrapositive reasoning.",
          {"Modus ponens.": "MP needs P, not ¬Q.",
           "Hypothetical syllogism.": "HS chains two implications.",
           "Reductio ad absurdum.": "RAA derives a contradiction to refute an assumption."}),
        Q("Propositional Logic",
          "How many rows does the truth table of a formula with n distinct atomic propositions have?",
          "2^n",
          ["n", "n²", "n!"],
          "Each atomic proposition can be T or F independently.",
          {"n": "Underestimates the number of distinct valuations.",
           "n²": "Not how combinations grow.",
           "n!": "Permutation count, not assignment count."}),
        Q("Propositional Logic",
          "Which formula is a contradiction?",
          "P ∧ ¬P",
          ["P ∨ ¬P",
           "P → P",
           "P ↔ P"],
          "A proposition can't be true and false simultaneously.",
          {"P ∨ ¬P": "Tautology.",
           "P → P": "Tautology — implication from any P to itself.",
           "P ↔ P": "Tautology."}),
        Q("Logical Equivalence",
          "The contrapositive of P → Q is…",
          "¬Q → ¬P.",
          ["Q → P.",
           "¬P → ¬Q.",
           "P → ¬Q."],
          "Contrapositive is logically equivalent to the original implication.",
          {"Q → P.": "That's the converse — not equivalent.",
           "¬P → ¬Q.": "That's the inverse — not equivalent.",
           "P → ¬Q.": "That's the negation of the consequent, not contrapositive."}),
        Q("Validity",
          "Affirming the consequent is the invalid pattern:",
          "From P → Q and Q, infer P.",
          ["From P → Q and P, infer Q.",
           "From P → Q and ¬Q, infer ¬P.",
           "From P → Q and ¬P, infer ¬Q."],
          "Q can be true for many reasons besides P; assuming P is a fallacy.",
          {"From P → Q and P, infer Q.": "Modus ponens — valid.",
           "From P → Q and ¬Q, infer ¬P.": "Modus tollens — valid.",
           "From P → Q and ¬P, infer ¬Q.": "Denying the antecedent — also invalid, but different from affirming the consequent."}),
        Q("Predicate Logic",
          "¬∃x F(x) is logically equivalent to…",
          "∀x ¬F(x).",
          ["∃x ¬F(x).",
           "¬∀x F(x).",
           "∀x F(x)."],
          "Quantifier negation: 'no F exists' iff 'every x is non-F'.",
          {"∃x ¬F(x).": "That's 'some non-F exists', not 'no F exists'.",
           "¬∀x F(x).": "That's 'some non-F' (in disguise).",
           "∀x F(x).": "Opposite of the original."}),
        Q("Truth Tables",
          "P ∨ Q is false exactly when…",
          "Both P and Q are false.",
          ["At least one is false.",
           "P is true.",
           "P and Q are the same."],
          "Disjunction is inclusive: at least one true makes it true.",
          {"At least one is false.": "The other could still be true.",
           "P is true.": "That makes the disjunction true.",
           "P and Q are the same.": "Could be both true or both false."}),
        Q("Predicate Logic",
          "A free variable in a formula is one that…",
          "Is not bound by a quantifier within the formula.",
          ["Has no value assigned in any model.",
           "Appears more than once.",
           "Is preceded by ¬."],
          "Free variables stand in for arbitrary objects; sentences (no free variables) are what get truth values.",
          {"Has no value assigned in any model.": "Models do assign values; free variables are just not bound in the formula.",
           "Appears more than once.": "Multiplicity doesn't matter for being free.",
           "Is preceded by ¬.": "Negation doesn't affect binding."}),
        Q("Inference Rules",
          "From P ∨ Q and ¬P, we may conclude Q. This rule is called…",
          "Disjunctive syllogism.",
          ["Modus ponens.",
           "Conjunction elimination.",
           "Existential introduction."],
          "Disjunctive syllogism uses one disjunct's falsity to assert the other.",
          {"Modus ponens.": "MP works on implications, not disjunctions.",
           "Conjunction elimination.": "That uses ∧, not ∨.",
           "Existential introduction.": "That's about quantifiers."}),
    ],
    medium=[
        Q("Logical Equivalence",
          "Which of the following is logically equivalent to (P → Q) ∧ (Q → P)?",
          "P ↔ Q",
          ["P ∧ Q", "P ∨ Q", "¬(P ↔ Q)"],
          "Biconditional is defined as the conjunction of an implication and its converse.",
          {"P ∧ Q": "True only when both are true; biconditional also accepts both false.",
           "P ∨ Q": "Doesn't require the truth values to match.",
           "¬(P ↔ Q)": "The negation of the biconditional, the opposite."}),
        Q("Validity",
          "An argument is logically valid iff…",
          "Its conclusion is true in every model where its premises are true.",
          ["Its conclusion is true in every model.",
           "Its premises are true in every model.",
           "It is short."],
          "Validity is semantic preservation: no countermodel where premises hold and conclusion fails.",
          {"Its conclusion is true in every model.": "That makes the conclusion a tautology — stronger than validity of an argument.",
           "Its premises are true in every model.": "That makes premises tautologies, also stronger.",
           "It is short.": "Length is irrelevant."}),
        Q("Predicate Logic",
          "∀x ∃y R(x, y) and ∃y ∀x R(x, y) differ in that the second…",
          "Requires a single y that works for every x.",
          ["Is logically equivalent to the first.",
           "Is always false.",
           "Cannot be expressed in first-order logic."],
          "Order of quantifiers matters: 'some y works for all x' is strictly stronger than 'for every x, some y'.",
          {"Is logically equivalent to the first.": "They're not equivalent in general.",
           "Is always false.": "It depends on R.",
           "Cannot be expressed in first-order logic.": "Both are first-order."}),
        Q("Truth Tables",
          "Which formula has the same truth table as P ↔ ¬Q?",
          "¬(P ↔ Q)",
          ["P → Q", "P ∧ ¬Q", "P ∨ Q"],
          "Both are true exactly when P and Q have different truth values.",
          {"P → Q": "Has a different table.",
           "P ∧ ¬Q": "Only true when P true and Q false; the biconditional with ¬Q also accepts P false, Q true.",
           "P ∨ Q": "Different table."}),
        Q("Proof",
          "Proof by contradiction (reductio ad absurdum) works by…",
          "Assuming ¬P, deriving a contradiction, and concluding P.",
          ["Assuming P and showing it's true.",
           "Listing all possible cases.",
           "Constructing an example."],
          "RAA exploits the law of non-contradiction.",
          {"Assuming P and showing it's true.": "That's circular.",
           "Listing all possible cases.": "That's proof by cases.",
           "Constructing an example.": "That's a direct example/construction."}),
        Q("Predicate Logic",
          "An interpretation (model) for a first-order language must specify…",
          "A non-empty domain and an assignment to each predicate, function symbol, and constant.",
          ["Only truth values for atomic sentences.",
           "Only a domain.",
           "Only the truth value of ⊥."],
          "Truth of a sentence is defined relative to a complete interpretation.",
          {"Only truth values for atomic sentences.": "Atomic truth depends on the underlying interpretation.",
           "Only a domain.": "You also need to interpret the non-logical symbols.",
           "Only the truth value of ⊥.": "⊥ is logically false in every model."}),
        Q("Inference Rules",
          "Universal instantiation lets you conclude…",
          "F(c) from ∀x F(x), for any term c in the language.",
          ["∀x F(x) from F(c).",
           "∃x F(x) from F(c).",
           "¬F(c) from ∀x F(x)."],
          "UI eliminates a universal by picking any term.",
          {"∀x F(x) from F(c).": "That's universal generalization (with side conditions).",
           "∃x F(x) from F(c).": "That's existential introduction.",
           "¬F(c) from ∀x F(x).": "Wrong direction."}),
        Q("Inference Rules",
          "Existential instantiation: from ∃x F(x), you may assume F(c) for a fresh constant c. The 'fresh' restriction is required because…",
          "Without it, you could illicitly identify the existential witness with previously-used terms.",
          ["The system uses only finite proofs.",
           "Constants must always be fresh in logic.",
           "Otherwise the deduction is too long."],
          "EI introduces a temporary name for an unknown witness; reusing names would over-specify.",
          {"The system uses only finite proofs.": "Length isn't the reason.",
           "Constants must always be fresh in logic.": "Other rules allow reuse.",
           "Otherwise the deduction is too long.": "Length is unrelated to soundness."}),
        Q("Logical Equivalence",
          "The formula ¬∀x F(x) is logically equivalent to…",
          "∃x ¬F(x).",
          ["∀x ¬F(x).",
           "¬∃x F(x).",
           "∃x F(x)."],
          "Negating a universal yields an existential of the negation.",
          {"∀x ¬F(x).": "That's the negation of an existential, not a universal.",
           "¬∃x F(x).": "Equivalent to ∀x ¬F(x), not to ¬∀x F(x).",
           "∃x F(x).": "Doesn't account for the outer negation."}),
        Q("Validity",
          "A countermodel to an argument is…",
          "An interpretation in which all premises are true and the conclusion is false.",
          ["An interpretation in which all premises are false.",
           "An interpretation in which the conclusion is true.",
           "Any model of the conclusion."],
          "A single countermodel suffices to show invalidity.",
          {"An interpretation in which all premises are false.": "That doesn't show invalidity.",
           "An interpretation in which the conclusion is true.": "Conclusion truth doesn't matter for invalidity.",
           "Any model of the conclusion.": "Models of the conclusion alone tell us nothing about validity."}),
        Q("Propositional Logic",
          "Conjunctive Normal Form (CNF) expresses a formula as…",
          "A conjunction of disjunctions of literals.",
          ["A disjunction of conjunctions of literals.",
           "A list of equivalences.",
           "A single implication."],
          "CNF is the canonical form for SAT solvers and resolution.",
          {"A disjunction of conjunctions of literals.": "That's DNF.",
           "A list of equivalences.": "Not a standard normal form.",
           "A single implication.": "Doesn't generalize."}),
        Q("Logical Equivalence",
          "¬(P → Q) is logically equivalent to…",
          "P ∧ ¬Q.",
          ["¬P ∨ Q.",
           "¬P ∧ ¬Q.",
           "Q → P."],
          "P → Q is false iff P is true and Q is false; that's exactly P ∧ ¬Q.",
          {"¬P ∨ Q.": "That's P → Q itself, not its negation.",
           "¬P ∧ ¬Q.": "True only when both are false.",
           "Q → P.": "Different table."}),
        Q("Predicate Logic",
          "In ∀x (P(x) → Q(x)), the variable x is…",
          "Bound by ∀x throughout the entire scope.",
          ["Free.",
           "Both free and bound.",
           "Undefined."],
          "x appears under the scope of ∀x, so it's bound.",
          {"Free.": "It would be free outside the quantifier's scope.",
           "Both free and bound.": "Inside this formula, x is bound.",
           "Undefined.": "It's defined as bound by ∀x."}),
        Q("Inference Rules",
          "From P, infer P ∨ Q for any Q. This rule is…",
          "Disjunction introduction (∨I).",
          ["Disjunction elimination.",
           "Conjunction introduction.",
           "Existential introduction."],
          "Adding a disjunct to a known truth preserves truth.",
          {"Disjunction elimination.": "That uses a disjunction to derive something else.",
           "Conjunction introduction.": "That builds ∧.",
           "Existential introduction.": "That's a quantifier rule."}),
        Q("Proof",
          "Conditional proof / →-introduction lets you derive P → Q by…",
          "Assuming P in a subproof and deriving Q, then discharging the assumption.",
          ["Assuming Q and deriving P.",
           "Showing P is a tautology.",
           "Showing Q is a tautology."],
          "Standard deduction theorem rule: assume the antecedent, prove the consequent, conclude the implication.",
          {"Assuming Q and deriving P.": "Wrong direction.",
           "Showing P is a tautology.": "Not how → is introduced.",
           "Showing Q is a tautology.": "Q being a tautology gives → trivially, but isn't the general rule."}),
        Q("Predicate Logic",
          "Universal generalization allows you to conclude ∀x F(x) from F(c) provided…",
          "c is arbitrary — it does not appear in the assumptions or in F(x).",
          ["c is a specific constant in the language.",
           "F(c) is a premise.",
           "x is bound elsewhere."],
          "The constant must not be 'tainted' by other commitments; this guarantees the proof works for any object.",
          {"c is a specific constant in the language.": "Specific constants can't be generalized this freely.",
           "F(c) is a premise.": "Premises can't be universally generalized.",
           "x is bound elsewhere.": "Binding elsewhere is irrelevant."}),
        Q("Validity",
          "A logical consequence relation ⊨ is defined so that Γ ⊨ φ iff…",
          "Every model that makes all of Γ true also makes φ true.",
          ["Some model makes all of Γ true and φ true.",
           "φ is provable from Γ in some proof system.",
           "Γ and φ have the same truth value."],
          "Semantic entailment is preservation of truth across all models.",
          {"Some model makes all of Γ true and φ true.": "That's joint satisfiability, not entailment.",
           "φ is provable from Γ in some proof system.": "That's syntactic consequence (⊢); they coincide by soundness/completeness.",
           "Γ and φ have the same truth value.": "Not a standard logical relation."}),
        Q("Inference Rules",
          "Hypothetical syllogism is the rule…",
          "From P → Q and Q → R, infer P → R.",
          ["From P → Q and ¬Q, infer ¬P.",
           "From P ∧ Q, infer P.",
           "From P ∨ Q and ¬P, infer Q."],
          "Chaining implications.",
          {"From P → Q and ¬Q, infer ¬P.": "That's modus tollens.",
           "From P ∧ Q, infer P.": "Conjunction elimination.",
           "From P ∨ Q and ¬P, infer Q.": "Disjunctive syllogism."}),
        Q("Predicate Logic",
          "First-order logic is undecidable in the following sense:",
          "There is no algorithm that, given any formula, decides whether it is valid.",
          ["No formulas are valid.",
           "Every valid formula is also satisfiable.",
           "First-order logic has no models."],
          "Church and Turing's undecidability theorem: validity in FOL is recursively enumerable but not decidable.",
          {"No formulas are valid.": "Many are.",
           "Every valid formula is also satisfiable.": "True but not what undecidability means.",
           "First-order logic has no models.": "False; it has many."}),
        Q("Soundness",
          "A proof system is sound if…",
          "Every derivable formula is logically valid.",
          ["Every valid formula is derivable.",
           "It contains all axioms of arithmetic.",
           "It has finitely many rules."],
          "Soundness ⊢ ⇒ ⊨: provability respects truth.",
          {"Every valid formula is derivable.": "That's completeness.",
           "It contains all axioms of arithmetic.": "Soundness is a logic property, not arithmetic.",
           "It has finitely many rules.": "Finite rules don't imply soundness."}),
    ],
    hard=[
        Q("Soundness",
          "Gödel's completeness theorem (for first-order logic) says…",
          "Every logically valid formula is provable in standard proof systems.",
          ["Every theorem of arithmetic is true.",
           "First-order logic is decidable.",
           "Every true formula has a finite proof."],
          "Together with soundness, completeness gives ⊨ ⇔ ⊢ for FOL.",
          {"Every theorem of arithmetic is true.": "That's incompleteness-adjacent territory.",
           "First-order logic is decidable.": "It isn't.",
           "Every true formula has a finite proof.": "Only formulas valid in all models do."}),
        Q("Validity",
          "Compactness theorem: a set Γ of first-order formulas is satisfiable iff…",
          "Every finite subset of Γ is satisfiable.",
          ["Γ is finite.",
           "Γ is decidable.",
           "Γ contains a tautology."],
          "Compactness has rich consequences: existence of non-standard models of arithmetic, Löwenheim–Skolem applications, etc.",
          {"Γ is finite.": "Finiteness isn't required.",
           "Γ is decidable.": "Decidability is irrelevant.",
           "Γ contains a tautology.": "Tautologies are trivially satisfiable but don't characterize compactness."}),
        Q("Predicate Logic",
          "Löwenheim–Skolem (downward) says that every satisfiable first-order theory in a countable language has…",
          "A countable model.",
          ["Only finite models.",
           "Only uncountable models.",
           "Exactly one model."],
          "Downward LS guarantees a countable model, even for theories aiming at uncountable structures (Skolem's paradox).",
          {"Only finite models.": "First-order theories can have infinite models.",
           "Only uncountable models.": "Opposite of the theorem.",
           "Exactly one model.": "First-order theories with infinite models have many models of each cardinality."}),
        Q("Soundness",
          "Gödel's first incompleteness theorem applies to…",
          "Any consistent, recursively axiomatized theory strong enough to express elementary arithmetic.",
          ["Every formal theory whatsoever.",
           "Only Peano Arithmetic.",
           "Propositional logic."],
          "Incompleteness needs enough arithmetic for self-reference; weaker systems (e.g., presburger arithmetic) are complete.",
          {"Every formal theory whatsoever.": "Some theories are complete (e.g., the theory of real closed fields).",
           "Only Peano Arithmetic.": "It applies more broadly.",
           "Propositional logic.": "Propositional logic is complete and decidable."}),
        Q("Inference Rules",
          "Resolution is a refutation-complete proof method for…",
          "First-order logic restricted to clausal (CNF) form.",
          ["Modal logic only.",
           "Higher-order logic.",
           "Intuitionistic logic only."],
          "Resolution proves Γ ⊨ φ by deriving the empty clause from Γ ∪ {¬φ} in CNF.",
          {"Modal logic only.": "Modal logics need different proof systems.",
           "Higher-order logic.": "HOL isn't complete in general.",
           "Intuitionistic logic only.": "Resolution is classical."}),
        Q("Predicate Logic",
          "An n-ary relation R on a domain D is interpreted in a model as…",
          "A subset of D^n.",
          ["A function from D to D.",
           "An element of D.",
           "A formula in the language."],
          "Relations correspond to sets of tuples.",
          {"A function from D to D.": "That's a unary function.",
           "An element of D.": "That's a constant.",
           "A formula in the language.": "Formulas are syntax; relations are semantics."}),
        Q("Propositional Logic",
          "The propositional SAT problem is NP-complete. Which transformation is canonical for the reduction?",
          "Cook's reduction: encoding any nondeterministic Turing machine's accepting computation as a CNF formula.",
          ["Reducing 3-coloring to SAT via Kempe chains.",
           "Showing SAT is in P-complete.",
           "Reducing SAT to QBF."],
          "Cook's theorem (1971) showed SAT is NP-complete via direct simulation of NDTMs.",
          {"Reducing 3-coloring to SAT via Kempe chains.": "That's a reduction from 3-coloring, but Cook–Levin is the seminal NP-completeness proof.",
           "Showing SAT is in P-complete.": "P-completeness is for log-space reductions, not NP.",
           "Reducing SAT to QBF.": "That places SAT in PSPACE, but doesn't show NP-completeness."}),
        Q("Logical Equivalence",
          "Two formulas φ and ψ are logically equivalent iff…",
          "They have the same truth value in every model.",
          ["They have the same number of connectives.",
           "They share a propositional letter.",
           "One implies the other."],
          "Equivalence is mutual entailment: φ ⊨ ψ and ψ ⊨ φ.",
          {"They have the same number of connectives.": "Syntactic length is irrelevant.",
           "They share a propositional letter.": "Sharing letters doesn't imply equivalence.",
           "One implies the other.": "That's one-way entailment, not equivalence."}),
        Q("Predicate Logic",
          "Skolemization eliminates existential quantifiers by…",
          "Replacing existentially-quantified variables with fresh function symbols of the surrounding universal variables.",
          ["Removing them entirely.",
           "Converting them to disjunctions.",
           "Replacing them with new constants only, regardless of context."],
          "If ∀x ∃y R(x, y), Skolemize to ∀x R(x, f(x)) where f is a new function.",
          {"Removing them entirely.": "Just dropping ∃ changes meaning.",
           "Converting them to disjunctions.": "That's not Skolemization.",
           "Replacing them with new constants only, regardless of context.": "Constants only suffice when no enclosing ∀; in general you need functions."}),
        Q("Modal Logic",
          "In modal logic, □P is read as 'necessarily P'. In Kripke semantics, □P holds at world w iff…",
          "P holds at every world accessible from w.",
          ["P holds at some world accessible from w.",
           "P holds at w.",
           "P is a tautology."],
          "The accessibility relation R determines which worlds are 'reachable'; □ is universal over them.",
          {"P holds at some world accessible from w.": "That's ◇P (possibility).",
           "P holds at w.": "Modal operators look beyond the current world.",
           "P is a tautology.": "Tautologies are necessary in every system, but □P generally isn't a tautology."}),
        Q("Validity",
          "Łoś's theorem about ultraproducts implies which classical result?",
          "The compactness theorem of first-order logic.",
          ["Gödel's incompleteness theorems.",
           "The Church–Turing thesis.",
           "Tarski's truth definition."],
          "Łoś's theorem gives a slick model-theoretic proof of compactness via ultraproducts.",
          {"Gödel's incompleteness theorems.": "Different territory entirely.",
           "The Church–Turing thesis.": "Computability, not model theory.",
           "Tarski's truth definition.": "Tarski's work is foundational but separate."}),
        Q("Proof",
          "Sequent calculus's cut rule is admissible in classical logic, which means…",
          "Any proof using cut can be transformed into a cut-free proof.",
          ["Cut cannot be applied at all.",
           "Cut creates inconsistency.",
           "Cut implies completeness."],
          "Gentzen's Hauptsatz: cut elimination yields the subformula property, useful for proof analysis.",
          {"Cut cannot be applied at all.": "Cut is a legal rule; it's just removable.",
           "Cut creates inconsistency.": "It doesn't.",
           "Cut implies completeness.": "Cut elimination is a structural result."}),
        Q("Soundness",
          "A first-order theory is consistent iff…",
          "It has at least one model.",
          ["It is finite.",
           "It contains the law of excluded middle.",
           "It is complete."],
          "Gödel's completeness theorem: consistency (syntactic) ⇔ satisfiability (semantic).",
          {"It is finite.": "Theories can be infinite.",
           "It contains the law of excluded middle.": "Classical theories typically do, but consistency is independent.",
           "It is complete.": "Consistency and completeness are different."}),
        Q("Predicate Logic",
          "Robinson Arithmetic Q is weaker than Peano Arithmetic in that…",
          "It lacks the induction schema.",
          ["It has no successor function.",
           "It uses second-order quantifiers.",
           "It has no equality."],
          "Q is finitely axiomatized and still allows Gödel's incompleteness theorem to apply.",
          {"It has no successor function.": "It has S.",
           "It uses second-order quantifiers.": "Q is first-order.",
           "It has no equality.": "Q has equality."}),
        Q("Inference Rules",
          "Natural deduction's reductio rule lets you conclude ¬P from a subproof in which P leads to ⊥. This rule is…",
          "Negation introduction (¬I).",
          ["Negation elimination.",
           "Modus ponens.",
           "Conjunction elimination."],
          "¬I packages a contradiction-from-assumption into a negation.",
          {"Negation elimination.": "That's how ¬ is used, not introduced.",
           "Modus ponens.": "MP eliminates →.",
           "Conjunction elimination.": "That works on ∧."}),
        Q("Validity",
          "Two formulas φ, ψ are interderivable iff…",
          "φ ⊢ ψ and ψ ⊢ φ in the chosen proof system.",
          ["They are syntactically identical.",
           "Both are tautologies.",
           "Both have the same length."],
          "Interderivability is the syntactic counterpart of equivalence.",
          {"They are syntactically identical.": "Identity is far stricter.",
           "Both are tautologies.": "Both being tautologies makes them equivalent vacuously, but interderivability is stronger relational notion.",
           "Both have the same length.": "Length doesn't matter."}),
        Q("Propositional Logic",
          "Tarski's truth definition for first-order logic is recursive on…",
          "The structure of formulas, using variable assignments.",
          ["Possible worlds.",
           "Type levels.",
           "Step numbers in a derivation."],
          "T-schema-style recursion: define satisfaction over atomic, then connectives and quantifiers.",
          {"Possible worlds.": "That's Kripke semantics for modal logic.",
           "Type levels.": "Type theory is a different framework.",
           "Step numbers in a derivation.": "That's proof-theoretic, not semantic."}),
        Q("Soundness",
          "Why is propositional logic decidable while first-order logic is not?",
          "Truth in propositional logic can be checked by enumerating 2^n valuations; first-order quantification ranges over potentially infinite domains.",
          ["First-order logic has too many connectives.",
           "Propositional logic has no models.",
           "Propositional logic uses 1-ary predicates."],
          "The undecidability of FOL is a corollary of Church and Turing's work.",
          {"First-order logic has too many connectives.": "Connective count is finite.",
           "Propositional logic has no models.": "It does — valuations are models.",
           "Propositional logic uses 1-ary predicates.": "Propositional logic has no predicates or variables."}),
        Q("Predicate Logic",
          "If a first-order theory has an infinite model, then by the Löwenheim–Skolem theorems it has…",
          "Models of every infinite cardinality.",
          ["Only one infinite model up to isomorphism.",
           "Only finite models.",
           "A model whose cardinality is a prime."],
          "Upward + downward LS together give models of every infinite cardinality ≥ |language|.",
          {"Only one infinite model up to isomorphism.": "Categoricity in all cardinalities is impossible by LS.",
           "Only finite models.": "Opposite.",
           "A model whose cardinality is a prime.": "Arbitrary."}),
        Q("Modal Logic",
          "The modal axiom T (□P → P) corresponds to the property of the accessibility relation being…",
          "Reflexive.",
          ["Symmetric.",
           "Transitive.",
           "Functional."],
          "Sahlqvist correspondence: T ↔ reflexive, 4 ↔ transitive, 5 ↔ Euclidean, B ↔ symmetric.",
          {"Symmetric.": "That's axiom B.",
           "Transitive.": "That's axiom 4.",
           "Functional.": "That gives a different axiom."}),
    ],
)

BOOK = LOGIC
