"""Quiz bank: MACHINE_LEARNING."""
from quiz_banks._common import Book, Q

MACHINE_LEARNING = Book(
    title="Dive into Deep Learning",
    parent_topic="AI & Machine Learning",
    subtopic="Machine Learning",
    slug="machine-learning-d2l",
    source_url="https://d2l.ai/",
    easy=[
        Q("Supervised Learning",
          "What distinguishes supervised from unsupervised learning?",
          "Supervised learning trains on labeled examples; unsupervised does not.",
          ["Supervised uses neural networks; unsupervised uses decision trees.",
           "Supervised is faster than unsupervised.",
           "Supervised requires GPUs; unsupervised runs on CPU."],
          "Supervised learning fits a function from inputs to labels using (x, y) pairs; unsupervised methods (clustering, density estimation) work from x alone.",
          {"Supervised uses neural networks; unsupervised uses decision trees.": "Both paradigms use both model families.",
           "Supervised is faster than unsupervised.": "Speed isn't a defining trait.",
           "Supervised requires GPUs; unsupervised runs on CPU.": "Hardware doesn't define the learning paradigm."}),
        Q("Loss Functions",
          "Mean squared error penalizes prediction errors how?",
          "Quadratically — larger errors hurt disproportionately more.",
          ["Linearly — every error counts the same per unit.",
           "Logarithmically — large errors are softened.",
           "Not at all — MSE measures variance, not error."],
          "MSE is the average of squared residuals; doubling an error quadruples its contribution.",
          {"Linearly — every error counts the same per unit.": "That describes mean absolute error (L1).",
           "Logarithmically — large errors are softened.": "MSE amplifies, not softens, large errors.",
           "Not at all — MSE measures variance, not error.": "MSE measures error directly."}),
        Q("Classification",
          "Logistic regression for binary classification outputs…",
          "A probability between 0 and 1 via the sigmoid function.",
          ["The raw linear combination of features.",
           "An integer class label directly.",
           "A vector of one-hot probabilities."],
          "Logistic regression passes wᵀx + b through σ(z) = 1/(1 + e^{−z}) to give P(y = 1 | x).",
          {"The raw linear combination of features.": "That's linear regression's output before sigmoid.",
           "An integer class label directly.": "Labels come from thresholding the probability.",
           "A vector of one-hot probabilities.": "That's softmax over multiple classes."}),
        Q("Regularization",
          "Adding an L2 penalty to a loss function encourages…",
          "Smaller weight magnitudes.",
          ["Exactly sparse weights (many zeros).",
           "Higher-degree polynomial features.",
           "Larger learning rates."],
          "L2 (ridge) adds λ ‖w‖² to the loss, pulling each weight toward zero in proportion to its magnitude.",
          {"Exactly sparse weights (many zeros).": "Sparsity comes from L1 (lasso), not L2.",
           "Higher-degree polynomial features.": "Regularization shrinks, it doesn't add features.",
           "Larger learning rates.": "Learning rate is an optimizer setting, unrelated to the penalty."}),
        Q("Regularization",
          "L1 regularization differs from L2 in that L1…",
          "Encourages exact zeros, performing implicit feature selection.",
          ["Always trains faster.",
           "Squares the weights.",
           "Adds noise to the inputs."],
          "L1 penalty λ∑|wᵢ| has corners on the axes, so the optimum often sits with several weights exactly at zero.",
          {"Always trains faster.": "Speed isn't the distinguishing trait.",
           "Squares the weights.": "That's L2.",
           "Adds noise to the inputs.": "That's data augmentation or input dropout."}),
        Q("Optimization",
          "Stochastic gradient descent (SGD) differs from full-batch gradient descent in that SGD…",
          "Estimates the gradient from a single sample or mini-batch each step.",
          ["Uses second-order curvature information.",
           "Always converges in one epoch.",
           "Requires no learning rate."],
          "SGD trades exactness for speed: noisy gradients but many more updates per pass through the data.",
          {"Uses second-order curvature information.": "That's Newton's method or quasi-Newton (L-BFGS).",
           "Always converges in one epoch.": "SGD typically needs many epochs.",
           "Requires no learning rate.": "Learning rate is critical for SGD."}),
        Q("Neural Networks",
          "An activation function in a neural network's hidden layer must be non-linear because…",
          "Composing linear layers without non-linearity collapses to a single linear function.",
          ["Non-linear functions are faster to compute.",
           "Linear functions can't be differentiated.",
           "Non-linearity reduces overfitting."],
          "Stacking Wx + b layers without a non-linearity yields another affine map, so depth gives no extra expressive power.",
          {"Non-linear functions are faster to compute.": "Activations like ReLU are fast, but speed isn't the reason.",
           "Linear functions can't be differentiated.": "Linear functions are trivially differentiable.",
           "Non-linearity reduces overfitting.": "Non-linearity adds capacity, not less."}),
        Q("Neural Networks",
          "ReLU activation is defined as…",
          "max(0, x)",
          ["1 / (1 + e^{−x})",
           "tanh(x)",
           "x²"],
          "Rectified Linear Unit zeros out negatives and passes positives through unchanged.",
          {"1 / (1 + e^{−x})": "That's sigmoid.",
           "tanh(x)": "Hyperbolic tangent ranges in (−1, 1) and is smooth everywhere.",
           "x²": "Squaring is rarely used as an activation; it's not piecewise-linear."}),
        Q("Training",
          "Backpropagation is essentially…",
          "An application of the chain rule for computing gradients of a composed function.",
          ["A clustering algorithm.",
           "A way to invert matrices quickly.",
           "A regularization technique."],
          "Backprop traverses the computation graph in reverse, multiplying local Jacobians via the chain rule.",
          {"A clustering algorithm.": "Clustering is unsupervised; backprop is gradient computation.",
           "A way to invert matrices quickly.": "Backprop computes gradients, not inverses.",
           "A regularization technique.": "Backprop doesn't regularize; it differentiates."}),
        Q("Evaluation",
          "Why split data into training and test sets?",
          "To estimate generalization to unseen data.",
          ["To increase training accuracy.",
           "To balance class frequencies.",
           "To reduce model size."],
          "Test-set performance is the unbiased estimate of how the model will perform on new data drawn from the same distribution.",
          {"To increase training accuracy.": "Holding out data lowers training accuracy if anything.",
           "To balance class frequencies.": "Class balancing is a separate concern.",
           "To reduce model size.": "Splits don't change the model."}),
        Q("Classification",
          "The softmax function converts a vector of logits into…",
          "A probability distribution over classes that sums to 1.",
          ["A binary mask.",
           "A one-hot vector.",
           "A vector of unbounded reals."],
          "softmax(zᵢ) = e^{zᵢ} / Σⱼ e^{zⱼ} normalizes logits into a valid distribution.",
          {"A binary mask.": "Softmax outputs are continuous, not binary.",
           "A one-hot vector.": "Argmax of softmax is one-hot; softmax itself isn't.",
           "A vector of unbounded reals.": "Outputs are bounded in (0, 1)."}),
        Q("Evaluation",
          "What does cross-validation give you that a single train/test split doesn't?",
          "A lower-variance estimate of generalization performance.",
          ["A faster training loop.",
           "A guarantee against overfitting.",
           "A larger model."],
          "k-fold CV averages over k splits, reducing the variance of the performance estimate at the cost of k× training.",
          {"A faster training loop.": "CV is slower, not faster.",
           "A guarantee against overfitting.": "It estimates overfitting; doesn't prevent it.",
           "A larger model.": "CV doesn't change model size."}),
        Q("Optimization",
          "Momentum in SGD…",
          "Adds an exponentially weighted average of past gradients to each update.",
          ["Decreases the learning rate over time.",
           "Trains multiple models in parallel.",
           "Rounds gradients to zero."],
          "Momentum smooths the trajectory: v ← βv + ∇L, w ← w − η v. It accelerates along consistent directions.",
          {"Decreases the learning rate over time.": "That's a learning-rate schedule, not momentum.",
           "Trains multiple models in parallel.": "That's parallelism, not momentum.",
           "Rounds gradients to zero.": "Momentum keeps history, doesn't zero gradients."}),
        Q("Neural Networks",
          "Dropout regularizes a network by…",
          "Randomly zeroing activations during training.",
          ["Pruning weights below a threshold permanently.",
           "Adding L2 to every parameter.",
           "Halving the batch size."],
          "At each training step, units are kept with probability p; this prevents co-adaptation and acts like training an ensemble.",
          {"Pruning weights below a threshold permanently.": "That's magnitude pruning, not dropout.",
           "Adding L2 to every parameter.": "L2 is weight decay; dropout is stochastic.",
           "Halving the batch size.": "Batch size doesn't regularize directly."}),
        Q("Classification",
          "Precision and recall measure different aspects of a classifier. Precision is…",
          "TP / (TP + FP) — fraction of predicted positives that are correct.",
          ["TP / (TP + FN) — fraction of actual positives recovered.",
           "(TP + TN) / total — overall accuracy.",
           "FP / (FP + TN) — false positive rate."],
          "Precision asks how many of your positive predictions were right.",
          {"TP / (TP + FN) — fraction of actual positives recovered.": "That's recall (sensitivity).",
           "(TP + TN) / total — overall accuracy.": "That's accuracy.",
           "FP / (FP + TN) — false positive rate.": "That's the false-positive rate (1 − specificity)."}),
        Q("Convolutional Networks",
          "A convolutional layer's key parameter-sharing property means…",
          "The same filter is applied at every spatial location.",
          ["Each output pixel has its own learned weights.",
           "Filters are randomly different at each location.",
           "Weights are tied across channels."],
          "Sharing filter weights across the input grid gives translation equivariance and dramatically fewer parameters than a dense layer.",
          {"Each output pixel has its own learned weights.": "That's a dense (fully-connected) layer.",
           "Filters are randomly different at each location.": "There's no sharing in that case.",
           "Weights are tied across channels.": "Each filter has separate per-channel weights; sharing is spatial, not across channels."}),
        Q("Bias-Variance",
          "An underfitting model exhibits…",
          "High bias and low variance.",
          ["High bias and high variance.",
           "Low bias and high variance.",
           "Low bias and low variance."],
          "Underfit models are too rigid: they miss the signal (high bias) and don't change much with new data (low variance).",
          {"High bias and high variance.": "That's a poorly-fit unstable model — rare for true underfitting.",
           "Low bias and high variance.": "That's overfitting.",
           "Low bias and low variance.": "That's the ideal — not underfitting."}),
        Q("Training",
          "An epoch is…",
          "One complete pass through the training dataset.",
          ["One batch of updates.",
           "One forward pass on a single example.",
           "One evaluation on the test set."],
          "After processing every training example once (in batches), one epoch has elapsed.",
          {"One batch of updates.": "That's a single step.",
           "One forward pass on a single example.": "That's a single example, not an epoch.",
           "One evaluation on the test set.": "Evaluation isn't part of an epoch's definition."}),
        Q("Loss Functions",
          "Cross-entropy loss for a true class y and predicted distribution p is…",
          "−log p(y) — negative log-likelihood of the true class.",
          ["(y − p)² summed over classes.",
           "|y − p| averaged over classes.",
           "p(y) − 1 summed over classes."],
          "Cross-entropy with one-hot targets reduces to −log p(y); minimizing it maximizes the likelihood of the true labels.",
          {"(y − p)² summed over classes.": "That's MSE applied to one-hot labels — not standard for classification.",
           "|y − p| averaged over classes.": "That's L1.",
           "p(y) − 1 summed over classes.": "Not a standard loss."}),
        Q("Neural Networks",
          "Batch normalization normalizes activations using statistics computed…",
          "Per mini-batch during training, with running averages used at inference.",
          ["Per individual sample.",
           "Once at initialization and never again.",
           "Only on the test set."],
          "BN standardizes (x − μ_B) / σ_B on each batch and learns a scale/shift; running estimates of μ, σ are kept for inference.",
          {"Per individual sample.": "That's layer normalization or instance normalization.",
           "Once at initialization and never again.": "Statistics are updated each batch.",
           "Only on the test set.": "Reversed — train-time normalization is the whole point."}),
    ],
    medium=[
        Q("Optimization",
          "Adam combines two ideas from prior optimizers. Which?",
          "Momentum (first-moment estimate) and per-parameter adaptive learning rates (second-moment estimate).",
          ["Newton's method and stochastic gradients.",
           "Coordinate descent and L2 regularization.",
           "Simulated annealing and dropout."],
          "Adam tracks m_t (moving average of gradients) and v_t (moving average of squared gradients), correcting bias and adapting the step per parameter.",
          {"Newton's method and stochastic gradients.": "Adam doesn't use exact Hessian information.",
           "Coordinate descent and L2 regularization.": "Adam updates all parameters per step.",
           "Simulated annealing and dropout.": "Neither idea is part of Adam."}),
        Q("Classification",
          "Why does logistic regression use the log-loss (cross-entropy) rather than MSE?",
          "Log-loss is convex in the parameters and is the negative log-likelihood under the model.",
          ["Log-loss runs faster than MSE.",
           "MSE doesn't work for probabilities.",
           "Log-loss requires no gradient."],
          "Under the Bernoulli model, the MLE objective is precisely log-loss; MSE on sigmoid outputs is non-convex and has vanishing gradients far from 0.5.",
          {"Log-loss runs faster than MSE.": "Speed isn't the reason; convexity and likelihood are.",
           "MSE doesn't work for probabilities.": "MSE can be defined, but loses the MLE interpretation and convexity.",
           "Log-loss requires no gradient.": "Log-loss is gradient-based like any loss."}),
        Q("Regularization",
          "Early stopping regularizes by…",
          "Halting training when validation loss stops improving, implicitly constraining model capacity.",
          ["Adding noise to the gradients.",
           "Reducing the number of layers.",
           "Increasing the learning rate."],
          "Early stopping effectively limits how far parameters can move from initialization, similar in spirit to L2 in some regimes.",
          {"Adding noise to the gradients.": "That's a separate technique.",
           "Reducing the number of layers.": "Stopping doesn't change architecture.",
           "Increasing the learning rate.": "Stopping is about when to halt, not step size."}),
        Q("Training",
          "Vanishing gradients in deep networks arise primarily when…",
          "Activations or weights repeatedly compress gradient magnitudes through many layers.",
          ["Gradients are explicitly set to zero.",
           "The learning rate is too large.",
           "Batch size is too small."],
          "Sigmoids saturate, and chained Jacobians with norms < 1 shrink the signal exponentially with depth.",
          {"Gradients are explicitly set to zero.": "That's gradient clipping with threshold 0, not the natural cause.",
           "The learning rate is too large.": "Large LR causes explosion, not vanishing.",
           "Batch size is too small.": "Batch size affects variance, not systematic vanishing."}),
        Q("Convolutional Networks",
          "If a 5×5 input is convolved with a 3×3 kernel using stride 1 and no padding, the output has size…",
          "3×3",
          ["5×5", "7×7", "2×2"],
          "Output size = (input − kernel) / stride + 1 = (5 − 3)/1 + 1 = 3.",
          {"5×5": "Would require 'same' padding.",
           "7×7": "Would require 'full' padding.",
           "2×2": "That would correspond to stride 2."}),
        Q("Bias-Variance",
          "Adding more training data primarily reduces…",
          "Variance, with limited effect on bias.",
          ["Bias, with limited effect on variance.",
           "Both equally.",
           "Neither — only model size matters."],
          "More data tightens the estimator's distribution (less variance) but doesn't change the model's expressivity (bias).",
          {"Bias, with limited effect on variance.": "Bias is mostly about model capacity, not data quantity.",
           "Both equally.": "Variance shrinks much faster with data than bias does.",
           "Neither — only model size matters.": "Data quantity matters substantially."}),
        Q("Neural Networks",
          "Xavier (Glorot) initialization picks weight variances to…",
          "Keep the variance of activations and gradients roughly constant across layers.",
          ["Make every weight equal to 1/n.",
           "Randomize signs only, leaving magnitude fixed.",
           "Start every weight at zero."],
          "Variance ∝ 1/(fan-in + fan-out) keeps the forward signal and backward gradient at similar scale.",
          {"Make every weight equal to 1/n.": "Glorot is a distribution, not a constant.",
           "Randomize signs only, leaving magnitude fixed.": "That's sign initialization, not Xavier.",
           "Start every weight at zero.": "All-zero init breaks symmetry and prevents learning."}),
        Q("Classification",
          "An ROC curve plots…",
          "True positive rate against false positive rate across thresholds.",
          ["Precision against recall across thresholds.",
           "Loss against epoch.",
           "Accuracy against batch size."],
          "ROC sweeps the decision threshold, plotting TPR vs FPR; AUC measures area under it.",
          {"Precision against recall across thresholds.": "That's a PR curve, not ROC.",
           "Loss against epoch.": "That's a training curve.",
           "Accuracy against batch size.": "Not a standard plot."}),
        Q("Optimization",
          "Learning-rate warmup is most useful when…",
          "Training large models with adaptive optimizers like Adam, to avoid destabilizing early steps.",
          ["The dataset is small.",
           "Labels are noisy.",
           "Batch size is 1."],
          "Warmup linearly ramps the LR from 0 to its target, letting Adam's running statistics stabilize before large updates.",
          {"The dataset is small.": "Warmup is more about stable large-scale training.",
           "Labels are noisy.": "Label noise is a different problem.",
           "Batch size is 1.": "Warmup isn't tied to batch size of 1."}),
        Q("Generalization",
          "The bias-variance decomposition for squared loss writes the expected error as…",
          "Bias² + Variance + Irreducible noise.",
          ["Bias × Variance + Noise.",
           "Bias + Variance only.",
           "Variance² + Noise²."],
          "E[(ŷ − y)²] = (bias)² + var + σ² when targets have inherent noise σ².",
          {"Bias × Variance + Noise.": "The terms add, not multiply.",
           "Bias + Variance only.": "Missing the irreducible noise term.",
           "Variance² + Noise².": "Only bias is squared in the decomposition."}),
        Q("Convolutional Networks",
          "Pooling layers (max or average) primarily provide…",
          "Spatial downsampling and a small amount of translation invariance.",
          ["Parameter sharing across channels.",
           "Non-linearity equivalent to ReLU.",
           "Regularization equivalent to dropout."],
          "Pooling shrinks the spatial dimensions and gives a coarse invariance to small shifts.",
          {"Parameter sharing across channels.": "Pooling has no parameters.",
           "Non-linearity equivalent to ReLU.": "Max-pool is non-linear but isn't ReLU.",
           "Regularization equivalent to dropout.": "Pooling isn't stochastic in the same sense."}),
        Q("Sequence Models",
          "Why do plain RNNs struggle with long-range dependencies?",
          "Gradients vanish or explode as they're propagated through many time steps.",
          ["RNNs cannot share parameters.",
           "RNNs use no non-linearity.",
           "RNNs require fixed-length inputs."],
          "Repeated multiplication by the recurrent Jacobian over many steps shrinks or blows up gradients exponentially.",
          {"RNNs cannot share parameters.": "Parameter sharing across time is exactly what RNNs do.",
           "RNNs use no non-linearity.": "They typically use tanh or ReLU.",
           "RNNs require fixed-length inputs.": "RNNs handle variable-length sequences."}),
        Q("Sequence Models",
          "LSTM and GRU mitigate vanishing gradients by…",
          "Introducing gated additive paths so information can flow over many steps without repeated multiplication.",
          ["Replacing tanh with sigmoid everywhere.",
           "Doubling the number of layers.",
           "Removing the hidden state."],
          "The cell state in an LSTM accumulates additively; the gates control writes and reads, preserving gradient magnitude.",
          {"Replacing tanh with sigmoid everywhere.": "Gates use sigmoid, but that alone doesn't fix vanishing.",
           "Doubling the number of layers.": "More layers can worsen the problem.",
           "Removing the hidden state.": "RNNs require state."}),
        Q("Generalization",
          "Double descent describes the phenomenon where…",
          "Test error decreases, rises, then decreases again as model capacity grows past the interpolation threshold.",
          ["Training error always doubles before halving.",
           "Adding regularization doubles the test error.",
           "The learning rate must be set in two phases."],
          "Over-parameterized models can generalize well past the classical U-shape, giving a second descent in test error.",
          {"Training error always doubles before halving.": "Training error typically just decreases.",
           "Adding regularization doubles the test error.": "Regularization usually lowers it.",
           "The learning rate must be set in two phases.": "That's a schedule, not double descent."}),
        Q("Loss Functions",
          "Why is cross-entropy preferred over MSE for classification?",
          "It penalizes confident wrong predictions much more strongly, giving stronger gradients near the wrong class.",
          ["It runs faster on GPUs.",
           "It always produces calibrated probabilities.",
           "MSE only works for regression problems with integer targets."],
          "Cross-entropy's gradient with respect to logits is (p − y), which doesn't vanish for confident wrong predictions the way MSE-on-sigmoid does.",
          {"It runs faster on GPUs.": "Compute is comparable.",
           "It always produces calibrated probabilities.": "Calibration isn't automatic.",
           "MSE only works for regression problems with integer targets.": "MSE works on any real targets."}),
        Q("Optimization",
          "Gradient clipping is most commonly used to address…",
          "Exploding gradients, especially in RNN training.",
          ["Vanishing gradients in deep CNNs.",
           "Overfitting on small datasets.",
           "Slow convergence on convex problems."],
          "Clipping ‖∇‖ to a max norm prevents single huge updates from destabilizing the optimizer.",
          {"Vanishing gradients in deep CNNs.": "Clipping doesn't help when gradients are too small.",
           "Overfitting on small datasets.": "Regularization, not clipping, handles overfitting.",
           "Slow convergence on convex problems.": "Step-size schedules help convergence; clipping handles spikes."}),
        Q("Training",
          "Train-test data leakage means…",
          "Information from the test set has influenced model training or selection.",
          ["The training set is too large.",
           "The model uses leaky ReLU.",
           "Test labels are missing."],
          "Common leaks: tuning hyperparameters on the test set, computing normalization stats over all data, or duplicate samples across splits.",
          {"The training set is too large.": "Size isn't leakage.",
           "The model uses leaky ReLU.": "Activations are unrelated.",
           "Test labels are missing.": "That's an unlabeled-test problem, not leakage."}),
        Q("Regularization",
          "Weight decay in SGD is equivalent to which regularizer (in the simplest sense)?",
          "L2 regularization on the weights.",
          ["L1 regularization on the weights.",
           "Dropout on the activations.",
           "Data augmentation."],
          "Adding λw to the gradient is the derivative of (λ/2) ‖w‖², so SGD with weight decay implements L2.",
          {"L1 regularization on the weights.": "L1's gradient is sign(w), not w.",
           "Dropout on the activations.": "Dropout is stochastic; weight decay is deterministic.",
           "Data augmentation.": "Augmentation transforms inputs; weight decay penalizes weights."}),
        Q("Generalization",
          "Why does data augmentation often improve generalization?",
          "It expands the effective training distribution, exposing the model to nuisance variations.",
          ["It speeds up forward passes.",
           "It reduces the number of parameters.",
           "It replaces validation data."],
          "Augmentations encode invariances (rotation, crop, color jitter) so the model learns features robust to them.",
          {"It speeds up forward passes.": "Augmentation typically slows training.",
           "It reduces the number of parameters.": "Architecture is unchanged.",
           "It replaces validation data.": "Held-out data is still needed."}),
        Q("Classification",
          "The softmax+cross-entropy gradient with respect to logits z is…",
          "p − y, where p is the softmax output and y is one-hot.",
          ["−log(p − y)",
           "(p − y)²",
           "p × (1 − p)"],
          "This clean form is one reason softmax + cross-entropy is the canonical pairing for classification.",
          {"−log(p − y)": "Not a valid gradient form.",
           "(p − y)²": "That would be a squared loss, not its gradient.",
           "p × (1 − p)": "That's σ's derivative for a single sigmoid output."}),
    ],
    hard=[
        Q("Optimization",
          "Adam's bias correction (m̂_t = m_t / (1 − β₁^t)) addresses…",
          "The initial under-estimate of the moving averages caused by zero initialization.",
          ["Numerical overflow in the denominator.",
           "Non-stationarity of the gradient distribution.",
           "Class imbalance in the data."],
          "Because m_0 = 0, m_t is biased toward zero for small t; dividing by 1 − β₁^t un-biases the estimate.",
          {"Numerical overflow in the denominator.": "Numerical stability is handled by the ε term.",
           "Non-stationarity of the gradient distribution.": "Adam doesn't model non-stationarity explicitly.",
           "Class imbalance in the data.": "Optimizer doesn't address imbalance."}),
        Q("Generalization",
          "Why can over-parameterized neural networks generalize well despite fitting the training data exactly?",
          "Implicit bias of SGD selects low-norm or smooth interpolating solutions among many possible ones.",
          ["The training data is always linearly separable.",
           "Modern GPUs round gradients in a regularizing way.",
           "Dropout is the only thing that makes it work."],
          "Among interpolating models, SGD tends to find solutions in flat / low-norm regions that generalize; this is an active research area.",
          {"The training data is always linearly separable.": "Empirically false in most settings.",
           "Modern GPUs round gradients in a regularizing way.": "Numerical noise isn't the explanation.",
           "Dropout is the only thing that makes it work.": "Networks generalize even without dropout."}),
        Q("Convolutional Networks",
          "A 1×1 convolution is best understood as…",
          "A per-pixel linear combination across channels — essentially a channel-wise MLP applied independently at each spatial location.",
          ["An identity operation.",
           "A pooling layer.",
           "A normalization layer."],
          "1×1 convs mix channels without changing spatial layout; used heavily in bottlenecks (Inception, ResNets).",
          {"An identity operation.": "Only if weights are exactly identity; in general it's learned.",
           "A pooling layer.": "Pooling doesn't have learnable weights per channel.",
           "A normalization layer.": "Normalization standardizes statistics, not linear mix."}),
        Q("Sequence Models",
          "Self-attention's computational cost scales with sequence length n as…",
          "O(n²) in time and memory for the attention matrix.",
          ["O(n) — linear in sequence length.",
           "O(n log n).",
           "O(d²) where d is the embedding dim, independent of n."],
          "Each token attends to every other, giving an n × n attention matrix; reducing this is an active research area (linear attention, sparse attention).",
          {"O(n) — linear in sequence length.": "Linear attention variants exist but plain self-attention is quadratic.",
           "O(n log n).": "Not a standard cost class for attention.",
           "O(d²) where d is the embedding dim, independent of n.": "Per-token projections are O(d²) but attention itself is n-dependent."}),
        Q("Sequence Models",
          "Layer normalization vs batch normalization: layer norm computes statistics over…",
          "The features of a single example, independent of the batch.",
          ["Multiple batches concatenated.",
           "The labels.",
           "Time and channel dimensions of the batch jointly."],
          "Layer norm is per-example, which makes it suitable for variable-length sequences and small batches.",
          {"Multiple batches concatenated.": "That's the opposite of what layer norm does.",
           "The labels.": "Norms operate on activations, not labels.",
           "Time and channel dimensions of the batch jointly.": "That mixes examples — would be batch-like."}),
        Q("Classification",
          "The cross-entropy decomposes as H(p, q) = H(p) + KL(p ‖ q). For one-hot p, this becomes…",
          "KL(p ‖ q) — H(p) is zero because p is deterministic.",
          ["H(p) only.",
           "Always 0.",
           "−log q only when q is one-hot too."],
          "A deterministic distribution has zero entropy, so minimizing cross-entropy reduces to minimizing KL divergence to the empirical label.",
          {"H(p) only.": "H(p) = 0 for one-hot p.",
           "Always 0.": "Only if q = p exactly.",
           "−log q only when q is one-hot too.": "−log q is the cross-entropy for any q; one-hot q would be 0 or ∞."}),
        Q("Optimization",
          "The convergence rate of plain gradient descent on a smooth convex function is…",
          "O(1/t) in function value.",
          ["O(1/√t)", "O(e^{−t})", "O(log t)"],
          "For L-smooth convex objectives, after t steps f(x_t) − f* ≤ O(1/t); strongly convex gives geometric (e^{−t}-style) convergence.",
          {"O(1/√t)": "That's subgradient method on non-smooth convex functions.",
           "O(e^{−t})": "That's strongly convex, not just smooth convex.",
           "O(log t)": "Not a standard rate."}),
        Q("Training",
          "Mixed-precision training stores most computations in lower precision (e.g., FP16) but keeps a master copy in FP32. Why?",
          "To preserve numerical stability of small updates that would underflow in FP16.",
          ["To run on TPUs only.",
           "To compress the model permanently.",
           "To reduce labels' precision."],
          "Tiny gradient updates can be smaller than the FP16 smallest representable step; an FP32 master copy accumulates them without loss.",
          {"To run on TPUs only.": "TPU/GPU compatibility differs by hardware; not the reason.",
           "To compress the model permanently.": "Mixed-precision is for training, not deployment compression.",
           "To reduce labels' precision.": "Labels are typically integers."}),
        Q("Generalization",
          "Why does the no-free-lunch theorem matter in practice?",
          "No learning algorithm is universally best; performance depends on the data distribution's structure.",
          ["It says deep learning always wins.",
           "It means more data is always worse than less.",
           "It implies cross-validation is impossible."],
          "Averaged over all possible problems, every algorithm performs equally; practical wins come from matching inductive bias to the data.",
          {"It says deep learning always wins.": "Opposite — no method wins everywhere.",
           "It means more data is always worse than less.": "Empirically false in most settings.",
           "It implies cross-validation is impossible.": "CV is fine; NFL is about algorithm universality."}),
        Q("Convolutional Networks",
          "Residual connections (skip connections) help training primarily by…",
          "Providing identity gradient paths that mitigate optimization difficulty in deep networks.",
          ["Adding regularization equivalent to dropout.",
           "Doubling the number of features per layer.",
           "Forcing each layer to learn the identity."],
          "Allowing y = x + F(x) means at worst a layer can pass the signal through; gradients flow unimpeded through the skip path.",
          {"Adding regularization equivalent to dropout.": "Skip connections aren't a regularizer in this sense.",
           "Doubling the number of features per layer.": "Channel counts aren't changed.",
           "Forcing each layer to learn the identity.": "The opposite — they make the identity easy when useful, not required."}),
        Q("Optimization",
          "SGD with replacement and SGD without replacement (random reshuffling) differ in that…",
          "Random reshuffling typically converges faster in practice; with replacement is easier to analyze theoretically.",
          ["Random reshuffling is unbiased; with replacement is biased.",
           "Both produce identical iterates given the same seed.",
           "Random reshuffling requires sorting the data."],
          "Theory often assumes replacement (i.i.d.) for clean bounds; practice prefers reshuffling per epoch for empirical speedup.",
          {"Random reshuffling is unbiased; with replacement is biased.": "Both are unbiased in expectation.",
           "Both produce identical iterates given the same seed.": "Sampling rule differs, so iterates differ.",
           "Random reshuffling requires sorting the data.": "No sorting — just permutation."}),
        Q("Loss Functions",
          "Focal loss modifies cross-entropy by…",
          "Down-weighting easy examples via a (1 − p_t)^γ factor, focusing learning on hard ones.",
          ["Adding L2 to the logits.",
           "Replacing softmax with sigmoid for multi-class.",
           "Computing loss only on the top-k predictions."],
          "Focal loss = −(1 − p_t)^γ log p_t; high-confidence correct predictions contribute little, useful for heavily imbalanced detection tasks.",
          {"Adding L2 to the logits.": "Not the mechanism.",
           "Replacing softmax with sigmoid for multi-class.": "That's a separate change.",
           "Computing loss only on the top-k predictions.": "Top-k isn't part of focal loss."}),
        Q("Generalization",
          "Sharpness-aware minimization (SAM) seeks parameters that…",
          "Minimize the worst-case loss in a neighborhood around w, encouraging flat minima.",
          ["Are the global minimum of the loss exactly.",
           "Have the largest gradients.",
           "Lie on a specific sphere of the parameter space."],
          "SAM updates use ∇L at w + ε, where ε is the adversarial perturbation; this biases toward flat regions correlated with generalization.",
          {"Are the global minimum of the loss exactly.": "Not a SAM objective specifically.",
           "Have the largest gradients.": "Opposite of flat minima.",
           "Lie on a specific sphere of the parameter space.": "Not an SAM property."}),
        Q("Sequence Models",
          "In a Transformer, positional encodings are necessary because…",
          "Self-attention is order-invariant; without positional information, token order is lost.",
          ["The optimizer requires position labels.",
           "Tokens have no embedding otherwise.",
           "Layer norm uses positions internally."],
          "Permuting input tokens produces a permuted output unless positional encodings break the symmetry.",
          {"The optimizer requires position labels.": "Optimizer doesn't see positions.",
           "Tokens have no embedding otherwise.": "Tokens get content embeddings independently.",
           "Layer norm uses positions internally.": "Layer norm doesn't use position."}),
        Q("Optimization",
          "Why does using a too-large learning rate often cause loss to diverge in deep networks?",
          "Each step overshoots local curvature, amplifying parameter updates and gradient magnitudes.",
          ["The optimizer runs out of memory.",
           "Weights become integers.",
           "The CPU rounds gradients down."],
          "With LR > 2/L (L = local Lipschitz constant), GD on a quadratic diverges; in deep nets the effective L can be very large.",
          {"The optimizer runs out of memory.": "LR doesn't affect memory.",
           "Weights become integers.": "Floating-point weights stay continuous.",
           "The CPU rounds gradients down.": "Not the mechanism."}),
        Q("Bayesian Methods",
          "MAP estimation with a Gaussian prior on weights is equivalent to MLE with…",
          "L2 regularization on the weights.",
          ["L1 regularization on the weights.",
           "No regularization.",
           "Dropout."],
          "Log of a Gaussian prior contributes −(λ/2) ‖w‖² to the log-posterior, identical to L2 weight decay.",
          {"L1 regularization on the weights.": "L1 corresponds to a Laplace prior.",
           "No regularization.": "Uniform prior gives plain MLE.",
           "Dropout.": "Dropout has a Bayesian interpretation but a different one."}),
        Q("Training",
          "Knowledge distillation transfers information from a large teacher to a small student by…",
          "Training the student to match the teacher's soft probability outputs (often with a temperature).",
          ["Copying the teacher's parameters.",
           "Pruning the teacher to fit the student's size.",
           "Quantizing the teacher's gradients."],
          "Soft targets carry richer information than hard labels (dark knowledge); temperature smooths the distribution.",
          {"Copying the teacher's parameters.": "Architectures usually differ; you can't copy directly.",
           "Pruning the teacher to fit the student's size.": "That's pruning, not distillation.",
           "Quantizing the teacher's gradients.": "Quantization is a separate technique."}),
        Q("Convolutional Networks",
          "Depthwise separable convolutions reduce computation by…",
          "Splitting standard convolution into per-channel spatial filtering followed by 1×1 channel mixing.",
          ["Doubling kernel size.",
           "Removing spatial structure entirely.",
           "Sharing weights across batches."],
          "If standard cost is k² · C_in · C_out, separable is k² · C_in + C_in · C_out — a major saving when C_out is large.",
          {"Doubling kernel size.": "Opposite direction.",
           "Removing spatial structure entirely.": "Spatial filtering is preserved per channel.",
           "Sharing weights across batches.": "Weights are already shared across batches."}),
        Q("Loss Functions",
          "Label smoothing replaces one-hot targets with…",
          "(1 − α) on the true class and α/(K − 1) on each other class.",
          ["Random labels.",
           "All zeros.",
           "Two-hot encodings."],
          "Label smoothing tempers overconfidence and often improves calibration with marginal accuracy cost.",
          {"Random labels.": "That would corrupt training.",
           "All zeros.": "Then there's nothing to fit.",
           "Two-hot encodings.": "Only used in multi-label problems."}),
        Q("Generalization",
          "Why does ensembling typically improve test accuracy over any single model in the ensemble?",
          "Averaging predictions cancels uncorrelated errors, reducing variance of the predictor.",
          ["It always reduces bias.",
           "It compresses the model.",
           "It eliminates training data needs."],
          "If errors of base models are partially independent, the averaged predictor has lower variance and often lower expected error.",
          {"It always reduces bias.": "Bias reduces only if base models systematically err in different directions.",
           "It compresses the model.": "Ensembles are larger, not smaller.",
           "It eliminates training data needs.": "Each model still needs training data."}),
    ],
)




BOOK = MACHINE_LEARNING
