"""Quiz bank: Computer Networking (CNP3)."""
from quiz_banks._make_book import make_book

BOOK = make_book(
    title="Computer Networking: Principles, Protocols and Practice",
    parent_topic="Computer Science",
    subtopic="Networking",
    slug="networking-cnp3",
    source_url="https://www.computer-networking.info/",
    easy=[
        (
            "OSI and TCP/IP",
            "How many layers does the OSI reference model define?",
            "7",
            ["5", "4", "3"],
            "The OSI model has seven layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.",
            {
                "5": "Five layers describe the original Internet stack sketch, not the full OSI model.",
                "4": "Four layers match the TCP/IP stack, not OSI.",
                "3": "Three is too few — OSI splits concerns more finely than a minimal stack.",
            },
        ),
        (
            "OSI and TCP/IP",
            "In the TCP/IP model, at which layer does IP operate?",
            "Internet (network) layer",
            ["Application layer", "Transport layer", "Link layer"],
            "IP provides host-to-host datagram delivery; it sits below TCP/UDP and above link technologies.",
            {
                "Application layer": "Applications use TCP/UDP sockets; IP is lower in the stack.",
                "Transport layer": "TCP and UDP live at transport; IP is one layer below.",
                "Link layer": "Link layers (Ethernet, Wi-Fi) frame IP packets; IP itself is not the link layer.",
            },
        ),
        (
            "IP Addressing",
            "How many bits are in a standard IPv4 address?",
            "32",
            ["64", "128", "16"],
            "IPv4 addresses are 32-bit dotted-quad values, usually written as four decimal octets.",
            {
                "64": "64 bits is common for MAC addresses, not IPv4.",
                "128": "128 bits is the size of an IPv6 address.",
                "16": "16 bits cannot uniquely identify billions of hosts on the Internet.",
            },
        ),
        (
            "TCP and UDP",
            "Which transport protocol is connection-oriented and provides reliable, in-order byte delivery?",
            "TCP",
            ["UDP", "ICMP", "ARP"],
            "TCP sets up a connection, acknowledges data, and retransmits losses; UDP is connectionless and best-effort.",
            {
                "UDP": "UDP sends datagrams without establishing or maintaining a connection.",
                "ICMP": "ICMP carries control messages (e.g., ping), not application byte streams.",
                "ARP": "ARP resolves IP to link-layer addresses on a LAN, not end-to-end transport.",
            },
        ),
        (
            "Routing",
            "What is the primary job of an IP router?",
            "Forward packets between networks using routing tables",
            ["Assign IP addresses to hosts on a single LAN",
             "Terminate TLS for web clients",
             "Translate domain names to IP addresses"],
            "Routers examine destination IP prefixes and choose the next hop toward the destination network.",
            {
                "Assign IP addresses to hosts on a single LAN": "That is typically DHCP on a LAN, not core routing.",
                "Terminate TLS for web clients": "TLS termination is an application/proxy function, not basic IP forwarding.",
                "Translate domain names to IP addresses": "DNS resolvers perform name translation, not routers.",
            },
        ),
        (
            "DNS",
            "What does the Domain Name System (DNS) primarily map?",
            "Human-readable hostnames to IP addresses",
            ["IP addresses to MAC addresses",
             "TCP ports to process names on a host",
             "URLs to HTML documents"],
            "DNS is a distributed naming system that resolves names like www.example.com to A/AAAA records.",
            {
                "IP addresses to MAC addresses": "ARP (or IPv6 ND) maps IP to link-layer addresses on a subnet.",
                "TCP ports to process names on a host": "That is local service naming (/etc/services), not Internet DNS.",
                "URLs to HTML documents": "HTTP fetches resources; DNS only supplies name-to-address (and related) records.",
            },
        ),
        (
            "HTTP",
            "Which TCP port does unencrypted HTTP use by default?",
            "80",
            ["443", "53", "22"],
            "HTTP historically listens on port 80; HTTPS uses 443 with TLS.",
            {
                "443": "Port 443 is the default for HTTPS (HTTP over TLS).",
                "53": "Port 53 is reserved for DNS.",
                "22": "Port 22 is commonly used for SSH.",
            },
        ),
        (
            "Congestion Control",
            "Network congestion occurs when…",
            "Demand for bandwidth exceeds what links and buffers can carry",
            ["A host has no default gateway configured",
             "DNS caching expires",
             "A switch learns too many MAC addresses"],
            "Congestion is overload: queues grow, delay rises, and packets may be dropped.",
            {
                "A host has no default gateway configured": "Missing a gateway breaks reachability but is not congestion.",
                "DNS caching expires": "TTL expiry causes fresh lookups, not link overload.",
                "A switch learns too many MAC addresses": "MAC table limits affect switching, not Internet-wide bandwidth contention.",
            },
        ),
        (
            "Switching",
            "Compared with a classic hub, an Ethernet switch…",
            "Forwards frames only to the port leading toward the destination MAC",
            ["Broadcasts every frame to all ports always",
             "Operates at the network layer using IP addresses",
             "Cannot learn MAC addresses"],
            "Switches build a MAC address table and filter traffic, reducing collisions versus a hub.",
            {
                "Broadcasts every frame to all ports always": "That describes a hub (or unknown unicast flood), not normal switched unicast.",
                "Operates at the network layer using IP addresses": "Basic switches forward using MAC addresses at layer 2.",
                "Cannot learn MAC addresses": "Learning source MACs per port is how switches forward efficiently.",
            },
        ),
        (
            "OSI and TCP/IP",
            "Which OSI layer is closest to where web browsers and mail clients interact with sockets?",
            "Application",
            ["Physical", "Network", "Data link"],
            "HTTP, SMTP, and DNS are application-layer protocols accessed via transport APIs.",
            {
                "Physical": "Physical layer deals with bits on the wire, not application protocols.",
                "Network": "IP is network layer; browsers use higher-level protocols on top of TCP.",
                "Data link": "Ethernet framing is below IP and far below HTTP.",
            },
        ),
        (
            "IP Addressing",
            "Which IPv4 address range is reserved for private networks (RFC 1918)?",
            "10.0.0.0/8",
            ["8.8.8.0/24", "127.0.0.0/8", "224.0.0.0/4"],
            "10/8, 172.16/12, and 192.168/16 are private; they are not routed on the public Internet.",
            {
                "8.8.8.0/24": "8.8.8.x is a public anycast DNS service range, not a private block.",
                "127.0.0.0/8": "127/8 is loopback on the local host, not LAN private addressing.",
                "224.0.0.0/4": "224/4 is multicast space, not private unicast.",
            },
        ),
        (
            "TCP and UDP",
            "UDP is often chosen instead of TCP when…",
            "Low latency matters more than guaranteed delivery (e.g., live media, DNS queries)",
            ["Every byte must arrive in order without loss",
             "A three-way handshake is required before data",
             "Flow control must throttle a fast sender"],
            "UDP exposes datagrams with no retransmission or ordering — acceptable when apps handle loss or repeat queries.",
            {
                "Every byte must arrive in order without loss": "That requirement favors TCP, not UDP.",
                "A three-way handshake is required before data": "UDP has no connection setup; TCP uses the three-way handshake.",
                "Flow control must throttle a fast sender": "TCP provides window-based flow control; UDP does not.",
            },
        ),
        (
            "Routing",
            "A host's default gateway is…",
            "The router on the local subnet used to reach off-subnet destinations",
            ["The DNS server that resolves all names",
             "The MAC address of the destination host",
             "The longest prefix in the global BGP table"],
            "Hosts send non-local traffic to the default gateway's IP on the LAN.",
            {
                "The DNS server that resolves all names": "DNS and default routing solve different problems.",
                "The MAC address of the destination host": "Gateways are reached on-LAN; remote MACs are not known initially.",
                "The longest prefix in the global BGP table": "BGP tables live in routers; hosts only need a default route.",
            },
        ),
        (
            "DNS",
            "Which DNS record type maps a hostname to an IPv4 address?",
            "A",
            ["AAAA", "MX", "CNAME"],
            "A records hold 32-bit IPv4 addresses; AAAA holds IPv6.",
            {
                "AAAA": "AAAA maps to IPv6, not IPv4.",
                "MX": "MX specifies mail exchangers, not host IPv4 addresses.",
                "CNAME": "CNAME is an alias to another name, not a direct IPv4 address.",
            },
        ),
        (
            "HTTP",
            "An HTTP response status code of 404 means…",
            "The requested resource was not found on the server",
            ["The request was understood and a new resource was created",
             "The server is temporarily overloaded",
             "The client must authenticate"],
            "404 Not Found indicates the URI does not map to a resource the server can serve.",
            {
                "The request was understood and a new resource was created": "That describes 201 Created.",
                "The server is temporarily overloaded": "503 Service Unavailable signals overload or maintenance.",
                "The client must authenticate": "401/403 relate to authentication and authorization.",
            },
        ),
        (
            "TCP and UDP",
            "The first packet of a TCP three-way handshake carries which flag(s)?",
            "SYN",
            ["ACK only", "FIN", "RST"],
            "The client sends SYN; the server replies SYN-ACK; the client completes with ACK.",
            {
                "ACK only": "ACK alone completes the handshake; it is not the opening packet.",
                "FIN": "FIN signals connection teardown, not setup.",
                "RST": "RST aborts a connection, it does not open one politely.",
            },
        ),
        (
            "Switching",
            "When a switch receives a frame on a port, it typically learns…",
            "The source MAC address and associates it with that ingress port",
            ["The destination IP address of every packet",
             "The TCP congestion window of the sender",
             "The DNS name of the host"],
            "Learning tables map MAC → port so future frames to that MAC can be switched unicast.",
            {
                "The destination IP address of every packet": "Classic switches do not parse IP for learning; they use MAC headers.",
                "The TCP congestion window of the sender": "Congestion control is end-to-end transport behavior.",
                "The DNS name of the host": "DNS names are not present in Ethernet frame headers.",
            },
        ),
        (
            "OSI and TCP/IP",
            "Ethernet framing and MAC addresses belong to which OSI layer?",
            "Data link",
            ["Physical", "Network", "Transport"],
            "Layer 2 handles node-to-node delivery on a single link (e.g., Ethernet switches).",
            {
                "Physical": "Physical is signaling and media; framing with MACs is data link.",
                "Network": "IP addressing and routing are network layer.",
                "Transport": "TCP/UDP ports are transport layer.",
            },
        ),
        (
            "IP Addressing",
            "A subnet mask in IPv4 is used to…",
            "Separate the network prefix from the host portion of an address",
            ["Encrypt packets between two hosts",
             "Assign TCP port numbers",
             "Resolve hostnames to IP addresses"],
            "Masking (or prefix length) tells hosts and routers which bits identify the subnet.",
            {
                "Encrypt packets between two hosts": "Encryption is provided by protocols like IPsec/TLS, not the mask.",
                "Assign TCP port numbers": "Ports are transport-layer identifiers on a host.",
                "Resolve hostnames to IP addresses": "DNS performs name resolution.",
            },
        ),
        (
            "Congestion Control",
            "When a router's queue is full, it may…",
            "Drop arriving packets, signaling senders to slow down",
            ["Increase the TCP sequence number of all flows",
             "Convert TCP into UDP automatically",
             "Disable ARP on the LAN"],
            "Tail drops (or active queue management) cause loss that TCP interprets as congestion signals.",
            {
                "Increase the TCP sequence number of all flows": "Sequence numbers are chosen by endpoints, not routers on drop.",
                "Convert TCP into UDP automatically": "Routers do not change transport protocols.",
                "Disable ARP on the LAN": "ARP is unrelated to router queue overflow.",
            },
        ),
    ],
    medium=[
        (
            "OSI and TCP/IP",
            "Which pairing correctly matches a protocol to its typical TCP/IP layer?",
            "UDP — transport; IP — internet; Ethernet — link",
            ["HTTP — transport; IP — application; UDP — link",
             "TCP — network; DNS — physical; ARP — transport",
             "ICMP — application; TLS — link; BGP — transport"],
            "End systems stack applications over TCP/UDP, then IP, then link technologies.",
            {
                "HTTP — transport; IP — application; UDP — link": "HTTP is application-layer; IP is not application; UDP is not link.",
                "TCP — network; DNS — physical; ARP — transport": "TCP is transport; DNS is application; ARP is link-adjacent resolution.",
                "ICMP — application; TLS — link; BGP — transport": "ICMP is network control; TLS sits above transport; BGP is inter-domain routing.",
            },
        ),
        (
            "IP Addressing",
            "How many usable host addresses does a /24 IPv4 subnet have (excluding network and broadcast)?",
            "254",
            ["256", "512", "1022"],
            "/24 leaves 8 host bits: 2^8 − 2 = 254 usable addresses on classic IPv4 subnets.",
            {
                "256": "256 is 2^8 total addresses, but network and broadcast addresses are not assigned to hosts.",
                "512": "512 would correspond to nine host bits, not eight.",
                "1022": "1022 is usable hosts in a /22, not a /24.",
            },
        ),
        (
            "TCP and UDP",
            "TCP flow control primarily uses which mechanism?",
            "Receive window advertised in ACKs",
            ["Random early detection in routers",
             "TTL decrements on each hop",
             "CNAME chains in DNS"],
            "The receiver's window tells the sender how much buffer space is available, preventing overrun.",
            {
                "Random early detection in routers": "RED is an active queue management policy for congestion, not TCP flow control.",
                "TTL decrements on each hop": "TTL limits packet lifetime, not sender rate to receiver buffers.",
                "CNAME chains in DNS": "DNS aliases do not regulate TCP sending rates.",
            },
        ),
        (
            "Routing",
            "Longest-prefix matching in a routing table means…",
            "The most specific (longest) matching route wins for a destination",
            ["The route with the fewest hops always wins",
             "The first route inserted in the table wins",
             "Only default routes may be used"],
            "If both 10.0.0.0/8 and 10.1.0.0/16 match, the /16 route is chosen because it is longer.",
            {
                "The route with the fewest hops always wins": "Hop count may matter inside a protocol, but forwarding uses prefix specificity first.",
                "The first route inserted in the table wins": "Order alone does not define IP forwarding; match length does.",
                "Only default routes may be used": "Default 0.0.0.0/0 is used only when no more-specific route matches.",
            },
        ),
        (
            "DNS",
            "What is the main purpose of a DNS caching resolver?",
            "Answer repeated queries locally using TTL-based cached records",
            ["Authoritatively store all Internet domain registrations",
             "Encrypt HTTP payloads end-to-end",
             "Assign MAC addresses on Wi-Fi"],
            "Resolvers cache RRsets until TTL expires, reducing load on authoritative servers and latency.",
            {
                "Authoritatively store all Internet domain registrations": "Registrars and authoritative servers hold zone data; resolvers cache copies.",
                "Encrypt HTTP payloads end-to-end": "TLS protects HTTP; DNS may use DNSSEC but that is separate from caching.",
                "Assign MAC addresses on Wi-Fi": "DHCP/SLAAC and link layers handle addressing on LANs.",
            },
        ),
        (
            "HTTP",
            "HTTP/1.1 persistent connections allow…",
            "Multiple requests and responses on the same TCP connection",
            ["Only one request per TCP connection ever",
             "UDP transport for all web pages",
             "Automatic conversion of GET to POST"],
            "Keep-alive reuses TCP, amortizing handshake cost; pipelining/chunking evolved further in later versions.",
            {
                "Only one request per TCP connection ever": "That was common in HTTP/1.0 without Keep-Alive, not HTTP/1.1 default behavior.",
                "UDP transport for all web pages": "HTTP runs over TCP (or QUIC in HTTP/3), not classic UDP web transport.",
                "Automatic conversion of GET to POST": "Methods are chosen by the client; servers do not silently rewrite them.",
            },
        ),
        (
            "Congestion Control",
            "TCP slow start initially increases the congestion window…",
            "Exponentially each RTT until a threshold or loss is detected",
            ["Linearly by one MSS per RTT from the first packet",
             "Not at all until the connection closes",
             "Only when the receiver sends FIN"],
            "During slow start, cwnd doubles roughly every RTT (for each ACKed segment), probing available bandwidth.",
            {
                "Linearly by one MSS per RTT from the first packet": "Linear increase is congestion avoidance after slow start or threshold.",
                "Not at all until the connection closes": "Slow start explicitly grows the window at connection start.",
                "Only when the receiver sends FIN": "FIN ends the connection; slow start applies at the beginning.",
            },
        ),
        (
            "Switching",
            "A broadcast domain in a switched LAN is typically…",
            "The set of ports that receive a broadcast frame (e.g., destination MAC FF:FF:FF:FF:FF:FF)",
            ["Exactly one TCP connection",
             "All routers in the global Internet",
             "Only hosts with public IPv4 addresses"],
            "Broadcasts flood within a VLAN/broadcast domain unless constrained by routers or L3 switches.",
            {
                "Exactly one TCP connection": "TCP connections are transport-layer sessions between two endpoints.",
                "All routers in the global Internet": "The Internet is partitioned into many broadcast domains separated by routers.",
                "Only hosts with public IPv4 addresses": "Private addresses still participate in LAN broadcast domains.",
            },
        ),
        (
            "OSI and TCP/IP",
            "Encapsulation as data moves down the stack means…",
            "Each layer adds its own header (and sometimes trailer) around the payload from the layer above",
            ["Only the application layer adds headers",
             "Headers are removed at every hop without change",
             "IP addresses are replaced by MAC addresses globally"],
            "A TCP segment becomes payload inside an IP datagram, which is payload inside an Ethernet frame.",
            {
                "Only the application layer adds headers": "Transport, network, and link layers all add headers/trailers.",
                "Headers are removed at every hop without change": "Headers are processed and often rewritten (e.g., TTL, MACs) per hop.",
                "IP addresses are replaced by MAC addresses globally": "IP end-to-end identifiers remain; MACs are hop-by-hop on each link.",
            },
        ),
        (
            "IP Addressing",
            "Network Address Translation (NAT) on a home router allows…",
            "Many private hosts to share one public IPv4 address using port translation",
            ["Unlimited new public IPv4 addresses for every LAN host",
             "IPv6-only communication without any translation",
             "DNSSEC validation for all zones"],
            "NAT maps (private IP, port) tuples to (public IP, port) on outbound flows and reverses inbound replies.",
            {
                "Unlimited new public IPv4 addresses for every LAN host": "NAT conserves addresses; it does not mint new public ones per host.",
                "IPv6-only communication without any translation": "NAT64/DNS64 exist for IPv6↔IPv4, but classic NAT is an IPv4 workaround.",
                "DNSSEC validation for all zones": "DNSSEC is about DNS authenticity, not IPv4 address sharing.",
            },
        ),
        (
            "TCP and UDP",
            "Which field in the TCP header helps the receiver detect duplicate or out-of-order segments?",
            "Sequence number",
            ["UDP checksum only", "Ethernet type", "HTTP ETag"],
            "Sequence numbers label the byte stream so the receiver can acknowledge cumulatively and reorder.",
            {
                "UDP checksum only": "UDP checksum covers the datagram but does not provide byte-stream ordering.",
                "Ethernet type": "EtherType identifies the encapsulated protocol, not TCP byte positions.",
                "HTTP ETag": "ETags are application-layer cache validators, not transport sequencing.",
            },
        ),
        (
            "Routing",
            "Distance-vector routing protocols (e.g., RIP) advertise…",
            "Periodic updates of reachability metrics to neighbors",
            ["The entire link-state database to every router in the world",
             "Only MAC address tables",
             "HTML cache headers"],
            "Routers tell neighbors their best known distances; Bellman-Ford style computation selects paths.",
            {
                "The entire link-state database to every router in the world": "Link-state protocols flood topology; distance-vector shares vectors to neighbors.",
                "Only MAC address tables": "MAC tables are for switches on a LAN.",
                "HTML cache headers": "Cache-Control is an HTTP concept, not a routing protocol payload.",
            },
        ),
        (
            "DNS",
            "A DNS iterative query from a resolver to a root server typically receives…",
            "A referral to a TLD nameserver rather than the final answer",
            ["The A record for www.example.com immediately",
             "A TCP RST",
             "An HTTP 301 redirect"],
            "Iterative resolution walks the hierarchy: root → TLD → authoritative, with referrals along the way.",
            {
                "The A record for www.example.com immediately": "The root usually does not know leaf records; it delegates.",
                "A TCP RST": "DNS runs over UDP/TCP port 53, not as arbitrary TCP resets from roots.",
                "An HTTP 301 redirect": "HTTP redirects are unrelated to DNS iterative resolution.",
            },
        ),
        (
            "HTTP",
            "An HTTP GET request is defined as…",
            "Safe and idempotent retrieval of a representation (should not change server state by convention)",
            ["Always carrying a JSON body that creates resources",
             "Encrypted by TLS inside the TCP header",
             "A replacement for DNS A queries"],
            "GET fetches resources; side effects belong in POST/PUT/PATCH/DELETE per method semantics.",
            {
                "Always carrying a JSON body that creates resources": "Bodies on GET are discouraged; creation uses POST/PUT.",
                "Encrypted by TLS inside the TCP header": "TLS encrypts the connection above TCP; it is not inside the TCP header.",
                "A replacement for DNS A queries": "DNS resolves names; HTTP requests resources from servers.",
            },
        ),
        (
            "Congestion Control",
            "Explicit Congestion Notification (ECN) allows routers to…",
            "Mark IP packets instead of dropping them, signaling congestion to TCP endpoints",
            ["Disable TCP acknowledgments",
             "Increase link speed automatically",
             "Bypass DNS entirely"],
            "ECN-capable routers set CE bits; TCP reacts similarly to loss without always discarding packets.",
            {
                "Disable TCP acknowledgments": "TCP still ACKs; ECN modifies how congestion is signaled.",
                "Increase link speed automatically": "ECN does not change physical link rates.",
                "Bypass DNS entirely": "ECN is an IP/TCP feature unrelated to name resolution.",
            },
        ),
        (
            "Switching",
            "Spanning Tree Protocol (STP) on switches prevents…",
            "Bridging loops that would cause broadcast storms",
            ["IP address exhaustion on the Internet",
             "TCP three-way handshakes from completing",
             "HTTPS certificate expiration"],
            "STP blocks redundant paths logically so only one active tree forwards frames between segments.",
            {
                "IP address exhaustion on the Internet": "That is an addressing/policy issue, not a layer-2 loop issue.",
                "TCP three-way handshakes from completing": "STP affects Ethernet topology, not TCP state machines directly.",
                "HTTPS certificate expiration": "Certificates are application/TLS concerns.",
            },
        ),
        (
            "TCP and UDP",
            "The TCP checksum covers which parts (conceptually)?",
            "TCP header, payload, and a pseudo-header with IP addresses and protocol",
            ["Only the Ethernet FCS",
             "Only the HTTP response body",
             "Only the DNS query name"],
            "The pseudo-header ties the segment to the IP endpoints so misdelivery corrupts the checksum.",
            {
                "Only the Ethernet FCS": "FCS protects the frame on the wire; TCP has its own end-to-end checksum.",
                "Only the HTTP response body": "HTTP is payload inside TCP; TCP checksum covers more than application data alone.",
                "Only the DNS query name": "DNS over UDP/TCP has its own checks; TCP checksum is transport-wide.",
            },
        ),
        (
            "Routing",
            "Link-state routing (e.g., OSPF) requires each router to…",
            "Flood reliable link-state advertisements and run Dijkstra locally",
            ["Exchange only hop counts with no topology map",
             "Learn routes exclusively from DHCP",
             "Use HTTP caching headers to pick paths"],
            "With a consistent LSDB, each router computes shortest paths independently using link weights.",
            {
                "Exchange only hop counts with no topology map": "That describes distance-vector style updates, not full link-state flooding.",
                "Learn routes exclusively from DHCP": "DHCP may give hosts a default route, not intra-domain OSPF topology.",
                "Use HTTP caching headers to pick paths": "Routing protocols do not use HTTP cache directives.",
            },
        ),
        (
            "DNS",
            "DNS over UDP typically uses truncation (TC bit) when…",
            "The response is too large for UDP, prompting retry over TCP",
            ["The client sends a SYN packet",
             "HTTP returns status 500",
             "A switch MAC table overflows"],
            "Large responses (many records) exceed UDP payload limits; TCP DNS carries the full message.",
            {
                "The client sends a SYN packet": "SYN is TCP connection setup, not a DNS UDP field.",
                "HTTP returns status 500": "HTTP errors are unrelated to DNS TC.",
                "A switch MAC table overflows": "Switch scaling issues do not set the DNS TC bit.",
            },
        ),
        (
            "HTTP",
            "The Host header in HTTP/1.1 is important because…",
            "It specifies the authority (hostname) for virtual hosting on a shared IP",
            ["It replaces TCP port numbers entirely",
             "It encrypts the request body",
             "It stores the client's MAC address"],
            "Multiple sites can share one IP; Host tells the server which name the client intended.",
            {
                "It replaces TCP port numbers entirely": "TCP still uses ports; Host names the logical site.",
                "It encrypts the request body": "TLS encrypts; Host is cleartext metadata in HTTP/1.1.",
                "It stores the client's MAC address": "MAC addresses are link-layer and not carried in HTTP Host.",
            },
        ),
    ],
    hard=[
        (
            "OSI and TCP/IP",
            "Why is strict OSI layering often blurred in real implementations (e.g., TCP checksum pseudo-header)?",
            "Practical stacks violate pure layering for performance and end-to-end integrity",
            ["Because IP is actually an application protocol",
             "Because Ethernet switches must parse HTTP headers",
             "Because DNS runs below the physical layer"],
            "Cross-layer information (pseudo-header, offload, QUIC in user space) trades purity for speed and correctness.",
            {
                "Because IP is actually an application protocol": "IP remains network-layer datagram delivery.",
                "Because Ethernet switches must parse HTTP headers": "Switches need not parse HTTP for basic forwarding.",
                "Because DNS runs below the physical layer": "DNS is application-layer naming, above transport.",
            },
        ),
        (
            "IP Addressing",
            "IPv6 Stateless Address Autoconfiguration (SLAAC) combines…",
            "Router Advertisements (prefix) with interface identifiers (often EUI-64 or privacy extensions)",
            ["DHCPv4 OFFER packets with ARP replies",
             "HTTP 302 redirects with TLS session tickets",
             "BGP AS_PATH prepending on every host"],
            "Hosts learn prefixes from RA messages and form addresses without a DHCP server for basic connectivity.",
            {
                "DHCPv4 OFFER packets with ARP replies": "Those are IPv4/Ethernet mechanisms, not IPv6 SLAAC.",
                "HTTP 302 redirects with TLS session tickets": "Web protocols do not configure IPv6 addressing.",
                "BGP AS_PATH prepending on every host": "BGP is inter-domain routing between routers, not host autoconfig.",
            },
        ),
        (
            "TCP and UDP",
            "TCP Reno reacts to a timeout (RTO) primarily by…",
            "Setting ssthresh to cwnd/2, resetting cwnd to 1 MSS, and retransmitting the earliest unACKed segment",
            ["Immediately closing the connection with FIN",
             "Switching to UDP for the rest of the flow",
             "Ignoring loss because cumulative ACKs always recover"],
            "Timeout implies severe congestion; Reno collapses the window and begins slow start again.",
            {
                "Immediately closing the connection with FIN": "Timeouts trigger retransmit and window collapse, not mandatory FIN.",
                "Switching to UDP for the rest of the flow": "Transport protocol does not change mid-connection.",
                "Ignoring loss because cumulative ACKs always recover": "Timeouts exist precisely when ACK-based recovery is insufficient.",
            },
        ),
        (
            "Routing",
            "BGP path selection between two valid routes to the same prefix typically considers (among other knobs)…",
            "Local policy attributes (LOCAL_PREF, AS_PATH length, MED) before installing a route",
            ["Only the color of the fiber cable",
             "The HTTP User-Agent string of clients",
             "The TTL of DNS caches"],
            "BGP is policy-driven inter-domain routing; attribute comparison implements operator preferences.",
            {
                "Only the color of the fiber cable": "Physical appearance is irrelevant to BGP decision processes.",
                "The HTTP User-Agent string of clients": "BGP runs between routers, not from browser headers.",
                "The TTL of DNS caches": "DNS TTL does not influence BGP best-path selection.",
            },
        ),
        (
            "DNS",
            "DNSSEC primarily provides…",
            "Authentication and integrity of DNS data via chained signatures, not confidentiality",
            ["Encryption of all DNS queries so ISPs cannot see QNAMEs",
             "Automatic NAT traversal for TCP",
             "Replacement of TCP congestion control"],
            "DNSSEC signs RRsets; resolvers validate from trust anchors. QNAMEs may still leak without DNS-over-TLS/HTTPS.",
            {
                "Encryption of all DNS queries so ISPs cannot see QNAMEs": "Privacy needs DoT/DoH; DNSSEC does not encrypt queries by default.",
                "Automatic NAT traversal for TCP": "NAT traversal uses other mechanisms (STUN/ICE), not DNSSEC.",
                "Replacement of TCP congestion control": "DNSSEC is unrelated to transport congestion algorithms.",
            },
        ),
        (
            "HTTP",
            "HTTP/2 multiplexing improves on HTTP/1.1 chiefly by…",
            "Interleaving many streams over one TCP connection with binary framing and stream IDs",
            ["Opening a new TCP connection per image unconditionally",
             "Sending all resources over UDP port 53",
             "Eliminating TLS entirely"],
            "HTTP/2 avoids head-of-line blocking at the HTTP layer (though TCP HOL remains until HTTP/3/QUIC).",
            {
                "Opening a new TCP connection per image unconditionally": "That was an HTTP/1.1 workaround; HTTP/2 reduces parallel connections.",
                "Sending all resources over UDP port 53": "HTTP/2 still runs over TCP/TLS in common deployments, not DNS UDP.",
                "Eliminating TLS entirely": "HTTPS still uses TLS; HTTP/2 is often negotiated inside TLS ALPN.",
            },
        ),
        (
            "Congestion Control",
            "TCP Cubic (common on Linux) models its window growth with a cubic function primarily to…",
            "Scale aggressively on high-bandwidth-delay-product paths while probing fairly after loss",
            ["Guarantee zero packet loss on the Internet",
             "Replace IP routing tables on every ACK",
             "Disable slow start permanently"],
            "Cubic targets W_max-dependent growth for high BDP links, improving throughput versus linear Reno on fat pipes.",
            {
                "Guarantee zero packet loss on the Internet": "Loss still occurs; Cubic adapts rates, it cannot eliminate congestion.",
                "Replace IP routing tables on every ACK": "Routing is separate; Cubic only adjusts sender congestion window.",
                "Disable slow start permanently": "Connections still begin with slow start; Cubic governs congestion avoidance growth.",
            },
        ),
        (
            "Switching",
            "VLANs (802.1Q) allow a single physical switch fabric to…",
            "Isolate broadcast domains logically using tagged Ethernet frames",
            ["Route IP packets between continents without routers",
             "Encrypt TCP payloads at layer 2 by default",
             "Assign TCP port 443 to every host"],
            "802.1Q tags carry VLAN IDs so ports can participate in multiple logical LANs securely segmented.",
            {
                "Route IP packets between continents without routers": "Inter-VLAN routing still needs a router or L3 switch.",
                "Encrypt TCP payloads at layer 2 by default": "VLANs segment traffic; encryption is not their primary function.",
                "Assign TCP port 443 to every host": "Port numbers are transport endpoints on hosts, not VLAN tags.",
            },
        ),
        (
            "OSI and TCP/IP",
            "The primary reason QUIC (HTTP/3) moves reliability into user space over UDP is to…",
            "Reduce transport-layer head-of-line blocking and enable faster connection establishment with integrated TLS",
            ["Avoid using any encryption on the web",
             "Eliminate the need for IP addresses",
             "Make DNS iterative queries obsolete"],
            "QUIC multiplexes streams with independent loss recovery and combines crypto with setup, unlike single-byte-stream TCP.",
            {
                "Avoid using any encryption on the web": "QUIC mandates TLS 1.3 integration for security.",
                "Eliminate the need for IP addresses": "QUIC still runs over IP (v4 or v6).",
                "Make DNS iterative queries obsolete": "HTTP still relies on DNS (or alternatives like DoH) for naming.",
            },
        ),
        (
            "IP Addressing",
            "CIDR aggregation in the global routing table helps providers…",
            "Advertise a shorter prefix covering many customer subnets, shrinking table size",
            ["Assign duplicate public IPv4 addresses to different continents safely",
             "Remove the need for default routes on hosts",
             "Store MAC addresses inside DNS A records"],
            "Summarization (e.g., aggregating /24s into a /16 announcement) reduces BGP churn and memory.",
            {
                "Assign duplicate public IPv4 addresses to different continents safely": "Public addresses must remain globally unique.",
                "Remove the need for default routes on hosts": "Hosts still need defaults to reach non-local prefixes.",
                "Store MAC addresses inside DNS A records": "A records hold IP addresses, not Ethernet MACs.",
            },
        ),
        (
            "TCP and UDP",
            "Selective Acknowledgments (SACK) in TCP allow the sender to…",
            "Retransmit only missing segments when multiple disjoint ranges are outstanding",
            ["Ignore all losses after the first duplicate ACK",
             "Send data without ever numbering bytes",
             "Run without any receiver window"],
            "SACK blocks in options describe non-contiguous received data, improving recovery on multiple losses.",
            {
                "Ignore all losses after the first duplicate ACK": "Duplicate ACKs trigger fast retransmit; SACK refines which segments to resend.",
                "Send data without ever numbering bytes": "Sequence numbers are still fundamental to TCP.",
                "Run without any receiver window": "Flow control still uses the receive window alongside SACK.",
            },
        ),
        (
            "Routing",
            "Equal-cost multi-path (ECMP) forwarding sends flows along different next hops by often hashing…",
            "Five-tuple (src/dst IP, protocol, ports) so packets of a flow stay on one path",
            ["Only the HTTP Server header",
             "The DNS TTL value alone",
             "Random MAC addresses per packet on WAN links"],
            "Per-flow hashing preserves ordering within a TCP connection while utilizing parallel links.",
            {
                "Only the HTTP Server header": "Routers forward on IP headers before HTTP is visible (if at all).",
                "The DNS TTL value alone": "TTL in DNS records is unrelated to router ECMP hash keys.",
                "Random MAC addresses per packet on WAN links": "WAN routing uses IP forwarding; MACs change per hop on L2 segments.",
            },
        ),
        (
            "DNS",
            "A DNS negative cache entry (NXDOMAIN) prevents…",
            "Repeated queries for names that do not exist until the SOA MINIMUM TTL expires",
            ["Encryption of TLS certificates",
             "TCP slow start on new connections",
             "Ethernet STP reconvergence"],
            "Resolvers cache failures as well as successes, reducing load during typos or attacks.",
            {
                "Encryption of TLS certificates": "Certificates are validated in TLS, not by DNS negative caching.",
                "TCP slow start on new connections": "Negative DNS caching does not alter TCP congestion algorithms.",
                "Ethernet STP reconvergence": "STP is a layer-2 loop prevention protocol.",
            },
        ),
        (
            "HTTP",
            "HTTP conditional GET with If-None-Match: <etag> can yield status 304 when…",
            "The representation is unchanged and the server allows reuse of the cached copy",
            ["The TCP connection was reset",
             "DNS returns NXDOMAIN",
             "The client's MAC address changed"],
            "304 Not Modified saves bandwidth: the body is omitted but caches revalidate metadata.",
            {
                "The TCP connection was reset": "Resets abort the connection; they do not produce a valid 304 response.",
                "DNS returns NXDOMAIN": "NXDOMAIN means the name does not exist, unrelated to HTTP validators.",
                "The client's MAC address changed": "Link-layer changes do not drive HTTP entity-tag validation.",
            },
        ),
        (
            "Congestion Control",
            "Bufferbloat is problematic because large router queues…",
            "Add excessive delay (latency) even at moderate utilization, hurting interactive traffic",
            ["Prevent switches from learning MAC addresses",
             "Disable DNSSEC chain of trust",
             "Force all HTTP requests to use POST"],
            "Large buffers keep packets queued, inflating RTT and confusing TCP's congestion signals (delay-based CC targets this).",
            {
                "Prevent switches from learning MAC addresses": "MAC learning is independent of WAN queue sizing.",
                "Disable DNSSEC chain of trust": "DNSSEC validation is unrelated to queue depth.",
                "Force all HTTP requests to use POST": "HTTP methods are chosen by clients/servers, not queue length.",
            },
        ),
        (
            "Switching",
            "Cut-through switching differs from store-and-forward because it…",
            "Begins forwarding after reading the destination MAC, before the entire frame arrives",
            ["Waits for TCP acknowledgment before sending frames",
             "Requires IP fragmentation on every packet",
             "Only works with HTTP/3 QUIC streams"],
            "Cut-through reduces latency but may forward corrupted frames because the FCS was not checked yet.",
            {
                "Waits for TCP acknowledgment before sending frames": "Switches operate on frames, not TCP ACKs.",
                "Requires IP fragmentation on every packet": "Fragmentation is an IP feature, not a switch forwarding mode requirement.",
                "Only works with HTTP/3 QUIC streams": "Switching is layer-2; application protocols are irrelevant.",
            },
        ),
        (
            "TCP and UDP",
            "SYN cookies mitigate SYN flood attacks by…",
            "Encoding connection state cryptographically in the initial sequence number instead of storing half-open state",
            ["Dropping all SYN packets unconditionally",
             "Switching from TCP to ICMP for web traffic",
             "Disabling three-way handshakes entirely"],
            "Under load, the server can still reply SYN-ACK without reserving full TCB until ACK validates the cookie.",
            {
                "Dropping all SYN packets unconditionally": "That would deny service to everyone, not mitigate selectively.",
                "Switching from TCP to ICMP for web traffic": "Web traffic remains TCP/TLS; SYN cookies are a TCP server technique.",
                "Disabling three-way handshakes entirely": "Handshake still occurs; state is encoded, not removed.",
            },
        ),
        (
            "Routing",
            "Policy-based routing differs from destination longest-prefix forwarding because it…",
            "Can forward traffic based on source, DSCP, or interface policy before the usual FIB lookup",
            ["Only uses Ethernet broadcast addresses",
             "Requires HTTP/2 server push on all packets",
             "Eliminates the need for IP headers"],
            "PBR applies route maps/ACLs to steer traffic (e.g., force VPN egress) beyond destination-only tables.",
            {
                "Only uses Ethernet broadcast addresses": "IP routing uses prefixes, not broadcast MACs on WAN paths.",
                "Requires HTTP/2 server push on all packets": "Routing is layer-3; HTTP features are not consulted per packet.",
                "Eliminates the need for IP headers": "IP headers remain essential for any IP routing decision.",
            },
        ),
        (
            "DNS",
            "An ANY query in classic DNS was deprecated largely because…",
            "It encouraged amplification attacks and oversized responses",
            ["It encrypted all answers with TLS 1.3",
             "It replaced AAAA records for IPv6",
             "It made BGP converge faster"],
            "ANY responses can be huge, aiding reflection/amplification; operators now prefer type-specific queries.",
            {
                "It encrypted all answers with TLS 1.3": "DNS ANY was not an encryption mechanism.",
                "It replaced AAAA records for IPv6": "IPv6 uses AAAA; ANY was a meta-query type.",
                "It made BGP converge faster": "BGP convergence is unrelated to DNS query types.",
            },
        ),
        (
            "HTTP",
            "Cross-Origin Resource Sharing (CORS) preflight OPTIONS requests exist because…",
            "Browsers must check server permission before non-simple cross-origin methods/headers",
            ["TCP requires OPTIONS before SYN",
             "DNS roots only answer OPTIONS queries",
             "Switches must learn MACs via HTTP"],
            "Preflight lets servers declare allowed origins/methods/headers for XHR/fetch across origins.",
            {
                "TCP requires OPTIONS before SYN": "TCP handshake uses SYN, not HTTP OPTIONS.",
                "DNS roots only answer OPTIONS queries": "DNS does not use HTTP methods.",
                "Switches must learn MACs via HTTP": "MAC learning uses Ethernet frames, not CORS.",
            },
        ),
    ],
)
