"""Quiz bank: Operating Systems (OSTEP)."""
from quiz_banks._make_book import make_book

EASY = [
    (
        "Processes",
        "What does a process control block (PCB) primarily store?",
        "Per-process kernel metadata such as registers, state, and scheduling info.",
        [
            "The entire contents of the process heap and stack.",
            "Only the program's machine code on disk.",
            "A list of every file ever opened on the system.",
        ],
        "The PCB is the kernel's record for a process: identifiers, CPU context, memory pointers, and scheduling state—not a full memory dump.",
        {
            "The entire contents of the process heap and stack.": "Process memory lives in separate address-space structures; the PCB holds pointers and metadata, not full heaps.",
            "Only the program's machine code on disk.": "Executable code is stored in files and mapped pages, not duplicated wholesale in the PCB.",
            "A list of every file ever opened on the system.": "Open files are tracked per process, but not as a global history of all system activity.",
        },
    ),
    (
        "Processes",
        "After a successful fork() in Unix, what does fork() return in the child?",
        "0",
        ["The child's PID", "The parent's PID", "−1"],
        "fork() returns 0 to the child and the child's PID to the parent; −1 indicates failure.",
        {
            "The child's PID": "The child receives 0; the parent receives the new PID.",
            "The parent's PID": "The parent gets the child's PID, not its own.",
            "−1": "−1 signals failure, not success in the child.",
        },
    ),
    (
        "Processes",
        "A context switch between two processes requires the kernel to…",
        "Save and restore CPU register state and switch to the other process's address space.",
        [
            "Copy the entire disk image of each process.",
            "Recompile both programs from source.",
            "Flush every file on the system to disk.",
        ],
        "Scheduling swaps the running context: register image, stack pointer, page tables or address-space ID, and related kernel bookkeeping.",
        {
            "Copy the entire disk image of each process.": "Processes are not duplicated at the storage layer on each switch.",
            "Recompile both programs from source.": "Executables are already loaded; switching is a runtime operation.",
            "Flush every file on the system to disk.": "Context switches do not require global filesystem sync.",
        },
    ),
    (
        "Threads",
        "Threads in the same process typically share…",
        "Address space, open file descriptors, and signal disposition.",
        [
            "Separate private address spaces",
            "Independent copies of the entire heap only",
            "Nothing; each thread is a separate process",
        ],
        "Threads are lightweight execution units within one process: they share memory and OS resources attached to that process.",
        {
            "Separate private address spaces": "That describes different processes, not threads in one process.",
            "Independent copies of the entire heap only": "Sharing is broader than heap copies and includes code, globals, and OS handles.",
            "Nothing; each thread is a separate process": "Threads deliberately share process resources; processes do not.",
        },
    ),
    (
        "Threads",
        "On a single-core CPU, running multiple threads can still improve overall throughput when…",
        "Some threads block on I/O while others run.",
        [
            "All threads are CPU-bound and never block",
            "Threads eliminate the need for the scheduler",
            "Each thread must busy-wait on a lock",
        ],
        "Overlapping computation with I/O waits keeps the CPU busy; pure CPU-bound work on one core does not speed up with more threads.",
        {
            "All threads are CPU-bound and never block": "With no blocking, one core cannot run threads in parallel—only interleaved.",
            "Threads eliminate the need for the scheduler": "More threads increase scheduling work, not remove it.",
            "Each thread must busy-wait on a lock": "Busy-waiting wastes CPU time and hurts throughput.",
        },
    ),
    (
        "Scheduling",
        "First-Come, First-Served (FCFS) scheduling is…",
        "Non-preemptive: a job runs until it finishes or blocks.",
        [
            "Preemptive on every memory access",
            "Always optimal for average turnaround time",
            "Identical to shortest-remaining-time-first",
        ],
        "FCFS runs jobs in arrival order without time-slice preemption, which can cause convoy effects behind long jobs.",
        {
            "Preemptive on every memory access": "FCFS does not preempt based on memory references.",
            "Always optimal for average turnaround time": "Long jobs at the front can inflate waiting time for everyone behind them.",
            "Identical to shortest-remaining-time-first": "SRTF preempts on remaining time; FCFS does not.",
        },
    ),
    (
        "Scheduling",
        "Round-robin scheduling requires defining…",
        "A time quantum (time slice).",
        [
            "The exact burst time of every job in advance",
            "A static priority that never changes",
            "That all jobs have equal memory footprints",
        ],
        "RR gives each ready job up to one quantum before moving it to the tail of the ready queue.",
        {
            "The exact burst time of every job in advance": "RR is preemptive by time, not by known burst lengths.",
            "A static priority that never changes": "Priorities are central to priority schedulers, not basic RR.",
            "That all jobs have equal memory footprints": "Memory size is unrelated to RR's time-slice rule.",
        },
    ),
    (
        "Scheduling",
        "Non-preemptive Shortest Job First (SJF) minimizes which metric for a given set of jobs (all available at time 0)?",
        "Average waiting time.",
        [
            "Maximum turnaround time for every job",
            "CPU utilization on a multi-core machine only",
            "Number of context switches in a real-time system with deadlines",
        ],
        "Among non-preemptive orders with known bursts, SJF is optimal for average waiting time; it is not optimal for every per-job metric.",
        {
            "Maximum turnaround time for every job": "A very short job last could still have high turnaround; SJF optimizes averages, not every max.",
            "CPU utilization on a multi-core machine only": "SJF is a uniprocessor ordering property here, not a multicore utilization guarantee.",
            "Number of context switches in a real-time system with deadlines": "Context switches and deadline feasibility are different objectives.",
        },
    ),
    (
        "Virtual Memory",
        "A primary reason operating systems use virtual memory is to…",
        "Give each process a large, private address space while mapping only used pages to RAM.",
        [
            "Make physical RAM unnecessary",
            "Guarantee zero page faults after startup",
            "Store all data only on the CPU stack",
        ],
        "Virtual memory decouples logical addresses from physical frames, enabling protection, sharing, and demand loading.",
        {
            "Make physical RAM unnecessary": "Virtual memory still backs hot pages with physical RAM.",
            "Guarantee zero page faults after startup": "Demand paging causes faults when pages are first touched.",
            "Store all data only on the CPU stack": "Processes use heap, mappings, and files—not just the stack.",
        },
    ),
    (
        "Virtual Memory",
        "A page fault on a demand-paged system usually means…",
        "The referenced page is not currently mapped in physical memory (or permissions failed).",
        [
            "The CPU has failed permanently",
            "The disk is full so the OS must halt",
            "The process has no valid page table",
        ],
        "A fault traps to the OS, which may load the page, grow the stack, or deliver a segmentation fault for illegal access.",
        {
            "The CPU has failed permanently": "Page faults are normal control events handled by the OS.",
            "The disk is full so the OS must halt": "Faults can occur for many reasons; full disk is one possible failure mode, not the definition.",
            "The process has no valid page table": "User processes have page tables; faults reference valid tables with missing or protected entries.",
        },
    ),
    (
        "Paging",
        "In a paging system, a virtual address is commonly split into…",
        "A page number and an offset within the page.",
        [
            "A segment name and line number only",
            "An inode number and block offset only",
            "A process ID and thread ID only",
        ],
        "The page number indexes the page table; the offset indexes a byte within the chosen frame.",
        {
            "A segment name and line number only": "That mixes segmentation terminology with unrelated line numbers.",
            "An inode number and block offset only": "Inode/block pairs belong to file indexing, not CPU virtual addresses.",
            "A process ID and thread ID only": "Identifiers are not the standard virtual-address partition for paging.",
        },
    ),
    (
        "Paging",
        "Internal fragmentation in paging refers to…",
        "Unused bytes within the last page allocated to a region.",
        [
            "Free space between unrelated processes on disk",
            "Bytes lost when segments of different sizes are packed",
            "Time wasted in the scheduler queue",
        ],
        "If a process needs slightly more than k pages, the final page may be only partly used—waste inside the page granularity.",
        {
            "Free space between unrelated processes on disk": "That is not the usual definition of internal fragmentation in paging.",
            "Bytes lost when segments of different sizes are packed": "Variable-sized segments relate to segmentation/external fragmentation concepts.",
            "Time wasted in the scheduler queue": "That is scheduling delay, not memory fragmentation.",
        },
    ),
    (
        "File Systems",
        "In Unix-like systems, an inode primarily stores…",
        "File metadata (permissions, size, timestamps, block pointers) but not the file name.",
        [
            "The directory path string as the canonical name",
            "The user's password hash",
            "The list of all running processes",
        ],
        "Directory entries map names to inode numbers; the inode holds on-disk structure for the file object itself.",
        {
            "The directory path string as the canonical name": "Paths are resolved via directory entries; names live in directories, not inodes.",
            "The user's password hash": "Authentication data lives in system databases, not per-file inodes.",
            "The list of all running processes": "Process tables are kernel structures unrelated to inodes.",
        },
    ),
    (
        "File Systems",
        "A directory entry in a typical Unix file system associates a file name with…",
        "An inode number.",
        [
            "The file's entire data blocks inline",
            "The physical sector of the disk motor",
            "The PID of the process that created the file",
        ],
        "Lookup reads the directory mapping name → inode, then loads metadata from the inode.",
        {
            "The file's entire data blocks inline": "Directory entries are small; data blocks are referenced from the inode.",
            "The physical sector of the disk motor": "Directories map names to inode indices, not hardware motor sectors.",
            "The PID of the process that created the file": "Creation PID is not the standard directory entry payload.",
        },
    ),
    (
        "Concurrency",
        "A critical section is…",
        "Code that accesses shared mutable state and must not run concurrently with other such code.",
        [
            "Any function that performs I/O to disk",
            "The boot loader's first 512 bytes",
            "A region of virtual memory that is always read-only",
        ],
        "Mutual exclusion protects critical sections so updates to shared data remain consistent.",
        {
            "Any function that performs I/O to disk": "I/O alone does not define a critical section; sharing and mutation do.",
            "The boot loader's first 512 bytes": "That is a disk layout artifact, not a synchronization concept.",
            "A region of virtual memory that is always read-only": "Read-only mappings need no mutex for writers.",
        },
    ),
    (
        "Concurrency",
        "A mutex (lock) is used to…",
        "Ensure at most one thread executes a protected critical section at a time.",
        [
            "Increase parallelism by allowing unlimited concurrent writers",
            "Replace the need for any page table",
            "Sort ready-queue jobs by shortest burst time",
        ],
        "Locks serialize access so invariants on shared structures hold during updates.",
        {
            "Increase parallelism by allowing unlimited concurrent writers": "Mutexes restrict concurrency to preserve correctness.",
            "Replace the need for any page table": "Memory translation is unrelated to locking.",
            "Sort ready-queue jobs by shortest burst time": "That is a scheduling policy, not mutual exclusion.",
        },
    ),
    (
        "Deadlocks",
        "Which condition is NOT required for deadlock in Coffman's classic four conditions?",
        "Preemption of resources (resources can be forcibly taken away).",
        [
            "Mutual exclusion",
            "Hold and wait",
            "Circular wait",
        ],
        "Deadlock needs mutual exclusion, hold-and-wait, no preemption, and circular wait; preemption prevents deadlock by breaking hold-and-wait chains.",
        {
            "Mutual exclusion": "Mutual exclusion is one of the four necessary conditions.",
            "Hold and wait": "Hold and wait is required for deadlock to arise.",
            "Circular wait": "Circular wait completes the cycle of waiting processes.",
        },
    ),
    (
        "Deadlocks",
        "Hold and wait means a process…",
        "Keeps resources it already holds while waiting for additional resources.",
        [
            "Releases all resources before requesting any",
            "Must finish I/O before requesting the CPU",
            "Cannot block in the kernel",
        ],
        "Hold-and-wait allows partial allocation, which can create cycles when combined with other conditions.",
        {
            "Releases all resources before requesting any": "That would violate hold-and-wait; some designs avoid deadlock by requiring atomic acquisition.",
            "Must finish I/O before requesting the CPU": "I/O ordering is unrelated to resource hold-and-wait.",
            "Cannot block in the kernel": "Processes block routinely; hold-and-wait is about resources, not blocking itself.",
        },
    ),
    (
        "I/O",
        "With programmed I/O (polling), the CPU…",
        "Repeatedly checks a device status register until the operation completes.",
        [
            "Sleeps until the device sends an interrupt",
            "Transfers data without ever touching device registers",
            "Offloads all copying to another process's page table",
        ],
        "Polling keeps the CPU in a tight loop testing ready bits—simple but wasteful while waiting.",
        {
            "Sleeps until the device sends an interrupt": "That describes interrupt-driven I/O, not polling.",
            "Transfers data without ever touching device registers": "Programmed I/O explicitly uses device registers.",
            "Offloads all copying to another process's page table": "Page tables are unrelated to device polling.",
        },
    ),
    (
        "I/O",
        "Interrupt-driven I/O allows the CPU to…",
        "Do other work until the device signals completion.",
        [
            "Eliminate all device drivers",
            "Guarantee devices need no buffers",
            "Avoid handling trap frames in the kernel",
        ],
        "The device raises an interrupt when attention is needed, reducing busy-wait compared with pure polling.",
        {
            "Eliminate all device drivers": "Drivers still manage devices; interrupts are how they get CPU attention.",
            "Guarantee devices need no buffers": "Buffering is still required for speed mismatches.",
            "Avoid handling trap frames in the kernel": "Interrupts enter the kernel via trap/interrupt handling.",
        },
    ),
]

MEDIUM = [
    (
        "Scheduling",
        "Shortest Remaining Time First (SRTF) differs from non-preemptive SJF because SRTF…",
        "Preempts the running job when a newly arrived job has shorter remaining time.",
        [
            "Never preempts and runs jobs strictly in arrival order",
            "Requires jobs to perform I/O after exactly one time quantum",
            "Ignores remaining burst time and uses only static priorities",
        ],
        "SRTF is preemptive SJF: the CPU may switch when a shorter job becomes ready.",
        {
            "Never preempts and runs jobs strictly in arrival order": "That describes FCFS, not SRTF.",
            "Requires jobs to perform I/O after exactly one time quantum": "I/O patterns are not part of SRTF's definition.",
            "Ignores remaining burst time and uses only static priorities": "SRTF is explicitly based on remaining time, not static priority alone.",
        },
    ),
    (
        "Scheduling",
        "Priority inversion occurs when…",
        "A high-priority task waits indirectly because a low-priority task holds a needed lock.",
        [
            "All tasks run at the same priority",
            "The CPU runs idle while the ready queue is empty",
            "A page fault replaces the wrong physical frame",
        ],
        "A medium-priority task can preempt the low-priority lock holder, delaying the high-priority waiter—classic inversion.",
        {
            "All tasks run at the same priority": "Equal priorities do not create inversion between high and low tasks.",
            "The CPU runs idle while the ready queue is empty": "That is idleness, not inversion.",
            "A page fault replaces the wrong physical frame": "That is a memory-management error, unrelated to scheduling priorities.",
        },
    ),
    (
        "Scheduling",
        "Multilevel feedback queues (MLFQ) often use priority aging to…",
        "Prevent starvation by gradually increasing the priority of long-waiting jobs.",
        [
            "Eliminate the need for time quanta",
            "Store executable code inside the ready queue nodes",
            "Guarantee zero context switches",
        ],
        "Without aging, low-priority jobs may never run; boosting priority after waiting addresses fairness.",
        {
            "Eliminate the need for time quanta": "Lower levels still commonly use quanta similar to round robin.",
            "Store executable code inside the ready queue nodes": "Queues hold scheduling entities, not program binaries.",
            "Guarantee zero context switches": "MLFQ scheduling still context-switches between jobs.",
        },
    ),
    (
        "Processes",
        "A zombie process in Unix is one that…",
        "Has exited but whose exit status has not yet been reaped by its parent.",
        [
            "Consumes maximum CPU in an infinite loop",
            "Has no page table and cannot run user code",
            "Shares no memory with its parent after fork",
        ],
        "The kernel retains a minimal PCB until wait() collects the exit code—hence 'zombie.'",
        {
            "Consumes maximum CPU in an infinite loop": "Zombies are not running; they are terminated entries awaiting reap.",
            "Has no page table and cannot run user code": "Zombies are dead processes, but the definition is about unreaped exit state.",
            "Shares no memory with its parent after fork": "Memory sharing is unrelated to zombie state after exit.",
        },
    ),
    (
        "Processes",
        "The exec family of system calls replaces…",
        "The current process image with a new program while keeping the same PID (in the same process).",
        [
            "Only the parent process with a new child PID",
            "The kernel's interrupt vector table",
            "Every thread in the system with a single global stack",
        ],
        "fork() duplicates; exec() loads a new executable into the calling process's address space.",
        {
            "Only the parent process with a new child PID": "exec does not create a new PID; fork does.",
            "The kernel's interrupt vector table": "exec affects user process memory, not CPU trap vectors globally.",
            "Every thread in the system with a single global stack": "exec affects one process image, not all threads system-wide.",
        },
    ),
    (
        "Threads",
        "Kernel-level threads are advantageous because…",
        "The kernel can schedule threads independently, even if one thread blocks in the kernel.",
        [
            "The kernel never needs to context-switch",
            "User code can ignore all synchronization",
            "They always use less memory than a single-threaded process",
        ],
        "Blocking in the kernel on one user thread does not necessarily block all threads if they are kernel threads.",
        {
            "The kernel never needs to context-switch": "More kernel threads can mean more switching, not less.",
            "User code can ignore all synchronization": "Shared memory still requires locks regardless of thread model.",
            "They always use less memory than a single-threaded process": "Thread structures add overhead; the benefit is schedulability, not guaranteed smaller footprint.",
        },
    ),
    (
        "Virtual Memory",
        "Copy-on-write (COW) after fork() is used to…",
        "Defer copying physical pages until one process writes, sharing read-only mappings initially.",
        [
            "Copy every page eagerly at fork time always",
            "Prevent parent and child from ever sharing memory",
            "Disable page tables in the child",
        ],
        "COW marks shared pages read-only and copies a frame only on write, making fork() cheaper.",
        {
            "Copy every page eagerly at fork time always": "Eager copy is the opposite of COW's lazy strategy.",
            "Prevent parent and child from ever sharing memory": "COW explicitly shares until a write occurs.",
            "Disable page tables in the child": "Both processes need valid page tables with shared read-only mappings.",
        },
    ),
    (
        "Virtual Memory",
        "The working set model approximates a process's demand by tracking…",
        "Pages referenced in a recent time window (working set size/limit).",
        [
            "Every file name in the filesystem cache",
            "Only pages never accessed since boot",
            "The number of threads in other processes",
        ],
        "Thrashing can be reduced by ensuring enough frames to cover the working set of active pages.",
        {
            "Every file name in the filesystem cache": "Working sets refer to virtual pages a process touches, not directory names.",
            "Only pages never accessed since boot": "Cold pages are the opposite of the actively referenced working set.",
            "The number of threads in other processes": "Cross-process thread counts do not define a process's working set.",
        },
    ),
    (
        "Paging",
        "A translation lookaside buffer (TLB) caches…",
        "Recent virtual-to-physical translations to avoid full page-table walks.",
        [
            "Entire disk blocks for journaling",
            "User passwords for authentication",
            "CPU microcode patches only",
        ],
        "On a TLB hit, the MMU finds the frame quickly; on a miss, the OS or hardware walks page tables.",
        {
            "Entire disk blocks for journaling": "TLBs cache address translations, not filesystem journal blocks.",
            "User passwords for authentication": "Security credentials are unrelated to the MMU.",
            "CPU microcode patches only": "Microcode is separate from per-address translation caching.",
        },
    ),
    (
        "Paging",
        "A multi-level page table's main benefit is…",
        "Sparse address spaces: only allocate inner tables for used virtual regions.",
        [
            "Eliminating all page faults",
            "Making every virtual address have the same page number",
            "Removing the need for physical memory",
        ],
        "Single huge tables waste memory; hierarchical tables allocate pages of page-table entries on demand.",
        {
            "Eliminating all page faults": "Page faults still occur for demand paging and protection.",
            "Making every virtual address have the same page number": "Page numbers vary with virtual addresses.",
            "Removing the need for physical memory": "Multi-level tables still map to physical frames.",
        },
    ),
    (
        "Paging",
        "Effective memory access time with a TLB combines hit rate and costs. If a memory reference takes 100 ns, a TLB hit takes 1 ns extra, a TLB miss adds a 100 ns table walk, and TLB hit rate is 99%, the effective time is approximately…",
        "101 ns",
        ["200 ns", "100 ns", "201 ns"],
        "EAT ≈ hit_rate × (100+1) + (1−hit_rate) × (100+100+1) = 0.99×101 + 0.01×201 ≈ 101 ns.",
        {
            "200 ns": "That would ignore the high hit rate and assume every access pays a full walk.",
            "100 ns": "That omits TLB overhead even on hits.",
            "201 ns": "That is the miss cost only, not the weighted average.",
        },
    ),
    (
        "File Systems",
        "Journaling in a file system is primarily intended to…",
        "Make crash recovery consistent by recording intended updates before applying them.",
        [
            "Encrypt all file names with a per-user key",
            "Store data only in the CPU cache",
            "Eliminate the need for directories",
        ],
        "Write-ahead logging lets the system replay or undo partial operations after power loss.",
        {
            "Encrypt all file names with a per-user key": "Encryption is orthogonal to journaling's consistency goal.",
            "Store data only in the CPU cache": "Persistent files still live on block storage.",
            "Eliminate the need for directories": "Namespaces still need directory structure.",
        },
    ),
    (
        "File Systems",
        "A hard link and a symbolic (soft) link differ because a hard link…",
        "Adds another directory entry for the same inode, while a symlink stores a path string.",
        [
            "Always points to a different inode with duplicate data blocks immediately",
            "Cannot reference files, only directories",
            "Requires the target file to be on a different file system",
        ],
        "Hard links share the inode; symlinks are separate files containing a pathname that may dangle.",
        {
            "Always points to a different inode with duplicate data blocks immediately": "Hard links share the inode; duplicate data is not created.",
            "Cannot reference files, only directories": "Hard links typically reference files; symlinks can name paths broadly.",
            "Requires the target file to be on a different file system": "Hard links must be on the same file system; symlinks can cross mounts.",
        },
    ),
    (
        "Concurrency",
        "A counting semaphore initialized to 1 can serve as…",
        "A mutex if only one thread waits on it at a time and no owner tracking is required.",
        [
            "A replacement for virtual memory",
            "A disk scheduling elevator",
            "A page-replacement policy",
        ],
        "Binary semaphores can serialize access like locks, though mutexes often include ownership semantics.",
        {
            "A replacement for virtual memory": "Semaphores synchronize threads; they do not translate addresses.",
            "A disk scheduling elevator": "Elevator algorithms reorder disk requests, not thread admission.",
            "A page-replacement policy": "Page replacement picks frames; semaphores coordinate threads.",
        },
    ),
    (
        "Concurrency",
        "A monitor bundles…",
        "Mutual exclusion with condition variables for wait/signal on shared state.",
        [
            "Only spinlocks with no waiting queues",
            "CPU microcode and device firmware in one struct",
            "A filesystem inode and disk superblock",
        ],
        "Monitors encapsulate data and operations so only one thread runs inside at a time, with condition queues for coordination.",
        {
            "Only spinlocks with no waiting queues": "Monitors rely on blocking and condition queues, not busy-wait alone.",
            "CPU microcode and device firmware in one struct": "That mixes unrelated low-level components.",
            "A filesystem inode and disk superblock": "Monitors are a concurrency construct, not on-disk metadata.",
        },
    ),
    (
        "Concurrency",
        "Spinlocks are most appropriate when…",
        "The critical section is very short and the lock will not be held across blocking calls.",
        [
            "Threads may sleep while holding the lock",
            "The system is always single-core with long critical sections",
            "Page faults must be handled inside the critical section",
        ],
        "Spinning wastes CPU if waits are long or the holder blocks; short, non-blocking sections on multicore can favor spinlocks.",
        {
            "Threads may sleep while holding the lock": "Sleeping while holding a spinlock would waste CPUs spinning for a long time.",
            "The system is always single-core with long critical sections": "On one core, spinning during long sections is especially wasteful.",
            "Page faults must be handled inside the critical section": "Faults may block; spinlocks should not be held across blocking events.",
        },
    ),
    (
        "Deadlocks",
        "In the banker's algorithm, a state is safe if…",
        "There exists an ordering in which every process can finish with currently available resources.",
        [
            "Every process holds the maximum resources it might ever need",
            "No process may request additional resources",
            "The system has detected a cycle in the wait-for graph",
        ],
        "Safety is a forecast: some sequence of completions releases enough resources for everyone to terminate.",
        {
            "Every process holds the maximum resources it might ever need": "That describes allocation at the limit, not the definition of a safe sequence.",
            "No process may request additional resources": "Future requests are modeled via claim/max matrices; safety considers them.",
            "The system has detected a cycle in the wait-for graph": "A cycle suggests deadlock; safety is a preventive test before granting.",
        },
    ),
    (
        "Deadlocks",
        "A cycle in a resource-allocation graph indicates deadlock only if…",
        "Each resource in the cycle has a single instance (no multi-unit resources).",
        [
            "Every resource has unlimited instances",
            "No process is waiting",
            "All edges are request edges only with no assignment edges",
        ],
        "With multiple instances, a cycle is necessary but not sufficient; with single-instance resources, a cycle implies deadlock.",
        {
            "Every resource has unlimited instances": "Unlimited instances break deadlock via cycles because requests can always be satisfied.",
            "No process is waiting": "Deadlock requires waiting processes; no waiting means no deadlock.",
            "All edges are request edges only with no assignment edges": "Assignment edges show ownership; cycles need both assignment and request structure.",
        },
    ),
    (
        "I/O",
        "Direct Memory Access (DMA) allows…",
        "Devices to transfer data to or from memory without per-word CPU copying.",
        [
            "The CPU to execute user programs in device firmware",
            "Disks to modify page tables without the OS",
            "Processes to bypass all permission checks automatically",
        ],
        "The CPU sets up DMA descriptors; the device moves bytes, then interrupts when done.",
        {
            "The CPU to execute user programs in device firmware": "DMA moves data; it does not run arbitrary user programs on the device.",
            "Disks to modify page tables without the OS": "Page tables are managed by the OS/MMU, not autonomously by disks.",
            "Processes to bypass all permission checks automatically": "DMA is set up by the kernel with IOMMUs/permissions on modern systems.",
        },
    ),
    (
        "I/O",
        "Device drivers present a uniform interface to the kernel by…",
        "Translating OS requests (open/read/write/ioctl) into device-specific commands and interrupts.",
        [
            "Eliminating the need for hardware interrupts",
            "Storing files only in the TLB",
            "Running all devices at the same clock frequency",
        ],
        "Drivers hide hardware details while the kernel exposes a consistent I/O abstraction.",
        {
            "Eliminating the need for hardware interrupts": "Most devices still use interrupts or polling; drivers handle both.",
            "Storing files only in the TLB": "Files live on persistent media; the TLB caches translations only.",
            "Running all devices at the same clock frequency": "Clocking is hardware-dependent, not unified by drivers.",
        },
    ),
]

HARD = [
    (
        "Paging",
        "Belady's anomaly demonstrates that with FIFO page replacement…",
        "Increasing the number of frames can sometimes increase the number of page faults.",
        [
            "Fault rate is strictly decreasing in the number of frames",
            "LRU always performs worse than random replacement",
            "Optimal replacement is implementable in real hardware without future knowledge",
        ],
        "FIFO lacks stack property; more memory does not guarantee fewer faults for all reference strings.",
        {
            "Fault rate is strictly decreasing in the number of frames": "Belady's anomaly is exactly the failure of monotonic improvement.",
            "LRU always performs worse than random replacement": "LRU is not the policy exhibiting Belady's anomaly in the classic result.",
            "Optimal replacement is implementable in real hardware without future knowledge": "OPT needs future reference information and is a theoretical benchmark.",
        },
    ),
    (
        "Paging",
        "The clock (second-chance) page replacement algorithm approximates LRU by…",
        "Scanning frames in a circular list and clearing reference bits before evicting.",
        [
            "Always evicting the most recently used page",
            "Sorting frames by physical address each nanosecond",
            "Never using a hardware reference bit",
        ],
        "A set reference bit gives a page a second chance; cleared bits identify less recently used victims.",
        {
            "Always evicting the most recently used page": "That would maximize faults, opposite of LRU's goal.",
            "Sorting frames by physical address each nanosecond": "Clock scans in ring order, not by sorting physical addresses continuously.",
            "Never using a hardware reference bit": "The algorithm depends on reference bits maintained by hardware/OS.",
        },
    ),
    (
        "Paging",
        "Huge pages (large pages) can improve TLB coverage because…",
        "Each TLB entry maps a larger virtual range, reducing misses for sequential/access-local workloads.",
        [
            "They eliminate the need for page tables entirely",
            "They guarantee zero internal fragmentation",
            "They prevent any process from sharing memory",
        ],
        "Fewer translations cover more bytes; the tradeoff is potential internal fragmentation and allocation granularity.",
        {
            "They eliminate the need for page tables entirely": "Page tables still exist; mappings are just coarser.",
            "They guarantee zero internal fragmentation": "Larger granularity can increase internal fragmentation within a huge page.",
            "They prevent any process from sharing memory": "Shared mappings can use large pages when aligned and supported.",
        },
    ),
    (
        "Virtual Memory",
        "An inverted page table indexes entries by…",
        "Physical frame number, recording which virtual page (and process) occupies each frame.",
        [
            "Virtual page number only, one global table without process context",
            "File inode number and byte offset",
            "Thread ID and stack pointer exclusively",
        ],
        "Inverted tables scale with physical memory size but need hashing/collision handling to search by virtual address.",
        {
            "Virtual page number only, one global table without process context": "Classic multi-level tables index by virtual page; inverted flips the keying.",
            "File inode number and byte offset": "That is filesystem addressing, not inverted page tables.",
            "Thread ID and stack pointer exclusively": "Address translation keys on virtual pages and process context, not stack pointers alone.",
        },
    ),
    (
        "Virtual Memory",
        "Address Space Layout Randomization (ASLR) improves security by…",
        "Randomizing bases of stack, heap, and mappings so exploits cannot rely on fixed addresses.",
        [
            "Encrypting every virtual page with a user-supplied password",
            "Disabling all page faults",
            "Running the kernel in user mode",
        ],
        "Uncertainty in layout reduces success of return-oriented and buffer-overflow attacks that jump to known addresses.",
        {
            "Encrypting every virtual page with a user-supplied password": "ASLR changes placement, not per-page user encryption.",
            "Disabling all page faults": "Faults still occur; ASLR only varies where regions are placed.",
            "Running the kernel in user mode": "Privilege levels are unchanged; layout is randomized.",
        },
    ),
    (
        "Scheduling",
        "On a preemptive uniprocessor, Earliest-Deadline-First (EDF) is optimal for…",
        "Minimizing lateness among independent jobs with known deadlines, if total utilization ≤ 1.",
        [
            "Maximizing disk throughput on a RAID array",
            "Eliminating priority inversion without any locks",
            "Guaranteeing zero page faults for all processes",
        ],
        "EDF dynamically prioritizes the job with the nearest deadline; overload (U > 1) still makes some jobs miss deadlines.",
        {
            "Maximizing disk throughput on a RAID array": "That is storage scheduling, not uniprocessor real-time task scheduling.",
            "Eliminating priority inversion without any locks": "Inversion is a locking/scheduling interaction; EDF does not remove locks.",
            "Guaranteeing zero page faults for all processes": "Memory behavior is unrelated to EDF's deadline optimality.",
        },
    ),
    (
        "Scheduling",
        "Priority inheritance is used to…",
        "Temporarily boost the priority of a lock holder so it finishes and releases the lock a high-priority waiter needs.",
        [
            "Permanently assign all threads to priority 0",
            "Replace mutexes with busy-wait spinlocks only",
            "Disable preemption globally forever",
        ],
        "Boosting the holder reduces indirect blocking of high-priority tasks in priority inversion scenarios.",
        {
            "Permanently assign all threads to priority 0": "Inheritance is temporary and targeted, not a global downgrade.",
            "Replace mutexes with busy-wait spinlocks only": "Inheritance complements proper locking; it does not eliminate mutexes.",
            "Disable preemption globally forever": "The system remains preemptive; only specific priorities are adjusted.",
        },
    ),
    (
        "Threads",
        "The many-to-one (M:1) user-thread model can perform poorly on multiprocessors because…",
        "The kernel schedules only the single underlying kernel thread, limiting true parallel execution of user threads.",
        [
            "Each user thread always gets its own hardware page table root",
            "The kernel creates a new process for every mutex lock",
            "User threads cannot block on I/O",
        ],
        "Without a kernel thread per user thread, blocking one user thread can block all, and other cores may sit idle.",
        {
            "Each user thread always gets its own hardware page table root": "M:1 shares one kernel context; separate page table roots are not per user thread by default.",
            "The kernel creates a new process for every mutex lock": "Locks do not spawn processes.",
            "User threads cannot block on I/O": "Blocking is exactly what exposes M:1 limitations.",
        },
    ),
    (
        "Processes",
        "After fork() with copy-on-write, a write to a shared page in the parent typically causes the kernel to…",
        "Trap on write, allocate a new frame, copy the page, and remap the writer's page table entry.",
        [
            "Immediately terminate both parent and child",
            "Mark the page executable only in the child",
            "Flush the entire TLB and disk cache before any user instruction runs",
        ],
        "Write protection on shared mappings triggers a COW fault handled by copying and updating permissions.",
        {
            "Immediately terminate both parent and child": "COW is a normal path, not a fatal error.",
            "Mark the page executable only in the child": "COW copies data pages; permissions follow policy for both address spaces.",
            "Flush the entire TLB and disk cache before any user instruction runs": "Only affected mappings/TLB entries need updating, not global flush of all caches.",
        },
    ),
    (
        "File Systems",
        "Log-structured file systems (LFS) optimize write performance by…",
        "Appending all changes sequentially to a log and cleaning segments later.",
        [
            "Updating every inode in place randomly across the disk",
            "Storing data only in CPU registers",
            "Forbidding any form of buffering or caching",
        ],
        "Sequential writes match disk bandwidth; garbage collection reclaims space from old segments.",
        {
            "Updating every inode in place randomly across the disk": "That resembles traditional layouts LFS tries to avoid for write cost.",
            "Storing data only in CPU registers": "LFS still persists to block storage.",
            "Forbidding any form of buffering or caching": "Buffer caches remain important; layout is what changes.",
        },
    ),
    (
        "File Systems",
        "Copy-on-write tree structures (as in some snapshotting file systems) create snapshots by…",
        "Pointing new metadata roots at old blocks and copying only blocks that would be modified.",
        [
            "Duplicating the entire disk image eagerly on every read",
            "Deleting all previous versions immediately on each write",
            "Storing snapshots only in the TLB",
        ],
        "COW trees share unchanged blocks between versions, paying space for divergent writes only.",
        {
            "Duplicating the entire disk image eagerly on every read": "Reads should remain cheap; duplication happens on write to shared blocks.",
            "Deleting all previous versions immediately on each write": "Snapshots retain old roots reachable for prior versions.",
            "Storing snapshots only in the TLB": "Snapshots are persistent metadata/block structures, not TLB entries.",
        },
    ),
    (
        "Concurrency",
        "Peterson's algorithm solves mutual exclusion for two threads using only loads/stores when…",
        "Shared variables (flag, turn) are accessed with proper memory ordering or on sequentially consistent hardware.",
        [
            "More than two threads share one flag array of size 1",
            "No shared variables exist",
            "The CPU disables interrupts in user space without kernel help",
        ],
        "Peterson's is a classic two-thread spin algorithm; correctness requires visible ordering of flag/turn updates.",
        {
            "More than two threads share one flag array of size 1": "Peterson's is defined for two participants; more threads need different algorithms.",
            "No shared variables exist": "The algorithm explicitly uses shared flag and turn variables.",
            "The CPU disables interrupts in user space without kernel help": "User programs cannot rely on interrupt masking alone on modern preemptive OSes.",
        },
    ),
    (
        "Concurrency",
        "Mesa semantics for condition variables differ from Hoare semantics because Mesa…",
        "Requires the waiter to re-check the condition after wakeup (while loop), not assume it holds immediately.",
        [
            "Automatically transfers monitor ownership to the signaled thread on signal",
            "Forbids using while loops around wait",
            "Guarantees the signaled thread runs before the signaler continues",
        ],
        "With Mesa, signal/broadcast moves threads to ready; they compete and must verify predicates before proceeding.",
        {
            "Automatically transfers monitor ownership to the signaled thread on signal": "That is closer to Hoare; Mesa does not hand over the monitor immediately.",
            "Forbids using while loops around wait": "Mesa-style code mandates re-testing conditions in a loop.",
            "Guarantees the signaled thread runs before the signaler continues": "Hoare gives stronger immediate handoff; Mesa does not.",
        },
    ),
    (
        "Concurrency",
        "The ABA problem in lock-free programming occurs when…",
        "A location appears unchanged (A→B→A) but its structure was modified, fooling compare-and-swap checks.",
        [
            "Two threads never run concurrently",
            "All locks are implemented with semaphores only",
            "Virtual memory is disabled",
        ],
        "CAS only compares values, not histories; reuse of the same pointer/value after pop/push can succeed incorrectly.",
        {
            "Two threads never run concurrently": "ABA arises under concurrency with reuse of nodes/values.",
            "All locks are implemented with semaphores only": "ABA is specific to lock-free CAS-based structures.",
            "Virtual memory is disabled": "ABA is about pointer/value identity, not paging on/off.",
        },
    ),
    (
        "Concurrency",
        "A memory barrier (fence) in concurrent code ensures…",
        "Ordering constraints so some loads/stores cannot be reordered across the fence by compiler or CPU.",
        [
            "All threads run on the same CPU core",
            "Heap allocations require no synchronization",
            "Page replacement chooses OPT automatically",
        ],
        "Barriers publish/consume shared data safely on weak memory models.",
        {
            "All threads run on the same CPU core": "Barriers matter especially when threads run on different cores with reordering.",
            "Heap allocations require no synchronization": "Allocation and memory ordering are separate concerns.",
            "Page replacement chooses OPT automatically": "OPT is unrelated to CPU memory ordering fences.",
        },
    ),
    (
        "Deadlocks",
        "Deadlock prevention by breaking 'hold and wait' typically requires…",
        "Processes to request all needed resources atomically before starting (or release all before new requests).",
        [
            "Allowing circular wait chains to form freely",
            "Ignoring maximum claim vectors in the banker algorithm",
            "Granting every request immediately without checking safety",
        ],
        "If a process cannot hold partial allocations while waiting, circular wait chains cannot form via held resources.",
        {
            "Allowing circular wait chains to form freely": "That would not prevent deadlock.",
            "Ignoring maximum claim vectors in the banker algorithm": "Claims are central to avoidance algorithms, not this prevention tactic.",
            "Granting every request immediately without checking safety": "Immediate unsafe grants cause deadlock rather than prevent it.",
        },
    ),
    (
        "Deadlocks",
        "Deadlock detection with multiple instances of resources often uses…",
        "A wait-for graph or reduction of the resource-allocation state to see if a safe sequence exists.",
        [
            "Only the FCFS CPU scheduling rule",
            "ASLR entropy values",
            "TLB hit rate measurements",
        ],
        "Detection examines whether processes can finish with current availability, similar in spirit to safety checks.",
        {
            "Only the FCFS CPU scheduling rule": "FCFS is unrelated to resource deadlock detection.",
            "ASLR entropy values": "Security randomization does not detect resource deadlocks.",
            "TLB hit rate measurements": "TLB statistics measure translation performance, not deadlock.",
        },
    ),
    (
        "I/O",
        "An I/O scheduler elevator (e.g., SCAN) reduces seek cost on disks by…",
        "Serving requests in one direction along the disk until the end, then reversing.",
        [
            "Issuing every request in random order always",
            "Caching virtual addresses in the TLB",
            "Disabling DMA transfers entirely",
        ],
        "Directional scanning batches nearby cylinder requests, improving throughput versus pure FCFS on rotating media.",
        {
            "Issuing every request in random order always": "Random ordering increases seeks; elevators sort spatially.",
            "Caching virtual addresses in the TLB": "TLBs are for memory translation, not disk arm scheduling.",
            "Disabling DMA transfers entirely": "DMA and arm scheduling are independent optimizations.",
        },
    ),
    (
        "I/O",
        "Spurious wakeups on condition variables imply that correct code should…",
        "Re-test the waited-on predicate in a loop after returning from wait.",
        [
            "Never call signal or broadcast",
            "Assume the predicate is true without checking",
            "Disable the scheduler entirely",
        ],
        "Threads may wake without the condition holding; loops prevent proceeding on false wakeups.",
        {
            "Never call signal or broadcast": "Signaling is still required; callers must handle spurious wakeups.",
            "Assume the predicate is true without checking": "That races with concurrent changes and spurious wakeups.",
            "Disable the scheduler entirely": "Scheduling continues; waiters must verify state.",
        },
    ),
    (
        "Virtual Memory",
        "Thrashing in a demand-paging system is best described as…",
        "Excessive paging where CPU time is dominated by fault handling and little useful work completes.",
        [
            "A state where no page faults occur",
            "Optimal CPU-bound throughput with infinite frames",
            "A filesystem journaling mode",
        ],
        "When the working set does not fit, processes fault constantly, queue grows, and performance collapses.",
        {
            "A state where no page faults occur": "Thrashing involves very high fault rates, not zero faults.",
            "Optimal CPU-bound throughput with infinite frames": "Enough frames prevent thrashing; infinite memory is not the definition.",
            "A filesystem journaling mode": "Thrashing is a memory overcommit phenomenon, not a log mode.",
        },
    ),
]

BOOK = make_book(
    title="Operating Systems: Three Easy Pieces",
    parent_topic="Computer Science",
    subtopic="Operating Systems",
    slug="operating-systems-ostep",
    source_url="https://pages.cs.wisc.edu/~remzi/OSTEP/",
    easy=EASY,
    medium=MEDIUM,
    hard=HARD,
)
