"""Quiz bank: PROBABILITY."""
from quiz_banks._common import Book, Q

PROBABILITY = Book(
    title="Introduction to Probability",
    parent_topic="Mathematics",
    subtopic="Probability",
    slug="probability-grinstead-snell",
    source_url="https://math.dartmouth.edu/~prob/prob/prob.pdf",
    easy=[
        Q("Sample Spaces",
          "Two fair six-sided dice are rolled. What is the probability of rolling a sum of 7?",
          "1/6",
          ["1/12", "1/36", "7/36"],
          "There are 36 equally-likely outcomes; six of them sum to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1). So 6/36 = 1/6.",
          {"1/12": "Half of the correct answer — this misses three of the six outcomes.",
           "1/36": "That's the probability of a single specific pair like (1,6).",
           "7/36": "There are six outcomes summing to 7, not seven."}),
        Q("Conditional Probability",
          "If P(A) = 1/2 and P(B|A) = 1/3, what is P(A ∩ B)?",
          "1/6",
          ["5/6", "1/3", "2/3"],
          "P(A ∩ B) = P(B|A) · P(A) = (1/3)(1/2) = 1/6.",
          {"5/6": "That's roughly P(A) + P(B|A), which isn't a valid formula.",
           "1/3": "That's P(B|A) — the conditional, not the joint.",
           "2/3": "Not derivable from the given numbers."}),
        Q("Independence",
          "Events A and B are independent if and only if…",
          "P(A ∩ B) = P(A) · P(B).",
          ["P(A ∪ B) = P(A) + P(B).",
           "P(A | B) = 0.",
           "P(A) = P(B)."],
          "Independence is defined by factorization of the joint; equivalent forms: P(A|B) = P(A) when P(B) > 0.",
          {"P(A ∪ B) = P(A) + P(B).": "That's mutual exclusivity, not independence.",
           "P(A | B) = 0.": "That says A and B can't co-occur — also mutual exclusivity.",
           "P(A) = P(B).": "Equal probabilities don't imply independence."}),
        Q("Distributions",
          "A Bernoulli random variable with parameter p has expected value…",
          "p",
          ["p(1 − p)", "1/p", "p²"],
          "E[X] = 1·p + 0·(1−p) = p.",
          {"p(1 − p)": "That's the variance of a Bernoulli.",
           "1/p": "That's E[X] for a Geometric distribution.",
           "p²": "Not a Bernoulli mean."}),
        Q("Distributions",
          "If X ~ Binomial(n, p), what is E[X]?",
          "np",
          ["p", "np(1 − p)", "n − p"],
          "A Binomial is the sum of n independent Bernoulli(p)'s, so E[X] = np.",
          {"p": "That's E[X] for a single Bernoulli.",
           "np(1 − p)": "That's the variance of a Binomial.",
           "n − p": "Not a standard quantity."}),
        Q("Expectation",
          "Linearity of expectation says E[X + Y] equals E[X] + E[Y]…",
          "Always, even when X and Y are dependent.",
          ["Only when X and Y are independent.",
           "Only for discrete random variables.",
           "Only when X and Y have the same distribution."],
          "Linearity holds regardless of dependence — a key reason it's so useful.",
          {"Only when X and Y are independent.": "Independence is required for variance, not expectation.",
           "Only for discrete random variables.": "It holds for continuous too.",
           "Only when X and Y have the same distribution.": "Identical distributions aren't required."}),
        Q("Variance",
          "Var(X + Y) = Var(X) + Var(Y) holds when…",
          "X and Y are uncorrelated.",
          ["X and Y have the same mean.",
           "X and Y are identically distributed.",
           "X = Y."],
          "Var(X+Y) = Var(X) + Var(Y) + 2 Cov(X, Y); the cross term vanishes when correlation is zero.",
          {"X and Y have the same mean.": "Means don't affect the variance identity.",
           "X and Y are identically distributed.": "Same distribution doesn't imply independence.",
           "X = Y.": "Then Var(2X) = 4 Var(X), not 2 Var(X)."}),
        Q("Distributions",
          "What is the probability of exactly k successes in n independent trials with success probability p?",
          "C(n, k) p^k (1 − p)^{n − k}",
          ["p^k", "C(n, k) p", "k · p"],
          "That's the Binomial probability mass function.",
          {"p^k": "Missing the combinatorial coefficient and the failure factor.",
           "C(n, k) p": "Off — needs p^k and the failure term.",
           "k · p": "Not a probability at all."}),
        Q("Conditional Probability",
          "Bayes' theorem expresses P(A | B) as…",
          "P(B | A) · P(A) / P(B)",
          ["P(A) · P(B)",
           "P(A | B) · P(B)",
           "P(A) − P(B)"],
          "Bayes rewrites the conditional via the symmetry P(A ∩ B) = P(A|B)P(B) = P(B|A)P(A).",
          {"P(A) · P(B)": "That's the joint when A, B are independent — not Bayes.",
           "P(A | B) · P(B)": "Circular — that just gives P(A ∩ B).",
           "P(A) − P(B)": "Not a probability formula."}),
        Q("Sample Spaces",
          "If A and B are mutually exclusive, then P(A ∪ B) equals…",
          "P(A) + P(B)",
          ["P(A) · P(B)",
           "P(A) + P(B) − P(A) P(B)",
           "max(P(A), P(B))"],
          "Disjoint events can't co-occur, so the inclusion-exclusion term P(A ∩ B) is zero.",
          {"P(A) · P(B)": "That's the joint under independence — not the union.",
           "P(A) + P(B) − P(A) P(B)": "Inclusion-exclusion with independence assumption — not for disjoint events.",
           "max(P(A), P(B))": "Only true in degenerate cases."}),
        Q("Distributions",
          "The Poisson distribution with rate λ has mean…",
          "λ",
          ["λ²", "1/λ", "λ(1 − λ)"],
          "E[X] = Σ k · e^{−λ} λ^k / k! = λ; the Poisson is also its own variance.",
          {"λ²": "Not a Poisson moment.",
           "1/λ": "That's the mean of an Exponential.",
           "λ(1 − λ)": "Not a Poisson quantity."}),
        Q("Distributions",
          "If X is Exponential(λ), what is E[X]?",
          "1/λ",
          ["λ", "λ²", "ln λ"],
          "The exponential pdf f(x) = λe^{−λx} integrates with x to give 1/λ.",
          {"λ": "That's the rate parameter, not the mean.",
           "λ²": "Not a moment of the Exponential.",
           "ln λ": "Not a standard quantity."}),
        Q("Expectation",
          "Drawing one card from a standard 52-card deck, what is the expected value of its rank if A = 1, J = 11, Q = 12, K = 13?",
          "7",
          ["6", "8", "6.5"],
          "Average of 1 through 13 is (1+13)/2 = 7; each rank has equal probability.",
          {"6": "Off by one.",
           "8": "Off by one in the other direction.",
           "6.5": "That's the mean of 1..12 — wrong upper bound."}),
        Q("Sample Spaces",
          "Three coins are flipped. What is the probability of exactly two heads?",
          "3/8",
          ["1/4", "1/2", "3/4"],
          "Three outcomes out of eight have exactly two heads: HHT, HTH, THH.",
          {"1/4": "That's two specific outcomes, not three.",
           "1/2": "That's the probability of any head appearing once or more (excluding all-tails would be 7/8).",
           "3/4": "Doesn't match the count."}),
        Q("Conditional Probability",
          "A test has 99% sensitivity and 95% specificity for a disease with 1% prevalence. If a random person tests positive, the chance they actually have the disease is closest to…",
          "About 17%.",
          ["About 95%.",
           "About 99%.",
           "About 1%."],
          "Bayes: P(D | +) = 0.99·0.01 / (0.99·0.01 + 0.05·0.99) ≈ 0.0099 / 0.0594 ≈ 0.167.",
          {"About 95%.": "Confusing test specificity with posterior probability.",
           "About 99%.": "Confusing sensitivity with posterior probability — base-rate fallacy.",
           "About 1%.": "That's the prior, before conditioning on the positive test."}),
        Q("Distributions",
          "A continuous uniform distribution on [a, b] has variance…",
          "(b − a)² / 12",
          ["(b − a) / 2", "(a + b) / 2", "(b − a)² / 6"],
          "By integration, σ² = (b − a)² / 12; the mean is (a+b)/2.",
          {"(b − a) / 2": "Half the range, not a variance.",
           "(a + b) / 2": "That's the mean.",
           "(b − a)² / 6": "Off by a factor of 2."}),
        Q("Variance",
          "The variance of a Bernoulli(p) random variable is…",
          "p(1 − p)",
          ["p", "p²", "1 − p"],
          "Var = E[X²] − E[X]² = p − p² = p(1 − p).",
          {"p": "That's the mean.",
           "p²": "Off — missing the (1 − p) factor.",
           "1 − p": "That's the failure probability, not the variance."}),
        Q("Distributions",
          "If X ~ Geometric(p) (number of trials until the first success), then E[X] is…",
          "1/p",
          ["p", "1/(1 − p)", "p(1 − p)"],
          "By the formula for the geometric mean, on average you need 1/p trials.",
          {"p": "That's the success probability per trial.",
           "1/(1 − p)": "That's the mean of a Geometric counting failures, off by convention.",
           "p(1 − p)": "Not a moment of the geometric."}),
        Q("Sample Spaces",
          "An event A satisfies P(A) = 0.3. What is P(A^c) (the complement)?",
          "0.7",
          ["0.3", "0", "1"],
          "P(A) + P(A^c) = 1, so P(A^c) = 1 − 0.3.",
          {"0.3": "That's P(A) itself.",
           "0": "Only if A is certain.",
           "1": "Only if A is impossible."}),
        Q("Expectation",
          "If E[X] = 5 and Y = 3X + 2, what is E[Y]?",
          "17",
          ["15", "5", "13"],
          "Linearity: E[3X + 2] = 3 E[X] + 2 = 15 + 2.",
          {"15": "Forgot to add 2.",
           "5": "That's E[X], not E[Y].",
           "13": "Off by 4 — arithmetic error."}),
    ],
    medium=[
        Q("Variance",
          "If Var(X) = 4 and Y = 5X + 7, what is Var(Y)?",
          "100",
          ["27", "20", "57"],
          "Var(aX + b) = a² Var(X) = 25 · 4. Constants don't change variance.",
          {"27": "Mixed up — would result from incorrect formula.",
           "20": "Used a, not a², for the scaling.",
           "57": "Added the constant; constants don't affect variance."}),
        Q("Distributions",
          "The standard normal has CDF Φ. P(−1.96 ≤ Z ≤ 1.96) is approximately…",
          "0.95",
          ["0.68", "0.99", "0.5"],
          "1.96 standard deviations from the mean covers about 95% of a standard normal.",
          {"0.68": "That's the one-sigma range (±1).",
           "0.99": "That's roughly the ±2.58 range.",
           "0.5": "That would be P(Z > 0) or P(Z < 0)."}),
        Q("Distributions",
          "The Central Limit Theorem states that, given i.i.d. random variables with finite variance, the standardized sample mean converges in distribution to…",
          "The standard normal.",
          ["Their own distribution.",
           "A uniform distribution.",
           "A Cauchy distribution."],
          "Regardless of the underlying distribution (with finite mean and variance), the sample mean is asymptotically normal.",
          {"Their own distribution.": "Only true for samples drawn from a normal.",
           "A uniform distribution.": "The CLT specifically gives the normal.",
           "A Cauchy distribution.": "Cauchy has no finite variance; CLT doesn't apply there."}),
        Q("Distributions",
          "If X and Y are independent Normal(μ_X, σ_X²) and Normal(μ_Y, σ_Y²), then X + Y is…",
          "Normal(μ_X + μ_Y, σ_X² + σ_Y²)",
          ["Normal(μ_X + μ_Y, σ_X + σ_Y)",
           "Normal(μ_X · μ_Y, σ_X · σ_Y)",
           "Not Gaussian in general."],
          "Means add, variances (not standard deviations) add when the variables are independent.",
          {"Normal(μ_X + μ_Y, σ_X + σ_Y)": "Variances add — standard deviations do not add directly.",
           "Normal(μ_X · μ_Y, σ_X · σ_Y)": "Products of normals aren't normal in general.",
           "Not Gaussian in general.": "Sum of independent normals is normal."}),
        Q("Conditional Probability",
          "P(A | B) = P(A) implies A and B are independent. What's another equivalent condition?",
          "P(B | A) = P(B).",
          ["P(A) = P(B).",
           "P(A ∪ B) = 1.",
           "P(A ∩ B) = 0."],
          "Independence is symmetric: knowing A doesn't change P(B) iff knowing B doesn't change P(A).",
          {"P(A) = P(B).": "Equal probabilities doesn't imply independence.",
           "P(A ∪ B) = 1.": "Covering the sample space isn't independence.",
           "P(A ∩ B) = 0.": "That's mutual exclusivity — typically incompatible with independence unless one has probability 0."}),
        Q("Distributions",
          "If X ~ Geometric(p) counting trials until first success, P(X > k) equals…",
          "(1 − p)^k",
          ["p^k", "1 − p^k", "k(1 − p)"],
          "X > k means the first k trials are all failures, each with probability (1 − p).",
          {"p^k": "That's k successes in a row.",
           "1 − p^k": "Not the survival function for Geometric.",
           "k(1 − p)": "Not a probability."}),
        Q("Variance",
          "Cov(X, X) equals…",
          "Var(X)",
          ["0", "1", "2 Var(X)"],
          "Cov(X, Y) = E[(X−μ_X)(Y−μ_Y)]; with Y = X this is Var(X).",
          {"0": "Only true for independent X, Y.",
           "1": "Only true for the correlation of X with itself.",
           "2 Var(X)": "Off by a factor."}),
        Q("Distributions",
          "The Poisson approximates the Binomial(n, p) well when…",
          "n is large and p is small with np = λ moderate.",
          ["n and p are both around 0.5.",
           "n is small.",
           "p approaches 1."],
          "Poisson(np) is the limiting distribution as n → ∞, p → 0 with np fixed.",
          {"n and p are both around 0.5.": "Normal approximation is better there.",
           "n is small.": "The approximation is asymptotic in n.",
           "p approaches 1.": "Symmetric to the relevant regime but the Poisson approximates rare events."}),
        Q("Expectation",
          "If X is uniform on {1, 2, …, n}, what is E[X²]?",
          "(n + 1)(2n + 1) / 6",
          ["(n + 1) / 2", "n² / 2", "(2n + 1) / 3"],
          "E[X²] = (1/n) Σ k² = (1/n) · n(n+1)(2n+1)/6 = (n+1)(2n+1)/6.",
          {"(n + 1) / 2": "That's E[X], not E[X²].",
           "n² / 2": "Not the right closed form.",
           "(2n + 1) / 3": "Not a standard moment."}),
        Q("Markov Chains",
          "A discrete-time Markov chain is specified by…",
          "A transition matrix P with P_{ij} = P(X_{t+1} = j | X_t = i).",
          ["A reward function only.",
           "A sequence of i.i.d. random variables.",
           "An initial distribution alone."],
          "Together with an initial distribution π_0, the transition matrix fully determines the chain.",
          {"A reward function only.": "Rewards are an MDP concept; not needed for a chain.",
           "A sequence of i.i.d. random variables.": "Markov chains have dependence by definition.",
           "An initial distribution alone.": "Needed but not sufficient."}),
        Q("Markov Chains",
          "A stationary distribution π of a Markov chain satisfies…",
          "πP = π (a left eigenvector with eigenvalue 1).",
          ["Pπ = π.",
           "π = 0.",
           "π = (1, 0, 0, …, 0)."],
          "Stationarity means the distribution is preserved after one step: π_j = Σ_i π_i P_{ij}.",
          {"Pπ = π.": "Wrong direction — π should be a row vector multiplied on the left.",
           "π = 0.": "Probabilities can't all be zero.",
           "π = (1, 0, 0, …, 0).": "Only stationary if state 1 absorbs."}),
        Q("Distributions",
          "If X is a continuous random variable with density f and Y = g(X) for a strictly increasing differentiable g, the density of Y is…",
          "f_X(g^{−1}(y)) / |g'(g^{−1}(y))|",
          ["f_X(y) · g'(y)",
           "f_X(g(y))",
           "f_X(y)"],
          "Change-of-variables for densities; the Jacobian factor accounts for the stretching of probability mass.",
          {"f_X(y) · g'(y)": "Multiplied instead of divided by the derivative — wrong direction.",
           "f_X(g(y))": "Missing the Jacobian.",
           "f_X(y)": "Ignores g entirely."}),
        Q("Distributions",
          "Markov's inequality states that for a non-negative random variable X and a > 0…",
          "P(X ≥ a) ≤ E[X] / a.",
          ["P(X ≥ a) = E[X] / a.",
           "P(X ≥ a) ≥ a / E[X].",
           "P(X ≤ a) ≤ E[X] / a."],
          "A general but often loose inequality; sharper variants (Chebyshev, Chernoff) use more information about X.",
          {"P(X ≥ a) = E[X] / a.": "It's an inequality, not equality, in general.",
           "P(X ≥ a) ≥ a / E[X].": "Reversed direction.",
           "P(X ≤ a) ≤ E[X] / a.": "Wrong direction on the inequality."}),
        Q("Distributions",
          "Chebyshev's inequality bounds P(|X − μ| ≥ kσ) by…",
          "1/k²",
          ["1/k", "e^{−k}", "k / σ"],
          "For any distribution with mean μ and variance σ², the chance of being k stdev from the mean is at most 1/k².",
          {"1/k": "Off — Chebyshev is in 1/k², which is tighter for large k.",
           "e^{−k}": "That's a Chernoff-style bound, needing MGF assumptions.",
           "k / σ": "Not a probability bound."}),
        Q("Conditional Probability",
          "Two events A, B with P(A) > 0 satisfy P(A | B) > P(A) iff…",
          "P(B | A) > P(B), i.e., A and B are positively associated.",
          ["P(A ∩ B) = 0.",
           "B is a subset of A.",
           "P(A) > P(B)."],
          "By Bayes, P(A|B)/P(A) = P(B|A)/P(B); they exceed 1 together.",
          {"P(A ∩ B) = 0.": "Mutual exclusivity would force P(A | B) = 0.",
           "B is a subset of A.": "That gives P(A | B) = 1 ≥ P(A), but isn't the iff.",
           "P(A) > P(B).": "Magnitudes aren't what positive association is about."}),
        Q("Distributions",
          "The moment generating function (MGF) of a random variable X is…",
          "M_X(t) = E[e^{tX}], when the expectation exists in a neighborhood of 0.",
          ["The cumulative distribution F_X.",
           "The characteristic function E[e^{iX}].",
           "Var(X) as a function of t."],
          "The MGF, when it exists, encodes all moments via derivatives at 0: M^{(n)}(0) = E[X^n].",
          {"The cumulative distribution F_X.": "CDF and MGF are different.",
           "The characteristic function E[e^{iX}].": "Characteristic functions use i (imaginary unit) and always exist; MGF uses real t.",
           "Var(X) as a function of t.": "Not how MGF is defined."}),
        Q("Markov Chains",
          "A state i is absorbing in a Markov chain when…",
          "P_{ii} = 1 (the chain stays in i forever once entered).",
          ["P_{ii} = 0.",
           "P_{ij} = 0 for all j ≠ i and P_{ii} = 0.",
           "i is the most probable initial state."],
          "Absorbing states have a self-loop probability of 1.",
          {"P_{ii} = 0.": "Opposite — that means i is left immediately.",
           "P_{ij} = 0 for all j ≠ i and P_{ii} = 0.": "Inconsistent: probabilities wouldn't sum to 1.",
           "i is the most probable initial state.": "Initial distribution is unrelated to absorption."}),
        Q("Distributions",
          "If X and Y are jointly normal with correlation 0, they are…",
          "Independent.",
          ["Identically distributed.",
           "Equal up to sign.",
           "Not necessarily uncorrelated."],
          "For jointly normal variables, zero correlation does imply independence (unlike the general case).",
          {"Identically distributed.": "Marginal distributions can differ.",
           "Equal up to sign.": "No such implication.",
           "Not necessarily uncorrelated.": "They are uncorrelated by assumption."}),
        Q("Expectation",
          "The law of total expectation says E[X] equals…",
          "E[ E[X | Y] ] for any random variable Y.",
          ["E[X] · P(Y).",
           "E[X | Y] for all Y.",
           "max_y E[X | Y = y]."],
          "Tower property / iterated expectation; powerful for conditioning arguments.",
          {"E[X] · P(Y).": "That's just E[X] times a probability.",
           "E[X | Y] for all Y.": "E[X | Y] is itself random.",
           "max_y E[X | Y = y].": "That's a worst-case conditional, not the mean."}),
        Q("Distributions",
          "If X is uniform on [0, 1], what is the distribution of −ln(1 − X) / λ?",
          "Exponential(λ)",
          ["Uniform(0, λ)",
           "Normal(0, 1/λ)",
           "Bernoulli(λ)"],
          "Inverse-CDF sampling: the inverse CDF of Exponential(λ) is −ln(1 − u) / λ.",
          {"Uniform(0, λ)": "Wrong distribution shape.",
           "Normal(0, 1/λ)": "Not how Gaussian sampling works from uniform.",
           "Bernoulli(λ)": "Bernoulli is discrete."}),
    ],
    hard=[
        Q("Distributions",
          "Hoeffding's inequality bounds the probability that the sample mean of n bounded i.i.d. variables deviates by more than t as…",
          "≤ 2 exp(−2 n t² / (b − a)²)",
          ["≤ exp(−t / σ)",
           "= t / √n",
           "≤ n / t²"],
          "For X_i ∈ [a, b], Hoeffding gives exponential concentration in n.",
          {"≤ exp(−t / σ)": "Not Hoeffding's form.",
           "= t / √n": "That's an asymptotic order of magnitude, not a bound.",
           "≤ n / t²": "Wrong direction."}),
        Q("Distributions",
          "The strong law of large numbers states that the sample mean of i.i.d. integrable random variables converges to μ…",
          "Almost surely.",
          ["In probability only.",
           "In distribution only.",
           "Only in L²."],
          "SLLN gives almost-sure convergence; the weak law gives convergence in probability.",
          {"In probability only.": "That's the weak law (WLLN).",
           "In distribution only.": "Convergence in distribution is weaker still.",
           "Only in L².": "L² convergence is yet another mode; SLLN is almost-sure."}),
        Q("Conditional Probability",
          "A martingale (M_n) with respect to a filtration satisfies E[M_{n+1} | F_n] = …",
          "M_n.",
          ["E[M_n] for all n.",
           "0.",
           "M_n + 1."],
          "The defining property of a martingale: the next value is, on average given the past, equal to the current value.",
          {"E[M_n] for all n.": "Conditional expectation can depend on the path.",
           "0.": "That would make every martingale zero.",
           "M_n + 1.": "That's a submartingale with deterministic drift."}),
        Q("Distributions",
          "If X is standard normal, then X² has what distribution?",
          "Chi-squared with 1 degree of freedom.",
          ["Standard normal.",
           "Exponential(1).",
           "Uniform on [0, 1]."],
          "X² with X ~ N(0,1) is χ²_1 by definition; sum of k independent squared normals is χ²_k.",
          {"Standard normal.": "Squaring a normal is not normal.",
           "Exponential(1).": "Exp(1/2) actually equals χ²_2, not χ²_1.",
           "Uniform on [0, 1].": "Probability integral transform applies to F(X), not X²."}),
        Q("Markov Chains",
          "An irreducible aperiodic finite-state Markov chain has…",
          "A unique stationary distribution to which the chain converges from any starting distribution.",
          ["Multiple stationary distributions.",
           "No stationary distribution.",
           "A stationary distribution only for symmetric chains."],
          "Perron–Frobenius / Markov chain convergence theorem.",
          {"Multiple stationary distributions.": "Irreducibility ensures uniqueness.",
           "No stationary distribution.": "Finite irreducible chains always have one.",
           "A stationary distribution only for symmetric chains.": "Symmetry isn't required."}),
        Q("Distributions",
          "The MGF uniqueness theorem says that if two distributions have MGFs equal in some neighborhood of 0, then…",
          "They are the same distribution.",
          ["They have the same mean only.",
           "They are jointly normal.",
           "They have the same support only."],
          "MGFs determine distributions when they exist on an open interval around 0.",
          {"They have the same mean only.": "MGF carries all moments.",
           "They are jointly normal.": "Joint normality is unrelated.",
           "They have the same support only.": "Support equality is weaker than full distribution equality."}),
        Q("Distributions",
          "Jensen's inequality for a convex function ϕ states that…",
          "E[ϕ(X)] ≥ ϕ(E[X])",
          ["E[ϕ(X)] ≤ ϕ(E[X])",
           "E[ϕ(X)] = ϕ(E[X])",
           "ϕ(X) is constant."],
          "For concave ϕ the inequality reverses; this is why log E ≥ E log under typical use of MLE-related inequalities.",
          {"E[ϕ(X)] ≤ ϕ(E[X])": "That's the concave case.",
           "E[ϕ(X)] = ϕ(E[X])": "Equality holds only if ϕ is affine or X is degenerate.",
           "ϕ(X) is constant.": "Not a general consequence."}),
        Q("Variance",
          "If (X_n) are i.i.d. with mean μ and finite variance σ², the sample variance S²_n is an unbiased estimator of σ² when defined with denominator…",
          "(n − 1)",
          ["n", "(n + 1)", "1"],
          "Dividing by n−1 corrects for using X̄ in place of μ (Bessel's correction).",
          {"n": "Divides yields a biased (low) estimator.",
           "(n + 1)": "Not a standard formula.",
           "1": "Sum of squared deviations isn't a variance."}),
        Q("Conditional Probability",
          "If X and Y are jointly distributed and you want to estimate X from Y minimizing MSE, the optimal estimator is…",
          "E[X | Y].",
          ["The mean E[X].",
           "Y itself.",
           "The mode of X."],
          "E[X | Y] is the L²-projection of X onto the σ-algebra of Y; it minimizes mean squared error.",
          {"The mean E[X].": "Only optimal if X is independent of Y.",
           "Y itself.": "Y need not be on the right scale or even the right variable.",
           "The mode of X.": "Mode minimizes 0-1 loss, not MSE."}),
        Q("Distributions",
          "The Kolmogorov 0-1 law states that…",
          "Tail events of independent sequences have probability 0 or 1.",
          ["All events have probability 0 or 1.",
           "Independent variables sum to 1.",
           "MGFs determine distributions."],
          "Useful in establishing 'event happens infinitely often' results for independent sequences.",
          {"All events have probability 0 or 1.": "Only tail events.",
           "Independent variables sum to 1.": "Garbage statement.",
           "MGFs determine distributions.": "True but unrelated to the 0-1 law."}),
        Q("Distributions",
          "Convergence in probability implies…",
          "Convergence in distribution.",
          ["Almost-sure convergence.",
           "Convergence in L¹.",
           "Convergence of all moments."],
          "Probability ⇒ distribution; the reverse implications generally don't hold without extra conditions.",
          {"Almost-sure convergence.": "Requires stronger assumptions (e.g., dominated convergence or BC).",
           "Convergence in L¹.": "Needs uniform integrability.",
           "Convergence of all moments.": "Requires UI of powers."}),
        Q("Distributions",
          "A copula encodes…",
          "The dependence structure between random variables, separated from their marginals.",
          ["The marginal distributions only.",
           "The mean vector.",
           "The variance only."],
          "Sklar's theorem: any joint CDF F decomposes as C(F_X, F_Y) where C is a copula.",
          {"The marginal distributions only.": "Opposite — copulas leave marginals out.",
           "The mean vector.": "Means aren't a dependence object.",
           "The variance only.": "Variance is a marginal property."}),
        Q("Markov Chains",
          "The Metropolis–Hastings algorithm constructs a Markov chain whose stationary distribution is π by…",
          "Accepting proposed moves with probability min(1, π(y) q(x | y) / (π(x) q(y | x))).",
          ["Always accepting moves that increase π.",
           "Sampling π directly.",
           "Using only deterministic moves."],
          "Detailed balance is satisfied by this acceptance rule, even when the proposal q is asymmetric.",
          {"Always accepting moves that increase π.": "That's hill-climbing; loses ergodicity.",
           "Sampling π directly.": "MH is for when you can't sample π directly.",
           "Using only deterministic moves.": "Randomness is essential."}),
        Q("Distributions",
          "Slutsky's theorem says: if X_n → X in distribution and Y_n → c in probability (constant c), then X_n + Y_n converges to…",
          "X + c in distribution.",
          ["Y_n + X.",
           "0.",
           "Nothing in general."],
          "Slutsky lets you combine a distributional limit with a probability limit cleanly.",
          {"Y_n + X.": "Not a limit object.",
           "0.": "Wrong unless c and X are both 0.",
           "Nothing in general.": "The theorem gives a clean limit."}),
        Q("Variance",
          "If X and Y are random variables, then E[XY] − E[X]E[Y] equals…",
          "Cov(X, Y).",
          ["Var(X).",
           "Var(X + Y).",
           "Always 0."],
          "Definition of covariance.",
          {"Var(X).": "Variance is the covariance of X with itself.",
           "Var(X + Y).": "That includes variances plus 2 Cov.",
           "Always 0.": "Only when X and Y are uncorrelated."}),
        Q("Distributions",
          "The Cauchy distribution is notorious because…",
          "Its mean and variance are undefined (the integrals diverge).",
          ["It has the largest possible variance.",
           "It is discrete.",
           "Its CDF doesn't exist."],
          "Heavy tails make moments infinite; the CLT doesn't apply to i.i.d. Cauchy samples.",
          {"It has the largest possible variance.": "Variance isn't even defined.",
           "It is discrete.": "Cauchy is continuous.",
           "Its CDF doesn't exist.": "F(x) = (1/π) arctan(x − x_0) + 1/2 exists."}),
        Q("Distributions",
          "If X ~ Normal(μ, σ²), then (X − μ)/σ has…",
          "The standard normal distribution.",
          ["A chi-squared distribution.",
           "A uniform distribution on [0, 1].",
           "A Cauchy distribution."],
          "Standardization centers and scales any normal to Standard Normal.",
          {"A chi-squared distribution.": "Squaring it would give χ²_1.",
           "A uniform distribution on [0, 1].": "Applying Φ to X would.",
           "A Cauchy distribution.": "Cauchy is unrelated."}),
        Q("Conditional Probability",
          "A sufficient statistic T for a parameter θ is one such that…",
          "P(data | T) does not depend on θ.",
          ["T = θ.",
           "T equals the MLE.",
           "T is unbiased."],
          "Sufficiency captures all information about θ in the data — Fisher–Neyman factorization.",
          {"T = θ.": "T is a function of data, not the parameter.",
           "T equals the MLE.": "MLE is one estimator; sufficiency is broader.",
           "T is unbiased.": "Unbiasedness is a separate concept."}),
        Q("Distributions",
          "The Borel–Cantelli lemma (first half) says: if Σ P(A_n) < ∞, then…",
          "P(A_n happens infinitely often) = 0.",
          ["P(A_n happens infinitely often) = 1.",
           "The events are independent.",
           "ΣP(A_n) = 1."],
          "Convergent sum forces almost-sure finiteness of how often the events happen.",
          {"P(A_n happens infinitely often) = 1.": "That's the second Borel–Cantelli (under independence + divergent sum).",
           "The events are independent.": "First Borel–Cantelli doesn't assume independence.",
           "ΣP(A_n) = 1.": "Not what the lemma says."}),
        Q("Markov Chains",
          "Detailed balance for a Markov chain with stationary distribution π is…",
          "π_i P_{ij} = π_j P_{ji} for all i, j.",
          ["π_i = π_j for all i, j.",
           "P_{ij} = P_{ji} for all i, j.",
           "π = uniform always."],
          "Reversibility under detailed balance ensures π is stationary; the chain is also called reversible.",
          {"π_i = π_j for all i, j.": "Uniform stationarity isn't the same as detailed balance.",
           "P_{ij} = P_{ji} for all i, j.": "That's a symmetric P, a special case.",
           "π = uniform always.": "Reversible chains can have non-uniform π."}),
    ],
)




BOOK = PROBABILITY
