"""Quiz bank: REINFORCEMENT_LEARNING."""
from quiz_banks._common import Book, Q

REINFORCEMENT_LEARNING = Book(
    title="Reinforcement Learning: An Introduction",
    parent_topic="AI & Machine Learning",
    subtopic="Reinforcement Learning",
    slug="reinforcement-learning-sutton-barto",
    source_url="http://incompleteideas.net/book/the-book-2nd.html",
    easy=[
        Q("MDPs",
          "A Markov Decision Process is fully specified by which tuple?",
          "(S, A, P, R, γ)",
          ["(S, A, π)", "(Q, V, π)", "(s, a, r)"],
          "States, actions, transition kernel, reward function, and discount factor are the canonical MDP definition.",
          {"(S, A, π)": "That's a controlled process — π is a policy, not part of the environment.",
           "(Q, V, π)": "These are quantities computed *from* an MDP.",
           "(s, a, r)": "That's a single transition, not the whole MDP."}),
        Q("MDPs",
          "The Markov property states that the next state and reward depend only on…",
          "The current state and action, independent of earlier history.",
          ["The full history of states and actions.",
           "The current state alone, not the action.",
           "The reward of the previous step."],
          "P(s', r | s_t, a_t, s_{t−1}, …) = P(s', r | s_t, a_t) — that's the Markov property.",
          {"The full history of states and actions.": "That's a non-Markov process.",
           "The current state alone, not the action.": "Action matters: the agent affects transitions.",
           "The reward of the previous step.": "Reward history doesn't enter the Markov assumption."}),
        Q("Returns",
          "In an infinite-horizon problem, discounting (γ < 1) is used because…",
          "It guarantees the return is finite and prioritizes nearer rewards.",
          ["It speeds up the optimizer.",
           "It eliminates exploration.",
           "It makes all rewards equal."],
          "G_t = Σ γ^k r_{t+k+1}; with γ < 1 and bounded rewards, the sum converges.",
          {"It speeds up the optimizer.": "Discounting affects the objective, not the optimizer directly.",
           "It eliminates exploration.": "Exploration is a separate concern.",
           "It makes all rewards equal.": "Opposite — it weights nearer ones more."}),
        Q("Value Functions",
          "The state-value function v_π(s) is defined as…",
          "The expected return starting from s and following policy π thereafter.",
          ["The largest reward obtainable from s.",
           "The probability of reaching a terminal state from s.",
           "The number of steps remaining from s."],
          "v_π(s) = E_π[ G_t | S_t = s ].",
          {"The largest reward obtainable from s.": "That's a piece of one trajectory, not an expectation.",
           "The probability of reaching a terminal state from s.": "That's a hitting probability, not a value.",
           "The number of steps remaining from s.": "That's horizon, not value."}),
        Q("Value Functions",
          "The Bellman equation for v_π relates v_π(s) to…",
          "An expectation of immediate reward plus γ times v_π at the next state.",
          ["The maximum action value from s.",
           "The visit count of s.",
           "The number of episodes elapsed."],
          "v_π(s) = Σ_a π(a|s) Σ_{s',r} P(s', r | s, a) [r + γ v_π(s')].",
          {"The maximum action value from s.": "That's the Bellman *optimality* equation.",
           "The visit count of s.": "Counts are about sampling, not the equation.",
           "The number of episodes elapsed.": "Episodes are unrelated to the equation."}),
        Q("Exploration",
          "ε-greedy action selection means…",
          "With probability 1−ε pick the greedy action; with probability ε pick a random action.",
          ["Always pick the greedy action.",
           "Pick uniformly at random with probability ε per step regardless of greedy.",
           "Decay rewards by ε each step."],
          "The exploration rate ε mixes a uniform random action with the greedy choice.",
          {"Always pick the greedy action.": "That's pure exploitation; no exploration.",
           "Pick uniformly at random with probability ε per step regardless of greedy.": "Reversed sense — greedy fires with 1−ε.",
           "Decay rewards by ε each step.": "ε is an action-selection parameter, not a reward modifier."}),
        Q("Algorithms",
          "Q-learning is best characterized as…",
          "Off-policy TD control: it learns the optimal action-value while behaving with any exploratory policy.",
          ["On-policy Monte Carlo control.",
           "An exact dynamic programming method.",
           "A purely model-based planner."],
          "The Q-learning update uses max_{a'} Q(s', a'), targeting the optimal policy regardless of the behavior policy.",
          {"On-policy Monte Carlo control.": "That's MC-control or SARSA.",
           "An exact dynamic programming method.": "Q-learning is sample-based, not exact DP.",
           "A purely model-based planner.": "Q-learning is model-free."}),
        Q("Algorithms",
          "SARSA differs from Q-learning in that SARSA…",
          "Uses the action actually taken in the next state for the TD target (on-policy).",
          ["Uses Monte Carlo returns.",
           "Updates the value of the previous state, not current.",
           "Requires a model of the environment."],
          "SARSA: Q(s,a) ← Q(s,a) + α[r + γ Q(s', a') − Q(s, a)] where a' is the chosen next action.",
          {"Uses Monte Carlo returns.": "Both SARSA and Q-learning are TD methods.",
           "Updates the value of the previous state, not current.": "Both update Q(s, a) for the just-taken transition.",
           "Requires a model of the environment.": "Both are model-free."}),
        Q("Returns",
          "An episodic task differs from a continuing task in that…",
          "It has a well-defined terminal state, so trajectories have finite length.",
          ["Episodic tasks have no rewards.",
           "Continuing tasks have only one action.",
           "Continuing tasks always converge faster."],
          "Episodic problems naturally yield Monte Carlo returns; continuing tasks rely on discounting or average reward.",
          {"Episodic tasks have no rewards.": "Rewards exist in both.",
           "Continuing tasks have only one action.": "Action set is unrelated.",
           "Continuing tasks always converge faster.": "Not a general property."}),
        Q("Algorithms",
          "Temporal difference (TD) learning updates value estimates using…",
          "A bootstrap from the next state's current estimate.",
          ["The Monte Carlo return of the whole episode.",
           "The exact Bellman solution.",
           "Random samples of states only."],
          "TD(0) uses target r + γ V(s'); it bootstraps from V rather than waiting for full returns.",
          {"The Monte Carlo return of the whole episode.": "That's MC, which doesn't bootstrap.",
           "The exact Bellman solution.": "TD samples; it doesn't solve Bellman in closed form.",
           "Random samples of states only.": "TD uses observed transitions, not random samples."}),
        Q("Policy",
          "A deterministic policy maps…",
          "Each state to a single action.",
          ["Each state to a distribution over actions.",
           "Each action to a reward.",
           "Each reward to a probability."],
          "π(s) = a; contrast with stochastic π(a | s).",
          {"Each state to a distribution over actions.": "That's a stochastic policy.",
           "Each action to a reward.": "That's a piece of the reward function.",
           "Each reward to a probability.": "Not a policy at all."}),
        Q("Reward",
          "Shaping rewards (giving small rewards along the way) can speed up learning but risks…",
          "Changing the optimal policy if the shaping isn't potential-based.",
          ["Eliminating exploration entirely.",
           "Reducing the discount factor.",
           "Making the problem non-Markov."],
          "Potential-based shaping (Ng et al., 1999) preserves optimal policies; arbitrary shaping can shift them.",
          {"Eliminating exploration entirely.": "Shaping affects targets, not exploration policy.",
           "Reducing the discount factor.": "γ is set separately.",
           "Making the problem non-Markov.": "Shaping based on s and s' stays Markov."}),
        Q("MDPs",
          "An optimal policy π* is one that achieves…",
          "Greater than or equal expected return than every other policy, in every state.",
          ["The shortest path between every pair of states.",
           "The largest reward on the first step.",
           "Exploration probability of zero."],
          "An optimal policy maximizes v_π(s) simultaneously for all s; such a policy always exists in finite MDPs.",
          {"The shortest path between every pair of states.": "That's a special case (goal-reaching with unit-cost rewards).",
           "The largest reward on the first step.": "Greedy on immediate reward isn't optimal in general.",
           "Exploration probability of zero.": "Optimality is defined by return, not exploration."}),
        Q("Value Functions",
          "The action-value function q_π(s, a) is…",
          "Expected return starting from s, taking action a, then following π.",
          ["Expected return starting from s following π.",
           "Probability of taking a in s.",
           "Reward of the action a."],
          "q_π(s, a) = E_π[ G_t | S_t = s, A_t = a ].",
          {"Expected return starting from s following π.": "That's v_π, not q_π.",
           "Probability of taking a in s.": "That's π(a | s).",
           "Reward of the action a.": "That's expected immediate reward, not the full return."}),
        Q("Algorithms",
          "Policy iteration alternates which two steps?",
          "Policy evaluation (compute v_π) and policy improvement (greedy with respect to v_π).",
          ["Forward pass and backward pass.",
           "Exploration and exploitation phases.",
           "Sampling and rejection."],
          "Each round computes v_π and then sets π'(s) ← argmax_a Σ_{s', r} P[r + γ v_π(s')]; the process converges to π*.",
          {"Forward pass and backward pass.": "That's neural network training.",
           "Exploration and exploitation phases.": "That's behavior, not algorithm structure.",
           "Sampling and rejection.": "That's a Monte Carlo idea."}),
        Q("Algorithms",
          "Value iteration is best described as…",
          "Repeatedly applying the Bellman optimality operator until v converges.",
          ["Random policy rollout.",
           "Gradient descent on the policy.",
           "A planning method that requires no model."],
          "v_{k+1}(s) ← max_a Σ_{s', r} P[r + γ v_k(s')]; fixed point is v*.",
          {"Random policy rollout.": "That's MC, not VI.",
           "Gradient descent on the policy.": "VI works on value, not policy gradient.",
           "A planning method that requires no model.": "VI needs P and R; it's model-based."}),
        Q("Exploration",
          "Optimistic initial values encourage exploration by…",
          "Setting Q-values above realistic returns so every action seems promising at first.",
          ["Adding a random exploration bonus to every reward.",
           "Lowering the learning rate.",
           "Decreasing γ."],
          "Until the optimistic values are corrected by experience, the greedy action keeps changing — exploration without ε.",
          {"Adding a random exploration bonus to every reward.": "That's UCB-style, not optimistic initialization.",
           "Lowering the learning rate.": "LR doesn't drive exploration.",
           "Decreasing γ.": "γ is unrelated to exploration."}),
        Q("Algorithms",
          "Monte Carlo control estimates Q from…",
          "Complete episode returns averaged across visits to each (s, a).",
          ["One-step TD bootstrapping.",
           "Exact Bellman backups.",
           "Random untargeted noise."],
          "MC waits until the episode ends, then assigns each visit's G value, averaging over many episodes.",
          {"One-step TD bootstrapping.": "That's TD, not MC.",
           "Exact Bellman backups.": "MC samples instead of solving.",
           "Random untargeted noise.": "MC uses real returns, not noise."}),
        Q("Returns",
          "n-step returns interpolate between TD(0) and Monte Carlo by…",
          "Using n actual rewards before bootstrapping from the value at step n.",
          ["Discounting only the n-th reward.",
           "Sampling n random actions.",
           "Averaging over n episodes."],
          "G^{(n)}_t = r_{t+1} + γ r_{t+2} + … + γ^{n−1} r_{t+n} + γ^n V(s_{t+n}); n = 1 is TD(0), n → ∞ is MC.",
          {"Discounting only the n-th reward.": "All rewards are discounted in the usual way.",
           "Sampling n random actions.": "n-step is about look-ahead, not sampling.",
           "Averaging over n episodes.": "That's a separate idea."}),
        Q("Function Approximation",
          "Why use function approximation (e.g., neural nets) for value functions?",
          "Tables are infeasible for large or continuous state spaces; approximators generalize across states.",
          ["Function approximators are always exact.",
           "Tables can't store negative numbers.",
           "Approximation eliminates the need for exploration."],
          "With |S| huge, tabular methods can't visit every state; parameterizing V or Q allows sharing across states.",
          {"Function approximators are always exact.": "They're approximate, hence the name.",
           "Tables can't store negative numbers.": "They can.",
           "Approximation eliminates the need for exploration.": "Exploration is still needed."}),
    ],
    medium=[
        Q("Algorithms",
          "Q-learning's update rule is Q(s,a) ← Q(s,a) + α [target − Q(s,a)]. The target is…",
          "r + γ max_{a'} Q(s', a')",
          ["r + γ Q(s', a')",
           "G_t (full Monte Carlo return)",
           "max_a Q(s, a)"],
          "Q-learning's max in the target makes it off-policy: the target reflects the optimal action regardless of behavior.",
          {"r + γ Q(s', a')": "That's SARSA's target.",
           "G_t (full Monte Carlo return)": "That's MC, not TD.",
           "max_a Q(s, a)": "That's a value, not a TD target."}),
        Q("Algorithms",
          "Why does Q-learning converge to Q* (under standard conditions) even when behavior is exploratory?",
          "Because the update's target uses max over next actions, not the behavior's choice.",
          ["Because exploration disappears over time automatically.",
           "Because the discount factor is always 1.",
           "Because rewards are always positive."],
          "Off-policy learning lets the target track the greedy policy while behavior explores; Robbins–Monro conditions on α plus sufficient visitation imply convergence.",
          {"Because exploration disappears over time automatically.": "Decay isn't required for convergence in tabular Q-learning, just sufficient coverage.",
           "Because the discount factor is always 1.": "Convergence holds for γ < 1 typically.",
           "Because rewards are always positive.": "Sign of rewards is irrelevant to convergence."}),
        Q("Value Functions",
          "The Bellman optimality equation for v* is…",
          "v*(s) = max_a Σ_{s', r} P(s', r | s, a) [r + γ v*(s')]",
          ["v*(s) = Σ_a π(a|s) [r + γ v*(s')]",
           "v*(s) = max_a Q(s, a) − ε",
           "v*(s) = γ v*(s')"],
          "Optimality replaces the policy-weighted average with a max over actions.",
          {"v*(s) = Σ_a π(a|s) [r + γ v*(s')]": "That's the Bellman expectation equation under π, not optimality.",
           "v*(s) = max_a Q(s, a) − ε": "ε doesn't appear in the Bellman equation.",
           "v*(s) = γ v*(s')": "Missing the reward and the max."}),
        Q("Algorithms",
          "Eligibility traces (TD(λ)) provide…",
          "A continuous interpolation between one-step TD and Monte Carlo via the trace decay parameter λ.",
          ["A way to discard old data.",
           "Faster matrix inversion for value iteration.",
           "An exploration bonus."],
          "λ = 0 reduces to TD(0); λ = 1 approximates MC; intermediate λ smooths credit assignment.",
          {"A way to discard old data.": "Traces decay old credit but don't 'discard' it.",
           "Faster matrix inversion for value iteration.": "Unrelated.",
           "An exploration bonus.": "Unrelated."}),
        Q("Function Approximation",
          "The 'deadly triad' that can cause divergence in RL with function approximation consists of…",
          "Function approximation + bootstrapping + off-policy learning.",
          ["Function approximation + on-policy + discounting.",
           "Monte Carlo + tabular + exploration.",
           "SARSA + replay + ε-greedy."],
          "Sutton and Barto show that combining these three properties can make TD diverge; each alone is safe.",
          {"Function approximation + on-policy + discounting.": "On-policy is generally safer.",
           "Monte Carlo + tabular + exploration.": "Tabular MC is well-behaved.",
           "SARSA + replay + ε-greedy.": "These aren't the canonical triad."}),
        Q("Policy",
          "REINFORCE updates the policy parameters θ by…",
          "Ascending the gradient of expected return: ∇θ log π_θ(a|s) · G_t.",
          ["Descending the gradient of the TD error.",
           "Maximum-likelihood imitation of expert actions.",
           "Inverting the Q-function."],
          "REINFORCE is the canonical Monte Carlo policy-gradient method; G_t is the return from time t.",
          {"Descending the gradient of the TD error.": "That's TD-style, not policy-gradient.",
           "Maximum-likelihood imitation of expert actions.": "That's behavioral cloning.",
           "Inverting the Q-function.": "No inversion involved."}),
        Q("Policy",
          "Actor-critic methods combine which two ideas?",
          "Policy gradients (actor) with a learned value baseline/critic to reduce variance.",
          ["Two competing policies playing against each other.",
           "Exploration and exploitation phases.",
           "Q-learning and SARSA."],
          "The critic estimates V or Q to compute advantages; the actor uses those advantages in its gradient.",
          {"Two competing policies playing against each other.": "That's self-play / GAN-style, not actor-critic.",
           "Exploration and exploitation phases.": "Not the actor-critic split.",
           "Q-learning and SARSA.": "Both are value methods; neither plays the actor role."}),
        Q("Exploration",
          "UCB (Upper Confidence Bound) for bandits selects the action maximizing…",
          "Q̂(a) + c √(ln t / N(a))",
          ["Q̂(a) + ε",
           "Q̂(a) − N(a)",
           "argmax over Q̂ only"],
          "UCB adds an exploration bonus inversely related to visit count, giving optimism-under-uncertainty.",
          {"Q̂(a) + ε": "That's ε-perturbation, not UCB.",
           "Q̂(a) − N(a)": "That penalizes well-visited arms too harshly and ignores log t.",
           "argmax over Q̂ only": "Pure greedy — no exploration."}),
        Q("Value Functions",
          "Importance sampling lets off-policy methods estimate v_π using behavior policy b's data by weighting returns with…",
          "∏_k π(a_k | s_k) / b(a_k | s_k)",
          ["π(a_k | s_k) − b(a_k | s_k)",
           "P(s_{k+1} | s_k, a_k)",
           "1 − γ"],
          "Ordinary importance sampling reweights every step of a trajectory by the ratio of target to behavior probabilities.",
          {"π(a_k | s_k) − b(a_k | s_k)": "Subtraction doesn't give a likelihood ratio.",
           "P(s_{k+1} | s_k, a_k)": "Dynamics ratios cancel out — only action probabilities matter.",
           "1 − γ": "γ is unrelated to IS."}),
        Q("Algorithms",
          "Experience replay in DQN serves to…",
          "Break correlations between consecutive samples by drawing batches from a replay buffer.",
          ["Permanently store the optimal policy.",
           "Replace TD targets with Monte Carlo returns.",
           "Eliminate the need for a target network."],
          "Sampling uniformly from a buffer decorrelates updates and amortizes data collection.",
          {"Permanently store the optimal policy.": "The buffer stores transitions, not policies.",
           "Replace TD targets with Monte Carlo returns.": "DQN uses 1-step TD targets.",
           "Eliminate the need for a target network.": "Target networks address a different stability issue."}),
        Q("Algorithms",
          "A target network in DQN stabilizes training by…",
          "Holding the parameters used to compute TD targets fixed for many steps, reducing target oscillation.",
          ["Doubling the learning rate.",
           "Training a second Q-network on negative samples.",
           "Averaging Q across all past episodes."],
          "Periodically copying weights from the online network to the target network prevents the target from chasing the prediction.",
          {"Doubling the learning rate.": "Unrelated.",
           "Training a second Q-network on negative samples.": "Not the role of the target net.",
           "Averaging Q across all past episodes.": "Polyak averaging is a variant; the canonical target net does periodic copies."}),
        Q("Algorithms",
          "Double Q-learning addresses which problem?",
          "Maximization bias from using the same estimator for action selection and evaluation.",
          ["Forgetting in replay buffers.",
           "Vanishing gradients in deep nets.",
           "Reward hacking."],
          "max E[Q̂] is biased upward; using two estimators, one for argmax and one for evaluation, removes the bias.",
          {"Forgetting in replay buffers.": "Catastrophic forgetting is a different issue.",
           "Vanishing gradients in deep nets.": "Unrelated.",
           "Reward hacking.": "Reward design issue, not estimator bias."}),
        Q("Function Approximation",
          "Why does naive Q-learning with neural networks sometimes diverge while tabular Q-learning converges?",
          "Bootstrapping with function approximation and off-policy updates loses the contraction guarantee.",
          ["Neural networks always overflow.",
           "Discounting is invalid with neural nets.",
           "Networks can't represent linear functions."],
          "The Bellman operator is a contraction in the tabular max-norm but not in the L2 norm typically used by FA — divergence is possible.",
          {"Neural networks always overflow.": "Numerics aren't the fundamental issue.",
           "Discounting is invalid with neural nets.": "γ < 1 still helps; not the cause.",
           "Networks can't represent linear functions.": "They can."}),
        Q("Policy",
          "Policy gradients with a value baseline b(s) leave the gradient unbiased because…",
          "E_a[(b(s)) ∇θ log π_θ(a|s)] = 0 for any b that doesn't depend on a.",
          ["b(s) is always zero.",
           "Baselines cancel by symmetry only with linear policies.",
           "The advantage function is non-negative."],
          "The expectation of the score function is zero, so subtracting b(s) reduces variance without bias.",
          {"b(s) is always zero.": "Baselines are usually non-zero.",
           "Baselines cancel by symmetry only with linear policies.": "It holds for any differentiable policy.",
           "The advantage function is non-negative.": "Advantages are signed."}),
        Q("Algorithms",
          "Generalized advantage estimation (GAE) combines n-step advantages by…",
          "Exponentially weighting them with parameter λ to balance bias and variance.",
          ["Picking only the longest available n.",
           "Averaging uniformly over all n.",
           "Discarding all n except 1."],
          "GAE: A^{GAE} = Σ (γλ)^k δ_{t+k}; λ=0 gives 1-step TD advantage, λ=1 approaches MC.",
          {"Picking only the longest available n.": "That ignores bias-variance trade-off.",
           "Averaging uniformly over all n.": "Uniform averaging is suboptimal.",
           "Discarding all n except 1.": "That's plain TD(0)."}),
        Q("Algorithms",
          "Why does PPO clip the policy probability ratio?",
          "To prevent updates that move the policy too far in one step, improving stability.",
          ["To enforce a hard KL constraint exactly.",
           "To eliminate the need for a critic.",
           "To make the policy deterministic."],
          "Clipping ratio r = π_new/π_old to [1−ε, 1+ε] approximates a trust region without an explicit KL constraint.",
          {"To enforce a hard KL constraint exactly.": "That's TRPO with the constraint; PPO is the looser surrogate.",
           "To eliminate the need for a critic.": "PPO uses a critic.",
           "To make the policy deterministic.": "PPO policies remain stochastic."}),
        Q("Returns",
          "Average reward formulations are useful when…",
          "Tasks are continuing and don't fit discounting well.",
          ["Episodes are very short.",
           "Reward is binary.",
           "Actions are continuous."],
          "Maximizing the long-run average reward r̄ avoids γ-specific artifacts in non-episodic tasks.",
          {"Episodes are very short.": "Discounted return works fine then.",
           "Reward is binary.": "Reward type isn't decisive.",
           "Actions are continuous.": "Action space is orthogonal to the return formulation."}),
        Q("Exploration",
          "Thompson sampling for bandits selects an arm by…",
          "Sampling a parameter from the posterior over rewards and picking the arm that's best under the sample.",
          ["Always picking the empirically best arm.",
           "Adding Gaussian noise to all Q-values.",
           "Selecting uniformly at random."],
          "Posterior sampling balances exploration and exploitation naturally — arms with high uncertainty get tried more often.",
          {"Always picking the empirically best arm.": "Greedy doesn't explore.",
           "Adding Gaussian noise to all Q-values.": "Closer to noisy networks, not Thompson.",
           "Selecting uniformly at random.": "Pure exploration."}),
        Q("Algorithms",
          "Model-based RL differs from model-free in that model-based methods…",
          "Learn or use an explicit model of P and R and plan with it.",
          ["Always achieve lower variance.",
           "Don't use rewards.",
           "Cannot use neural networks."],
          "Examples: Dyna-Q (learn and plan), MuZero (learn implicit model), value iteration (given a model).",
          {"Always achieve lower variance.": "Bias can be higher if the model is wrong.",
           "Don't use rewards.": "Rewards are central.",
           "Cannot use neural networks.": "They often do."}),
        Q("Reward",
          "Sparse rewards are challenging because…",
          "Most transitions provide no learning signal, making credit assignment hard.",
          ["They violate the Markov property.",
           "They require continuous action spaces.",
           "They guarantee divergence."],
          "Without intermediate signal, RL must propagate the rare reward backwards through long trajectories — exploration becomes critical.",
          {"They violate the Markov property.": "Sparsity doesn't break Markov.",
           "They require continuous action spaces.": "Sparsity affects rewards, not actions.",
           "They guarantee divergence.": "Sparse rewards make learning slow but not divergent."}),
    ],
    hard=[
        Q("Algorithms",
          "TRPO enforces a trust region using which constraint between successive policies?",
          "An average KL divergence bound: E_s[ KL(π_old(·|s) ‖ π_new(·|s)) ] ≤ δ.",
          ["A hard L2 distance on action probabilities.",
           "A fixed clipping ratio.",
           "A bound on the gradient norm."],
          "TRPO solves a constrained surrogate optimization with the KL constraint; PPO replaces this with a clipped objective.",
          {"A hard L2 distance on action probabilities.": "Not the TRPO constraint.",
           "A fixed clipping ratio.": "That's PPO.",
           "A bound on the gradient norm.": "That's gradient clipping, not TRPO's idea."}),
        Q("Function Approximation",
          "Why does the Bellman operator not generally contract in L2 under linear function approximation?",
          "Projection onto the value-function subspace can expand distances, so the composed operator may not contract.",
          ["L2 is not a valid norm for RL.",
           "Linear models can't represent any value function.",
           "γ ≥ 1 in continuing tasks."],
          "T_π is a γ-contraction in max-norm but not L2; projection Π under L2 followed by T_π can fail to contract.",
          {"L2 is not a valid norm for RL.": "It's just not the natural one for the Bellman operator.",
           "Linear models can't represent any value function.": "They can represent some; the issue is the projected operator.",
           "γ ≥ 1 in continuing tasks.": "Discount still gives contraction in max-norm."}),
        Q("Returns",
          "The variance of Monte Carlo returns versus TD targets: which is generally higher and why?",
          "MC has higher variance because it sums many random rewards; TD's variance is dampened by bootstrapping.",
          ["TD has higher variance because it bootstraps.",
           "Both have identical variance.",
           "Neither has variance — both are deterministic."],
          "MC accumulates noise across the whole episode; TD's variance comes from one step plus the value estimate.",
          {"TD has higher variance because it bootstraps.": "Bootstrapping reduces variance (at the cost of bias).",
           "Both have identical variance.": "They differ in general.",
           "Neither has variance — both are deterministic.": "Stochastic transitions and rewards make both random."}),
        Q("Algorithms",
          "What problem does Retrace(λ) solve compared to vanilla importance-weighted off-policy returns?",
          "It bounds the importance weights to control variance while remaining unbiased for the target policy.",
          ["It eliminates the need for a target policy.",
           "It works only in tabular settings.",
           "It assumes deterministic policies."],
          "Retrace truncates importance ratios at 1, giving safe off-policy learning with bounded variance.",
          {"It eliminates the need for a target policy.": "Off-policy still requires a target.",
           "It works only in tabular settings.": "It applies broadly.",
           "It assumes deterministic policies.": "It works with stochastic policies."}),
        Q("Function Approximation",
          "Soft Actor-Critic (SAC) maximizes an entropy-regularized objective:",
          "Expected return plus α · entropy(π(·|s)), encouraging exploration via stochasticity.",
          ["Expected return minus α · ‖θ‖².",
           "KL(π_new ‖ π_old) alone.",
           "Negative log-likelihood of expert demonstrations."],
          "SAC's reward becomes r + α · H[π], so the policy stays stochastic where rewards are similar.",
          {"Expected return minus α · ‖θ‖².": "That's parameter regularization, not entropy.",
           "KL(π_new ‖ π_old) alone.": "That's TRPO-style trust regions.",
           "Negative log-likelihood of expert demonstrations.": "That's behavioral cloning."}),
        Q("Reward",
          "Inverse reinforcement learning seeks to recover…",
          "A reward function consistent with observed expert behavior.",
          ["A policy that maximizes regret.",
           "The optimal Q-function without rewards.",
           "A model of the transition dynamics."],
          "IRL inverts the usual setup: behavior is given; the reward is inferred.",
          {"A policy that maximizes regret.": "Opposite of RL.",
           "The optimal Q-function without rewards.": "Q requires rewards in some form.",
           "A model of the transition dynamics.": "That's model learning, not IRL."}),
        Q("Algorithms",
          "MuZero distinguishes itself from AlphaZero by…",
          "Learning the model (dynamics, reward, value) end-to-end without given rules.",
          ["Using only model-free updates.",
           "Avoiding tree search.",
           "Training without any value targets."],
          "MuZero plans in a latent space using a learned model, removing AlphaZero's reliance on a perfect simulator.",
          {"Using only model-free updates.": "MuZero plans with a learned model — it's model-based.",
           "Avoiding tree search.": "MuZero still uses MCTS in latent space.",
           "Training without any value targets.": "Value targets are central."}),
        Q("Algorithms",
          "Why is bootstrapping a TD target with a stale target network helpful in deep Q-learning?",
          "It decouples the moving prediction from a slower target, mitigating feedback-loop divergence.",
          ["It removes the need for replay buffers.",
           "It guarantees the policy is greedy.",
           "It always improves sample efficiency."],
          "Without a target network, the network's prediction and its own target chase each other; freezing the target stabilizes the regression.",
          {"It removes the need for replay buffers.": "Replay is a separate stability tool.",
           "It guarantees the policy is greedy.": "Greediness is set by the action-selection rule.",
           "It always improves sample efficiency.": "Sample efficiency depends on many factors."}),
        Q("Function Approximation",
          "Linear TD(0) converges to which fixed point under on-policy distribution?",
          "The TD fixed point, which is generally different from the L2 projection of v_π onto the linear subspace.",
          ["The Monte Carlo solution.",
           "The exact v_π regardless of features.",
           "The minimum-norm v."],
          "TD finds w* solving Π T_π Π w* = Π w*, not the projection onto v_π; bounds compare it to the best linear approximator (e.g., Tsitsiklis & Van Roy).",
          {"The Monte Carlo solution.": "MC converges to the projection (least-squares), not the TD fixed point.",
           "The exact v_π regardless of features.": "Only if v_π is in the span.",
           "The minimum-norm v.": "Not characterized this way."}),
        Q("Policy",
          "The policy gradient theorem expresses ∇_θ J(θ) as…",
          "E_π [ ∇_θ log π_θ(a|s) · Q^π(s, a) ]",
          ["∇_θ Q^π(s, a) directly.",
           "Σ_s d_π(s) ∇_θ V^π(s) only.",
           "An exact value-iteration update."],
          "The score-function form makes the gradient computable without differentiating Q with respect to θ.",
          {"∇_θ Q^π(s, a) directly.": "Q depends on θ through the policy; the theorem avoids that.",
           "Σ_s d_π(s) ∇_θ V^π(s) only.": "Incomplete form.",
           "An exact value-iteration update.": "PG is sampling-based."}),
        Q("Exploration",
          "Intrinsic motivation methods (curiosity, RND) add rewards based on…",
          "Some measure of state novelty or prediction error from an auxiliary model.",
          ["Distance to the goal in pixels.",
           "Random noise added each step.",
           "Negative environment rewards only."],
          "Predicting random features (RND) gives high error on novel states; curiosity-driven exploration rewards visiting them.",
          {"Distance to the goal in pixels.": "That's a shaped reward, not curiosity.",
           "Random noise added each step.": "Noise doesn't drive directed exploration.",
           "Negative environment rewards only.": "Inverting rewards isn't intrinsic motivation."}),
        Q("MDPs",
          "A POMDP differs from an MDP in that the agent…",
          "Receives observations rather than the full state, so it must maintain a belief over states.",
          ["Has no reward function.",
           "Has only one action available.",
           "Has deterministic transitions."],
          "Partial observability necessitates belief-state planning or recurrent policies.",
          {"Has no reward function.": "POMDPs still have rewards.",
           "Has only one action available.": "Action space can be anything.",
           "Has deterministic transitions.": "Determinism is unrelated."}),
        Q("Algorithms",
          "Why is the Bellman optimality operator T* a γ-contraction in the max-norm?",
          "||T*v − T*w||_∞ ≤ γ ||v − w||_∞ follows from γ-discounted backups and the max being a non-expansion.",
          ["Because rewards are bounded by 1.",
           "Because v* is unique.",
           "Because the policy is deterministic."],
          "Contraction yields uniqueness of v* and convergence of value iteration via Banach's fixed-point theorem.",
          {"Because rewards are bounded by 1.": "Bounded rewards aren't required for the contraction; γ < 1 is.",
           "Because v* is unique.": "Uniqueness follows from contraction, not the other way.",
           "Because the policy is deterministic.": "Policy form is irrelevant to T*."}),
        Q("Returns",
          "n-step TD with off-policy corrections may suffer from…",
          "Variance growing with n due to products of importance-sampling ratios.",
          ["Inability to bootstrap.",
           "Loss of the Markov property.",
           "Negative discount factors."],
          "Each step contributes a ratio; long sequences multiply many of them, blowing up variance.",
          {"Inability to bootstrap.": "n-step still bootstraps.",
           "Loss of the Markov property.": "Markov is preserved.",
           "Negative discount factors.": "γ stays in [0, 1)."}),
        Q("Algorithms",
          "Dyna-Q integrates model-free Q-learning with model-based planning by…",
          "Updating Q from real transitions and simulated transitions drawn from a learned model.",
          ["Running tabular Q-learning twice as fast.",
           "Pre-training a policy with imitation learning.",
           "Replacing rewards with bootstrap estimates."],
          "After each real step, Dyna performs k 'planning' updates using simulated experience from the learned model.",
          {"Running tabular Q-learning twice as fast.": "Speedup comes from extra updates, not parallelism.",
           "Pre-training a policy with imitation learning.": "Dyna doesn't require demonstrations.",
           "Replacing rewards with bootstrap estimates.": "Rewards are still real."}),
        Q("Function Approximation",
          "Distributional RL (e.g., C51) models which quantity instead of just expected return?",
          "The full distribution Z(s, a) of returns, not just its mean Q(s, a).",
          ["The Hessian of the loss.",
           "The gradient of the reward.",
           "The entropy of the policy."],
          "Modeling Z gives richer training signal and often better-performing agents; expectations are recovered as a special case.",
          {"The Hessian of the loss.": "Second-order info isn't what distributional RL targets.",
           "The gradient of the reward.": "Not modeled.",
           "The entropy of the policy.": "Entropy is separate."}),
        Q("Policy",
          "Deterministic Policy Gradients (DPG/DDPG) update via ∇_θ J ≈ E[ ∇_a Q(s, a)|_{a=μ_θ(s)} · ∇_θ μ_θ(s) ]. This requires…",
          "Differentiable Q and continuous action spaces.",
          ["Discrete action spaces.",
           "A discrete reward function.",
           "An exact MDP model."],
          "Without continuous a, you can't take ∇_a Q; without differentiable Q (e.g., a critic network), you can't propagate.",
          {"Discrete action spaces.": "DPG specifically targets continuous control.",
           "A discrete reward function.": "Rewards can be continuous.",
           "An exact MDP model.": "DPG is model-free."}),
        Q("Algorithms",
          "Why does prioritized experience replay sample with probability ∝ |TD error|^α?",
          "To focus learning on transitions where the model is currently wrong.",
          ["To make the buffer act like a queue.",
           "To balance positive and negative rewards.",
           "To eliminate duplicates."],
          "High-error transitions carry more learning signal; importance-sampling weights correct the resulting bias.",
          {"To make the buffer act like a queue.": "Buffer is a ring; prioritization affects sampling probability.",
           "To balance positive and negative rewards.": "Reward sign isn't the criterion.",
           "To eliminate duplicates.": "Duplicates may still appear."}),
        Q("Returns",
          "In an absorbing state with zero further reward, the value should be…",
          "0",
          ["1", "γ", "−∞"],
          "No future reward and γ × 0 = 0 means v(absorbing) = 0 exactly.",
          {"1": "Would require future reward of 1/(1−γ).",
           "γ": "Discount alone doesn't define value.",
           "−∞": "Only with infinite negative reward, which isn't given."}),
        Q("Algorithms",
          "Why might tabular SARSA be safer than tabular Q-learning during learning in some environments (e.g., cliff walking)?",
          "SARSA accounts for the exploratory behavior policy in its targets, avoiding dangerous greedy actions.",
          ["SARSA uses larger learning rates.",
           "SARSA cannot diverge.",
           "SARSA ignores rewards."],
          "Q-learning targets the optimal policy and pushes toward the cliff edge during ε-greedy exploration; SARSA's on-policy target encourages a safer detour.",
          {"SARSA uses larger learning rates.": "LR is independent.",
           "SARSA cannot diverge.": "Tabular Q-learning is also stable.",
           "SARSA ignores rewards.": "Both methods use rewards."}),
    ],
)




BOOK = REINFORCEMENT_LEARNING
