"""Quiz bank: OpenIntro Statistics."""
from quiz_banks._make_book import make_book

_EASY = [
    (
        "Descriptive Statistics",
        "What is the mean of the values 4, 6, 8, 10, and 12?",
        "8",
        ["6", "10", "7"],
        "Mean = (4+6+8+10+12)/5 = 40/5 = 8.",
        {
            "6": "That's the median of an evenly spaced symmetric set, not the mean here.",
            "10": "That's the largest value, not the average.",
            "7": "Off by one from the correct average.",
        },
    ),
    (
        "Descriptive Statistics",
        "For the sorted data 2, 5, 7, 9, 11, what is the median?",
        "7",
        ["5", "9", "6.8"],
        "With five ordered values, the median is the middle observation: 7.",
        {
            "5": "That's the second value (Q1 region), not the middle.",
            "9": "That's the fourth value, not the median.",
            "6.8": "That's the mean (34/5), not the median.",
        },
    ),
    (
        "Descriptive Statistics",
        "Which measure of center is most appropriate for heavily right-skewed income data?",
        "Median",
        ["Mean", "Mode only", "Range"],
        "The mean is pulled toward extreme high earners; the median reflects a typical household better.",
        {
            "Mean": "Extreme high values inflate the mean for skewed income.",
            "Mode only": "Mode alone ignores most of the distribution.",
            "Range": "Range measures spread, not center.",
        },
    ),
    (
        "Descriptive Statistics",
        "The interquartile range (IQR) equals…",
        "Q3 − Q1",
        ["Q3 + Q1", "Maximum − minimum", "Standard deviation"],
        "IQR is the spread of the middle 50%: third quartile minus first quartile.",
        {
            "Q3 + Q1": "Adding quartiles is not a spread measure.",
            "Maximum − minimum": "That's the full range, not the middle half.",
            "Standard deviation": "SD uses all deviations from the mean, not quartiles.",
        },
    ),
    (
        "Descriptive Statistics",
        "A histogram displays…",
        "Counts or proportions of observations in contiguous bins along a numeric axis.",
        [
            "Exact pairwise correlations between every variable.",
            "Only categorical bar heights with gaps between unrelated bars.",
            "The theoretical PDF of a fitted model without data.",
        ],
        "Histograms group numeric data into bins; bar area/height shows frequency in each bin.",
        {
            "Exact pairwise correlations between every variable.": "Correlations need scatterplots or matrices, not a single-variable histogram.",
            "Only categorical bar heights with gaps between unrelated bars.": "Bar charts for categories differ; histogram bins are contiguous on a scale.",
            "The theoretical PDF of a fitted model without data.": "A histogram summarizes observed data, not a formula alone.",
        },
    ),
    (
        "Probability Basics",
        "If P(A) = 0.35, what is P(not A) for a simple event A?",
        "0.65",
        ["0.35", "1.35", "0.175"],
        "Complement rule: P(A^c) = 1 − P(A) = 0.65.",
        {
            "0.35": "That's P(A), not the complement.",
            "1.35": "Probabilities cannot exceed 1.",
            "0.175": "Not derived from the complement rule.",
        },
    ),
    (
        "Probability Basics",
        "Events A and B are independent. Which identity holds?",
        "P(A ∩ B) = P(A) · P(B)",
        [
            "P(A ∪ B) = P(A) + P(B) always.",
            "P(A | B) = 0 whenever B occurs.",
            "P(A) = P(B) always.",
        ],
        "Independence means the joint factorizes into marginals.",
        {
            "P(A ∪ B) = P(A) + P(B) always.": "That omits the overlap term unless events are mutually exclusive.",
            "P(A | B) = 0 whenever B occurs.": "Zero conditional probability means incompatibility, not independence.",
            "P(A) = P(B) always.": "Equal probabilities are not required for independence.",
        },
    ),
    (
        "Probability Basics",
        "A standard deck has 52 cards. What is P(drawing a heart on one random draw)?",
        "13/52 = 1/4",
        ["1/13", "1/2", "13/26"],
        "There are 13 hearts out of 52 equally likely cards.",
        {
            "1/13": "That's one specific rank (e.g., ace), not a suit.",
            "1/2": "Half the deck is not hearts.",
            "13/26": "26 is not the deck size.",
        },
    ),
    (
        "Probability Basics",
        "The law of large numbers says that as sample size increases, the sample mean…",
        "Tends to get closer to the population mean (under regular conditions).",
        [
            "Must exactly equal the population mean after 30 observations.",
            "Becomes more variable without bound.",
            "Is always equal to the sample median.",
        ],
        "Averaging stabilizes around the true mean for independent, identically distributed data.",
        {
            "Must exactly equal the population mean after 30 observations.": "Convergence is probabilistic, not a fixed n=30 identity.",
            "Becomes more variable without bound.": "Variability of the mean typically decreases with n.",
            "Is always equal to the sample median.": "Mean and median need not match, especially when skewed.",
        },
    ),
    (
        "Distributions",
        "The standard normal distribution has mean 0 and standard deviation…",
        "1",
        ["0", "√2", "π"],
        "Z-scores standardize to μ=0, σ=1.",
        {
            "0": "Zero standard deviation would be a constant, not a normal curve.",
            "√2": "Not the standard normal scale.",
            "π": "π is not the standard deviation of Z.",
        },
    ),
    (
        "Distributions",
        "For a Binomial(n, p) model, which assumption is essential?",
        "n independent trials with fixed success probability p and binary outcomes.",
        [
            "Outcomes are continuous and unbounded above.",
            "The number of trials changes after each success.",
            "Success probability p must equal 0.5.",
        ],
        "Binomial counts successes in n fixed, independent Bernoulli trials.",
        {
            "Outcomes are continuous and unbounded above.": "Binomial outcomes are counts of successes, built from 0/1 trials.",
            "The number of trials changes after each success.": "n is fixed in the standard Binomial.",
            "Success probability p must equal 0.5.": "p can be any value in [0,1].",
        },
    ),
    (
        "Distributions",
        "The empirical rule for an approximately normal distribution states that about 95% of data lie within…",
        "Mean ± 2 standard deviations",
        ["Mean ± 1 standard deviation", "Mean ± 3 standard deviations", "The IQR only"],
        "68–95–99.7: roughly 95% within two SDs.",
        {
            "Mean ± 1 standard deviation": "About 68% lie within one SD.",
            "Mean ± 3 standard deviations": "About 99.7% lie within three SDs.",
            "The IQR only": "The empirical rule is SD-based, not quartile-based.",
        },
    ),
    (
        "Distributions",
        "A right-skewed distribution has a longer tail toward…",
        "Larger values on the right",
        ["Smaller values on the left", "Both tails equally", "The median only"],
        "Right skew: mean typically exceeds median; extreme high values pull the tail right.",
        {
            "Smaller values on the left": "That describes left skew.",
            "Both tails equally": "Symmetric distributions have balanced tails.",
            "The median only": "Skew describes tail shape, not a single point.",
        },
    ),
    (
        "Confidence Intervals",
        "A 95% confidence interval for a population mean is interpreted as: if we repeated sampling many times and built intervals the same way, about 95% of those intervals would…",
        "Contain the true population mean.",
        [
            "Contain 95% of all future individual observations.",
            "Guarantee the next sample mean is correct.",
            "Prove the null hypothesis is false.",
        ],
        "CI coverage is a long-run property of the procedure, not a 95% chance for one fixed interval after data are seen.",
        {
            "Contain 95% of all future individual observations.": "A CI targets a parameter (mean), not the middle 95% of individuals.",
            "Guarantee the next sample mean is correct.": "Intervals estimate μ, not a deterministic guarantee for one draw.",
            "Prove the null hypothesis is false.": "Estimation intervals are separate from hypothesis tests.",
        },
    ),
    (
        "Confidence Intervals",
        "All else equal, increasing sample size n makes a confidence interval for μ…",
        "Narrower",
        ["Wider", "Unchanged always", "Invalid"],
        "Standard error σ/√n shrinks as n grows, reducing margin of error.",
        {
            "Wider": "Larger n adds information and typically tightens the interval.",
            "Unchanged always": "Margin of error depends on n through the standard error.",
            "Invalid": "Larger samples are preferred for precision.",
        },
    ),
    (
        "Hypothesis Testing",
        "In a significance test, the null hypothesis H₀ is…",
        "The default claim tested for possible rejection using sample evidence.",
        [
            "Always the researcher's preferred outcome.",
            "The probability that the alternative is true.",
            "The p-value itself.",
        ],
        "We assume H₀ unless data provide strong enough evidence against it.",
        {
            "Always the researcher's preferred outcome.": "H₀ is often a status-quo or no-effect statement.",
            "The probability that the alternative is true.": "Hypotheses are statements, not probabilities.",
            "The p-value itself.": "The p-value measures evidence against H₀, it is not H₀.",
        },
    ),
    (
        "Hypothesis Testing",
        "A p-value is…",
        "The probability, assuming H₀ is true, of observing data at least as extreme as what was observed.",
        [
            "The probability that H₀ is true after seeing the data.",
            "The probability that Hₐ is false.",
            "The same as the significance level α always.",
        ],
        "p-values are computed under the null; they are not posterior probabilities of H₀.",
        {
            "The probability that H₀ is true after seeing the data.": "That would be a Bayesian posterior, not a frequentist p-value.",
            "The probability that Hₐ is false.": "p-values do not directly give P(Hₐ false).",
            "The same as the significance level α always.": "α is a chosen threshold; p is computed from data.",
        },
    ),
    (
        "Hypothesis Testing",
        "Rejecting a true null hypothesis is called…",
        "A Type I error",
        ["A Type II error", "A power increase", "A confidence level"],
        "Type I = false positive (reject true H₀); controlled by α.",
        {
            "A Type II error": "Type II is failing to reject a false H₀.",
            "A power increase": "Power is 1 − P(Type II), not Type I.",
            "A confidence level": "Confidence applies to intervals, not this error label.",
        },
    ),
    (
        "Regression",
        "The correlation coefficient r always lies between…",
        "−1 and 1",
        ["0 and 1", "−∞ and ∞", "0 and 100"],
        "r measures linear association strength and direction on a bounded scale.",
        {
            "0 and 1": "Negative associations produce negative r.",
            "−∞ and ∞": "r is standardized and bounded.",
            "0 and 100": "Percent scales are not used for r.",
        },
    ),
    (
        "Regression",
        "In a scatterplot of study hours (x) and exam score (y), a positive correlation means…",
        "Higher x tends to occur with higher y.",
        [
            "x causes y with certainty.",
            "Higher x tends to occur with lower y.",
            "There is no linear pattern.",
        ],
        "Positive r: upward trend; causation requires further design, not correlation alone.",
        {
            "x causes y with certainty.": "Correlation does not establish causation.",
            "Higher x tends to occur with lower y.": "That describes negative correlation.",
            "There is no linear pattern.": "Positive correlation implies an upward association.",
        },
    ),
]

_MEDIUM = [
    (
        "Descriptive Statistics",
        "A sample has x̄ = 50 and s = 10 with n = 25. What is the standard error of the mean?",
        "2",
        ["10", "0.4", "5"],
        "SE = s/√n = 10/5 = 2.",
        {
            "10": "That's s, not the SE.",
            "0.4": "That's s/n, not s/√n.",
            "5": "That's √n, not the SE.",
        },
    ),
    (
        "Descriptive Statistics",
        "Data: 3, 3, 5, 7, 7, 7, 9. What are the first quartile Q1 and third quartile Q3 (using the usual inclusive median method)?",
        "Q1 = 3, Q3 = 7",
        ["Q1 = 5, Q3 = 9", "Q1 = 4, Q3 = 8", "Q1 = 3, Q3 = 9"],
        "Lower half {3,3,5} has median 3; upper half {7,7,7,9} has median 7.",
        {
            "Q1 = 5, Q3 = 9": "Those are not the medians of the lower/upper halves for this dataset.",
            "Q1 = 4, Q3 = 8": "Averaging across halves is not the standard quartile rule here.",
            "Q1 = 3, Q3 = 9": "Q3 is 7, not 9 (the maximum).",
        },
    ),
    (
        "Descriptive Statistics",
        "Which statement about variance and standard deviation is correct?",
        "Variance is in squared units; standard deviation restores the original units.",
        [
            "Standard deviation is always larger than the range.",
            "Variance can be negative for skewed data.",
            "Standard deviation equals mean deviation in every distribution.",
        ],
        "s² averages squared deviations; s = √s² returns to the data scale.",
        {
            "Standard deviation is always larger than the range.": "SD can be much smaller than the range.",
            "Variance can be negative for skewed data.": "Variance is a sum of squares; it is nonnegative.",
            "Standard deviation equals mean deviation in every distribution.": "SD uses squared deviations; mean absolute deviation differs.",
        },
    ),
    (
        "Descriptive Statistics",
        "A z-score of −1.5 for an observation means…",
        "The value is 1.5 standard deviations below the mean.",
        [
            "The value is 1.5 units below zero.",
            "The value is 1.5 standard deviations above the mean.",
            "The probability of the value is 0.15.",
        ],
        "z = (x − μ)/σ; negative z is below the mean.",
        {
            "The value is 1.5 units below zero.": "z is relative to the mean in SD units, not zero on the raw scale.",
            "The value is 1.5 standard deviations above the mean.": "Positive z would be above the mean.",
            "The probability of the value is 0.15.": "z is a standardized position, not a probability.",
        },
    ),
    (
        "Probability Basics",
        "P(A) = 0.4, P(B) = 0.5, and A, B are independent. What is P(A ∪ B)?",
        "0.7",
        ["0.9", "0.2", "0.1"],
        "P(A∪B) = 0.4 + 0.5 − 0.4·0.5 = 0.9 − 0.2 = 0.7.",
        {
            "0.9": "That's P(A)+P(B) without subtracting overlap.",
            "0.2": "That's P(A∩B), not the union.",
            "0.1": "Not from the inclusion-exclusion formula.",
        },
    ),
    (
        "Probability Basics",
        "In a class, 60% are undergraduates and 40% of all students are undergraduates who commute. What is P(commute | undergraduate)?",
        "2/3",
        ["0.24", "0.40", "0.60"],
        "P(C|U) = P(C∩U)/P(U) = 0.40/0.60 = 2/3.",
        {
            "0.24": "That's P(C∩U), not the conditional.",
            "0.40": "That's the joint proportion of all students, not conditional on U.",
            "0.60": "That's P(U), not P(C|U).",
        },
    ),
    (
        "Probability Basics",
        "A fair coin is flipped 4 times. What is P(exactly 2 heads)?",
        "6/16 = 3/8",
        ["4/16", "8/16", "2/16"],
        "Binomial: C(4,2)(1/2)^4 = 6/16.",
        {
            "4/16": "That's exactly one head (4 ways).",
            "8/16": "That's an even number of heads, not exactly two.",
            "2/16": "Too few favorable sequences.",
        },
    ),
    (
        "Probability Basics",
        "If X ~ Binomial(10, 0.3), what is E[X]?",
        "3",
        ["0.3", "10", "2.1"],
        "E[X] = np = 10·0.3 = 3.",
        {
            "0.3": "That's p, not the expected count.",
            "10": "That's n, not the mean.",
            "2.1": "That's Var(X) = np(1−p), not the mean.",
        },
    ),
    (
        "Distributions",
        "Heights in a population are Normal(μ=170 cm, σ=6 cm). Approximately what fraction is between 164 and 176 cm?",
        "About 68%",
        ["About 95%", "About 50%", "About 99.7%"],
        "164 to 176 is μ±σ, so about 68% by the empirical rule.",
        {
            "About 95%": "95% corresponds to about μ±2σ (158–182 here).",
            "About 50%": "μ±σ captures much more than half under a bell curve.",
            "About 99.7%": "That needs about μ±3σ.",
        },
    ),
    (
        "Distributions",
        "Which change increases the spread of a Binomial(n, p) distribution (holding n fixed)?",
        "Moving p away from 0.5 toward 0 or 1 (while staying between them).",
        [
            "Setting p exactly to 0.5 when n > 1.",
            "Replacing binary outcomes with a constant outcome.",
            "Decreasing n while keeping p.",
        ],
        "Variance np(1−p) is maximized at p=0.5; extreme p yields lower variance but more concentration at ends.",
        {
            "Setting p exactly to 0.5 when n > 1.": "p=0.5 maximizes variance for fixed n.",
            "Replacing binary outcomes with a constant outcome.": "Constants have zero variance.",
            "Decreasing n while keeping p.": "That changes n, not p alone as asked.",
        },
    ),
    (
        "Distributions",
        "Sample means from n=100 independent observations with finite variance are approximately normal because of…",
        "The Central Limit Theorem",
        [
            "The Law of Large Numbers alone",
            "Always having skewed parent distributions",
            "Using the sample median only",
        ],
        "CLT: distribution of x̄ approaches Normal as n grows, regardless of population shape (mild conditions).",
        {
            "The Law of Large Numbers alone": "LLN concerns convergence of x̄ to μ, not the shape of x̄'s sampling distribution.",
            "Always having skewed parent distributions": "Skew can persist in small samples; CLT helps means when n is large.",
            "Using the sample median only": "CLT statement is about the mean (or sums), not the median.",
        },
    ),
    (
        "Distributions",
        "A Poisson model with rate λ = 4 per hour is appropriate when…",
        "Events occur independently at a constant average rate over time with rare multiplicities in tiny intervals.",
        [
            "There are exactly two outcomes per trial with fixed n.",
            "Variance always equals zero.",
            "The sample size n is at most 30.",
        ],
        "Poisson counts rare events in fixed intervals; mean equals variance λ.",
        {
            "There are exactly two outcomes per trial with fixed n.": "That describes Binomial, not Poisson.",
            "Variance always equals zero.": "Poisson variance is λ.",
            "The sample size n is at most 30.": "n=30 is a rule of thumb for t, not Poisson modeling.",
        },
    ),
    (
        "Confidence Intervals",
        "You have x̄=120, s=15, n=36. A 95% t-interval for μ uses margin of error t*·(s/√n). What is s/√n?",
        "2.5",
        ["15", "0.4167", "6"],
        "Standard error = 15/√36 = 15/6 = 2.5.",
        {
            "15": "That's s, not SE.",
            "0.4167": "That's s/n, not s/√n.",
            "6": "That's √n, not SE.",
        },
    ),
    (
        "Confidence Intervals",
        "Holding data fixed, widening a CI from 90% to 99% confidence will…",
        "Increase the critical multiplier and make the interval wider.",
        [
            "Always narrow the interval because we are more confident.",
            "Leave the interval unchanged if n is large.",
            "Remove the need for a standard error.",
        ],
        "Higher confidence demands a larger z or t* and a wider interval.",
        {
            "Always narrow the interval because we are more confident.": "More confidence requires a wider interval, not narrower.",
            "Leave the interval unchanged if n is large.": "The critical value still changes with confidence level.",
            "Remove the need for a standard error.": "SE is still required to build the interval.",
        },
    ),
    (
        "Confidence Intervals",
        "A 95% CI for a proportion based on x=40 successes in n=200 uses a normal approximation. What is p̂?",
        "0.20",
        ["0.40", "0.02", "0.16"],
        "p̂ = x/n = 40/200 = 0.20.",
        {
            "0.40": "That's x/100, not x/n.",
            "0.02": "That's 1/n, not the sample proportion.",
            "0.16": "That's the standard error √(0.2·0.8/200), not p̂.",
        },
    ),
    (
        "Hypothesis Testing",
        "A two-sided z-test of H₀: μ=100 versus Hₐ: μ≠100 at α=0.05 rejects when |z| exceeds…",
        "1.96",
        ["1.645", "2.58", "0.05"],
        "Two-sided 95% critical values for z are ±1.96.",
        {
            "1.645": "That's the one-sided 5% cutoff.",
            "2.58": "That's closer to 99% two-sided.",
            "0.05": "That's α, not a critical z value.",
        },
    ),
    (
        "Hypothesis Testing",
        "A test has power 0.80 against a specific alternative. If H₀ is false in that way, the probability we correctly reject H₀ is…",
        "0.80",
        ["0.20", "0.05", "1.00"],
        "Power = 1 − β = P(reject H₀ | Hₐ true in the stated way).",
        {
            "0.20": "That's β (Type II error rate) if power is 0.80.",
            "0.05": "That's a common α, not power.",
            "1.00": "Power below 1 means some chance of missing the effect.",
        },
    ),
    (
        "Hypothesis Testing",
        "A p-value of 0.03 at α=0.05 means…",
        "Reject H₀ at the 5% level (assuming a two-sided test setup matches the p-value).",
        [
            "Accept H₀ with 97% probability.",
            "H₀ is true with probability 0.03.",
            "Fail to reject H₀ at the 5% level.",
        ],
        "p < α ⇒ reject H₀ in the standard fixed-α framework.",
        {
            "Accept H₀ with 97% probability.": "We do not accept H₀; we fail to reject or reject based on α.",
            "H₀ is true with probability 0.03.": "p is not P(H₀ true).",
            "Fail to reject H₀ at the 5% level.": "0.03 < 0.05 leads to rejection.",
        },
    ),
    (
        "Regression",
        "For least-squares simple regression, the slope b₁ equals r·(s_y/s_x). If r=0.8, s_x=5, s_y=10, what is b₁?",
        "1.6",
        ["0.4", "4", "8"],
        "b₁ = 0.8·(10/5) = 1.6.",
        {
            "0.4": "Inverted the ratio s_y/s_x.",
            "4": "Used r·(s_x/s_y) or doubled incorrectly.",
            "8": "That's r·s_y, not the slope formula.",
        },
    ),
    (
        "Regression",
        "R² = 0.64 in a simple linear regression means…",
        "64% of the variation in y is explained by the linear model in the sample.",
        [
            "The correlation is 0.64.",
            "64% of residuals are zero.",
            "The slope is 0.64.",
        ],
        "R² is the squared correlation in simple regression: fraction of variance explained.",
        {
            "The correlation is 0.64.": "r could be +0.8 or −0.8 since r²=0.64.",
            "64% of residuals are zero.": "Residuals are not mostly zero; R² measures explained variation.",
            "The slope is 0.64.": "R² is not the slope.",
        },
    ),
]

_HARD = [
    (
        "Descriptive Statistics",
        "A dataset has mean 100 and median 80. Which statement is most plausible?",
        "The distribution is right-skewed with a few large outliers pulling the mean up.",
        [
            "The distribution is perfectly symmetric.",
            "The distribution is left-skewed with outliers on the low side.",
            "Mean and median must be equal for any numeric data.",
        ],
        "Mean > median is typical when a right tail contains extreme high values.",
        {
            "The distribution is perfectly symmetric.": "Symmetric data would have mean ≈ median.",
            "The distribution is left-skewed with outliers on the low side.": "Left skew usually gives mean < median.",
            "Mean and median must be equal for any numeric data.": "Skew breaks equality between mean and median.",
        },
    ),
    (
        "Descriptive Statistics",
        "Using the 1.5×IQR outlier rule on Q1=20, Q3=40 (IQR=20), values above what threshold are flagged as high outliers?",
        "70",
        ["50", "60", "80"],
        "Upper fence = Q3 + 1.5·IQR = 40 + 30 = 70.",
        {
            "50": "That's Q3 + 0.5·IQR, not 1.5·IQR.",
            "60": "That's Q3 + IQR, not 1.5·IQR.",
            "80": "That's Q3 + 2·IQR.",
        },
    ),
    (
        "Descriptive Statistics",
        "A teacher standardizes two exams: Exam A scores have x̄=70, s=5; Exam B have x̄=80, s=10. A student scored 75 on A and 85 on B. Which z-score is higher?",
        "Exam A (z=1.0) is higher than Exam B (z=0.5).",
        [
            "Exam B because the raw score is higher.",
            "They are equal because both are 5 points above their means.",
            "Exam B because its standard deviation is larger.",
        ],
        "z_A=(75−70)/5=1.0; z_B=(85−80)/10=0.5.",
        {
            "Exam B because the raw score is higher.": "Standardization compares relative standing, not raw points alone.",
            "They are equal because both are 5 points above their means.": "Equal raw gaps do not imply equal z when SDs differ.",
            "Exam B because its standard deviation is larger.": "Larger SD shrinks z for the same raw gap above the mean.",
        },
    ),
    (
        "Probability Basics",
        "Disease prevalence 1%. Test sensitivity 99%, specificity 95%. For a randomly selected person who tests positive, P(disease | +) is closest to…",
        "About 17%",
        ["About 99%", "About 95%", "About 1%"],
        "Bayes: (0.99·0.01)/(0.99·0.01 + 0.05·0.99) ≈ 0.0099/0.0594 ≈ 0.167.",
        {
            "About 99%": "That's sensitivity P(+|disease), not the posterior.",
            "About 95%": "That's specificity among healthy people, not P(disease|+).",
            "About 1%": "That's the prior before the test.",
        },
    ),
    (
        "Probability Basics",
        "Cards are drawn without replacement from a deck. P(two aces in two draws) equals…",
        "(4/52)·(3/51)",
        ["(4/52)·(4/52)", "(1/13)·(1/13)", "4/52"],
        "First ace 4/52; second ace 3/51 given one ace removed.",
        {
            "(4/52)·(4/52)": "That treats draws as independent with replacement.",
            "(1/13)·(1/13)": "Independence assumption is wrong without replacement.",
            "4/52": "That's only the first draw succeeding.",
        },
    ),
    (
        "Probability Basics",
        "Suppose P(A)=0.6, P(B)=0.5, and P(A∩B)=0.4. Are A and B independent?",
        "No, because P(A∩B)=0.4 ≠ 0.6·0.5=0.3.",
        [
            "Yes, because both probabilities exceed 0.3.",
            "Yes, because P(A)+P(B)>1.",
            "Cannot determine without knowing P(A∪B).",
        ],
        "Independence requires the joint to factorize; here 0.4 ≠ 0.3.",
        {
            "Yes, because both probabilities exceed 0.3.": "Marginals alone do not prove independence.",
            "Yes, because P(A)+P(B)>1.": "Sum exceeding 1 shows overlap, not independence.",
            "Cannot determine without knowing P(A∪B).": "The joint is enough to check the product rule.",
        },
    ),
    (
        "Distributions",
        "If X ~ Normal(μ=50, σ=10), what is P(X > 60) approximately?",
        "0.16",
        ["0.34", "0.50", "0.84"],
        "60 is one SD above mean; upper tail above z=1 is about 16%.",
        {
            "0.34": "That's about one SD below to the mean region.",
            "0.50": "That's P(X>μ), not P(X>μ+σ).",
            "0.84": "That's the area below z=1, not above.",
        },
    ),
    (
        "Distributions",
        "For X ~ Binomial(400, 0.5), a normal approximation to P(X ≤ 210) should use a continuity correction of…",
        "P(Z ≤ (210.5 − 200)/√(400·0.5·0.5))",
        [
            "P(Z ≤ (210 − 200)/10) without adjustment",
            "P(Z ≤ (209.5 − 200)/10) using 209.5",
            "Exact binomial cannot be approximated for n=400",
        ],
        "When approximating P(X≤k), use k+0.5 in the z numerator for the upper-inclusive count.",
        {
            "P(Z ≤ (210 − 200)/10) without adjustment": "Skipping +0.5 mis-handles the discrete-to-continuous bridge.",
            "P(Z ≤ (209.5 − 200)/10) using 209.5": "209.5 corresponds to P(X≤209), not P(X≤210).",
            "Exact binomial cannot be approximated for n=400": "n=400 is large enough for a normal approximation.",
        },
    ),
    (
        "Distributions",
        "Waiting times T ~ Exponential(λ=0.2 per minute) have E[T] and SD[T] equal to…",
        "5 minutes each (1/λ)",
        ["0.2 minutes each", "25 minutes each", "2.5 minutes each"],
        "Exponential mean and SD are both 1/λ = 5 when λ=0.2.",
        {
            "0.2 minutes each": "0.2 is λ, not the mean.",
            "25 minutes each": "That's 1/λ² related scale, not the mean.",
            "2.5 minutes each": "Half of 1/λ is not the Exponential SD.",
        },
    ),
    (
        "Distributions",
        "A sampling distribution of x̄ has SD 2 when n=16 from a population with σ=8. If n increases to 64 (same population), the new SD of x̄ is…",
        "1",
        ["4", "2", "0.5"],
        "SD(x̄)=σ/√n: was 8/4=2; now 8/8=1.",
        {
            "4": "Doubling SD would require smaller n, not larger.",
            "2": "That's the old SE; larger n shrinks it.",
            "0.5": "Would need n=256 with σ=8.",
        },
    ),
    (
        "Confidence Intervals",
        "A 99% CI for μ is (48, 52) using a normal critical value. If everything else stays fixed except confidence drops to 95%, the new interval will be…",
        "Narrower than (48, 52)",
        ["Wider than (48, 52)", "Exactly (48, 52)", "Invalid without resampling"],
        "Lower confidence uses a smaller z* (about 1.96 vs 2.58), shrinking margin of error.",
        {
            "Wider than (48, 52)": "99% is wider than 95% for the same data and method.",
            "Exactly (48, 52)": "Changing confidence changes the critical multiplier.",
            "Invalid without resampling": "You can recompute the interval from the same x̄ and SE.",
        },
    ),
    (
        "Confidence Intervals",
        "Bootstrap percentile intervals for the median are preferred over a naive x̄±z·s/√n interval when…",
        "The data are strongly skewed with small n and the parameter of interest is the median.",
        [
            "The sample is huge and perfectly normal.",
            "You need a CI for the population mean with known σ.",
            "Every dataset has zero skew by definition.",
        ],
        "Bootstrap resamples the data to approximate the sampling distribution without normality for the median.",
        {
            "The sample is huge and perfectly normal.": "Classic t intervals often suffice for means with large normal samples.",
            "You need a CI for the population mean with known σ.": "Known-σ z intervals are a different scenario.",
            "Every dataset has zero skew by definition.": "Real data are often skewed.",
        },
    ),
    (
        "Confidence Intervals",
        "A two-sample t-interval for μ₁−μ₂ assumes (for the standard pooled-variance version taught early) that…",
        "Both groups are independent random samples with approximately normal populations and equal unknown variances.",
        [
            "Paired measurements within subjects are required.",
            "Population variances are known constants.",
            "Sample sizes must be exactly 30 each.",
        ],
        "Pooled two-sample t uses sp² combining groups under equal-variance assumption.",
        {
            "Paired measurements within subjects are required.": "Paired designs use differences and a one-sample t on pairs.",
            "Population variances are known constants.": "That's a z scenario, not the usual pooled t.",
            "Sample sizes must be exactly 30 each.": "n=30 is a guideline, not a strict requirement.",
        },
    ),
    (
        "Hypothesis Testing",
        "You perform 20 independent tests at α=0.05 with all nulls true. The expected number of false rejections is…",
        "1",
        ["0.05", "20", "10"],
        "Expected Type I errors ≈ m·α = 20·0.05 = 1.",
        {
            "0.05": "That's α per test, not the total expected count.",
            "20": "Would mean every test rejects, not the expectation under true nulls.",
            "10": "Not m·α for m=20.",
        },
    ),
    (
        "Hypothesis Testing",
        "A one-sample t-test for μ with n=15, s=12, x̄=118, H₀: μ=100, two-sided, gives t = (118−100)/(12/√15). What is |t|?",
        "About 5.81",
        ["About 1.5", "About 18", "About 0.45"],
        "|t| = 18/(12/3.873) ≈ 18/3.098 ≈ 5.81.",
        {
            "About 1.5": "That's the raw difference 18 divided by s incorrectly.",
            "About 18": "That's the numerator only, not divided by SE.",
            "About 0.45": "Uses s instead of SE in the denominator.",
        },
    ),
    (
        "Hypothesis Testing",
        "Switching from a two-sided to a one-sided test (same data, same α) will…",
        "Decrease the reported p-value (for a directionally consistent effect) and can increase power.",
        [
            "Always increase the p-value because less area is tested.",
            "Change only the sample size n.",
            "Make Type I error exceed α automatically.",
        ],
        "One-sided puts all α in one tail when the effect direction matches Hₐ.",
        {
            "Always increase the p-value because less area is tested.": "Halving tails can halve the p-value for the same z in the correct direction.",
            "Change only the sample size n.": "The data and n are unchanged; only the alternative tail changes.",
            "Make Type I error exceed α automatically.": "α is still controlled at the chosen level.",
        },
    ),
    (
        "Hypothesis Testing",
        "A 95% CI for μ is entirely above 0. For a two-sided test of H₀: μ=0 versus Hₐ: μ≠0 at α=0.05, you should…",
        "Reject H₀",
        [
            "Fail to reject H₀",
            "Accept H₀ with probability 0.95",
            "Conclude μ equals the upper endpoint exactly",
        ],
        "Equivalence: interval excludes 0 ⇔ two-sided test rejects μ=0 at matching 95% level (normal/t setup).",
        {
            "Fail to reject H₀": "0 is not inside the CI, so H₀: μ=0 is inconsistent.",
            "Accept H₀ with probability 0.95": "Tests do not yield P(H₀ true).",
            "Conclude μ equals the upper endpoint exactly": "The CI bounds an range, not a point estimate only.",
        },
    ),
    (
        "Regression",
        "A residual plot shows a clear curved pattern (smile shape) while r=0.9. What is the best conclusion?",
        "A linear model is inadequate despite high r; consider transformation or nonlinear terms.",
        [
            "The linear model is perfect because r is large.",
            "Outliers are impossible when r>0.8.",
            "Correlation proves the relationship is linear.",
        ],
        "r measures linear association; systematic curvature in residuals violates linearity assumptions.",
        {
            "The linear model is perfect because r is large.": "High r can still miss systematic curvature.",
            "Outliers are impossible when r>0.8.": "Outliers and curvature can coexist.",
            "Correlation proves the relationship is linear.": "r can be high for monotone nonlinear patterns too.",
        },
    ),
    (
        "Regression",
        "In regression, the least-squares line always passes through which point?",
        "(x̄, ȳ)",
        ["(0, 0)", "(min x, min y)", "(max x, max y)"],
        "The fitted line satisfies ȳ = b₀ + b₁x̄, so it goes through the sample means.",
        {
            "(0, 0)": "Only if the means are zero.",
            "(min x, min y)": "The line need not touch corner points of the data cloud.",
            "(max x, max y)": "Extreme points need not lie on the LS line.",
        },
    ),
    (
        "Regression",
        "Adding a spurious variable that is pure random noise to a multiple regression will, on average across many samples, tend to…",
        "Not improve true out-of-sample prediction and can inflate R² in-sample.",
        [
            "Always decrease R² in-sample.",
            "Guarantee statistically significant coefficients.",
            "Make residuals exactly zero for all rows.",
        ],
        "Extra noise predictors may fit sample idiosyncrasies (higher R²) without real predictive gain.",
        {
            "Always decrease R² in-sample.": "In-sample R² never decreases when adding predictors.",
            "Guarantee statistically significant coefficients.": "Noise variables are usually insignificant.",
            "Make residuals exactly zero for all rows.": "Perfect fit needs as many orthogonal predictors as points, not random noise alone.",
        },
    ),
]

BOOK = make_book(
    title="OpenIntro Statistics",
    parent_topic="Mathematics",
    subtopic="Statistics",
    slug="statistics-openintro",
    source_url="https://www.openintro.org/book/os/",
    easy=_EASY,
    medium=_MEDIUM,
    hard=_HARD,
)
