"""Quiz bank: Transformers (Dive into Deep Learning)."""
from quiz_banks._make_book import make_book

EASY = [
    (
        "Attention",
        "In the attention mechanism, what does the softmax over keys produce?",
        "A probability distribution over positions to weight values.",
        [
            "A fixed one-hot vector over the sequence",
            "The raw dot products without normalization",
            "The gradient of the loss with respect to queries",
        ],
        "Attention weights αᵢ = softmax(score(q, kᵢ)); they sum to 1 and select how much of each value to blend.",
        {
            "A fixed one-hot vector over the sequence": "Softmax yields a full distribution, not a single hard index (unless degenerate).",
            "The raw dot products without normalization": "Dot products are scores; softmax turns them into weights.",
            "The gradient of the loss with respect to queries": "Softmax is part of the forward pass, not backprop by definition here.",
        },
    ),
    (
        "Attention",
        "Scaled dot-product attention divides dot products by √d_k primarily to…",
        "Keep softmax inputs in a moderate range so gradients do not vanish.",
        [
            "Make attention weights exactly uniform",
            "Convert dot products into probabilities directly",
            "Eliminate the need for positional encoding",
        ],
        "Large d_k makes dot-product magnitudes large; scaling prevents extremely peaked softmax and tiny gradients.",
        {
            "Make attention weights exactly uniform": "Scaling stabilizes variance; it does not force uniform weights.",
            "Convert dot products into probabilities directly": "Softmax, not scaling alone, produces probabilities.",
            "Eliminate the need for positional encoding": "Positional encoding addresses order; scaling addresses magnitude.",
        },
    ),
    (
        "Attention",
        "The output of a single attention head is best described as…",
        "A weighted sum of value vectors using attention weights on keys.",
        [
            "The element-wise product of query and key only",
            "The maximum value vector in the sequence",
            "The average of all keys without weighting",
        ],
        "output = Σᵢ αᵢ vᵢ where αᵢ come from comparing the query to each key.",
        {
            "The element-wise product of query and key only": "Dot products score compatibility; values are aggregated, not just multiplied.",
            "The maximum value vector in the sequence": "Attention blends values; argmax would be hard selection.",
            "The average of all keys without weighting": "Keys set weights; values are what get summed.",
        },
    ),
    (
        "Self-Attention",
        "In self-attention, queries, keys, and values are derived from…",
        "The same input sequence (via learned linear projections).",
        [
            "A separate encoder-only memory bank",
            "Random noise vectors sampled each step",
            "Only the final token embedding",
        ],
        "Self-attention relates every position to every other position in one sequence: Q, K, V all come from X.",
        {
            "A separate encoder-only memory bank": "That describes cross-attention to another sequence.",
            "Random noise vectors sampled each step": "Q, K, V are deterministic functions of embeddings.",
            "Only the final token embedding": "All positions participate, not just the last token.",
        },
    ),
    (
        "Self-Attention",
        "Self-attention lets each token directly attend to…",
        "Any other token in the same sequence.",
        [
            "Only its immediate left neighbor",
            "Only tokens in a different batch element",
            "Only padding tokens exclusively",
        ],
        "All-pairs interactions build long-range dependencies in one layer (subject to masking in decoders).",
        {
            "Only its immediate left neighbor": "That is local recurrence; self-attention is all-to-all.",
            "Only tokens in a different batch element": "Attention is within one sequence instance.",
            "Only padding tokens exclusively": "Models mask padding out, not attend only to it.",
        },
    ),
    (
        "Self-Attention",
        "Compared with a single RNN layer over length n, vanilla self-attention's time complexity is often cited as…",
        "O(n²) in sequence length for the attention matrix.",
        [
            "O(n) because it runs in one parallel pass",
            "O(1) regardless of sequence length",
            "O(n³) due to three matmuls",
        ],
        "Computing all pairwise scores costs O(n²); parallel depth is O(1) per layer vs O(n) for RNNs.",
        {
            "O(n) because it runs in one parallel pass": "Parallelism is good, but pairwise scores still scale quadratically.",
            "O(1) regardless of sequence length": "Longer sequences still increase attention cost.",
            "O(n³) due to three matmuls": "QKV projections are O(n); the bottleneck is n×n attention.",
        },
    ),
    (
        "Positional Encoding",
        "Transformers have no built-in notion of token order, so positional encodings are added to…",
        "Inject information about each token's position in the sequence.",
        [
            "Replace the embedding layer entirely",
            "Normalize gradients across layers",
            "Reduce the vocabulary size",
        ],
        "Attention is permutation-invariant on embeddings alone; position tags break symmetry.",
        {
            "Replace the embedding layer entirely": "Positions augment token embeddings, not replace them.",
            "Normalize gradients across layers": "That is layer norm's role, not positional encoding.",
            "Reduce the vocabulary size": "Vocabulary is unrelated to sequence order.",
        },
    ),
    (
        "Positional Encoding",
        "Sinusoidal positional encodings in the original Transformer use…",
        "Fixed sine and cosine waves at different frequencies per dimension.",
        [
            "Learned integer indices only at training time",
            "One-hot vectors of length equal to vocabulary",
            "Random Gaussian noise added once per epoch",
        ],
        "PE(pos, 2i) = sin(pos / 10000^{2i/d}); cos on even/odd pairs gives smooth relative structure.",
        {
            "Learned integer indices only at training time": "Sinusoidal encodings are deterministic functions of position.",
            "One-hot vectors of length equal to vocabulary": "Position is not the same as token identity.",
            "Random Gaussian noise added once per epoch": "Sinusoidal PE is fixed, not resampled noise.",
        },
    ),
    (
        "Encoder-Decoder",
        "In a Transformer for machine translation, the encoder typically…",
        "Maps the source sentence to a stack of contextual representations.",
        [
            "Generates target tokens one at a time autoregressively",
            "Applies causal masking to every position",
            "Stores only the final hidden state as a single vector",
        ],
        "The encoder processes the full source with bidirectional (unmasked) self-attention.",
        {
            "Generates target tokens one at a time autoregressively": "Autoregressive generation is the decoder's job.",
            "Applies causal masking to every position": "Causal masking is used in the decoder, not the encoder stack.",
            "Stores only the final hidden state as a single vector": "All source positions remain available via representations.",
        },
    ),
    (
        "Encoder-Decoder",
        "Decoder cross-attention lets each target position attend to…",
        "Encoder outputs (memory) while also using masked self-attention on prior targets.",
        [
            "Future target tokens not yet generated",
            "Only its own embedding without context",
            "Random keys from an unrelated batch",
        ],
        "Cross-attention queries come from the decoder state; keys and values come from encoder outputs.",
        {
            "Future target tokens not yet generated": "Causal self-attention blocks future targets; cross-attn reads source.",
            "Only its own embedding without context": "Cross-attention explicitly pulls source information.",
            "Random keys from an unrelated batch": "Memory is aligned to the paired source sentence.",
        },
    ),
    (
        "Encoder-Decoder",
        "Teacher forcing during Transformer training means…",
        "The decoder input uses ground-truth previous tokens, not model predictions.",
        [
            "The teacher model has fewer layers than the student",
            "Gradients are disabled in the encoder",
            "Attention weights are frozen after epoch one",
        ],
        "Feeding correct prefixes speeds stable training; at inference the model feeds its own outputs.",
        {
            "The teacher model has fewer layers than the student": "Teacher forcing refers to inputs, not model distillation here.",
            "Gradients are disabled in the encoder": "Both stacks are typically trained jointly.",
            "Attention weights are frozen after epoch one": "Weights continue to update throughout training.",
        },
    ),
    (
        "Multi-Head Attention",
        "Multi-head attention runs several attention operations in parallel and then…",
        "Concatenates head outputs and projects them with a linear layer.",
        [
            "Averages all heads into a single scalar",
            "Discards all but the first head at inference",
            "Applies softmax across heads instead of positions",
        ],
        "Each head has its own Q, K, V projections; concat + W_O mixes subspaces.",
        {
            "Averages all heads into a single scalar": "Head outputs are vectors concatenated, not reduced to one scalar.",
            "Discards all but the first head at inference": "All heads contribute at train and test time.",
            "Applies softmax across heads instead of positions": "Softmax is over sequence positions within each head.",
        },
    ),
    (
        "Multi-Head Attention",
        "Using multiple heads allows the model to…",
        "Capture different relationship types (syntax, coreference, etc.) in parallel.",
        [
            "Reduce sequence length by a factor of h",
            "Eliminate the feed-forward sublayer",
            "Remove the need for layer normalization",
        ],
        "Different heads can specialize in distinct attention patterns over the same tokens.",
        {
            "Reduce sequence length by a factor of h": "Head count does not shorten the sequence.",
            "Eliminate the feed-forward sublayer": "FFN remains part of each Transformer block.",
            "Remove the need for layer normalization": "Layer norm is still used around sublayers.",
        },
    ),
    (
        "Multi-Head Attention",
        "If model dimension is d_model and there are h heads, each head typically uses dimension…",
        "d_k = d_v = d_model / h",
        [
            "d_model × h",
            "1 regardless of h",
            "twice the vocabulary size",
        ],
        "Splitting d_model across h heads keeps total parameter footprint manageable.",
        {
            "d_model × h": "Per-head dimension shrinks as h grows, not multiplies d_model.",
            "1 regardless of h": "Heads use substantial subspaces, not scalars only.",
            "twice the vocabulary size": "Head size is architectural, not tied to |V|.",
        },
    ),
    (
        "LLM Basics",
        "Large language models are typically trained with a…",
        "Causal (autoregressive) next-token prediction objective.",
        [
            "Purely masked bidirectional objective on full sentences only",
            "Clustering loss over document embeddings",
            "Pairwise ranking loss on image patches",
        ],
        "Given prefix tokens, the model predicts the distribution of the next token (MLE / cross-entropy).",
        {
            "Purely masked bidirectional objective on full sentences only": "BERT-style MLM is different from standard GPT-style LLM training.",
            "Clustering loss over document embeddings": "LLM pretraining is generative token modeling, not k-means.",
            "Pairwise ranking loss on image patches": "LLMs are text models; that describes vision ranking.",
        },
    ),
    (
        "LLM Basics",
        "At inference, autoregressive LLMs generate text by repeatedly…",
        "Sampling or selecting one token, appending it, and conditioning on the longer prefix.",
        [
            "Encoding the entire future paragraph in one forward pass",
            "Re-training all weights after each character",
            "Sorting the vocabulary alphabetically each step",
        ],
        "Each step extends the context; total cost grows with output length unless cached.",
        {
            "Encoding the entire future paragraph in one forward pass": "Future tokens are not known; generation is sequential.",
            "Re-training all weights after each character": "Weights are fixed at inference; only activations update.",
            "Sorting the vocabulary alphabetically each step": "Decoding uses model logits, not lexical sorting.",
        },
    ),
    (
        "LLM Basics",
        "Temperature in LLM sampling scales logits before softmax to…",
        "Control randomness — higher temperature yields flatter, more diverse distributions.",
        [
            "Increase model depth dynamically",
            "Cache key-value pairs from prior layers",
            "Enforce grammatical POS tags",
        ],
        "T > 1 spreads probability mass; T → 0 approaches greedy argmax.",
        {
            "Increase model depth dynamically": "Temperature affects sampling, not architecture depth.",
            "Cache key-value pairs from prior layers": "That is KV-cache optimization, not temperature.",
            "Enforce grammatical POS tags": "Sampling temperature does not hard-constrain syntax.",
        },
    ),
    (
        "KV Cache",
        "During autoregressive decoding, a KV cache stores…",
        "Previously computed key and value projections for past tokens.",
        [
            "The entire training dataset in RAM",
            "Only the softmax attention weights from step zero",
            "Gradients from the backward pass of prior tokens",
        ],
        "Keys and values for prefix tokens are reused instead of recomputed each new step.",
        {
            "The entire training dataset in RAM": "Caches hold activations for the current sequence, not the corpus.",
            "Only the softmax attention weights from step zero": "Caches store K and V tensors per layer, not just weights.",
            "Gradients from the backward pass of prior tokens": "Inference often runs without storing training gradients.",
        },
    ),
    (
        "KV Cache",
        "KV caching speeds up decoding because each new token…",
        "Only needs a forward pass for its query attending to cached K/V of the prefix.",
        [
            "Skips the attention mechanism entirely",
            "Reduces model parameters by half",
            "Eliminates the vocabulary softmax",
        ],
        "Work per step becomes roughly O(n) per layer on context length instead of recomputing O(n²) over the full prefix.",
        {
            "Skips the attention mechanism entirely": "Attention remains; prior K/V are reused.",
            "Reduces model parameters by half": "Parameter count is unchanged; compute is saved.",
            "Eliminates the vocabulary softmax": "The output projection and softmax still run each step.",
        },
    ),
    (
        "KV Cache",
        "Memory used by a KV cache grows with…",
        "Context length, number of layers, batch size, and hidden dimension.",
        [
            "Only the learning rate schedule",
            "The number of training epochs completed",
            "Whether layer norm uses bias terms",
        ],
        "Each layer stores K and V for all past positions — longer contexts mean larger caches.",
        {
            "Only the learning rate schedule": "Optimizer hyperparameters do not define cache size.",
            "The number of training epochs completed": "Cache size is a runtime inference concern, not epoch count.",
            "Whether layer norm uses bias terms": "Norm bias is tiny compared to per-token K/V storage.",
        },
    ),
]

MEDIUM = [
    (
        "Attention",
        "Bahdanau (additive) attention scores compatibility with…",
        "A feed-forward network on concatenated or combined query and key features.",
        [
            "Only the L2 distance between value vectors",
            "The determinant of the query-key outer product",
            "A fixed lookup table indexed by token ID",
        ],
        "score(q, k) = vᵀ tanh(W_q q + W_k k) generalizes dot-product when dimensions differ.",
        {
            "Only the L2 distance between value vectors": "Values are aggregated after scoring; scoring uses q and k.",
            "The determinant of the query-key outer product": "Attention scores are per-position scalars, not matrix determinants.",
            "A fixed lookup table indexed by token ID": "Scores are computed from representations, not static tables.",
        },
    ),
    (
        "Attention",
        "When attention scores are very large before softmax, the distribution becomes…",
        "Nearly one-hot, with small gradients to non-argmax keys.",
        [
            "Uniform with maximal gradient everywhere",
            "Always zero for every position",
            "Independent of the query vector",
        ],
        "Peaked softmax saturates; scaling dot products mitigates this in Transformers.",
        {
            "Uniform with maximal gradient everywhere": "Large logits yield peaked, not uniform, distributions.",
            "Always zero for every position": "Softmax always assigns positive mass summing to 1.",
            "Independent of the query vector": "Scores depend on q · k (or general score functions).",
        },
    ),
    (
        "Self-Attention",
        "In a Transformer encoder block, self-attention is followed by…",
        "A position-wise feed-forward network and residual connections with layer norm.",
        [
            "A recurrent state passed to the next sentence only",
            "A convolution with kernel size equal to vocabulary",
            "Deleting half the hidden dimensions permanently",
        ],
        "Pre-norm or post-norm variants wrap attention and FFN: Attn → FFN with residuals.",
        {
            "A recurrent state passed to the next sentence only": "Blocks are depth-stacked; RNN hidden state is not the core pattern.",
            "A convolution with kernel size equal to vocabulary": "FFN is two linear layers with activation on each position.",
            "Deleting half the hidden dimensions permanently": "Dimension is preserved across the block (aside from internal FFN expansion).",
        },
    ),
    (
        "Self-Attention",
        "Causal (masked) self-attention in GPT-style models sets attention logits to −∞ for…",
        "Positions j > i so token i cannot attend to future tokens.",
        [
            "All padding tokens in both directions",
            "Every pair of tokens in the encoder",
            "Only the first token in the sequence",
        ],
        "An upper-triangular mask preserves autoregressive conditioning: predict next token from past.",
        {
            "All padding tokens in both directions": "Padding uses separate masks; causal mask is about temporal order.",
            "Every pair of tokens in the encoder": "Encoder self-attention is typically unmasked bidirectional.",
            "Only the first token in the sequence": "Each position has its own allowed prefix set.",
        },
    ),
    (
        "Self-Attention",
        "Multi-layer self-attention stacks increase expressive power because…",
        "Later layers can build on increasingly mixed contextual representations.",
        [
            "Each layer removes positional information entirely",
            "Depth replaces the need for any parameters",
            "Only the first layer may attend to all positions",
        ],
        "Composition of attention + FFN lets higher layers model more abstract dependencies.",
        {
            "Each layer removes positional information entirely": "Positional signals propagate; depth refines context.",
            "Depth replaces the need for any parameters": "More layers add parameters and computation.",
            "Only the first layer may attend to all positions": "Every layer performs full (masked) attention over allowed positions.",
        },
    ),
    (
        "Positional Encoding",
        "Learned absolute positional embeddings differ from sinusoidal encodings in that they…",
        "Are trainable vectors indexed by position, capped by a maximum length.",
        [
            "Require no parameters and generalize beyond max length by formula",
            "Encode only relative distance without any position index",
            "Replace token embeddings in the output softmax",
        ],
        "Learned PE is flexible but may not extrapolate well past trained max sequence length.",
        {
            "Require no parameters and generalize beyond max length by formula": "That describes fixed sinusoidal encodings, not learned tables.",
            "Encode only relative distance without any position index": "Absolute learned embeddings tie to index i.",
            "Replace token embeddings in the output softmax": "Positions are added to inputs, not the final logits layer.",
        },
    ),
    (
        "Positional Encoding",
        "Relative positional bias (e.g., in T5 or some long-context models) modifies attention by…",
        "Adding a score based on distance i − j rather than only absolute position vectors.",
        [
            "Removing keys from distant tokens entirely",
            "Using only sinusoidal functions in the output layer",
            "Forcing all attention weights to be equal",
        ],
        "Relative biases let the model generalize patterns like 'nearby vs far' across sequence lengths.",
        {
            "Removing keys from distant tokens entirely": "Bias shifts scores; it does not drop keys.",
            "Using only sinusoidal functions in the output layer": "Biases are often learned buckets or functions of distance.",
            "Forcing all attention weights to be equal": "Bias changes relative preferences, not uniformity.",
        },
    ),
    (
        "Encoder-Decoder",
        "The original Transformer ties encoder and decoder with…",
        "Shared embedding space and stacked layers where decoder cross-attends to encoder memory.",
        [
            "Identical weights for every encoder and decoder layer",
            "No attention between source and target",
            "A single RNN hidden state between both sides",
        ],
        "Embeddings may be shared; decoder layers consume encoder outputs via cross-attention.",
        {
            "Identical weights for every encoder and decoder layer": "Layers are separate modules with different roles.",
            "No attention between source and target": "Cross-attention is the bridge from source to target.",
            "A single RNN hidden state between both sides": "Transformers replace RNN state with attention memory.",
        },
    ),
    (
        "Encoder-Decoder",
        "Beam search in Transformer decoding maintains…",
        "Multiple partial hypotheses ranked by cumulative log-probability.",
        [
            "A single greedy path with no alternatives",
            "The full attention matrix from training only",
            "All vocabulary words as equally likely each step",
        ],
        "Beam width b keeps top-b prefixes; expansion trades compute for better translations.",
        {
            "A single greedy path with no alternatives": "Beam search explicitly explores multiple prefixes.",
            "The full attention matrix from training only": "Beam search operates on decoding scores, not stored train matrices.",
            "All vocabulary words as equally likely each step": "Log-probs from the model rank continuations.",
        },
    ),
    (
        "Encoder-Decoder",
        "Encoder-decoder models like T5 frame many NLP tasks as…",
        "Text-to-text generation with a unified span-corruption or instruction format.",
        [
            "Purely contrastive image-caption ranking",
            "Unsupervised k-means over byte n-grams only",
            "Static template filling without neural parameters",
        ],
        "T5 casts classification, translation, and QA as generating target text strings.",
        {
            "Purely contrastive image-caption ranking": "T5 is text-to-text, not CLIP-style vision contrastive learning.",
            "Unsupervised k-means over byte n-grams only": "Training uses neural denoising / supervised text objectives.",
            "Static template filling without neural parameters": "The model learns parameters end-to-end.",
        },
    ),
    (
        "Multi-Head Attention",
        "With h heads and model dimension d_model, the concat of head outputs has dimension…",
        "h × (d_model / h) = d_model before the output projection.",
        [
            "d_model / h²",
            "2 × vocabulary size",
            "h² × d_model",
        ],
        "Each head outputs d_v = d_model/h; concatenating h heads restores width d_model.",
        {
            "d_model / h²": "Dimensions add across heads linearly, not divided twice.",
            "2 × vocabulary size": "Internal width is architectural, not 2|V|.",
            "h² × d_model": "Concatenation is linear in h, not h squared times d_model.",
        },
    ),
    (
        "Multi-Head Attention",
        "Grouped-query attention (GQA) reduces KV-cache memory by…",
        "Sharing one key-value head group among several query heads.",
        [
            "Removing queries entirely from inference",
            "Storing only the softmax normalization constant",
            "Using a vocabulary of size one",
        ],
        "Fewer distinct K/V projections are cached while queries remain numerous.",
        {
            "Removing queries entirely from inference": "Queries are still computed each step; K/V are shared.",
            "Storing only the softmax normalization constant": "Caches hold K/V tensors, not just scalar norms.",
            "Using a vocabulary of size one": "GQA is a head grouping trick, not trivial vocab.",
        },
    ),
    (
        "Multi-Head Attention",
        "Attention dropout is typically applied to…",
        "Attention probability weights (or their dropped counterparts) during training.",
        [
            "The final softmax over the vocabulary at decode time only",
            "All layer-normalization scale parameters",
            "The learning rate each optimizer step",
        ],
        "Dropping attention edges regularizes which positions interact, similar to edge dropout.",
        {
            "The final softmax over the vocabulary at decode time only": "That is separate from attention-weight dropout inside the block.",
            "All layer-normalization scale parameters": "Dropout targets activations/weights patterns, not γ in norm.",
            "The learning rate each optimizer step": "Dropout is stochastic regularization, not LR scheduling.",
        },
    ),
    (
        "LLM Basics",
        "Instruction-tuned LLMs are usually built by…",
        "Fine-tuning on prompt-response pairs (often after RLHF or preference optimization).",
        [
            "Removing the tokenizer and using raw bytes only",
            "Training only the positional embedding table",
            "Freezing all layers and training solely the softmax bias",
        ],
        "Supervised fine-tuning (and optional RLHF/DPO) aligns behavior to human instructions.",
        {
            "Removing the tokenizer and using raw bytes only": "Tokenization remains; tuning updates broader weights.",
            "Training only the positional embedding table": "Instruction tuning updates much of the network.",
            "Freezing all layers and training solely the softmax bias": "Far more than bias terms typically change.",
        },
    ),
    (
        "LLM Basics",
        "Top-p (nucleus) sampling chooses the next token from…",
        "The smallest set of highest-probability tokens whose cumulative mass exceeds p.",
        [
            "Exactly the top 1 token always",
            "A uniform random subset of size p tokens",
            "All tokens with probability below p only",
        ],
        "Nucleus sampling adapts breadth to model confidence, truncating the long tail.",
        {
            "Exactly the top 1 token always": "That is greedy decoding; top-p keeps a variable-sized set.",
            "A uniform random subset of size p tokens": "p is a cumulative probability threshold, not a count.",
            "All tokens with probability below p only": "Nucleus keeps high-mass tokens, not the low tail.",
        },
    ),
    (
        "LLM Basics",
        "Context window limits in LLMs arise primarily from…",
        "Quadratic attention cost and finite memory for activations or KV cache.",
        [
            "The tokenizer forbidding sequences longer than 10 tokens",
            "Loss functions that only accept two tokens",
            "CPUs being unable to multiply matrices",
        ],
        "Longer contexts increase memory and compute; architectures and caches must scale accordingly.",
        {
            "The tokenizer forbidding sequences longer than 10 tokens": "Modern tokenizers support thousands+ positions with engineering limits.",
            "Loss functions that only accept two tokens": "Cross-entropy applies per token across the whole window.",
            "CPUs being unable to multiply matrices": "Hardware limits exist, but the binding issue is model design and memory.",
        },
    ),
    (
        "KV Cache",
        "For batch inference with KV cache, each sequence in the batch needs…",
        "Separate cache slots (or paged blocks) so prefixes do not overwrite each other.",
        [
            "A single shared cache with no sequence id",
            "No storage because batches are stateless",
            "Recomputation of the full prompt every token for all rows",
        ],
        "Parallel decoding requires isolated K/V history per request in the batch.",
        {
            "A single shared cache with no sequence id": "Shared cache would mix unrelated conversations.",
            "No storage because batches are stateless": "Autoregressive batches are stateful across decode steps.",
            "Recomputation of the full prompt every token for all rows": "Caching avoids that redundant work.",
        },
    ),
    (
        "KV Cache",
        "PagedAttention (as in vLLM) improves KV-cache use by…",
        "Allocating non-contiguous fixed-size blocks analogous to virtual memory pages.",
        [
            "Storing weights in FP64 only",
            "Eliminating multi-head attention completely",
            "Training the model from scratch each request",
        ],
        "Paging reduces fragmentation when sequences of different lengths share GPU memory.",
        {
            "Storing weights in FP64 only": "Paging concerns activation cache layout, not weight dtype.",
            "Eliminating multi-head attention completely": "Attention remains; memory management changes.",
            "Training the model from scratch each request": "Serving reuses trained weights; cache is per-session state.",
        },
    ),
    (
        "KV Cache",
        "When using KV cache, the compute for a new token's query against length-n context is…",
        "O(n) per layer for attending to n cached keys (per head), not recomputing all n queries.",
        [
            "O(1) because cache removes all dependence on n",
            "O(n³) because cache cubes the sequence",
            "O(n²) for recomputing every prior query from scratch",
        ],
        "One new query attends to n stored keys; prior queries need not be re-forwarded.",
        {
            "O(1) because cache removes all dependence on n": "Attention still scales linearly with context per new token.",
            "O(n³) because cache cubes the sequence": "Caching reduces work; it does not introduce cubic cost.",
            "O(n²) for recomputing every prior query from scratch": "That is the uncached cost pattern caching avoids for old queries.",
        },
    ),
    (
        "Attention",
        "Luong dot attention and scaled dot-product attention differ mainly when…",
        "Luong uses dot(q, k) without the √d_k scale (and may use other score variants).",
        [
            "Luong forbids any use of value vectors",
            "Scaled dot-product never uses softmax",
            "Luong only applies to convolutional encoders",
        ],
        "The Transformer popularized scaled dot-product; Luong's multiplicative scores are closely related.",
        {
            "Luong forbids any use of value vectors": "Both paradigms aggregate values after scoring.",
            "Scaled dot-product never uses softmax": "Softmax normalization is standard in both families.",
            "Luong only applies to convolutional encoders": "Dot scores are architecture-agnostic.",
        },
    ),
]

HARD = [
    (
        "Self-Attention",
        "FlashAttention reduces memory traffic primarily by…",
        "Tiling softmax and matmuls to avoid materializing the full n×n attention matrix in HBM.",
        [
            "Replacing softmax with a linear activation",
            "Computing attention on CPU only",
            "Removing value vectors from the computation",
        ],
        "IO-aware tiling recomputes blocks on chip, cutting reads/writes of the large attention matrix.",
        {
            "Replacing softmax with a linear activation": "Softmax remains; fusion and tiling change memory movement.",
            "Computing attention on CPU only": "FlashAttention targets fast GPU kernels.",
            "Removing value vectors from the computation": "Values are still required for the weighted sum output.",
        },
    ),
    (
        "Self-Attention",
        "Rotary Position Embedding (RoPE) encodes position by…",
        "Rotating query and key pairs in 2D subspaces as a function of absolute index.",
        [
            "Adding a large constant to every value vector",
            "Permuting the vocabulary alphabetically",
            "Zeroing all dimensions past position 512",
        ],
        "RoPE encodes relative position in q·k via rotations; popular in LLaMA-class models.",
        {
            "Adding a large constant to every value vector": "RoPE acts on q and k, not via a single value offset trick.",
            "Permuting the vocabulary alphabetically": "Position encoding is in embedding space, not vocab order.",
            "Zeroing all dimensions past position 512": "RoPE does not hard-truncate dimensions that way.",
        },
    ),
    (
        "Positional Encoding",
        "ALiBi (Attention with Linear Biases) extends context by…",
        "Adding a linear penalty to attention logits based on key-query distance.",
        [
            "Training a separate RNN solely for position",
            "Doubling the embedding dimension every layer",
            "Removing causal masking in decoder-only models",
        ],
        "Slopes m_h per head bias distant keys, improving length extrapolation without explicit PE vectors.",
        {
            "Training a separate RNN solely for position": "ALiBi modifies attention scores directly.",
            "Doubling the embedding dimension every layer": "ALiBi does not require widening d_model each layer.",
            "Removing causal masking in decoder-only models": "Causal masking remains for autoregressive models.",
        },
    ),
    (
        "Positional Encoding",
        "Relative position representations (Shaw et al.) add embeddings for…",
        "Clipped relative distance between query index i and key index j.",
        [
            "The global document ID in a corpus",
            "The optimizer's second-moment estimates",
            "The number of FFN parameters only",
        ],
        "Learned or bucketed embeddings on (i − j) augment attention logits beyond content similarity.",
        {
            "The global document ID in a corpus": "Relative PE is intra-sequence, not a corpus-level ID.",
            "The optimizer's second-moment estimates": "Adam moments are unrelated to attention PE.",
            "The number of FFN parameters only": "Relative bias is about token offsets, not parameter counts.",
        },
    ),
    (
        "Encoder-Decoder",
        "In the Transformer, why are residual connections and layer normalization critical?",
        "They stabilize optimization of deep stacks and preserve signal through sublayers.",
        [
            "They remove the need for any attention computation",
            "They guarantee BLEU score of 100 on all languages",
            "They convert the model into a linear classifier only",
        ],
        "Residual paths + norm prevent vanishing signal and enable training many layers.",
        {
            "They remove the need for any attention computation": "Attention and FFN remain essential.",
            "They guarantee BLEU score of 100 on all languages": "No architectural trick guarantees perfect translation.",
            "They convert the model into a linear classifier only": "Transformers remain highly non-linear function approximators.",
        },
    ),
    (
        "Encoder-Decoder",
        "Cross-attention memory in the decoder uses encoder keys/values while queries come from…",
        "The decoder's current hidden state at that layer and position.",
        [
            "Random Gaussian vectors independent of the target",
            "Only the source embedding matrix untransformed",
            "Future target tokens supplied by the user at train time",
        ],
        "Q = H_dec; K,V = H_enc aligns each generating position with relevant source states.",
        {
            "Random Gaussian vectors independent of the target": "Queries are deterministic functions of decoder states.",
            "Only the source embedding matrix untransformed": "Encoder outputs are deep contextualized representations.",
            "Future target tokens supplied by the user at train time": "Future targets are masked in self-attention, not used as queries here.",
        },
    ),
    (
        "Multi-Head Attention",
        "Multi-query attention (MQA) uses…",
        "One shared key head and one shared value head across all query heads.",
        [
            "Independent K/V per query with no sharing",
            "No query projections at all",
            "Attention without any value aggregation",
        ],
        "MQA minimizes KV-cache size at some cost to expressiveness vs full multi-head KV.",
        {
            "Independent K/V per query with no sharing": "MQA explicitly shares K and V across heads.",
            "No query projections at all": "Multiple query heads remain; K/V are shared.",
            "Attention without any value aggregation": "Output is still a weighted sum of (shared) values.",
        },
    ),
    (
        "Multi-Head Attention",
        "The output projection W_O in multi-head attention mixes…",
        "Concatenated head subspaces back into the model dimension d_model.",
        [
            "Only the positional encodings, not head outputs",
            "Batch indices across unrelated datasets",
            "Softmax probabilities into a single scalar bias",
        ],
        "W_O ∈ ℝ^{d_model × d_model} learns how to combine head-specific features.",
        {
            "Only the positional encodings, not head outputs": "W_O acts on concatenated attention outputs.",
            "Batch indices across unrelated datasets": "Projection is within each sequence representation.",
            "Softmax probabilities into a single scalar bias": "W_O is a linear map on vectors, not a softmax reducer.",
        },
    ),
    (
        "LLM Basics",
        "Mixture-of-Experts (MoE) layers in large LLMs increase capacity by…",
        "Routing each token to a small subset of feed-forward experts instead of one dense FFN.",
        [
            "Duplicating the entire vocabulary per layer",
            "Removing attention in every other block",
            "Training without any activation function",
        ],
        "Sparse routing activates few experts per token, scaling parameters without dense FLOPs for all.",
        {
            "Duplicating the entire vocabulary per layer": "MoE affects FFN sublayers, not vocab duplication.",
            "Removing attention in every other block": "Attention stacks remain; FFN may be MoE.",
            "Training without any activation function": "Experts still use nonlinear activations (e.g., SwiGLU).",
        },
    ),
    (
        "LLM Basics",
        "RLHF for LLMs typically involves…",
        "Training a reward model on human preferences then optimizing the policy with PPO or similar.",
        [
            "Supervised clustering of tokenizer merges only",
            "Replacing cross-entropy with k-means loss",
            "Eliminating the decoder and using PCA only",
        ],
        "Preference data → reward model → policy gradient fine-tuning aligns outputs to human judgments.",
        {
            "Supervised clustering of tokenizer merges only": "RLHF targets generation quality, not BPE merge tables alone.",
            "Replacing cross-entropy with k-means loss": "Pretraining still uses likelihood; RLHF adds a preference stage.",
            "Eliminating the decoder and using PCA only": "LLMs remain autoregressive transformers.",
        },
    ),
    (
        "LLM Basics",
        "Speculative decoding accelerates generation when a smaller draft model…",
        "Proposes multiple tokens verified in parallel by the larger target model.",
        [
            "Increases the vocabulary size of the target model",
            "Disables the KV cache entirely",
            "Trains new embeddings from scratch each token",
        ],
        "Accepted draft prefixes save target-model steps; rejected drafts are rolled back.",
        {
            "Increases the vocabulary size of the target model": "Speculation is about parallel verification, not |V| changes.",
            "Disables the KV cache entirely": "Caching is compatible with speculative schemes.",
            "Trains new embeddings from scratch each token": "Weights are fixed; draft and target run forward passes.",
        },
    ),
    (
        "KV Cache",
        "Quantized KV caches (e.g., INT8/FP8) trade…",
        "Slightly reduced precision for lower memory bandwidth and larger batch/context capacity.",
        [
            "Exact lossless equivalence to FP64 training in all cases",
            "Removal of all attention computation",
            "Mandatory retraining for every new user message",
        ],
        "Low-precision K/V storage is an inference optimization with minor numerical error risk.",
        {
            "Exact lossless equivalence to FP64 training in all cases": "Quantization introduces approximation; serving tolerates small drift.",
            "Removal of all attention computation": "Attention still runs; tensors are stored cheaply.",
            "Mandatory retraining for every new user message": "Quantized cache is a deployment choice, not per-message training.",
        },
    ),
    (
        "KV Cache",
        "Multi-token prediction heads (some recent LLMs) interact with caching because…",
        "Each step may commit several future tokens, updating cache state for multiple positions at once.",
        [
            "They eliminate the sequence dimension entirely",
            "They forbid any causal masking",
            "They store the entire training corpus in cache",
        ],
        "Drafting multiple tokens per forward pass changes how cache entries advance per step.",
        {
            "They eliminate the sequence dimension entirely": "Sequences remain; decoding parallelism changes.",
            "They forbid any causal masking": "Causal structure is still required for valid conditioning.",
            "They store the entire training corpus in cache": "Cache holds session activations, not the training set.",
        },
    ),
    (
        "Attention",
        "Linear attention approximations (e.g., kernel feature maps) aim to…",
        "Reduce O(n²) pairwise softmax attention toward O(n) via associative aggregation tricks.",
        [
            "Remove all positional information from the model",
            "Guarantee exact equivalence to full softmax attention always",
            "Replace matrices with sorting algorithms only",
        ],
        "Feature maps φ(q)ᵀ(Σ φ(k)v) rewrite attention as cumulative sums under certain assumptions.",
        {
            "Remove all positional information from the model": "Linear attention methods still pair with positional schemes.",
            "Guarantee exact equivalence to full softmax attention always": "Approximations trade exactness for speed.",
            "Replace matrices with sorting algorithms only": "Core idea is algebraic reformulation, not sorting.",
        },
    ),
    (
        "Self-Attention",
        "Sliding-window (local) attention in long-context models limits each query to…",
        "Keys within a fixed window of neighboring positions.",
        [
            "Only the first and last token globally",
            "All tokens in unrelated documents in the batch",
            "Keys with index greater than the query only, unboundedly",
        ],
        "Local windows cap per-layer receptive field while stacking layers grows effective range.",
        {
            "Only the first and last token globally": "Windows are contiguous neighborhoods, not just endpoints.",
            "All tokens in unrelated documents in the batch": "Attention is scoped per sequence (plus masking).",
            "Keys with index greater than the query only, unboundedly": "Windows are bounded width; causal masks may still apply.",
        },
    ),
    (
        "Encoder-Decoder",
        "Non-autoregressive (NAT) Transformer decoders attempt to…",
        "Generate all target tokens in parallel, often requiring auxiliary alignment or latent variables.",
        [
            "Remove the encoder entirely",
            "Use only unigram bag-of-words without any context",
            "Guarantee identical outputs to autoregressive models without training changes",
        ],
        "Parallel decoding sacrifices simple likelihood factorization; iterative refinement or CTC-like losses help.",
        {
            "Remove the encoder entirely": "NAT models still condition on source representations.",
            "Use only unigram bag-of-words without any context": "NAT Transformers are structured neural models, not bag-of-words only.",
            "Guarantee identical outputs to autoregressive models without training changes": "Matching AR quality requires specialized training objectives.",
        },
    ),
    (
        "Multi-Head Attention",
        "Head dimension d_k smaller than d_model/h in some implementations implies…",
        "Projections map into a bottleneck subspace before the output projection expands again.",
        [
            "Attention is disabled for those layers",
            "The number of layers must equal h",
            "Softmax is applied across heads instead of positions",
        ],
        "Low-rank or factored attention variants change internal width while preserving block I/O shape.",
        {
            "Attention is disabled for those layers": "Attention still runs with adjusted projection sizes.",
            "The number of layers must equal h": "Head count and depth are independent hyperparameters.",
            "Softmax is applied across heads instead of positions": "Standard softmax is over sequence positions per head.",
        },
    ),
    (
        "LLM Basics",
        "Chain-of-thought prompting improves reasoning partly because…",
        "Intermediate tokens provide additional computation steps before the final answer token.",
        [
            "It increases parameter count during inference",
            "It removes the need for transformer layers",
            "It trains new logits solely on punctuation",
        ],
        "Generating rationale tokens activates deeper use of the same frozen weights (more depth in time).",
        {
            "It increases parameter count during inference": "Weights are unchanged; only the prompt/decode trajectory differs.",
            "It removes the need for transformer layers": "The same stacked layers process longer prompts.",
            "It trains new logits solely on punctuation": "CoT is prompting/inference behavior, not a punctuation-only retrain.",
        },
    ),
    (
        "KV Cache",
        "Prefix caching across user requests reuses KV blocks when…",
        "Multiple prompts share an identical initial token prefix (e.g., same system prompt).",
        [
            "Users use entirely different system instructions every time",
            "The model has zero layers",
            "Attention is replaced by k-nearest neighbors in pixel space",
        ],
        "Shared prompt prefixes hit the same cached K/V blocks, amortizing prefill cost.",
        {
            "Users use entirely different system instructions every time": "No shared prefix means little cache reuse.",
            "The model has zero layers": "Caching applies per layer's K/V activations.",
            "Attention is replaced by k-nearest neighbors in pixel space": "Prefix caching is for text transformer serving.",
        },
    ),
    (
        "Attention",
        "The Lipschitz concern with unscaled dot-product attention motivates scaling because…",
        "Dot-product variance grows with dimension, pushing softmax into saturation regions.",
        [
            "Softmax is undefined for any positive logits",
            "Values must be unit norm by definition",
            "Queries and keys must be orthogonal always",
        ],
        "Expected magnitude of q·k scales with d_k; dividing by √d_k stabilizes score distribution.",
        {
            "Softmax is undefined for any positive logits": "Softmax is well-defined; the issue is gradient flow when logits are huge.",
            "Values must be unit norm by definition": "Values are learned vectors without strict unit-norm constraint.",
            "Queries and keys must be orthogonal always": "Orthogonality is not required; similar directions yield large scores.",
        },
    ),
]

BOOK = make_book(
    title="Dive into Deep Learning",
    parent_topic="AI & Machine Learning",
    subtopic="Transformers",
    slug="transformers-d2l",
    source_url="https://d2l.ai/",
    easy=EASY,
    medium=MEDIUM,
    hard=HARD,
)
